### ISSUE TITLE
What happens if db is not closed at app exit

### ISSUE THREAD

**Issue by proofrock** [mattn/go-sqlite3#1008]
Hi,
   first of all, thanks for this great library. I have an application that uses SQLite, and eventually exits. Pretty much all the code docs are like this:
```go
db, err := sql.Open("sqlite3", "...")
if err != nil {
  // ...
}
defer db.Close()
```
But it may be difficult to track all the exit paths: for example, at `os.Exit()` the defers aren't called. So, what happens if the app exits and `db.Close()` is not called? 

From my experience, not much *seems* to happen, the files are not corrupted and can be opened afterward without any problem, both in WAL and non-WAL mode. Is this correct?

Thanks a lot!

     G.

**Comment by mattn** [comment]
It seems not related on go-sqlite3 or Go. Just it depend on the implementation of sqlite3. When the process exits, all of file descriptors or memories are abandoned by kernel. So we can know what will be happen. As far as I can say, you should not exit with os.Exit for the safe.

**Comment by proofrock** [comment]
Thank you, that's fair. As far as I can see, `Close()` calls `sqlite3_close_v2` (docs [here](https://www.sqlite.org/c3ref/close.html)). I'll try and ask in the SQLite forums, and if I get an answer I'll post an update here. Thanks!

As a side note, it's pretty difficult not to call `os.Exit()`. I'll try to update to using [something like this](https://github.com/vrecan/death).

**Comment by rittneje** [comment]
If your application crashes, exits abruptly, or loses power, the database will not be corrupted. (If this did happen, it would be a serious bug in SQLite.) However, any in progress (i.e., uncommitted) transactions for that application will be rolled back.

Also note that the operating system will automatically close all open files and associated file locks when the application exits. So even if you don't explicitly close the database yourself, it will ultimately be closed regardless.

If you are interesting in the kinds of bizarre situations that can lead to database corruption, the SQLite maintainers have detailed them here. https://www.sqlite.org/howtocorrupt.html

**Comment by proofrock** [comment]
Thank you! I'll peruse the link, seems like fun ;-)
