### ISSUE TITLE
A question about how to open the file stream database

### ISSUE THREAD

**Issue by AnxysUaen** [mattn/go-sqlite3#1009]
How to open a file stream?

**Comment by AnxysUaen** [comment]
The downloaded file is []byt. I don't want to write it to a local file, Is there any way to open it directly in the program?

**Comment by rittneje** [comment]
Does `sqlite3_deserialize` meet your needs? https://www.sqlite.org/c3ref/deserialize.html
It's not currently exposed via this library, but could be.

**Comment by AnxysUaen** [comment]
> Does `sqlite3_deserialize` meet your needs? https://www.sqlite.org/c3ref/deserialize.html It's not currently exposed via this library, but could be.

Thanks, I will try how to use it in Go

**Comment by rittneje** [comment]
Support for `Deserialize` has been added and will be included in the next release. https://pkg.go.dev/github.com/mattn/go-sqlite3@master#SQLiteConn.Deserialize
