### ISSUE TITLE
fail to build on windows with a few compiler

### ISSUE THREAD

**Issue by NewUserHa** [mattn/go-sqlite3#1012]
1. compiler from https://winlibs.com/ failed:
```
> go run .
# 
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\user\AppData\Local\Temp\go-link-2621619269\000016.o: in function `_cgo_preinit_init':
c:\go\src\runtime\cgo/gcc_libinit_windows.c:30: undefined reference to `__imp___iob_func'
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\user\AppData\Local\Temp\go-link-2621619269\000016.o: in function `x_cgo_sys_thread_create':
c:\go\src\runtime\cgo/gcc_libinit_windows.c:60: undefined reference to `__imp___iob_func'
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\user\AppData\Local\Temp\go-link-2621619269\000016.o: in function `x_cgo_notify_runtime_init_done':
c:\go\src\runtime\cgo/gcc_libinit_windows.c:101: undefined reference to `__imp___iob_func'
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\user\AppData\Local\Temp\go-link-2621619269\000017.o: in function `x_cgo_thread_start':
c:\go\src\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\user\AppData\Local\Temp\go-link-2621619269\000018.o: in function `_cgo_sys_thread_start':
c:\go\src\runtime\cgo/gcc_windows_amd64.c:31: undefined reference to `__imp___iob_func'
collect2.exe: error: ld returned 1 exit status
```
2. compiler from https://jmeubank.github.io/tdm-gcc/ succeeded.
3. havn't tested mingw-w64 and cygwin, unknown.

Is there possible for the first case a fix?

**Comment by rittneje** [comment]
What version of Go are you using?

**Comment by NewUserHa** [comment]
`go version go1.17.5 windows/amd64`

**Comment by rittneje** [comment]
Based upon the error you are seeing, it seems like an issue with your C library. In particular I think this is a problem with however `stderr` is being defined in C. Seems similar to this StackOverflow post. https://stackoverflow.com/a/30894349

**Comment by NewUserHa** [comment]
the first pre-build of gcc is more popular than the 2nd one, of course not as popular as MinGW-w64 or cygwin.
But 1st and 2nd both look like are minifiled from MinGW-w64. Therefore there shouldn't be any error while building.

so is there possible a fix?

**Comment by rittneje** [comment]
As this seems to be a cgo issue, and not an issue with this particular library, I suggest posting on the Go issue tracker to see if anyone there can help diagnose your issue. (Unfortunately, this is beyond my area of expertise.) https://github.com/golang/go/issues

**Comment by NewUserHa** [comment]
ok.
