### ISSUE TITLE
I got panic when using sqlite3_with_limit

### ISSUE THREAD

**Issue by xxz199539** [mattn/go-sqlite3#1013]
my code :
```
var sqlite3conn *sqlite3.SQLiteConn
    sql.Register("sqlite3_with_limit", &sqlite3.SQLiteDriver{
        ConnectHook: func(conn *sqlite3.SQLiteConn) error {
            sqlite3conn = conn
            return nil
        },
    })
    db, err := sql.Open("sqlite3_with_limit", "./foo.db")
    if err != nil {
        return err
    }
    limitVariableNumber := sqlite3conn.GetLimit(sqlite3.SQLITE_LIMIT_VARIABLE_NUMBER)
    fmt.Println(limitVariableNumber)
    sqlite3conn.SetLimit(sqlite3.SQLITE_LIMIT_VARIABLE_NUMBER, constants.MatchInsert)
```

I got panic because of  sqlite3conn is nill?， and can i use gorm open the same db file?

**Comment by mattn** [comment]
Can you provide stacktrace of the panic?

**Comment by rittneje** [comment]
This is because `sql.Open` does not immediately open a database connection. Hence your `ConnectHook` was never invoked, so `sqlite3conn` is still `nil`.

That said, this is also not a good way to set connection properties. You should do this logic inside the `ConnectHook` so that it happens on any database connection that the pool creates.

**Comment by xxz199539** [comment]
so, how can i connect db with gorm and set_limit ? can you give me some demo code,thanks

**Comment by rittneje** [comment]
That is more a question for the gorm library maintainers, but from what I can tell, something like this:
```go
func init() {
    sql.Register("sqlite3_with_limit", &sqlite3.SQLiteDriver{
        ConnectHook: func(conn *sqlite3.SQLiteConn) error {
            conn.SetLimit(sqlite3.SQLITE_LIMIT_VARIABLE_NUMBER, constants.MatchInsert)
            return nil
        },
    })
}

...

d := &sqlite.Dialector{
    DriverName: "sqlite3_with_limit",
    DSN: "file:...",
}
db, err := gorm.Open(d, &gorm.Config{})
...
```

**Comment by xxz199539** [comment]
it's helpful, thanks a lot !
