### ISSUE TITLE
gcc-11 sqlite3-binding.c causes memcpy compiler warning. Please upgrade sqlite-binding.c

### ISSUE THREAD

**Issue by aletheia7** [mattn/go-sqlite3#1014]
### Summary ###
Please upgrade sqlite-binding.c to version 3.38.0 to fix gcc-11 compiler warning.

### Issue ###
I upgraded gcc-10 to gcc-11 and received the following compilation warning:
```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3Fts5IndexQuery’:
sqlite3-binding.c:228445:18: warning: ‘memcpy’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
228445 |     if( nToken ) memcpy(&buf.p[1], pToken, nToken);
       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Versions ###
go-sqlite3 version: v1.14.11 (sqlite amalgamation sqlite3-binding.c version: 3.37.0).
Linux: Debian Testing/Bookworm
Go: go 1.17.6 linux/amd64

Must define go build -tags "sqlite_fts5" to see warning.

sqlite3-binding.c version 3.38.0 (unreleased)  fixed the problem (https://www.sqlite.org/snapshot/sqlite-snapshot-202202100101.tar.gz). Versions 3.37.1 and 3.37.2 do not fix the warning.

The compiler warning does not occur with gcc-10. ```export CC=gcc-10 ; go build```

**Comment by rittneje** [comment]
You will have to wait for SQLite 3.38.0 to be officially released first.

**Comment by aletheia7** [comment]
v.1.14.12 has sqlite 3.38.0 and fixes this issues.
