### ISSUE TITLE
Is the user_auth can only block your own program, but another program can skip user_auth to access it?

### ISSUE THREAD

**Issue by PengChong1111** [mattn/go-sqlite3#1032]
I  compiled the project with the tag sqlite_userauth, then I opened it with parameter `file:test.s3db?_auth&_auth_user=admin&_auth_pass=admin`. But then I find that I can open it with the parameter  `file:test.s3db?`. Is that right? Is this means the user_auth can only block your own program, but another program can skip user_auth to access it?

**Comment by rittneje** [comment]
When you open it the second time, are you still compiling with the sqlite_userauth tag? Note that any client application compiled without this tag (or, at the C level, without the `SQLITE_USER_AUTHENTICATION` option) will have unrestricted access to the entire database. This includes the standard `sqlite3` command line utility.

Also note that when compiling with sqlite_userauth, if you don't provide credentials or provide invalid ones, you will not receive any error until the first time you run some query. Neither `sql.Open` nor `sql.DB.Ping` have the capacity to return an error in this regard by default.

The various limitations of this extension are described in more detail here. https://www.sqlite.org/src/doc/trunk/ext/userauth/user-auth.txt (Personally, I find it to be a fairly useless extension.)

**Comment by PengChong1111** [comment]
Example One:
Compiled with parameter `sqlite_userauth` and create database `test.s3db` with parameter `file:test.s3db?_auth&_auth_user=admin&_auth_pass=admin`. Succeed in creating the database `test.s3db` .
Example Two:
Compiled with parameter `sqlite_userauth` and open database `test.s3db` with parameter `file:test.s3db?_auth&_auth_user=admin&_auth_pass=admin`. Succeed in opening the database `test.s3db` .
Example Three:
Compiled with parameter `sqlite_userauth` and open database `test.s3db` with parameter `file:test.s3db`. Succeed in opening `test.s3db`. But when execute `select` SQL, it occur errors `2022/04/19 13:55:42 SQLITE_AUTH: Unauthorized`.
Example Four:
Compiled without parameter `sqlite_userauth` and open database `test.s3db` with parameter `file:test.s3db`. succeed in opening `test.s3db` and got data from database correctly.
Example Five:
`apt install sqlite3`, then `sqlite3 test.s3db`. also could get the data.
In a words, go-sqlite3 can't deter other program to access the database, if they try to skip the authentic process.

**Comment by rittneje** [comment]
Correct. This is a short-coming of the userauth extension itself. This is partly why I consider it to be useless.

**Comment by rittneje** [comment]
@PengChong1111 Does this resolve your original question?
