### ISSUE TITLE
'sqlite3-binding.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by yifanstefanwang** [mattn/go-sqlite3#1033]
Wondering if anyone had library issues related to Apple M1 (not sure if this is the reason, just a wild guess)

Our project  is in `Golang` and uses `Bazel`, and `build` have been failing for me with ERROR `'/private/var/tmp/_bazel_<usr>/6a928f809ee3a14ad8b957e75e243b76/sandbox/darwin-sandbox/8/execroot/,project/external/com_github_mattn_go_sqlite3/backup.go:10:10: error: 'sqlite3-binding.h' file not found with <angled> include; use "quotes" instead`

I was trying to figure out a more generic way to fix this issue.

For a temp work around: I had to fix all of the following files’ #include <sqlite3-binding.h> to use “quotes” instead of \<angled>, now my `build` is WORKING!
- backup.go
- callback.go
- error.go
- sqlite3.go
- sqlite3_context.go
- sqlite3_load_extension.go
- sqlite3_type.go

MacOS: Monterey 12.3.1
Chip: Apple M1 Pro

**Comment by yifanstefanwang** [comment]
@mattn

**Comment by rittneje** [comment]
Which version of this library are you using? Because all the files you mentioned are already using `#include "sqlite3-binding.h"` since #868 was merged (so v1.14.10+).

**Comment by yifanstefanwang** [comment]
Thanks @rittneje , turns out we are using 1.14.9, trying 1.14.10 now
