### ISSUE TITLE
Question: RegisterPreUpdateHook Behavior

### ISSUE THREAD

**Issue by coreybutler** [mattn/go-sqlite3#1034]
The documentation for [RegisterPreUpdateHook](https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteConn.RegisterPreUpdateHook) states

> If there is an existing update hook for this connection, it will be removed. If callback is nil the existing hook (if any) will be removed without creating a new one.

This is the exact same verbiage as [RegisterUpdateHook](https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteConn.RegisterUpdateHook).

Does this mean `RegisterPreUpdateHook` and `RegisterUpdateHook` cannot be used simultaneously? Or should the `RegisterPreUpdateHook` documentation actually say "If there is an existing **pre**update hook for this connection,..."?

Perhaps I'm misunderstanding these hooks, but I thought `RegisterPreUpdateHook` occurs before an `INSERT`/`UPDATE`/`DELETE` while `RegisterUpdateHook` happens after.

**Comment by rittneje** [comment]
These are wrappers around the `sqlite3_update_hook` and `sqlite3_preupdate_hook` functions from the SQLite3 C library, which are documented [here](https://www.sqlite.org/c3ref/update_hook.html) and [here](https://sqlite.org/c3ref/preupdate_count.html), respectively.

The latter says this:
> At most one preupdate hook may be registered at a time on a single [database connection](https://sqlite.org/c3ref/sqlite3.html); each call to [sqlite3_preupdate_hook()](https://sqlite.org/c3ref/preupdate_count.html) overrides the previous setting.

So it seems to just be a typo in the Go docs.

**Comment by coreybutler** [comment]
Thanks for clarifying, @rittneje. I submitted a PR with updated code comments.
