### ISSUE TITLE
`:memory:` databases: Opening an *sql.Conn from a *sql.DB wipes the *DB, only gets restored after the *Conn is closed. 

### ISSUE THREAD

**Issue by bokwoon95** [mattn/go-sqlite3#1036]
This is only observed for `:memory:` databases, when I switch to using a file the problem does not exist.

### What I observe:
1. Open a `:memory: *sql.DB` and create some tables in it.
    - The tables exist.
3. Open an `*sql.Conn` from the `*sql.DB`. 
    - The tables exist in the `*Conn`, but they have been wiped from the `*DB`.
5. Close the `*sql.Conn`. 
    - The tables reappear in the `*sql.DB`.

### What I expected:
1. Open a `:memory: *sql.DB` and create some tables in it.
    - The tables exist.
3. Open an `*sql.Conn` from the `*sql.DB`. 
    - The tables exist both inside the `*Conn` and the `*DB` because they're both reading from the same database.
5. Close the `*sql.Conn`. 
    - The tables stay in the `*sql.DB`.

### Demo code:

```go
package main

import (
    "context"
    "database/sql"
    "fmt"
    "log"

    _ "github.com/mattn/go-sqlite3"
)

func main() {
    db, err := sql.Open("sqlite3", ":memory:")
    if err != nil {
        log.Fatalln(err)
    }
    _, err = db.Exec("CREATE TABLE foo ( id INT ); CREATE TABLE bar ( id INT );")
    if err != nil {
        log.Fatalln(err)
    }
    fmt.Println("Created tables foo and bar.")
    fmt.Println("Tables in *sql.DB:", getTables(db))
    conn, err := db.Conn(context.Background())
    if err != nil {
        log.Fatalln(err)
    }
    fmt.Println("Opened *sql.Conn.")
    fmt.Println("Tables in *sql.Conn:", getTables(conn))
    fmt.Println("Tables in *sql.DB:",getTables(db))
    conn.Close()
    fmt.Println("Closed *sql.Conn.")
    fmt.Println("Tables in *sql.DB:",getTables(db))
}

type DB interface {
    QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

func getTables(db DB) []string {
    var tables []string
    rows, err := db.QueryContext(context.Background(), "SELECT tbl_name FROM sqlite_schema WHERE type = 'table';")
    if err != nil {
        log.Fatal(err)
    }
    defer rows.Close()
    for rows.Next() {
        var table string
        err = rows.Scan(&table)
        if err != nil {
            log.Fatal(err)
        }
        tables = append(tables, table)
    }
    return tables
}
```
**Output:**
```shell
Created tables foo and bar.
Tables in *sql.DB: [foo bar]
Opened *sql.Conn.
Tables in *sql.Conn: [foo bar]
Tables in *sql.DB: [] # <-- empty
Closed *sql.Conn.
Tables in *sql.DB: [foo bar]
```
**Output if I change `:memory:` to an on-disk database:**
```shell
Created tables foo and bar.
Tables in *sql.DB: [foo bar]
Opened *sql.Conn.
Tables in *sql.Conn: [foo bar]
Tables in *sql.DB: [foo bar] # <-- not empty
Closed *sql.Conn.
Tables in *sql.DB: [foo bar]
```

This is not a big issue since I can workaround it by never opening an `*sql.Conn`, but I thought I'd bring it up in case this is unexpected behaviour that should be fixed. Or documented?

**Comment by rittneje** [comment]
https://www.sqlite.org/inmemorydb.html

> Every :memory: database is distinct from every other. So, opening two database connections each with the filename ":memory:" will create two independent in-memory databases.

You should not use `:memory:` unless you specifically limit the connection pool to a single connection. Otherwise, your results may vary.

If you use `file:<whatever>?vfs=memdb` instead, then you can open multiple connections (from the same process) and they will all use the same in-memory database. But as soon as the last connection closes, the in-memory database will be released, so be sure to account for this when configuring and managing your pool. Also, if you need multiple distinct in-memory databases, then you can give each a different name. Please also note that in-memory databases can never be shared by separate processes.

**Comment by bokwoon95** [comment]
> You should not use :memory: unless you specifically limit the connection pool to a single connection. Otherwise, your results may vary.

Gotcha, although in my case calling `db.SetMaxOpenConns(1)` blocks indefinitely because I'm taking an explicit connection out of the pool, causing call further calls to `*sql.DB` to block until the `*Conn` is closed. 

I also see that each connection getting its own `:memory:` instance has already been mentioned in the FAQ 😅:

> - Why I'm getting `no such table` error?
>
> Each connection to ":memory:" opens a brand new in-memory sql database, so if the stdlib's sql engine happens to open another connection and you've only specified ":memory:", that connection will see a brand new database.

> If you use file:<whatever>?vfs=memdb instead, then you can open multiple connections (from the same process) and they will all use the same in-memory database.

I still get the same problem with `file:foobar?vfs=memdb` , the first connection I take from the database has the tables but subsequent connections get a new `:memory:` database (all empty). It works if I add `cache=shared` to it, but that is not suitable for testing since all tests would share the same instance. I guess my best option is to not take an explicit `*sql.Conn` out of the pool and rely on `db.SetMaxOpenConns(1)` instead.

**Comment by rittneje** [comment]
@bokwoon95 This is because I forgot to mention a subtle but critical point about the memdb vfs.

> The "memdb" VFS now allows the same in-memory database to be shared among multiple database connections in the same process as long as the database name begins with "/".

If you do `file:/foobar?vfs=memdb` then it will work as expected.

**Comment by bokwoon95** [comment]
Thanks, can confirm it works. I will use `?vfs=memdb` from now.
