### ISSUE TITLE
How to quickly load a SQLite "dump" file?

### ISSUE THREAD

**Issue by otoolep** [mattn/go-sqlite3#1039]
Original issue: https://github.com/rqlite/rqlite/issues/1016

A rqlite user has reported it takes a long time to load a ~19MB SQL text file, generated by the `.dump` command. On my machine it takes 13 mins. Most of the time seems to be preparing the statements, detecting the first SQL statement in the SQL dump, and making the rest of the text the "tail", as per here:

https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L850

and so on.

rqlite calls this code via `ExecContext`:

https://github.com/rqlite/rqlite/blob/master/db/db.go#L437

So I suspect all this moving around of memory and text is just slow. Is there a faster way to load a valid SQL file? It takes a couple of seconds if one loads the file directly into a SQLite database.
```
$ time sqlite3 test.db < av_autoprovisionvalues.sql

real	0m1.931s
user	0m1.773s
sys	0m0.048s
```
Is there a way to use the go-sqlite3 API for shorter load times? To get the same (or closer) performance as the SQLite command itself?

**Comment by mattn** [comment]
Can you provide part of the queries? If it contains INSERT statement, it will be heavily. (So you can use `begin transaction`)

**Comment by otoolep** [comment]
Yes, it has thousands of INSERTs. And because it's generated by SQLite the file starts like so:
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE....
```
and ends with:
```
COMMIT;
```
I think it's the prepare and tail loop in https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L850 that takes all the time.

**Comment by otoolep** [comment]
>Another possibility is to use the actual SQLite database for this operation, rather than a dump file. Then you can leverage SQLite's [backup/restore API](https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteBackup), which should be faster.

I could totally do that, would be easy enough to add. Let me try that -- thanks.

**Comment by otoolep** [comment]
Loading the SQLite file directly works great -- load times for this case went from minutes to seconds. Thanks for the suggestion.

https://github.com/rqlite/rqlite/pull/1017
