### ISSUE TITLE
table not found when running query when a row is active

### ISSUE THREAD

**Issue by rbucker** [mattn/go-sqlite3#1057]
This is kinda quirky. I'm prepared to say it's my issue but it's just weird enough that it might actually be a thing. Before you hate me I found the quirqiest work around.... Here is the pseudo code.

```
open a database
attach another database
execute a sql statement which is a join between the main and attached db
loop thru the results 
   output some columns
   if some column changes value then
       execute a sql statement with a join between the main and attached (#2)
       loop thru the resuts
       loop;
   endif
loop;
```

When the inner sql (#2) is executed I get a table not found error referring to the attached table.

here is the work around.

```
open a database
attach another database
execute a sql statement which is a join between the main and attached db
loop thru the results 
   output some columns
   if some column changes value then
       attach the table (#a)
       execute a sql statement with a join between the main and attached (#2)
       loop thru the resuts
       loop;
       detach the table
   endif
loop;
```

see at (#a) I "attach" the database again and it does not throw an error but it actually completes.

## Here is the actual code

```
package main

import (
        "database/sql"
        "fmt"
        "log"
        "strings"
        _ "github.com/mattn/go-sqlite3"
)

func read(db *sql.DB, f bool) {
        rows, err := db.Query("SELECT t1.a FROM t1 left join db2.t2")
        if err != nil {
                log.Fatal(err)
        }
        if ! f {
        names := make([]string, 0)
        for rows.Next() {
                var name string
                if err := rows.Scan(&name); err != nil {
                        log.Fatal(err)
                }
                names = append(names, name)
                read(db, true)
        }
        log.Printf("%s are %d years old", strings.Join(names, ", "), 12)
        }
        defer rows.Close()
}

func attach(db *sql.DB) {
        result, err := db.Exec("attach 'db2' as db2")
        fmt.Printf("attach(): result=%v, err=%v\n", result, err);
}


func main() {
        db, err := sql.Open("sqlite3", "db1")
        defer db.Close()
        attach(db)
        read(db, false)
        fmt.Printf("open(): %v\n", err);
}
```

**Comment by rbucker** [comment]
I'm not sure why sql.DB is a connection pool model or what the advantage is. Clearly there is this disadvantage where any connection state changes like `attach` or maybe some `pragma` calls create a non-deterministic connection state that might have very serious side effects.

I asked the sqlite team about the problem and they blamed golang/go-sqlite3 right away. While I was a little put off how quickly they responded with that; once they demonstrated that it was possible to execute two active queries from the same connection and subsequently reproduced the issue with multiple connections as described... The problem is the pool.

https://sqlite.org/forum/forumpost/14f38c2f5a

**Comment by rittneje** [comment]
It is a pool because `sql.DB` is generic, and for SQL variants that aren't SQLite (read: client-server models), connection pooling is a necessary feature.

**Comment by rbucker** [comment]
And it seems because of goroutines it has to be. It sure would be great if there was a way to indicate which commands or best practices... in my case I got lucky because it was a 2 connection financial report and not 100s or 1000s of web pages.

https://stackoverflow.com/questions/25751830/golang-sqlite-database-connection-pooling

Feel free to close this ticket if no action will be taken.
