### ISSUE TITLE
Propagating errors from VTabCursor

### ISSUE THREAD

**Issue by mactaggart** [mattn/go-sqlite3#1075]
I noticed that returning an error from various methods in VTabCursor (Filter, Next, etc.) does not result in an error being propagated when executing a query. Returning an error from Filter, for example, will cause no rows to be returned, however, the caller can't distinguish if an error occurred or if there were simply no results. Is this expected behavior?

**Comment by itizir** [comment]
https://github.com/mattn/go-sqlite3/issues/902

**Comment by mactaggart** [comment]
@itizir this is exactly what I was after. thanks!
