### ISSUE TITLE
_localtime32(0): not defined

### ISSUE THREAD

**Issue by gitmybox** [mattn/go-sqlite3#109]
When I build the example simple.go, I have the error "_localtime32(0): not defined" with exit code 2

Pls advise what is the problem. Thanks

**Comment by Mistuke** [comment]
@andrewstucki it seems that in this commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/23b9f70a63785b16bd45083224e4b3d7927033f0/ the symbols were moved from `libmingwex.a` to `libmsvcrt.a` So a plausible for this may be to link against that.
