### ISSUE TITLE
Annoying warning # command-line-arguments ld: warning: -no_pie is deprecated when targeting new OS versions

### ISSUE THREAD

**Issue by ollolollollooloo** [mattn/go-sqlite3#1093]
Mac M1. 
I want to disable this annoying warning:

```
# command-line-arguments
ld: warning: -no_pie is deprecated when targeting new OS versions
```

<img width="447" alt="Screen Shot 2022-09-20 at 3 03 47 PM" src="https://user-images.githubusercontent.com/31069733/191189591-2f1333d0-5830-48a2-ba2a-ff119cb1eb34.png">

**Comment by rittneje** [comment]
https://github.com/golang/go/issues/54482#issuecomment-1251124908
