### ISSUE TITLE
create a index on not exist column will lead user CAN NOT query database by command line

### ISSUE THREAD

**Issue by rencalo770** [mattn/go-sqlite3#1094]
hi, there may be 2 bugs about sqlite3.
1. when i execute a sql by go api to  create a index on not exist column , it will lead me can not query databse by command line.
2. i can create a index on a column by command line ,even if this column does not exist in table.

**Comment by rittneje** [comment]
Please provide a reproducible example of these issues.

**Comment by rittneje** [comment]
I'm going to close this due to lack of activity. Feel free to open a new issue with more details if the issue persists.
