### ISSUE TITLE
Cannot compile in Windows

### ISSUE THREAD

**Issue by oSethoum** [mattn/go-sqlite3#1097]
I have openssl installed but the code still won't compile the error is:
```console
github.com/xeodou/go-sqlcipher
sqlite3-binding.c:24328:10: fatal error: openssl/rand.h: No such file or directory
24328 | #include <openssl/rand.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

am on `window 10`
any help?

**Comment by rittneje** [comment]
You are not using this repository. Please file an issue with github.com/xeodou/go-sqlcipher

**Comment by oSethoum** [comment]
@rittneje ops sorry wrong repository, after being frustrated with the error.
