### ISSUE TITLE
db.Query with variable

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [mattn/go-sqlite3#1113]
Hello, I've been trying to find a solution for two hours now, but I can't. How do I make a query with a variable? Please help me :(
```go
...

func searchUser(w http.ResponseWriter, r *http.Request) {
    q := r.URL.Query().Get("q")
    rows, err := db.Query("SELECT * FROM users WHERE name like '%q%'")
...
```

**Comment by rittneje** [comment]
It's not entirely clear what you are looking for, but I'm guessing you mean this:
```go
db.Query("SELECT * FROM users WHERE name LIKE '%' || ? || '%'", q)
``` 

However, please note that you would need to consider the situation where `q` itself contains `%` and/or `_`. I'm not sure what your requirements or expectations are.
