### ISSUE TITLE
Where is WAL mode

### ISSUE THREAD

**Issue by fairking** [mattn/go-sqlite3#1121]
Hi guys.

Reading the [doc](https://github.com/mattn/go-sqlite3#dsn-examples) I have found an example which uses shared cache mode: `file:test.db?cache=shared&mode=memory`. But referring to the [sqlite3 doc](https://www.sqlite.org/sharedcache.html) it says it is discouraged and `WAL mode` should be used instead. Could someone explain how to enable WAL mode? Does `_journal_mode` refers to WAL mode or there is something else.

**Comment by victory460** [comment]
@fairking How to config wal mode by go-sqlite3？

**Comment by YanyunTao** [comment]
@fairking In WAL mode, one transaction continues to write to the SQLite database, and another transaction will report the error "database is locked" when creating, updating, and inserting data. Is this a WAL mode configuration problem?
