### ISSUE TITLE
 unknown type name 'sigset_t'; did you mean '_sigset_t'?

### ISSUE THREAD

**Issue by DehaiWang** [mattn/go-sqlite3#1122]
my computer is windows 10,i build to linux,but some thing is not working well.

I installed tdm-gcc,and add the bin folder to the Windows path.

my setting:
```
SET CGO_ENABLED=1
SET GOOS=linux
SET GOARCH=amd64
go build --tags "amd64"
```

the error message is :
```

# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:63:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
   63 |  sigset_t ign, oset;
      |  ^~~~~~~~
      |  _sigset_t
gcc_linux_amd64.c:68:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
   68 |  sigfillset(&ign);
      |  ^~~~~~~~~~
gcc_linux_amd64.c:63:16: error: unused variable 'oset' [-Werror=unused-variable]
   63 |  sigset_t ign, oset;
      |                ^~~~
cc1.exe: all warnings being treated as errors
```

go env is:
```
G:\GolangWorks\src\gosqlitea>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=G:\GoCache
set GOENV=C:\Users\90820\AppData\Roaming\go\env
set GOEXE=
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=G:\GolangPath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=linux
set GOPATH=G:\GolangPath;G:\GolangWorks;G:\GoWorksLc
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=G:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=G:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=G:\GolangWorks\src\gosqlitea\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\90820\AppData\Local\Temp\go-build1349213426=/tmp/go-build -gno-record-gcc-switches
```

**Comment by rittneje** [comment]
What do `where gcc` and `gcc --version` report?

**Comment by DehaiWang** [comment]
gcc --version in cmd and show :

```
C:\Users\90820>gcc --version
gcc (tdm64-1) 10.3.0
Copyright (c) 2020 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。
```

**Comment by DehaiWang** [comment]
@rittneje 
gcc --version in cmd and show :
```
C:\Users\90820>gcc --version
gcc (tdm64-1) 10.3.0
Copyright (c) 2020 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。
```

**Comment by rittneje** [comment]
My understanding is that tdm-gcc is not a cross-compiler. You need a C compiler that runs on Windows but targets Linux. See https://github.com/golang/go/issues/40129

**Comment by DehaiWang** [comment]
@rittneje  
 sorry, i not find i need whitch one from` https://musl.cc/`
i try  some ways, but failed.

**Comment by rittneje** [comment]
It's not something I've ever done, sorry. My recommendation is to compile inside a docker container. That way you can just use regular gcc.

**Comment by mattn** [comment]
FYI, I'm using msys2 mingw64 gcc compiler.

**Comment by DehaiWang** [comment]
@mattn   i build in windows for linux, need   cross build ,mingw64 gcc not work

**Comment by xpfo-go** [comment]
@DehaiWang 你好 我也碰到相同的问题，请问您是如何解决的

**Comment by IAOTW** [comment]
@DehaiWang 你好，请问最后是如何解决的呢？可否分享一下

**Comment by xpfo-go** [comment]
> @DehaiWang 你好，请问最后是如何解决的呢？可否分享一下

开启CGO跨平台编译得时候，应该是缺少了某个包，再linux上打包即可。

**Comment by DehaiWang** [comment]
@xpfo-go  应该是windows下的跨平台编译C或者C++代码的工具有些不完全适配的问题，没用GCC，用的zig，
`    set CGO_ENABLED=1`
`    set GOOS=linux`
 `   set GOARCH=amd64`
`    set CC=zig cc -target x86_64-linux`
 `   SET CXX=zig c++ -target x86_64-linux`
 `  go build --tags=linux/amd64 -o  XX   main.go`

**Comment by xpfo-go** [comment]
> @xpfo-go 应该是windows下的跨平台编译C或者C++代码的工具有些不完全适配的问题，没用GCC，用的zig， ` set CGO_ENABLED=1` ` set GOOS=linux` ` set GOARCH=amd64` ` set CC=zig cc -target x86_64-linux` ` SET CXX=zig c++ -target x86_64-linux` ` go build --tags=linux/amd64 -o XX main.go`

感谢
