### ISSUE TITLE
Scan returns empty string depending on order

### ISSUE THREAD

**Issue by rupakbajgain** [mattn/go-sqlite3#1123]
if i use
SELECT * FROM jobs , or
SELECT ID, url, props, handler, CINFO FROM jobs
rows.Scan(&k.ID, &k.Url, &k.Props, &k.Pid, &k.CINFO)
>this always shows CINFO empty
 
but later i tried it again with
SELECT ID, url, CINFO, props, handler FROM jobs
rows.Scan(&k.ID, &k.Url, &k.CINFO, &k.Props, &k.Pid)
> it works properly

it was doing something like this previously but i think something like this fixed it too .

where,
	ID int
	Url string
	Props string
	Pid int
	CINFO string

**Comment by rittneje** [comment]
Please provide a minimal reproducer, including the dump of the database file (including schema and data), as well as the Go code.

**Comment by rupakbajgain** [comment]
Sorry i tried to so this today but it do not reproduce, I should have zipped it then, i will upload it later if someting like this happens , i have double checked it before opeaning issue,
the function order was
> open db
>
`
func LoadAllJobs() []JobsInfo {
	jobs := []JobsInfo{}
	//load contents
	rows, err := Db.Query("SELECT * FROM jobs")
	defer rows.Close()
    if err != nil {
        fmt.Println("Not found")
    }

    for rows.Next() {
        k := JobsInfo{}
        rows.Scan(&k.ID, &k.Url, &k.Props, &k.Pid, &k.CINFO)
        //fmt.Println("info",k)
		jobs = append(jobs, k)
    }
	return jobs
}
`
> do other operations with those datas
but i have changed a lot of codes by then, and it was my 1st go code so ...

**Comment by rittneje** [comment]
@rupakbajgain Please open a new issue if you are able to reproduce the problem.
