### ISSUE TITLE
get "near ".": syntax error" when query ".tables"

### ISSUE THREAD

**Issue by himcc** [mattn/go-sqlite3#1135]
code : https://gist.github.com/himcc/3fc0268cb395eda620d55d29ba87d355

What's wrong?

How can i get tables  name and schema?

**Comment by otoolep** [comment]
`.tables` is not SQL syntax (obviously). `.tables` is implemented by the SQLite shell, not by the database itself. Instead do:

`SELECT name FROM sqlite_master WHERE type="table"`

https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L154
