### ISSUE TITLE
LastInsertId returning 0

### ISSUE THREAD

**Issue by mauserzjeh** [mattn/go-sqlite3#1140]
Not sure if it's a bug or I misunderstood something, but `LastInsertId` returns 0 in the following scenario:

```sql
INSERT INTO urls 	(parent_id, workspace_id, active, is_sitemap, in_progress, url, parser_type, crawled_at)
VALUES 			(?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT 	 	(workspace_id, url)
DO UPDATE SET
			updated_at = CURRENT_TIMESTAMP
RETURNING 		id
```

I have this query to either insert or update a row in the database. When an insert happens `LastInsertId` properly returns the `id` of the  row. But if a record is already in the database, then the returned value is 0 and also `LastInsertId` does not produce any errors either.

How could I retrieve the id of the row when having an `UPSERT`?

**Comment by mattn** [comment]
You don't need to append `RETURNING id`.

**Comment by mauserzjeh** [comment]
Removing the `RETURNING id` does not change the outcome. `LastInsertId` returns 0, despite I see the `updated_at` columns being updated in each row which were already inside the database.

**Comment by mattn** [comment]
It seems limitation.

See https://sqlite.org/lang_returning.html

**Comment by mauserzjeh** [comment]
In the details section it says: ***A RETURNING clause for an [UPSERT](https://sqlite.org/lang_upsert.html) reports both inserted and updated rows.***. And the limitations mentioned in the 3. point in the docs does not apply to this example.

**Comment by mauserzjeh** [comment]
So there is no support currently for this usecase? I have also found this forum you have linked. I tested out my query with the sqlite3 CLI and it does return the correct `id` when I run the query I posted earlier against my database. But it still does return 0 when I am trying to accomplish the same in Go.

**Comment by rittneje** [comment]
`LastInsertId` does exactly that - returns the ID of the last _insert_. Updates don't count.

For your use case, you should use `Query`/`QueryRow` instead of `Exec`, with the `RETURNING id` clause. This will allow you to fetch the returned ID via `Scan`.

**Comment by mauserzjeh** [comment]
@rittneje many thanks for the suggestion. I have switched to `QueryRow` for my query and used `Scan` and its working perfectly fine. Somehow I did not realise I can use `QueryRow` for `INSERT` 🤦‍♂️ 😄
