### ISSUE TITLE
Getting `unknown function: REGEXP()` when preparing an `INSERT` into table with `REGEXP` constraint.

### ISSUE THREAD

**Issue by FF-AntiK** [mattn/go-sqlite3#1142]
I'm using go-sqlite3 v1.14.16
I'm on Archlinux with go 1.20 and sqlite 3.41.1

The following code produces the `unknown function: REGEXP()` error:

```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	log.Println("Open DB")
	db, err := sql.Open("sqlite3", "test.db")
	if err != nil {
		log.Fatal(err)
	}

	defer func() {
		log.Println("Close DB")
		log.Fatal(db.Close())
	}()

	_, err = db.Exec(`
		CREATE TABLE mytest(
			test TEXT CHECK(test REGEXP '^[A-ZÄÖÜ][0-9A-ZÄÖÜa-zäöü]*$')
		);
	`)
	if err != nil {
		log.Fatal(err)
	}

	// this fails with: unknown function: REGEXP()
	stmt, err := db.Prepare("INSERT INTO mytest(test) VALUES(?);")
	if err != nil {
		log.Fatal(err)
	}

	_, err = stmt.Exec("Z1")
	if err != nil {
		log.Fatal(err)
	}
}
```

Are REGEXP constraints not supported by `go-sqlite3`?

**Comment by rittneje** [comment]
`REGEXP` is not part of vanilla SQLite. You will need to register it yourself via [`RegisterFunc`](https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteConn.RegisterFunc).

> The REGEXP operator is a special syntax for the regexp() user function. No regexp() user function is defined by default and so use of the REGEXP operator will normally result in an error message. If an [application-defined SQL function](https://www.sqlite.org/appfunc.html) named "regexp" is added at run-time, then the "X REGEXP Y" operator will be implemented as a call to "regexp(Y,X)".

**Comment by FF-AntiK** [comment]
Thank you very much for clarification!
I was confused because the sqlite package provided by the official Archlinux repos seems to have `REGEXP` support out of the box. But it's totally possible that it's just patched by the Archlinux maintainers.

Can you tell me how the signature of such a `regexp` function should look like?
I'd assume `func regexp(x, y string) error`?

**Comment by rittneje** [comment]
> I was confused because the sqlite package provided by the official Archlinux repos seems to have REGEXP support out of the box. But it's totally possible that it's just patched by the Archlinux maintainers.

I'm assuming you are referring to `sqlite3` the CLI, which is distinct from `sqlite3` the C library. As of v3.36.0, the CLI includes the regex extension by default, but the library does not. https://www.sqlite.org/changes.html#version_3_36_0
