### ISSUE TITLE
Use golang to update produces database is locked

### ISSUE THREAD

**Issue by whale-baby** [mattn/go-sqlite3#1148]
The following code will generate an error`SQL Error: database is locked`, and it is not used to write concurrent operations. Other database operations are also closed normally. Does anyone know how to solve this?

```
func WritehttpHostinfo(system string, username string, cookie string) {

    db := Opendb()
	defer db.Close()

	/*stmt, err := db.Prepare("UPDATE http SET SYSTEM=?, USERNAME=? WHERE IP=?")
	SqlcheckErr(err)*/

	res, err := db.Exec("UPDATE http SET SYSTEM=?, USERNAME=? WHERE IP=?", system, username, cookie)
	SqlcheckErr(err)

	affect, err := res.RowsAffected()
	SqlcheckErr(err)

	fmt.Println(affect)

}
```

**Comment by rittneje** [comment]
Please provide a complete minimum reproduction if possible.

What version of Go are you using? What version of this library are you using? Are you using any build tags? How did you open the database? What was the connection string?

Are there any other processes (such as the sqlite3 CLI) that are also using this database?

You mentioned that other operations "closed normally". What do you mean by this? What are the operations in question?

One thing I will point out is that creating a new `*sql.DB` instance per request like this is an anti-pattern. `*sql.DB` is a connection pool. You should create a single instance at application startup.

**Comment by whale-baby** [comment]
No other process is used to access sqlite3, the version used is as follows:
- golang：go1.18.4 linux/amd64
- SQLite：3.38.2

```
func Opendb() *sql.DB {
	Dir, _ := os.Getwd()
	Dirdb := Dir + "/db/xxx.db"
	db, err := sql.Open("sqlite3", Dirdb)
	SqlcheckErr(err)

	return db
}

func WritehttpHostinfo(system string, username string, cookie string) {

	db := Opendb()
	defer db.Close()

	/*stmt, err := db.Prepare("UPDATE http SET SYSTEM=?, USERNAME=? WHERE IP=?")
	SqlcheckErr(err)*/

	res, err := db.Exec("UPDATE http SET SYSTEM=?, USERNAME=? WHERE IP=?", system, username, cookie)
	SqlcheckErr(err)

	affect, err := res.RowsAffected()
	SqlcheckErr(err)

	fmt.Println(affect)

}
````
