### ISSUE TITLE
request for new release

### ISSUE THREAD

**Issue by kamyuentse** [mattn/go-sqlite3#1159]
Hi, @mattn 

I want to use the serialize/deserialize feature https://github.com/mattn/go-sqlite3/pull/1089 , which is not included in the latest release. Any plan to publish a new release?

**Comment by sagarishere** [comment]
I want to use the inbuilt json support of sqlite as well.

**Comment by rittneje** [comment]
@mattn what do you think? I am not familiar with the release process.

**Comment by rittneje** [comment]
Closing because the feature in question was included in [v1.14.17](https://github.com/mattn/go-sqlite3/releases/tag/v1.14.17).
