### ISSUE TITLE
Build failure with musl 1.2.4

### ISSUE THREAD

**Issue by jefferyto** [mattn/go-sqlite3#1164]
OpenWrt updated musl to 1.2.4 and we are seeing this build failure with [ooni/probe-cli](https://github.com/ooni/probe-cli) (which uses go-sqlite3):

```
sqlite3-binding.c:35911:42: error: 'pread64' undeclared here (not in a function); did you mean 'pread'?
35911 |   { "pread64",      (sqlite3_syscall_ptr)pread64,    0  },
      |                                          ^~~~~~~
      |                                          pread
sqlite3-binding.c:35929:42: error: 'pwrite64' undeclared here (not in a function); did you mean 'pwrite'?
35929 |   { "pwrite64",     (sqlite3_syscall_ptr)pwrite64,   0  },
      |                                          ^~~~~~~~
      |                                          pwrite
sqlite3-binding.c: In function 'seekAndRead':
sqlite3-binding.c:35915:49: error: unknown type name 'off64_t'; did you mean 'off_t'?
35915 | #define osPread64 ((ssize_t(*)(int,void*,size_t,off64_t))aSyscall[10].pCurrent)
      |                                                 ^~~~~~~
sqlite3-binding.c:38777:11: note: in expansion of macro 'osPread64'
38777 |     got = osPread64(id->h, pBuf, cnt, offset);
      |           ^~~~~~~~~
sqlite3-binding.c:35915:58: error: expected ')' before 'aSyscall'
35915 | #define osPread64 ((ssize_t(*)(int,void*,size_t,off64_t))aSyscall[10].pCurrent)
      |                   ~                                      ^~~~~~~~
sqlite3-binding.c:38777:11: note: in expansion of macro 'osPread64'
38777 |     got = osPread64(id->h, pBuf, cnt, offset);
      |           ^~~~~~~~~
sqlite3-binding.c: In function 'seekAndWriteFd':
sqlite3-binding.c:35933:57: error: unknown type name 'off64_t'; did you mean 'off_t'?
35933 | #define osPwrite64  ((ssize_t(*)(int,const void*,size_t,off64_t))\
      |                                                         ^~~~~~~
sqlite3-binding.c:38906:17: note: in expansion of macro 'osPwrite64'
38906 |   do{ rc = (int)osPwrite64(fd, pBuf, nBuf, iOff);}while( rc<0 && errno==EINTR);
      |                 ^~~~~~~~~~
sqlite3-binding.c:35934:21: error: expected ')' before 'aSyscall'
35934 |                     aSyscall[13].pCurrent)
      |                     ^~~~~~~~
sqlite3-binding.c:38906:17: note: in expansion of macro 'osPwrite64'
38906 |   do{ rc = (int)osPwrite64(fd, pBuf, nBuf, iOff);}while( rc<0 && errno==EINTR);
      |                 ^~~~~~~~~~
sqlite3-binding.c:35933:21: note: to match this '('
35933 | #define osPwrite64  ((ssize_t(*)(int,const void*,size_t,off64_t))\
      |                     ^
sqlite3-binding.c:38906:17: note: in expansion of macro 'osPwrite64'
38906 |   do{ rc = (int)osPwrite64(fd, pBuf, nBuf, iOff);}while( rc<0 && errno==EINTR);
      |                 ^~~~~~~~~~
```

(This is from a PR for the current version of probe-cli which uses 1.14.16; we are also seeing very similar errors when building an older version of probe-cli which uses 1.14.15.)

This is because in musl 1.2.4, LFS64 interfaces were marked as deprecated ([release notes](https://musl.libc.org/releases.html), [commit](https://git.musl-libc.org/cgit/musl/commit/?h=v1.2.4&id=25e6fee27f4a293728dd15b659170e7b9c7db9bc)).

Perhaps `HAVE_PREAD`/`HAVE_PWRITE` can be set instead of `HAVE_PREAD64`/`HAVE_PWRITE64` in sqlite3.go?

**Comment by omerxx** [comment]
Not sure how come this isn't extremely urgent to users out there but the #1177 save me.
So for what it's worth I added this to my `go.mod`:
```golang
replace github.com/mattn/go-sqlite3 => github.com/leso-kn/go-sqlite3 v0.0.0-20230710125852-03158dc838ed
```

**Comment by nekopsykose** [comment]
you can use `CGO_CFLAGS="-D_LARGEFILE64_SOURCE"` as a workaround too.

**Comment by doesnmisclown** [comment]
Issue doesn't fix for me
![IMG_20230716_111334_171](https://github.com/mattn/go-sqlite3/assets/116358854/8dc27e2b-5511-4815-b71c-08b4ceed0db2)

**Comment by avakarev** [comment]
This is now broken in latest `go:alpine` image (`1.21.5-alpine3.19`).
Alpine 3.19 was released on 2023-12-07: https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html
It is shipped with `gcc` 13.2 and `musl-dev` 2.14 https://pkgs.alpinelinux.org/packages?name=musl-dev&branch=v3.19&repo=&arch=x86_64

As a temporary workaround, it's possible to downgrade base go image to `go:alpine3.18` in Dockerfile.

\cc @mattn

**Comment by bassosimone** [comment]
@mattn can you take a look at this issue? It seems it's breaking a lot of go-sqlite3 builds with musl! 🙏

**Comment by mattn** [comment]
See https://github.com/mattn/go-sqlite3/pull/1177

**Comment by dagenius007** [comment]
> you can use `CGO_CFLAGS="-D_LARGEFILE64_SOURCE"`(passed to `go` via environment when building) as a workaround too.

This worked for me

**Comment by r10r** [comment]
@mattn  Can this be closed because the fix is included in [**v1.14.19**](https://github.com/mattn/go-sqlite3/tree/v1.14.19) ?

I can successfully build on alpine with musl 1.2.4 after upgrading
```
go get github.com/mattn/go-sqlite3@v1.14.19
```

**Comment by davidindra** [comment]
I agree with @r10r, upgrading to 1.14.19 fixes the issue.

**Comment by martinrode** [comment]
This fails with `alpine-3.19` too. Any attempts to fix this?

**Comment by rittneje** [comment]
@martinrode which version of this library are you using?

**Comment by martinrode** [comment]
> @martinrode which version of this library are you using?

The latest released version v1.14.16

**Comment by rittneje** [comment]
@martinrode the latest release is v1.14.22

**Comment by rittneje** [comment]
Closing because this issue is resolved in [v1.14.19](https://github.com/mattn/go-sqlite3/releases/tag/v1.14.19).
If you are still experiencing this issue, please first confirm you are using at least that version. (The GitHub releases page does not consider tags and thus is out of date.)

**Comment by martinrode** [comment]
It's fine. Works with TAG checkout v1.14.22. I checked Github Releases only and there the latest is .16.

**Comment by SloCompTech** [comment]
If anyone is still looking for solution, this worked for me:
```bash
# Remove previous dependency link
go mod edit -droprequire=github.com/mattn/go-sqlite3

# Add new dependecy link with newest version
go mod edit -require=github.com/mattn/go-sqlite3@v1.14.28

# Update package cache
go mod tidy

# Then build your go project/lib
```

**Comment by juliandecoss** [comment]
@SloCompTech  perfect Solution, @1.14.17 has that problem, updating it.
