### ISSUE TITLE
difference between linux build vs libsqlite3 linux

### ISSUE THREAD

**Issue by meetme2meat** [mattn/go-sqlite3#1171]
I'm a bit confused about `linux` build vs `libsqlite3 linux` build all my past experiences whenever I used a sqlite3 database all the wrappers were compiled against libsqlite3 binding. So I'm not sure what is the difference between them?

Also, According to the sqlite3  https://www.sqlite.org/threadsafe.html

But then I read this in README.md. says it not enable with build tag libsqlite3 

```
Serialized. In serialized mode, SQLite can be safely used by multiple threads with no restrictions. But the read say it support for serialisation is default unless the build tag is libsqlite3.
```

Enable Serialization with libsqlite3 | sqlite_serialize | Serialization and deserialization of a SQLite database is available by default, unless the build tag libsqlite3 is set.To enable this functionality even if libsqlite3 is set, add the build tag sqlite_serialize.
-- | -- | --

**Comment by rittneje** [comment]
There is no `linux` build tag.

By default this library statically links against the bundled version of SQLite3. If you use the `libsqlite3` build tag, then it will instead be dynamically linked against the system library.

The `sqlite_serialize` build tag is referring to the `Serialize` and `Deserialize` methods, not the thread safety of the database connection. See https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_serialize.go
