### ISSUE TITLE
package using go-sqlite3 fails to compile

### ISSUE THREAD

**Issue by ezplanet** [mattn/go-sqlite3#1174]
I have a package that depends on gorm sqlite which in turns depends on this library.

The package compiles without errors on a raspberry pi running raspbian buster with go lang version 1.11.6.
I have another Rpi 3 running bullseye (fresh install and updated to the latest), go version is 1.15.15.

The new installation involved go getting all the dependencies required for the package.
On this platform the package fails to compile with the following error:
```
[...]
github.com/eclipse/paho.mqtt.golang
# github.com/mattn/go-sqlite3
../github.com/mattn/go-sqlite3/sqlite3_opt_serialize.go:41:26: undefined: math.MaxInt
```

I tried all the suggestions found in a similar report and in README.md without success including
```
apt install gcc-arm*
```
and compile using:
```
env CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++     CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7     go build -v
```
That should not really be necessary on a raspberry Pi.

This looks like a bug.

**Comment by rittneje** [comment]
As mentioned in the [README](https://github.com/mattn/go-sqlite3#description), this library supports Go 1.18+. `math.MaxInt` was introduced in [Go 1.17](https://tip.golang.org/doc/go1.17#math).
