### ISSUE TITLE
Why does the compilation freeze after importing go-sqlite3

### ISSUE THREAD

**Issue by 1nformation** [mattn/go-sqlite3#1180]
![image](https://github.com/mattn/go-sqlite3/assets/93757156/a0d97eb3-8ef6-487c-af9d-19340ca7e3a3)
![image](https://github.com/mattn/go-sqlite3/assets/93757156/d4c6327b-7d17-4476-8d88-802389b50fcc)
![image](https://github.com/mattn/go-sqlite3/assets/93757156/97c7c50b-ea3e-4aef-97ef-ae47d8bf8171)

**Comment by 1nformation** [comment]
I used gin

**Comment by 1nformation** [comment]
![image](https://github.com/mattn/go-sqlite3/assets/93757156/9b8dc019-3805-4296-a750-017e8cebc6c7)

**Comment by 1nformation** [comment]
@mattn

**Comment by rittneje** [comment]
Is it actually frozen, or just slow? It can take a while for your computer to build this library due to the C code.

Also, in the future, please do not share code as an image. Use a code block like so:
````
```go
package main

...
```
````

**Comment by 1nformation** [comment]
It is frozen

**Comment by 1nformation** [comment]
> Is it actually frozen, or just slow? It can take a while for your computer to build this library due to the C code.
> 
> Also, in the future, please do not share code as an image. Use a code block like so:
> 
> ```
> ```go
> package main
> 
> ...
> ```
> ```

When I remove go-sqlite3, the project is programmed fine

**Comment by 1nformation** [comment]
I think I know what the problem is, thanks
