### ISSUE TITLE
Installation Failed?

### ISSUE THREAD

**Issue by cabexius** [mattn/go-sqlite3#1181]
Help guys? (os: centos-7)

not sure what i am doing wrong , am i trying to install the package, but it is failing?

[cabexius@jellybean tmp]$ CGO_ENABLED=1 go install github.com/mattn/go-sqlite3@latest
go: downloading github.com/mattn/go-sqlite3 v1.14.17
package github.com/mattn/go-sqlite3 is not a main package
[cabexius@jellybean tmp]$ go version
go version go1.20.6 linux/amd64
[cabexius@jellybean tmp]$

**Comment by cabexius** [comment]
a bit weird, but have managed to get it working. closing this out. posting simple sequence that got it working on environment

mkdir test
go mod init m.test
go get -u github.com/mattn/go-sqlite3@latest

`package main

import (
        "database/sql"
        "fmt"
        "log"

        _ "github.com/mattn/go-sqlite3"
)

func main() {

        db, err := sql.Open("sqlite3", ":memory:")

        if err != nil {
                log.Fatal(err)
        }

        defer db.Close()

        var version string
        err = db.QueryRow("SELECT SQLITE_VERSION()").Scan(&version)

        if err != nil {
                log.Fatal(err)
        }

        fmt.Println(version)
}`
go build hello.go
./hello

**Comment by rittneje** [comment]
go install is for building applications, hence the error message. There is no reason to build this library (or any other) in isolation.
