### ISSUE TITLE
[Want help] examples of virtual table's Update method

### ISSUE THREAD

**Issue by galaxybyte** [mattn/go-sqlite3#1182]
Is there any examples of virtual table's Update method in the latest version?

**Comment by rittneje** [comment]
Evidently not. https://github.com/mattn/go-sqlite3/blob/master/_example/vtable/vtable.go

**Comment by galaxybyte** [comment]
Thank you, I find it in the unit test: https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_vtable_test.go
