### ISSUE TITLE
[Want help] How to use compiled go-sqlite3 on Windows?

### ISSUE THREAD

**Issue by nur91m** [mattn/go-sqlite3#1183]
I need to use sqlite with case-insensitive future in my project. So I build with 
`go build -tags "icu"`

This command executed without any issue. But it also doesn't give any message that the command was executed successfully. My question is how to use the compiled go-sqlite3 in my go app? I've been googling, chatting with GPT to get any information about using compiled sqlite.

**Comment by otoolep** [comment]
Are you a Go programmer? If so, it should be pretty obvious how to include a Go module like go-sqlite3, right?

https://github.com/mattn/go-sqlite3/blob/master/_example/simple/simple.go

**Comment by rittneje** [comment]
@nur91m As a dotnet developer, you are probably used to a workflow where every library is a DLL that has to be deployed with your application. As @otoolep mentioned, that is not how it typically works in Go; instead you just write your code to import third-party modules in the same way you would your own code (or the standard library), and the compiler will produce a single static executable.

**Comment by nur91m** [comment]
> @nur91m As a dotnet developer, you are probably used to a workflow where every library is a DLL that has to be deployed with your application. As @otoolep mentioned, that is not how it typically works in Go; instead you just write your code to import third-party modules in the same way you would your own code (or the standard library), and the compiler will produce a single static executable.

Thanks. I got it worked after your clarification.
