### ISSUE TITLE
RETURNING directive is not working.

### ISSUE THREAD

**Issue by erudenko** [mattn/go-sqlite3#1184]
Hello dear community.

Sqlite has a support of `RETURNING` directive [from version 3.35](https://www.sqlite.org/lang_returning.html).

I have checked my current version of go-sqlite3:
```go
	a, b, c := sqlite3.Version()
	fmt.Println(a, b, c)

// output:
// 3.39.5 2022-10-14 20:58:05 554764a6e721fab307c63a4f98cd958c8428a5d9d8edfde951858d6fd02daapl
```

It said the current sqlite version is 3.39.

When I use sqlite from my console, which is 3.39.5 as well, everything works fine:

```sql
sqlite> CREATE table a (id varchar not null);
sqlite> insert into a (id) values ('1') RETURNING *;
1
```

But when I am trying to use it with go-sqlite3 driver, I am getting error: `Received unexpected error: near "RETURNING": syntax error`. As soon as I remove RETURNING directive - it works fine.

Do I need to recompile it with some specific extension? 

Thank you!

**Comment by rittneje** [comment]
I am not able to reproduce this error. Can you provide a sample Go program that demonstrates the issue? Also, what version of this wrapper library are you using?

**Comment by cinemast** [comment]
Upgrading from `v1.14.6` to `v1.14.22` resolved this issue for me.
