### ISSUE TITLE
Ordering of query parameters

### ISSUE THREAD

**Issue by itzloop** [mattn/go-sqlite3#1194]
# Description
If my query argument placeholders ($1, $2, ... ) are not in the same order as the arguments I'm passing, affected rows will be 0 in the update queries. I only checked it for update queries.

# How to reproduce

```sql
CREATE TABLE IF NOT EXISTS user_words(
    user_id BIGINT,
    word TEXT,
    last_asked TIMESTAMP,
    PRIMARY KEY(user_id, word)
);

INSERT INTO user_words (user_id, word, last_asked) VALUES
(1, 'word1', '0001-01-01 00:00:00+00:00'),
(2, 'word2', '0001-01-01 00:00:00+00:00'),
(3, 'word3', '0001-01-01 00:00:00+00:00'),
(4, 'word4', '0001-01-01 00:00:00+00:00');
```

And then in go ([playground](https://go.dev/play/p/2OCtA0YlMbw)):
```go
sqlDB, err := sql.Open("sqlite3", "./sample.db")
if err != nil {
	log.Fatalln("failed to connect to db")
}

_, err = sqlDB.ExecContext(context.Background(), `
CREATE TABLE IF NOT EXISTS user_words(
user_id BIGINT,
word TEXT,
last_asked TIMESTAMP,
PRIMARY KEY(user_id, word)
);

INSERT INTO user_words (user_id, word, last_asked) VALUES
(1, 'word1', '0001-01-01 00:00:00+00:00'),
(2, 'word2', '0001-01-01 00:00:00+00:00'),
(3, 'word3', '0001-01-01 00:00:00+00:00'),
(4, 'word4', '0001-01-01 00:00:00+00:00');
`)
if err != nil {
	log.Fatalln(err.Error())
}
rowsAffected, err := sqlDB.ExecContext(context.Background(), `UPDATE user_words SET last_asked = $3 WHERE user_id = $1 AND word = $2`, 1, "word1", time.Now().In(time.UTC))
if err != nil {
	log.Fatalln(err.Error())
}

log.Println(rowsAffected.RowsAffected()) // THIS WILL PRINT: 0, nil
```

Now if you change the ordering ($1, $2, $3), every thing works as expected.

# Environment

| OS                         | Kernel           | CPU                | Go Bin Version       | Sqlite Lib Version |
| -------------------------- | ---------------- | ------------------ | -------------------- | ------------------ |
| Manjaro Linux x86_64 (KDE) | 6.1.51-1-MANJARO | AMD Ryzen 9 6900HS | go1.21.0 linux/amd64 | v1.14.17           |

**Comment by rittneje** [comment]
In SQLite, `$1` means a parameter named `1`, not the first parameter. You need to use `?001` instead. See https://www.sqlite.org/lang_expr.html#varparam
