### ISSUE TITLE
LastInsertId and RowsAffected methods of sqlite.Result object return constant nil error

### ISSUE THREAD

**Issue by paszahipsta** [mattn/go-sqlite3#1198]
https://github.com/mattn/go-sqlite3/blob/9fd6f4ffd3430f64ec35c64063b59af680582e11/sqlite3.go#L2008C55-L2008C55

If the error is constantly nil, there is no reason for keeping it there. Also the syntax of code would be a bit cleaner:

```
if result.RowsAffected() > 10 {
    //do smt
}
```

instead of adding the line for declaring the err variable.
```
res, err := result.RowsAffected()
if err != nil {
return err
}
if res > 10 {
//do smt
}
```

My proposal is to delete the error parameters from these functions as they're not serving any purpose right now.

**Comment by rittneje** [comment]
These are required to meet the driver interface. https://pkg.go.dev/database/sql/driver#RowsAffected
