### ISSUE TITLE
In-memory database access fails with multiple goroutines

### ISSUE THREAD

**Issue by rob94110** [mattn/go-sqlite3#1205]
The following test code works when the data source is a real file, but fails in various ways when using an in-memory store.  Do I need some additional locking in my code?  My reading of the Sqlite documentation and the go-sqlite3 code here indicates that this kind of access is supported, but I could very well be confused.

```
package main

import (
	"database/sql"
	"fmt"
	"testing"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

type store struct {
	db *sql.DB
}

func newStore() *store {
	source := ":memory:"
	// source := ""
	// source := "bug.sql"
	db, err := sql.Open("sqlite3", source)
	if err != nil {
		panic(err)
	}
	s := &store{
		db: db,
	}
	return s
}

func (s *store) create() {
	create := "CREATE TABLE IF NOT EXISTS t (col1 TEXT PRIMARY KEY, col2);"
	_, err := s.db.Exec(create)
	if err != nil {
		panic(err)
	}
}

func (s *store) insert() {
	tx, err := s.db.Begin()
	if err != nil {
		panic(err)
	}

	insert := "INSERT INTO t(col1, col2) VALUES(?, ?);"
	stmt, err := tx.Prepare(insert)
	if err != nil {
		panic(err)
	}
	defer stmt.Close()

	_, err = stmt.Exec(time.Now().String(), "xyz")
	if err != nil {
		panic(err)
	}

	if err := tx.Commit(); err != nil {
		panic(err)
	}
}

func (s *store) query() {
	query := "SELECT col1, col2 FROM t;"
	rows, err := s.db.Query(query)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	for rows.Next() {
		var col1, col2 string
		if err := rows.Scan(&col1, &col2); err != nil {
			panic(err)
		}
		println(col1, col2)
	}
	if err := rows.Err(); err != nil {
		panic(err)
	}
}

func TestBug(t *testing.T) {
	s := newStore()
	s.create()

	go func() {
		for i := 0; ; i++ {
			fmt.Println("insert", i)
			s.insert()
			time.Sleep(1 * time.Second)
		}
	}()

	go func() {
		for i := 0; ; i++ {
			fmt.Println("query", i)
			s.query()
			time.Sleep(1 * time.Second)
		}
	}()

	time.Sleep(5 * time.Second)
}
```

When I run it I get results such as:

```
go test -v ./...
=== RUN   TestBug
query 0
insert 0
query 1
insert 1
2024-01-20 17:55:57.655678 -0800 PST m=+0.001661626 xyz
panic: no such table: t

goroutine 7 [running]:
bug.(*store).insert(0x102957858?)
	/Users/rob/work/go-sqlite3-test/bug_test.go:47 +0x160
bug.TestBug.func1()
	/Users/rob/work/go-sqlite3-test/bug_test.go:88 +0x8c
created by bug.TestBug in goroutine 5
	/Users/rob/work/go-sqlite3-test/bug_test.go:85 +0x64
FAIL	bug	1.178s
FAIL
```
The first couple of inserts and queries succeeded, and then I get the "no such table" error.

Any insight into what's going wrong here would be much appreciated.

Thanks.

**Comment by rob94110** [comment]
Of course as soon as I posted this I found the FAQ entries that somehow I had missed.  To recap for anyone else stumbling around, without the `?cache=shared` flag any additional database connections that are used internally from a connection pool will see different databases, and therefore can run into the "no such table" problem.

But enabling the shared cache flag will now potentially cause a "database table is locked" error if multiple goroutines attempt to access the table.  So some kind of application-level locking is required to handle that.

**Comment by rittneje** [comment]
@rob94110 The modern recommendation is to use the memdb vfs (i.e., `file:/foobar?vfs=memdb`), not shared cache. Note that the leading slash is required.

**Comment by rob94110** [comment]
Thank you!  I can't find any definitive documentation for this feature for some reason.

**Comment by iutx** [comment]
> @rob94110 The modern recommendation is to use the memdb vfs (i.e., `file:/foobar?vfs=memdb`), not shared cache. Note that the leading slash is required.

I took this approach, but it would cause `no such table` error sometimes. :(
