### ISSUE TITLE
"NOT json_valid(NULL)" unexpected empty result (works in CLI)

### ISSUE THREAD

**Issue by tommyblue** [mattn/go-sqlite3#1224]
We have a query where returns an empty result when`json_valid` is called on a `NULL` value, but only in the library. The query, when executed through SQLite3 command line returns the expected result.

A workaround is to remove the `json_valid` check replacing with a simple "IS NULL".

The fact that the issue only happens when using the go-sqlite3 library let me think to a possible bug, so I'm posting here.
Let me know if we can provide additional info.

This is the query:

```sql
SELECT ac.*
FROM alarm_categories AS ac
	LEFT JOIN alarm_categories_alarms AS aca ON ac.id = aca.alarm_category_id
	LEFT JOIN alarm_categories_time_slots AS acts ON ac.id = acts.alarm_category_id
	LEFT JOIN time_slots AS ts ON acts.time_slot_id = ts.id
	LEFT JOIN json_each(ts.slots) AS slot ON 1
WHERE 
	aca.alarm_id = ? 
	AND ac.enabled 
	AND CASE
		WHEN ts.type = 'date' THEN ts.start <= strftime('%s', 'now') AND ts.end >= strftime('%s', 'now')
		WHEN ts.type = 'weekly' THEN INSTR(ts.days, strftime('%w', 'now')) > 0 -- there are no double digits since weekday is 0-6
		ELSE FALSE
	END 
	AND (
		NOT json_valid(slot.value) -- <<< the issue is here
		OR (
			strftime('%H:%M', 'now') >= json_extract(slot.value, '$.from') 
			AND 
			strftime('%H:%M', 'now') <= json_extract(slot.value, '$.to')
		)
	)
ORDER BY level
LIMIT 1;
```

And this is the fixed version:

```sql
SELECT ac.*
FROM alarm_categories AS ac
	LEFT JOIN alarm_categories_alarms AS aca ON ac.id = aca.alarm_category_id
	LEFT JOIN alarm_categories_time_slots AS acts ON ac.id = acts.alarm_category_id
	LEFT JOIN time_slots AS ts ON acts.time_slot_id = ts.id
	LEFT JOIN json_each(ts.slots) AS slot ON 1
WHERE 
	aca.alarm_id = ? 
	AND ac.enabled 
	AND CASE
		WHEN ts.type = 'date' THEN ts.start <= strftime('%s', 'now') AND ts.end >= strftime('%s', 'now')
		WHEN ts.type = 'weekly' THEN INSTR(ts.days, strftime('%w', 'now')) > 0 -- there are no double digits since weekday is 0-6
		ELSE FALSE
	END 
	AND (
		NOT slot.value IS NULL -- <<< this is the "fix"
		OR (
			strftime('%H:%M', 'now') >= json_extract(slot.value, '$.from') 
			AND 
			strftime('%H:%M', 'now') <= json_extract(slot.value, '$.to')
		)
	)
ORDER BY level
LIMIT 1;
```

**Comment by rittneje** [comment]
https://www.sqlite.org/json1.html#jvalid

> If either X or Y inputs to json_valid() are NULL, then the function returns NULL. 

This behavior was changed in SQLite itself at some point. With the 3.34.1 CLI, I see:
```
sqlite> select json_valid(null);
0
```

With 3.46.0, I see:
```
sqlite> json_valid(null)
NULL
```

Closing because there is nothing we can do about a breaking change in SQLite itself. If you feel strongly about it, please open an issue in the [forum](https://sqlite.org/forum/forummain) (but they are extremely unlikely to do anything about it).

**Comment by tommyblue** [comment]
@rittneje thanks for the quick answer, aligning the CLI and lib versione the behaviour is now coherent between the two 🖖🏼
