### ISSUE TITLE
Database file does not get created when using connection string

### ISSUE THREAD

**Issue by tcarlton2000** [mattn/go-sqlite3#1226]
I am trying to create an app in a docker image that will auto-create the SQLite database if it does not exist. This works properly when I open the database using `db, err := sql.Open("sqlite3", "test.db")`. However, I want to create separate read and write connections so that reads are not blocked by writes. If I change the command to `db, err := sql.Open("sqlite3", "file:test.db?mode=rw")` to enable this, I get the error `unable to open database file: no such file or directory` if the database file does not already exist. What do I need to do in order to use connection strings and have the database file created if it doesn't exist.

**Comment by otoolep** [comment]
See https://github.com/rqlite/rqlite/blob/master/db/db.go#L140 to see how rqlite does exactly what you want.

Not sure what's going wrong for you, but looking at working code might help.

**Comment by otoolep** [comment]
Open rw connection: https://github.com/rqlite/rqlite/blob/master/db/db.go#L156

Open ro connection: https://github.com/rqlite/rqlite/blob/master/db/db.go#L168

**Comment by rittneje** [comment]
If you want it to auto-create the database file, you'll need `mode=rwc` not `mode=rw`. See https://www.sqlite.org/c3ref/open.html#urifilenamesinsqlite3open

**Comment by tcarlton2000** [comment]
That worked. Thanks.
