### ISSUE TITLE
Segmentation Violation

### ISSUE THREAD

**Issue by cloudtriquetra** [mattn/go-sqlite3#1265]
ERROR
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104957ae8]

goroutine 1 [running]:
database/sql.(*DB).conn(0x20?, {0x104ae4c10?, 0x104bef100?}, 0x80?)
        /usr/local/go/src/database/sql/sql.go:1310 +0x28
database/sql.(*DB).exec(0x0, {0x104ae4c10, 0x104bef100}, {0x104a84a6f, 0x90}, {0x0, 0x0, 0x0}, 0x50?)
        /usr/local/go/src/database/sql/sql.go:1679 +0x40
database/sql.(*DB).ExecContext.func1(0xc8?)
        /usr/local/go/src/database/sql/sql.go:1662 +0x54
database/sql.(*DB).retry(0x1400006be68?, 0x1400006be40)
        /usr/local/go/src/database/sql/sql.go:1566 +0x4c
database/sql.(*DB).ExecContext(0x1400006bee8?, {0x104ae4c10?, 0x104bef100?}, {0x104a84a6f?, 0x104ae4968?}, {0x0?, 0x1400006bf38?, 0x1048e37f8?})
        /usr/local/go/src/database/sql/sql.go:1661 +0x94
database/sql.(*DB).Exec(...)
        /usr/local/go/src/database/sql/sql.go:1675
main.createTables()
        /Users/arkaprava/code/d/main.go:25 +0x4c
main.InitDB()
        /Users/arkaprava/code/d/main.go:17 +0x44
main.main()
        /Users/arkaprava/code/d/main.go:32 +0x1c
exit status 2
```

**Comment by cloudtriquetra** [comment]
Code

package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
)

var DB *sql.DB

func InitDB() {
	DB, err := sql.Open("sqlite3", "./effort.db")
	if err != nil {
		panic("Error opening database: " + err.Error())
	}
	DB.SetMaxOpenConns(1)
	createTables()
}

func createTables() {
	createTables := `CREATE TABLE IF NOT EXISTS efforts (
    effort_id               INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name           text NOT NULL
);`
	_, err := DB.Exec(createTables)
	if err != nil {
		panic("Effort DB Creation Failed" + err.Error())
	}
}

func main() {
	InitDB()
}

**Comment by cloudtriquetra** [comment]
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/arkaprava/Library/Caches/go-build'
GOENV='/Users/arkaprava/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/arkaprava/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/arkaprava/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'

**Comment by 0xts** [comment]
@cloudtriquetra Did you manage to get it to work? Facing same issue? Even though the import is added for the driver.

**Comment by cloudtriquetra** [comment]
> @cloudtriquetra Did you manage to get it to work? Facing same issue, even though the import is added for the driver.

https://www.reddit.com/r/golang/s/nOI7HdAY3W

**Comment by mattn** [comment]
Variable DB in initDB is local variable. So global DB is not updated.

**Comment by ahmedIbrahimmahmud** [comment]
the problem is DB is local to InitDB() function when you try to access it in createTable() function it will return nil.
to resolve your issue is to declare the err in initDB like
var err
DB, err = sql.Open("sqlite3", "./effort.db")
