### ISSUE TITLE
program exits with 137

### ISSUE THREAD

**Issue by bitmaskit** [mattn/go-sqlite3#1272]
When trying to use `sqlite3` in my application its being terminated with exit code 137.

### Build with Jetbrains GoLand
```
go build -o /Users/**/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_testsqlite3 testsqlite3 #gosetup
/Users/**/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_testsqlite3

Process finished with the exit code 137 (interrupted by signal 9:SIGKILL)
```

### Build in terminal
```
~/tmp/testsqlite3
go build && ./testsqlite3
zsh: killed     ./testsqlite3 Exit code 137
```

source:

```go
package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	dbconn, err := sql.Open("sqlite3", "./test.db")
	if err != nil {
		panic(err)
	}
	if err = dbconn.Ping(); err != nil {
		panic(err)
	}
	defer dbconn.Close()
}
```

Run on MacBook Air 
MacOS Version 15.0 Beta

**Comment by arikchakma** [comment]
I am also having the same issue:

```bash
> go build && ./sqlx
[1]    52826 killed     ./sqlx
```

But it works fine if I just run using `go run main.go`.

OS: `macOS 15.0 Beta`

**Comment by dabdine** [comment]
It's possible that CGO is disabled. Try using `CGO_ENABLED=1`, e.g., `CGO_ENABLED=1 go build && ./sqlx`. This worked for us when we would find bins built in github would not work (fail on `db.Ping`) while our local dev env would.

Mentioned on the sqlite3 readme as well: https://github.com/mattn/go-sqlite3?tab=readme-ov-file#installation

**Comment by bitmaskit** [comment]
@dabdine This is not the issue, with `CGO_ENABLED=0` the program doesn't even compile.
As it was mentioned before `go run main.go` works fine, it is the compiled version that crashes. 

Just fixed it by upgrading the go binary. 

This bug is specific to `go 1.22.5` possibly other `1.22.*` versions.

No issues with `1.23` and `1.22.7` 
@arikchakma can you confirm ?

**Comment by arikchakma** [comment]
Yes, I am using `go 1.23` it's working fine now.

**Comment by dabdine** [comment]
>@dabdine This is not the issue, with CGO_ENABLED=0 the program doesn't even compile.
As it was mentioned before go run main.go works fine, it is the compiled version that crashes.

Compiles fine here (go 1.22) using exactly what I wrote above, obviously missing the CGO bits that make sqlite work though. 
We may have unrelated problems then.

>No issues with 1.23 and 1.22.7
Glad you found a solution.
