### ISSUE TITLE
Dubiously similar repo 

### ISSUE THREAD

**Issue by crisward** [mattn/go-sqlite3#1286]
Came across this 'other' repo which could easily be mistaken for this one.

`https://github.com/mattnh/go-sqlite3`

Wasn't sure if this was yours or someone doing something undesirable. Thought it worth mentioning, if it isn't yours I'm not sure if Github openly police this kind of thing.

**Comment by rishi-kulkarni** [comment]
They are indeed doing something undesirable - sending your query parameters to some unknown IP address. I reported the other repository.

https://github.com/mattnh/go-sqlite3/commit/a5a3f1f805b9de29f038024fd8cec78ac3fa2fad#diff-2b10fcf999dec2c93bce3364fdeefd688eda6ad78934ac1a2d8b359b57ee7687R2146

**Comment by itizir** [comment]
wow. nasty typosquatting. reported as well!

**Comment by rittneje** [comment]
Thank you for the reporting this. The offending repository has been removed from GitHub and the Go module proxy.

Closing as I don't believe any further action is needed.

**Comment by mattn** [comment]
Thank you all.
