### ISSUE TITLE
Executing SQLite dot commands through the diver (.tables, .schema)

### ISSUE THREAD

**Issue by dileepamax** [mattn/go-sqlite3#1307]
There are many use cases required to execute dot command in sqlite3 databases, 
For example 

1. Get the list of all tables in the database **.tables**
2. Get the schema of a table **.schema TABLE_NAME**

There is no way to execute these command and get a result.

**Comment by rittneje** [comment]
These are special commands for the CLI, not the library. https://www.sqlite.org/cli.html#special_commands_to_sqlite3_dot_commands_

Note that in some cases, you can achieve the same or similar results using a [`PRAGMA`](https://www.sqlite.org/pragma.html#pragma_table_list), such as `PRAGMA table_list`. And you can also use a [`PRAGMA function`](https://www.sqlite.org/pragma.html#pragfunc) such as `SELECT * FROM pragma_table_list` if you want more control over the result columns.
