### ISSUE TITLE
How to make extensions go gettable

### ISSUE THREAD

**Issue by 0x6e6562** [mattn/go-sqlite3#141]
I'd like to include support for md5 via a loadable extension, which I've been able to compile and load as per the documentation. I can successfully run this by configuring:

``` go
sql.Register("sqlite3_ext", &sqlite3.SQLiteDriver{ Extensions: []string{"md5"} })

db, err := sql.Open("sqlite3_ext", "/tmp/db")
```

And the function seems to execute fine.

The issue is that the extension is built using a Makefile (in my case md5.dylib) and this gets loaded dynamically. So if I want to distribute application with this, how would I go about making it available using go get? Presumably I'm going to have include some steps to get the shared library into the same location and this compiled Go app? Or is there a way to statically link the extension, so that whole thing is go gettable?

**Comment by patrickdevivo** [comment]
I'm very curious to know how to accomplish something similar, but with the [csv virtual table](http://www3.sqlite.org/csv.html) extension. Thank you for posting your resolution @0x6e6562 - it's been very helpful in understanding possible approaches, but I'm struggling to get successful results. It may be something I'm missing in my approach, but if you have any insights why the csv vtable might be different from the md5 extension, I'd love to know! (6 years later 😄 )
