### ISSUE TITLE
Prepared statement are broken after sqlite error

### ISSUE THREAD

**Issue by threez** [mattn/go-sqlite3#150]
I created a prepared statement for an `INSERT`. If the insert failed, e.g. because a `UNIQUE` constraint was violated, the prepared statement is broken and needs to be recreated in order to work again.

I have an example project, [here](https://github.com/UserStack/ustackd/blob/master/backends/sqlite.go#L159-L160) where you can find the code to recreate the statement. If i remove it, my tests fail. I created a simple version of the problem here:

``` go
package main

import (
    "database/sql"
    "fmt"
    _ "github.com/mattn/go-sqlite3"
)

func main() {
    var db *sql.DB
    db, _ = sql.Open("sqlite3", ":memory:")
    db.Exec(`CREATE TABLE IF NOT EXISTS Users (
        uid INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        CONSTRAINT SingleKeys UNIQUE (name) ON CONFLICT ROLLBACK
    );`)
    stmt, _ := db.Prepare(`INSERT INTO Users (name) VALUES (?);`)
    _, e1 := stmt.Exec("test")
    fmt.Printf("Should NOT return error: %s\n", e1)
    _, e2 := stmt.Exec("test")
    fmt.Printf("Should return error: %s\n", e2)
    _, e3 := stmt.Exec("test1")
    fmt.Printf("Should NOT return error: %s\n", e3)
    stmt1, _ := db.Prepare(`INSERT INTO Users (name) VALUES (?);`)
    _, e4 := stmt1.Exec("test1")
    fmt.Printf("Should NOT return error: %s\n", e4)
}
```

**Comment by antoine-lizee** [comment]
This got me stuck for a while. I updated because of this thread, and now it works fine. Thanks!
