### ISSUE TITLE
The exe can't run when I use -race flag for "go build"

### ISSUE THREAD

**Issue by varding** [mattn/go-sqlite3#154]
I build the simple code below with -race flag,when I run the exe,windows popup a dialog show the exe is stopped.

build: go build -race main

If I build the code without the -race flag,everything is fine

---

If I comment the "ping" statement,leaving only the open and close statement,the is works fine with -race flag
## All the code is below:

package main

import (
    "database/sql"
    "fmt"
    _ "github.com/mattn/go-sqlite3"
)

func main() {
    db, err := sql.Open("sqlite3", "./test.db")
    if err != nil {
        fmt.Println("err%+v", err)
        return
    }
    defer db.Close()

```
err = db.Ping()
if err != nil {
    panic(err.Error())
}
fmt.Println("ok")
```

}

**Comment by GJRTimmer** [comment]
Outdated; Closed
