### ISSUE TITLE
error on execute example code

### ISSUE THREAD

**Issue by Spefer** [mattn/go-sqlite3#163]
On Win7 64bit, go1.4(64bit). there is a error on execute example code, I have got compile successfully.
Exception 0xc0000005 0x8 0x64d138 0x64d138
PC=0x64d138
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc_sqlite3_exec(0xbd68e8, 0xbd7bc0, 0x0, 0x0, 0x0, 0xc000000000)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:266 +0x4a
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc08202c018, 0x5cd3f0, 0x54, 0x0, 0x0, 0x0, 0x0)
	D:/golang/goath/src/github.com/mattn/go-sqlite3/sqlite3.go:227 +0xca
github.com/mattn/go-sqlite3.(*SQLiteConn).Exec(0xc08202c018, 0x5cd3f0, 0x54, 0x66f9d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/golang/goath/src/github.com/mattn/go-sqlite3/sqlite3.go:166 +0x92
database/sql.(*DB).exec(0xc08204e000, 0x5cd3f0, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/database/sql/sql.go:898 +0x2e9
database/sql.(*DB).Exec(0xc08204e000, 0x5cd3f0, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/database/sql/sql.go:875 +0xd4
main.main()
	D:/mwserver/src/sqlite_test/main.go:24 +0x1df

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc08204e000)
	c:/go/src/database/sql/sql.go:589 +0x53
created by database/sql.Open
	c:/go/src/database/sql/sql.go:452 +0x323
rax     0x0
rbx     0x3
rcx     0x94
rdx     0x5e11a0
rdi     0x1
rsi     0xbd7860
rbp     0x0
rsp     0x22f7b8
r8      0x1
r9      0x0
r10     0x0
r11     0x203
r12     0x0
r13     0x3
r14     0x2
r15     0x0
rip     0x64d138
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by mattn** [comment]
Could you please show me the way to reproduce?

**Comment by Spefer** [comment]
@mattn 

PC envrionment: Win7 64bit, go 1.4 64bit, editor(liteide)

1. I use "go get" this code to my local gopath folder
2. then I copy simple code under your code folder "github.com\mattn\go-sqlite3\_example\simple\simple.go"to a new go file like "sqlite_test.go" in my command project
3. compile it and try to run it

get that kind of error when execute sqlite_test.exe
file

**Comment by mattn** [comment]
Could you please check this issue is same as https://github.com/golang/go/issues/9356 ?

**Comment by Spefer** [comment]
@mattn yes, it is the same,thank for your feedback

**Comment by mattn** [comment]
Should be fixed by golang/go#9356
