### ISSUE TITLE
Compiling error on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by forhappy** [mattn/go-sqlite3#167]
<pre>
☁  go-sqlite3 [master] go build
# _/Users/hpfu/SCM-Repos/GitHub/go-sqlite3
In file included from ./backup.go:9:
./sqlite3.h:35:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>     /* Needed for the definition of va_list */
         ^
1 error generated.
</pre>

**Comment by forhappy** [comment]
<pre>
☁  go-sqlite3 [master] go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hpfu/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.3.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.3.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
</pre>

**Comment by mattn** [comment]
You don't have stdarg.h, right?

**Comment by forhappy** [comment]
I update my gcc to gcc-4.9, it works fine now, thanks ；-）

**Comment by mattn** [comment]
Well, you didn't use gcc before you install.

    CC="clang"

**Comment by sekimura** [comment]
I just ran into the exact same issue today and found out what was going on. I did installed clang on my Mac in the past from http://clang.llvm.org/ . Somehow I deleted all builtin headers placed at $(dirname /path/to/tool)/../lib/clang/3.3/include. As a result /usr/local/bin/clang could not find stdarg.h

Using /usr/bin/clang, which I believe it's a hard link to the clang from Xcode command line tools, solved the issue.

HTH
