### ISSUE TITLE
cgo.exe exit status:2 not building my code

### ISSUE THREAD

**Issue by seshu3564** [mattn/go-sqlite3#168]
c:/go/bin/go.exe build  [C:/go/src]
go build github.com/mattn/go-sqlite3: c:\go\pkg\tool\windows_amd64\cgo.exe: exit status 2
Error: process exited with code 1.

**Comment by mattn** [comment]
Could you please try:

```
$ go get -x github.com/mattn/go-sqlite3
```

**Comment by seshu3564** [comment]
![image](https://cloud.githubusercontent.com/assets/10649817/5869609/cc4be95c-a2e1-11e4-8179-580f9073a765.png)

the program cant start bcoz zlib1.dll missing from computer

**Comment by mattn** [comment]
It seems that your installation of mingw has problem.

**Comment by seshu3564** [comment]
thanks for the answer. problem is with my mingw or gcc.  rectified it by installing neatly...

**Comment by mattn** [comment]
Cool

**Comment by AkhilaSharma** [comment]
go build VistaraGoAgent/thirdparty/github.com/cloudfoundry/gosigar: C:\Go\pkg\to
ol\windows_amd64\cgo.exe: exit status 2.It is showing this error .
can u please tell me what the problem is ?Please reply as soon as possible.

**Comment by mattn** [comment]
try `go build -x`

**Comment by AkhilaSharma** [comment]
xml3.go:7:2: cannot find package "xmlfunc" in any of:
        C:\Go\src\xmlfunc (from $GOROOT)
        A:\goworkspace\src\xmlfunc (from $GOPATH).
got this error

**Comment by mattn** [comment]
you need to get xmlfunc your self. sorry i don't know that xmlfunc is.

**Comment by AkhilaSharma** [comment]
xml function is existing but still it is showing error.can u please tell me some other way to resolve this error.plz rply asap.

**Comment by mattn** [comment]
Sorry, probably it's not issue of go-sqlite3.

**Comment by AkhilaSharma** [comment]
ok ok .thanks

**Comment by Ollicicilly** [comment]
C:\Users\Puck\go\src>go get -x github.com\mattn\go-sqlite3
WORK=C:\Users\Puck\AppData\Local\Temp\go-build444513126
mkdir -p $WORK\github.com\mattn\go-sqlite3\_obj\
mkdir -p $WORK\github.com\mattn\
cd C:\Users\Puck\go\src\github.com\mattn\go-sqlite3
CGO_LDFLAGS="-g" "-O2" "-lmingwex" "-lmingw32" "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\Puck\\AppData\\Local\\Temp\\go-build444513126\\github.com\\mattn\\go-sqlite3\\_obj\\" -importpath github.com/mattn/go-sqlite3 -- -I "C:\\Users\\Puck\\AppData\\Local\\Temp\\go-build444513126\\github.com\\mattn\\go-sqlite3\\_obj\\" -g -O2 -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_TRACE_SIZE_LIMIT=15 -Wno-deprecated-declarations -I. -fno-stack-check -fno-stack-protector -mno-stack-arg-probe backup.go callback.go error.go sqlite3.go sqlite3_load_extension.go sqlite3_type.go sqlite3_windows.go
go build github.com/mattn/go-sqlite3: C:\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2

**Comment by msprog** [comment]
hi, I have the same of ur problem
did u solve it?
the error is : go build gocv.io/x/gocv: C:\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2

**Comment by ahdyt** [comment]
> hi, I have the same of ur problem did u solve it? the error is : go build gocv.io/x/gocv: C:\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2

reproducible using mingw from chocolately. Tell me about your story to fix this exit status 2.

**Comment by alexeysp11** [comment]
Recently I've also been facing the problem: `runtime/cgo: C:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2`. You probably need to take the following steps: 
1. Install `TDM-GCC` compiler from [GitHub repo](https://github.com/jmeubank/tdm-gcc) (go to releases and download exe installer) or from [TDM-GCC site](https://jmeubank.github.io/tdm-gcc/download/). 

2. Open command line and execute: 
```
go env GOENV
```
This command returns you a path to env file. 

3. Open env file in any text editor. 

4. Execute in command line:
```
where gcc
```
Copy the path of `TDM-GCC` compiler. 

5. Set `CC` parameter in env file to the path of `TDM-GCC` compiler. 

This worked for me. 

It's also possible to use [SWIG compiler](https://github.com/swig/swig) to compile C/C++ code in golang apps, but I haven't tested it yet.
