### ISSUE TITLE
sqlite3 encrypt API

### ISSUE THREAD

**Issue by denji** [mattn/go-sqlite3#172]
SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files.
- https://github.com/sqlcipher/sqlcipher (SQLCipher Community Edition)

#### Features

- Fast performance with as little as 5-15% overhead for encryption on many operations
- 100% of data in the database file is encrypted
- Good security practices (CBC mode, key derivation)
- Zero-configuration and application level cryptography
- Algorithms provided by the peer reviewed OpenSSL crypto library.
- Configurable crypto providers

**Comment by mattn** [comment]
go-sqlite3 can load extensions.

https://github.com/mattn/go-sqlite3/blob/master/_example/mod_vtable/extension.go#L12-L16

I'm thinking the extension should be possible to load with same way.
