### ISSUE TITLE
time.Time values are scanned in the local timezone

### ISSUE THREAD

**Issue by elwinar** [mattn/go-sqlite3#174]
See [sqlite3.go#L545](https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L545) for example. 

I was wondering why this choice was made ? It would seem more consistent to always scan to UTC, and let the user change the timezone as needed.

**Comment by mattn** [comment]
go-sqlite3 should work as same as another RDBMS (ex. pg). If go-sqlite3 returns UTC, all of ORMs should have conversion for go-sqlite3. I think.

**Comment by elwinar** [comment]
That's a point, but in the other hand, the convention for SQL-stored dates is to always store them in UTC and let the application do the timezone shifting as necessary.

**Comment by mattn** [comment]
@porjo
https://github.com/mattn/go-sqlite3/commit/0b05acc293a940d3bfedf2df5fba12c49ac9ec35

Do you have any opinion?

**Comment by porjo** [comment]
Sorry, I'm a little confused about this myself. According to sqlite3 doco, datetimes stored as TEXT should follow ISO8601. According to Wikipedia for ISO8601, datetime without timezone designator should be read as local time. Go-sqlite3 does not currently do this however, reading them as UTC...

As for dates stored as INTEGER, these will always are always UTC while in integer form, so it would make sense for these to remain as UTC when converted to a Go time value.

**Comment by elwinar** [comment]
The question is a mess, that sure.

In my opinion, the `time.Time` scanned should be returned to the 
end-user as an UTC time. But it doesn't prevent the driver to implement 
correctly ISO 8601, that is to detect whether the timezone is noted in 
the date, and consider it as local timezone if not. Then shift it to UTC 
before returning. That way both the norm and the convention are 
observed, and the behavior of the driver is consistent.

Maybe with a mention of this particular working on the driver's page, so 
users are made aware of this point.

**Comment by mattn** [comment]
@porjo What go-sqlite3 should do, do you think?

**Comment by mattn** [comment]
I added `loc=XXX` parameter to handle timezone.

4c5c4e526100f23b17fda84d39a8109cfec00118

If someone want to store datetime as local string, loc is required.
