### ISSUE TITLE
Specify package dependency on gcc in Readme

### ISSUE THREAD

**Issue by smile-on** [mattn/go-sqlite3#175]
People with different level of knowlege are trying to use it. Please, make README a little more friendly. Now, [Installation](https://github.com/mattn/go-sqlite3#installation) section of README.md makes illusion of the package as self contained. Please clearly specify dependency on C compiler. An extra line would help to avoid "surprises" and direct people to read FAQ. Here it how this note may look like.

`Minimum requirements are Go 1.1+ with CGO enabled and GCC/MinGW C compiler. 
See "compile" section in FAQ.`

Compilation on windows deserves its own section in FAQ. Take a look at [Google's sqlite3 package](https://godoc.org/code.google.com/p/go-sqlite/go1/sqlite3) as an example of documenting package dependencies. Short, clear and sets users aware of an extra step.

`Windows users should install mingw-w64 (http://mingw-w64.sourceforge.net/), TDM64-GCC (http://tdm-gcc.tdragon.net/), or another MinGW distribution, and make sure that gcc.exe is available from the %PATH%. MSYS is not required.
`

Thank you for the great package!

**Comment by smile-on** [comment]
Just a personal note. MinGW requires a bit of knowlege and effort to get compiler running on windows. Most GO users would just want your package on windows with minimal effort. My personal experience on windows 7 x64 - **TDM64-GCC pre-installation** is a best choice to have your package up and running. Just download and click. Than go get runs with with no issues!

**Comment by mattn** [comment]
Could you please send me a pull-request?
