### ISSUE TITLE
FTS support enabling

### ISSUE THREAD

**Issue by kiryl** [mattn/go-sqlite3#176]
Attempting to use full text search support cause error:

Failed to initialize database: no such module: fts4

It's requires compile-time options:

-DSQLITE_ENABLE_FTS3
-DSQLITE_ENABLE_FTS3_PARENTHESIS

And it would be nice to have ICU tokenizer too:

-DSQLITE_ENABLE_ICU

**Comment by mattn** [comment]
It's possible to add `-DSQLITE_ENABLE_FTS3` but it may not be possible to add icu feature. because go-sqlite3 is static build.

**Comment by kiryl** [comment]
Okay. That's good enough for me.

But please add -DSQLITE_ENABLE_FTS3_PARENTHESIS too. It enables better syntax for fts queries.
