### ISSUE TITLE
sqlite_update_hook

### ISSUE THREAD

**Issue by seshu3564** [mattn/go-sqlite3#177]
is there any api available for executing sqlite_update_hook on sqlite3 db.???

**Comment by mattn** [comment]
Currently, No.
But it's possible to implement as same as ConnectHook.
https://github.com/mattn/go-sqlite3/blob/master/_example/hook/hook.go#L14-L17

**Comment by seshu3564** [comment]
will it callback or notify for changes(update/delete/insert) in database??

**Comment by mattn** [comment]
if the sqlite3_update_hook can hook them, it will do.

**Comment by GJRTimmer** [comment]
Closed #434
