### ISSUE TITLE
Race in db queries?

### ISSUE THREAD

**Issue by hallyn** [mattn/go-sqlite3#185]
Hi,

The example program in https://gist.github.com/hallyn/05df347ada107e072ac6 creates a db, inserts a value, then launches 100 children to (a) insert another entry and (b) do a query for the original item.  Clearly there should be no case where a query returns no error, but returns an empty *db.Rows.  However, it does seem to happen.  Using a slower disk tends to prevent this, so it helps to have an ssd or tmpfs for /tmp.  In that case, you should see the error at least every other run, and certainly if you do 'for i in `seq 1 10`; do go run example.go; done'.

The error usually is:

thread0: query gave no error, but results are empty

**Comment by mattn** [comment]
I'm running this from morning. But still not reproduced.

**Comment by hallyn** [comment]
On Wed, Mar 18, 2015 at 08:24:33PM -0700, mattn wrote:
> I'm running this from morning. But still not reproduced.

Did you mount a tmpfs on /tmp?

We've reproduced this on both Ubuntu utopic and Ubuntu vivid
hosts and vms, but a slow spinning disk did prevent it from
happening.

If you definately cannot reproduce it, i wonder what else we
could look at on our systems as a possible cause.

**Comment by mattn** [comment]
Could you please latest commit?

**Comment by hallyn** [comment]
On Wed, Mar 18, 2015 at 09:30:56PM -0700, mattn wrote:
> Could you please latest commit?

commit 308067797b0fcce4ca06362580dc6db77c1bfeda
Author: Yasuhiro Matsumoto <mattn.jp@gmail.com>
Date:   Thu Mar 12 18:43:55 2015 +0900

    Apply -lpthread withou windows.

:100644 100644 edf3663... 4cdc4d5... M  sqlite3.go
:100644 100644 54b6c7a... 8d98b4a... M  sqlite3_other.go
:100644 100644 f47272d... abc8384... M  sqlite3_windows.go

**Comment by mattn** [comment]
latest commit s 5253daf8561a6ca5015fd5ce79e4367912146be9

**Comment by hallyn** [comment]
Ah, yes, that one fixes the issue - thanks!

**Comment by gwenn** [comment]
There was no bug in the driver but in the example:
You should check that there is no error (Row.Err()) before checking that the results are empty:
```go
             err = rows.Err()
             if err != nil {
                 fmt.Printf("thread%d: query gave error %q\n", me, err)
             } else if id == -1 {
                 fmt.Printf("thread%d: query gave no error, but results are empty\n", me)
             }
```
