### ISSUE TITLE
Integrate with Berkeley DB SQL API

### ISSUE THREAD

**Issue by doanchu** [mattn/go-sqlite3#186]
Berkeley DB SQL can be used as a replacement for Sqlite3. 
http://sepp.oetiker.ch/subversion-1.7.2-mo/installation/build_win_sql.html#id3637702

Can go-sqlite3 be modified to support Berkeley DB SQL?

**Comment by doanchu** [comment]
Just to update, I managed to use BDB SQL using the following guide:
https://code.google.com/p/tonatiuh/wiki/InstallingBerkeleyDBOnWindows

**Comment by mattn** [comment]
No, go-sqlite3 is embeding sqlite3 staticaly.

**Comment by GJRTimmer** [comment]
Close ?

**Comment by czh0** [comment]
go build --tags "libsqlite3 linux"
