### ISSUE TITLE
Error while getting driver from command line

### ISSUE THREAD

**Issue by digitalcraftsman** [mattn/go-sqlite3#191]
I tried to install your driver as part of the [examples of gorm](https://github.com/jinzhu/gorm) but failed and the system responded with the following message:

```
$ go get github.com/mattn/go-sqlite3

$ # github.com/mattn/go-sqlite3
$ exec: "gcc": executable file not found in %PATH%
```

Does anyone has an idea, why this message occurs?

**Comment by mattn** [comment]
you need to install gcc.

On 3/28/15, digitalcraftsman <notifications@github.com> wrote:
> I tried to install your driver as part of the [examples of
> "gorm"](https://github.com/jinzhu/gorm) but failed and the system responded
> with the following message:
>
> ```
> $ go get github.com/mattn/go-sqlite3
>
> $ # github.com/mattn/go-sqlite3
> $ exec: "gcc": executable file not found in %PATH%
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-sqlite3/issues/191


-- 
- Yasuhiro Matsumoto

**Comment by digitalcraftsman** [comment]
Thanks
