### ISSUE TITLE
doesn't compile using gomobile (for android/ios)

### ISSUE THREAD

**Issue by twoboxen** [mattn/go-sqlite3#201]
First there is an issue with pthread that I can get past, but then it seems to struggle linking with symbol conflicts.  I know sqlite and go both work on android, so i'm not sure why there is symbol duplication here.

example

``` go
// github.com/mattn/go-sqlite3/example2/test.go
package example2

import (
    "database/sql"

    _ "github.com/mattn/go-sqlite3"
)

var (
    db *sql.DB
)

func OpenDatabase(filePath string) error {
    d, err := sql.Open("sqlite3", filePath)
    if err != nil {
        return err
    }

    db = d
    return nil
}
```

Trying to bind without any patches

```
}{mhawkins:~/Library/go/src/github.com/mattn/go-sqlite3/example2}{gomobile bind                      }{master!}{
# github.com/mattn/go-sqlite3
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
collect2: error: ld returned 1 exit status
gomobile: exit status 2
```

Making this change (turning off pthread for android, as the link is not required)

```
diff --git a/sqlite3_other.go b/sqlite3_other.go
index 8d98b4a..5c96d59 100644
--- a/sqlite3_other.go
+++ b/sqlite3_other.go
@@ -9,6 +9,6 @@ package sqlite3
 /*
 #cgo CFLAGS: -I.
 #cgo linux LDFLAGS: -ldl
-#cgo LDFLAGS: -lpthread
+#cgo linux,-android LDFLAGS: -lpthread
 */
 import "C"
```

Gets me past the android link issue.  Now i'm having symbol conflicts, though

```
}{mhawkins:~/Library/go/src/github.com/mattn/go-sqlite3/example2}{gomobile bind                      }{master!}{
# command-line-arguments
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/5l: running /Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/arm-linux-androideabi-gcc failed: exit status 1
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000004.o: multiple definition of '__aeabi_uidivmod'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000001.o: previous definition here
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000004.o: multiple definition of '__aeabi_uidiv'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000001.o: previous definition here
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000004.o: multiple definition of '__udivsi3'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000001.o: previous definition here
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000004.o: multiple definition of '__aeabi_unwind_cpp_pr0'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000001.o: previous definition here
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-929937803/000004.o: multiple definition of '__gnu_Unwind_Restore_VFP_D'

...AND MANY MORE....
```

Any ideas?  It seems it's a cgo link issue, but I'm not sure what it is.

**Comment by minux** [comment]
Please remove LDFLAGS -lpthread from sqlite3_other.go,
it's never needed. Thanks.

See golang/go#10584 for the why android doesn't need
-lpthread.

**Comment by twoboxen** [comment]
I removed the link it but even when the contrived example i get the same errors

```
}{mhawkins:~/Library/go/src/github.com/mattn/go-sqlite3/example2}{gomobile bind                      }{master!}{
# command-line-arguments
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/5l: running /Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/arm-linux-androideabi-gcc failed: exit status 1
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-250010074/000004.o: multiple definition of '__aeabi_uidivmod'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-250010074/000001.o: previous definition here
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-250010074/000004.o: multiple definition of '__aeabi_uidiv'
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/go-link-250010074/000001.o: previous definition here
```

**Comment by minux** [comment]
This is golang/go#9510.

**Comment by mattn** [comment]
@minux do you mean: remove -lpthread `FOR ANDROID` with remaining it on linux, right?

**Comment by minux** [comment]
I mean you can remove -lpthread on every platform. Cgo will automatically
link pthread if necessary.

**Comment by mattn** [comment]
@minux okay, thanks.

**Comment by twoboxen** [comment]
Perhaps I'm a little slow, but I don't know how to fix the compilation issue with a dummy c file per https://github.com/golang/go/issues/9510

Could any of you fine folks explain what i need to do?  I'm sort of blocked.  

Thanks!

**Comment by minux** [comment]
Unfortunately there is no workaround for golang/go#9510.

**Comment by mattn** [comment]
golang/go#9510 is related issue of go-sqlite3?

**Comment by twoboxen** [comment]
It is related to the gomobile stuff.  Which sucks, because it's a
crazy common problem of mobile app code to need sqlite.  I am not sure
if it's possible to write an adapter to the system sqlite, but without
this I cannot move forward with gomobile for app business logic.  It
would require a pure go implementation of sqlite which doesn't exist
or an adaptable binding provided by gomobile which isn't planned.

Suck :(

**Comment by weitzj** [comment]
### Android Native Application (seems to work)

If you use an Android native project, e.g. `package main`, go-sqlite3 seems to work. Take the example project golang.org/x/mobile/example/basic and add the sql example code from https://github.com/mattn/go-sqlite3/issues/201#issue-71331035

Then run on an ARM device or ARM emulator:

```
gomobile build .
gomobile install .
```

### Android SDK Library (aar) (has duplicate symbols)

Trying to build an aar using `gomobile bind -target android` seems to fail as mentioned in https://github.com/mattn/go-sqlite3/issues/201#issue-71331035

If you pass some compiler-args to allow duplicate symbols, it at least compiles without errors. (Have not tested yet on device)

```
gomobile bind -target android -ldflags "-extldflags=-Wl,--allow-multiple-definition"
```

See:
- https://github.com/golang/go/issues/9510#issuecomment-150272401

**Comment by sb977** [comment]
I'm trying to compile with support for sqlite_math_functions.
I'm running:

export CGO_ENABLED=1 go build -tags "sqlite_math_functions"

on my project folder, which uses the sqlite3 database.

The compilation process doesn't give any errors. The binary is created.
But without the math functions.

Any ideas?

**Comment by rittneje** [comment]
@sb977 Which version of this library are you using?

**Comment by gen2brain** [comment]
@sb977 You usage is wrong; either export CGO_ENABLED for the session or just add it for the current command. Note the difference:
```
# export THIS=that echo $THIS
# THIS=that echo $THIS
that
```

**Comment by sb977** [comment]
> [@sb977](https://github.com/sb977) Your usage is wrong; either export CGO_ENABLED for the session or just add it for the current command. Note the difference:
> 
> ```
> # export THIS=that echo $THIS
> # THIS=that echo $THIS
> that
> ```

In any way, i try (without success):
 "export CGO_ENABLED=1"  [enter]
 "go build -tags "sqlite_math_functions" [enter]

same result, no built in math functions available
i use ver. 3.45.1

**Comment by rittneje** [comment]
@sb977 That seems like the SQLite C library version, not the version of this library. Which version of this library are you using?

**Comment by sb977** [comment]
go.mod:
github.com/mattn/go-sqlite3 v1.14.22
