### ISSUE TITLE
Do I need open every http handler for thread safe operation?

### ISSUE THREAD

**Issue by davyzhang** [mattn/go-sqlite3#209]

**Comment by mattn** [comment]
did you try below?

```go
db, err := sql.Open("sqlite3", "file:locked.sqlite?cache=shared&mode=rwc")
```

**Comment by davyzhang** [comment]
Thanks for your reply, sorry for the incomplete description. Now I have one db connection shared with some http handlers. I found some "database is locked" error during the running

go-sqlite3 used serialized mode by default why I still get the "locked" message when reading while  writing?

>SQLITE_CONFIG_SERIALIZED
>There are no arguments to this option. This option sets the threading mode to Serialized. In other words, this option enables all mutexes including the recursive mutexes on database connection and prepared statement objects. In this mode (which is the default when SQLite is compiled with SQLITE_THREADSAFE=1) the SQLite library will itself serialize access to database connections and prepared statements so that the application is free to use the same database connection or the same prepared statement in different threads at the same time. If SQLite is compiled with the SQLITE_THREADSAFE=0 compile-time option then it is not possible to set the Serialized threading mode and sqlite3_config() will return SQLITE_ERROR if called with the SQLITE_CONFIG_SERIALIZED configuration option.

And since I have only one connection, I guess shared cache can't help here.
Will WAL help here?

**Comment by mattn** [comment]
I'm not untra expert about locking of sqlite3. do you have any suggestion to fix this?

**Comment by davyzhang** [comment]
So far as I can tell, using shared cache and wal will make transaction faster, and avoid "many" errors.

But not all of them, I still can see "data base locked" error in my log, but much fewer than before

**Comment by davyzhang** [comment]
very dirty test for reproduce the problem
https://gist.github.com/davyzhang/1392344f993eac471c90

**Comment by mattn** [comment]
Could you try to add `&_busy_timeout=9999999` to connection string?

**Comment by davyzhang** [comment]
I updated the gist, but... seems no help here still lock error

**Comment by Compufreak345** [comment]
@davyzhang Did you get any new information about this issue? I've got the same problems.

**Comment by davyzhang** [comment]
@Compufreak345 Sorry, bad news. I think golang is not a suitable language for sqlite, especially writing http server applications. I switched my app to mysql/mariadb later after this lock issue, works fine.

**Comment by roxma** [comment]
@davyzhang 

According to https://github.com/mattn/go-sqlite3/issues/274,

It seems `db.SetMaxOpenConns(1)` or `_busy_timeout`  would be helpful.

**Comment by GJRTimmer** [comment]
TODO: Add db.SetMaxOpenConn(1) to README

**Comment by gdamore** [comment]
SetMaxOpenConn(1) only seems to affect if using a single process. I'm seeing this error when using multiple processes (two separate go programs).

**Comment by rittneje** [comment]
@gdamore What error specifically are you seeing? Also, if possible please provide the two go programs in question (or a minimal version that reproduces the issue).

**Comment by gdamore** [comment]
Unfortunately I cannot provide the source for the programs, as they have a lot of other proprietary IP in them.  I can however describe their behavior:

1. collect program opens the database and periodically inserts new events (telemetry) -- single table
2. query program opens the database, then runs a query to create a temporary table, using a select from the primary table.  (The select performs group by, and ordering, etc.)

Both programs may have multiple tables open that they do this for.  (For different resources.)

If the query program runs before the collect program (or rather before the collect program tries to open the database), then the collect program will encounter this error.  If the collect programs runs first, then we don't seem to have any problems at all.

Examination shows that the query program seems to be acquiring a write lock with fcntl on the last 510 bytes in the database file, and does not ever release it.

We are using WAL and shared cache, with just a single database connection per process.

Both programs are written in Go using this library.  The platform is illumos based.

If I find time later, I'll try to write a minimal repro case.

**Comment by arp242** [comment]
Does `cache=shared` have any effect with `db.SetMaxOpenConn(1)`? As I read the [SQLite docs](https://www.sqlite.org/sharedcache.html) I think it doesn't?

> If shared-cache mode is enabled and a thread establishes multiple connections to the same database, the connections share a single data and schema cache.

But with `SetMaxOpenConn(1)` I think Go never opens multiple connections?

In my testing concurrency issues seem resolved with just setting the connection limit to 1 (but I'm not sure if my tests are comprehensive).

**Comment by rittneje** [comment]
@arp242 In general, it is true that shared cache mode is irrelevant if you throttle the pool to one connection. However, if you have two separate connection pools for the same database, then shared cache mode would make a difference, even if each pool is throttled to one connection. But having two pools for the same database is generally indicative of some design issue.

On that note, the author of SQLite considers shared cache mode to be a misfeature (https://sqlite.org/forum/forumpost/1f291cdca4). Turning it on can result in "database table is locked" errors that are very difficult to resolve properly. (Not to be confused with "database is locked" errors, which are easily resolved in general by setting a busy timeout.) Consequently, despite what is currently stated in this repo's readme, you should never use shared cache. The only exception is if you are intend to have an in-memory database shared across multiple connections, but even then you are probably better served just throttling the connection pool to one anyway.

**Comment by arp242** [comment]
Right; thanks @rittneje.  I created a PR to update the documentation in the README a bit: #827 – let me know if I got anything wrong 😅
