### ISSUE TITLE
Build and link to system's libsqlite3 instead of packaged sqlite3 files

### ISSUE THREAD

**Issue by crosbymichael** [mattn/go-sqlite3#210]
Is there a way to have this go package be optionally built and linked to the version of libsqlite3 that you have installed on your host system instead of the included sqlite3 files in the repo?  

Do you think we could use something like Go build tags to add an `-lsqlite3` to the ldflags if we want this type of functionality?  

Thanks!

**Comment by mattn** [comment]
fixed in https://github.com/mattn/go-sqlite3/commit/ee9da4840dd680d1fe2927692ea4ab5f8cd7c91c
