### ISSUE TITLE
Is there any way to use the driver with SQLITE_ENABLE_UPDATE_DELETE_LIMIT flag?

### ISSUE THREAD

**Issue by elgris** [mattn/go-sqlite3#213]
This flag is useful when one is executing DELETE query with LIMIT clause: `DELETE FROM "sometable"  WHERE (name = 'foo') LIMIT 5`.
By default the driver returns an error: `near "LIMIT": syntax error`.

Is there any way to enable it for the driver? There is one possible problem: documentation says that this flag cannot be used with "amalgamation" source of sqlite3 driver: https://www.sqlite.org/compile.html

**Comment by gregf** [comment]
:+1:

**Comment by mattn** [comment]
anyone have objection?
