### ISSUE TITLE
gcc issue on windows 64

### ISSUE THREAD

**Issue by arulrajalivi** [mattn/go-sqlite3#214]
While trying to  do  "go install github.com/mattn/go-sqlite3" 
 I am getting the follwoing error. In one of the issues someone mentioned that  we don't need gcc if we install go-sqlite3. Any help would be greatly appreciated.
# github.com/mattn/go-sqlite3

exec: "gcc": executable file not found in %PATH%

Thanks
Arul

**Comment by mattn** [comment]
please type `where gcc` in your cmd.exe

**Comment by arulrajalivi** [comment]
Added C:/cygwin/bin to the %PATH% and I can see gcc.exe  in that location. Now I a getting the below error. when do a go build
# github.com/mattn/go-sqlite3
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
you need to install mingw not cygwin.

**Comment by arulrajalivi** [comment]
sure pointed it to C:/minggw/bin  and getting this error:
# github.com/mattn/go-sqlite3
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

**Comment by cfstras** [comment]
Does this mean mingw-w64 is the only option to build go-sqlite on 64-bit systems?
Can we do something about that?

**Comment by mattn** [comment]
AFAICS, @arulrajalivi 's compiler doesn't support 64bit.

**Comment by cfstras** [comment]
The default MinGW builds don't support 64bit, and on cygwin(64), go-sqlite doesn't link.

**Comment by benluo** [comment]
I use msys2 64 bit. I met the same problem. How to resolve it ?

**Comment by mattn** [comment]
don't use msys2 to build go app. msys2 rewrite $PATH with slash separators.

**Comment by rusco** [comment]
I am using this version of gcc (64 bit) and go get's run fine:
http://tdm-gcc.tdragon.net/

**Comment by Yggdrasill1989** [comment]
I installed TDM-GCC (64 bit), and I get some error:

fatal: unable to access 'https://github.com/mattn/go-sqlite3/': error setting certificate verify locations:
  CAfile: C:\Users\Yggdr\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\mingw32/usr/ssl/certs/ca-bundle.crt
  CApath: none
package github.com/mattn/go-sqlite3: exit status 128

**Comment by mattn** [comment]
@Yggdrasill1989 it's not issue of go-sqlite3.

**Comment by rusco** [comment]
@Yggdrasill1989: Big firewall ? utrasurf is your friend !

**Comment by Yggdrasill1989** [comment]
Thanks for your answers.
There's some problem about link to https, and I change to ssh link clone the project, it worked.

**Comment by 9uuso** [comment]
Installing 64-bit TDM-GCC worked for me. Cygwin was unable to locate 64-bit gcc even though I had chosen it to be installed during cygwin installation.

**Comment by SinghBasant** [comment]
Half a day & I almost did everything shared over here to get rid of this gcc issue :( I installed TDM-GCC , set the correct path. Please help. Got this error: 
![err](https://cloud.githubusercontent.com/assets/1387011/12325306/520e028e-baef-11e5-88be-97292e03b2f8.png)

**Comment by mattn** [comment]
I wonder whether your compiler is possible to work just for simple C source code. could you please try 
```
gcc -c code\sqlite3-binding.c
```

**Comment by SinghBasant** [comment]
@mattn Thanks for a response. Unfortunately, I didn't understand your response. Please elaborate. For info. I'm on Windows 10 Home (64 bit).

**Comment by mattn** [comment]
```
gcc -c code\sqlite3-binding.c
```
if your compiler works correctly, this command should work well.

**Comment by AlekseyMartynov** [comment]
This worked for me:

* Install MSYS2 x86_64 from https://msys2.github.io/
* In MSYS2 shell: `pacman -S mingw-w64-x86_64-make mingw-w64-x86_64-gcc`
* Add `C:\msys64\mingw64\bin` and `C:\msys64\usr\bin` to `PATH`
* Use `mingw32-make.exe` as `make`

**Comment by ifnu** [comment]
i remove my mingw 32 bit installtion and using mingw 64 installation from souceforge site here

https://sourceforge.net/projects/mingw-w64/

i follow default installation setup and it install mingw in this folder 

C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev0\mingw64\

so put C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev0\mingw64\bin folder in PATH directory and test with gcc command from cmd.

works like miracle

**Comment by wangwanqiang** [comment]
I got the same problem on win10 64bit.

**Comment by tmack8080** [comment]
I get this error on Windows 10 64-bit. The instructions state:
"if you install go-sqlite3 with go install github.com/mattn/go-sqlite3, you don't need gcc to build your app anymore."

So do I need a C compiler to use this driver?

c:\Go\workspace>go install github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

**Comment by rusco** [comment]
Yes, you need a c compiler, I recomend this distribution, works fine on my windows 7/64 bit PC:

http://tdm-gcc.tdragon.net/

**Comment by mcappleman** [comment]
Use the link @rusco shared. It worked for me on Windows 10 64. Thank you @rusco!!!

**Comment by dougpuob** [comment]
@rusco, thank you ! it works :)

**Comment by jianjyan** [comment]
I found the issue:

I was build code via git bash, the PATH variable is differ from the windows system "PATH";
like building in linux, I export the PATH by export PATH="$PATH:/c/TDM-GCC-64/bin", then the build is passed.

**Comment by surfmuggle** [comment]
The issue [Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work](https://stackoverflow.com/a/79591997/819887) was solved doing this

 1. download [mingw-w64](https://stackoverflow.com/questions/tagged/mingw-w64)
 1. add path to gcc.exe
 1. Open a new cmd.exe and test path by running `C:\>gcc --version` should return someting like *gcc (x86_64-win32-seh-rev...*
 1. Set variable in cmd.exe like this `SET CGO_ENABLED=1` test with `ECHO %CGO_ENABLED%`
 1. run `go build .` for the code that uses `mattn/go-sqlite3`
