### ISSUE TITLE
No buildable Go source files (Windows)

### ISSUE THREAD

**Issue by cadizjavier** [mattn/go-sqlite3#219]
I'm trying to build the package in Windows. The environment is working so far with others libraries without cgo. I installed [Mingw-w64](http://mingw-w64.org/) with all the packages and set the paths. 
When i do `go get github.com/mattn/go-sqlite3` i get
`C:\Code\Go\src\sample\main.go:14:2: no buildable Go source files in C:\Go\src\github.com\mattn\go-sqlite3`

This are some of my tools versions.
```
go version
go version go1.4.2 windows/i386

gcc --version
gcc.exe (GCC) 4.8.3
(...)
```
I don't know exactly how to build this. Any help appreciated. Thanks in advance.

**Comment by mattn** [comment]
probably, git clone failed. try to do it again like this:

```
$ go get -u -x github.com/mattn/go-sqlite3
```

**Comment by cadizjavier** [comment]
@mattn  Yes, indeed the got clone was failing. Thanks for the quick reply.

Strangely enough (probably my mistake) it doesn't fail with the others packages, i installed negroni and gorilla/mux without troubles.
For context and trying to help others that have the same issue i'm using [this Git for windows](https://git-scm.com/download/win). 

- `go get github.com/mattn/go-sqlite3` wasn't working for me so i clone manually the repo into the `%GOPATH%/src/mattn` with `git clone https://github.com/mattn/go-sqlite3`.
- After the successful clone i made go build in my project folder and a system error appears saying  `"The procedure entry point libintl_asprintf could not be located in the dynamic link library libint-8.dll".`
The issue was due that in my system i have several copies of that dll, so the build wasn't using the Mingw one. The windows Git installation has a copy (\Git\bin) of that library that was producing the conflict, so i renamed that dll and now the build use the Mingw version of `libintl-8.dll`.
- Now after running go build everything works smoothly.
