### ISSUE TITLE
Ship with SQLite 3.8.11 Bindings

### ISSUE THREAD

**Issue by alixaxel** [mattn/go-sqlite3#222]
SQLite 3.8.11 has just been released, and according to the [changelog](https://www.sqlite.org/releaselog/3_8_11_1.html) it comes with some nice performance improvements.

It would be great if the package was updated to use this version.

**Comment by mattn** [comment]
https://github.com/mattn/go-sqlite3/pull/171

This is same issue related on https://github.com/golang/go/issues/9356

I'll wait release of go1.5

**Comment by ayanamist** [comment]
go 1.5 has been released for a while, so?

**Comment by mattn** [comment]
will do but please wait.

**Comment by rusco** [comment]
I propose setting up a Gratipay account for this !

**Comment by alixaxel** [comment]
@rusco Good idea, :+1:.

**Comment by mattn** [comment]
I didn't merge this PR, but I could decide to merge latest amalgamation code to latest. thanks!
#264

**Comment by alixaxel** [comment]
@mattn Amazing, thanks!

**Comment by rusco** [comment]
:clap:
