### ISSUE TITLE
"no such table" error

### ISSUE THREAD

**Issue by hallyn** [mattn/go-sqlite3#223]
Hi,

when doing some heavy stress-testing of our application which imports go-sqlite3, during one failure case I saw:

error: no such table: containers

This was in the middle of a run, sandwiched between many successful queries and actions on the containers table.

This was on a brand new built vm, using go-sqlite commit b4142c444a8941d0d92b0b7103a24df9cd815e42.

Do you have any particular suggestions for figuring out what may have gone wrong?

Thanks!

**Comment by mattn** [comment]
Because connection doesn't have exclusion.
https://github.com/mattn/go-sqlite3/blob/master/sqlite3_test.go#L772

**Comment by mattn** [comment]
dup #216

**Comment by hallyn** [comment]
Hi, sorry, either I'm misunderstanding or I wasn't clear in the description.  This is about our own testcase of an application built on go-sqlite3, not the go-sqlite3 testcaess.  In our application testcase, the db is opened with the _txlock=exclusive option.  It mostly runs correctly, but with a very massive concurrent testcase I got this case where my db query claimed that a table didn't exist.

**Comment by Higan** [comment]
@hallyn Have you found the root cause of this issue? I'm facing a pretty similar error; the table should have been create, with lots of queries been executed successfully, but later an error was thrown claiming `no such table`.

**Comment by rittneje** [comment]
@Higan Do you have an example of your code that is having a problem? Are you using an actual database file, or an in-memory database? Are you using any temporary tables?

**Comment by sean-abbott** [comment]
I'm having a simliar issue, although my use case may be different. I am new to Gorm and ORMs in general, please be gentle with me.

I have:
```
func getFollowingPosts(db *gorm.DB, following []int, moral int, itemsPerPage int, offset int) PaginatedDropSearchResult {
    var drops []Droplet
    filteredDB := db.Where("user_id in (?)", following)
    if moral != 0 {
        filteredDB = filteredDB.Where("moral = ?", moral)
    }

    var totalRows int64
    filteredDB.Count(&totalRows)
    filteredDB.Limit(itemsPerPage).Offset(offset).Find(&drops)
    
    return PaginatedDropSearchResult{Drops: drops, NextOffset: offset + itemsPerPage, TotalResults: totalRows, ItemsPerPage: itemsPerPage}
}
```

everything EXCEPT the count works. The count fails with `no such table: ` and no further info.

I am using on disk sqlite3, although I'm not sure whether the returned db object is holding the query in memory.

**Comment by eehsiao** [comment]
@Higan @relud 
if you open in :memory: , must be ":memory:?cache=shared"

**Comment by ko80** [comment]
**Maybe this would help someone**

I had the same issue with 'no such table' and found an exact explanation:

*If sql.Rows is not closed before next query then driver returns no such table on next query. Issue exists only for in-memory storage, same test for file backed db runs fine.* 
https://github.com/mattn/go-sqlite3/issues/511#issuecomment-396290916

After that, I found the part of code where I had forgoggen to do rows.Close(), fixed that and now it works with no issues.

**Comment by LuckyDenis** [comment]
> @Higan Do you have an example of your code that is having a problem? Are you using an actual database file, or an in-memory database? Are you using any temporary tables?

setup: Ubuntu 20.04.1 LTS
go: go1.15 linux/amd64
sqlite3: SQLite version 3.31.1 2020-01-27 19:55:54

database:
CRATE TABLE data (
uid INTEGER PRIMARY KEY
);


```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/mattn/go-sqlite3"
)


func main() {
	database := "./foo.db"

	db, err := sql.Open("sqlite3", database)
	if err != nil {
		fmt.Println(nil)
		return
	}
	defer db.Close()

	_, err = db.Exec("SELECT * FROM data;")
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

stdout: ```no such table: data```

**Comment by mrbardia72** [comment]
@mattn 
How can I solve the following problem?
no such table: users

**Comment by rittneje** [comment]
@mrbardia72 Please open a new issue, with sufficient detail to diagnose your error.

**Comment by DANCANKARANI** [comment]
@mattn add table users, try this
db.CreateTable(&User{}).AutoMigrate(&Users{})
