### ISSUE TITLE
Support for UDFs?

### ISSUE THREAD

**Issue by alixaxel** [mattn/go-sqlite3#226]
For me, one of the most interesting features of SQLite, is the ability to extend the behaviour of SQL queries by implementing simple or aggregate UDFs (user-defined functions).

They are critical to implement the REGEXP operator for instance, and, in my current scenario, a RANK() function that operates on data returned by the FTS matchinfo().

I don't think I've seen anything regarding this in the docs (in pure Go). Would it be even possible to do it without C?

**Comment by mattn** [comment]
See https://github.com/mattn/go-sqlite3/tree/master/_example/mod_regexp
