### ISSUE TITLE
panic: sql: Scan error on column index 3: unsupported driver -> Scan pair: time.Time -> *string

### ISSUE THREAD

**Issue by firebitsbr** [mattn/go-sqlite3#230]
This is the environment of a VM devel I'm encoding:

Fedora 22 - x86_64
=======================================
Linux localhost.localdomain 4.1.4-200.fc22.x86_64 + debug # 1 SMP Tue Aug 4 02:57:14 UTC 2015 x86_64 x86_64 x86_64 GNU / Linux

Golang 1.4.2 Linux / amd64
=======================================
[Root @ localhost db] # go version
go version go1.4.2 linux / amd64

dbtest1.sql
=======================================
CREATE TABLE `userinfo` (
    `uid` INTEGER PRIMARY KEY AUTOINCREMENT,
    `username` VARCHAR (64) NULL,
    `uepartname` VARCHAR (64) NULL,
    `ureated` DATE NULL
);

# sqlite3 dbtest1.db < dbtest1.sql

dbtest1.go
=======================================
main package

import (
    "Database / sql"
    "Fmt"
    _ "Github.com/mattn/go-sqlite3"
)

func main () {
    db, err: = sql.Open ("sqlite3", "./dbtest1.db")
    checkErr (err)

    // Insert
    stmt, err: = db.Prepare ("INSERT INTO userinfo (username, departname, created) VALUES (,,)???")
    checkErr (err)

    res, err: = stmt.Exec ("astaxie", "研发 部门", "09/12/2012")
    checkErr (err)

    id, err: = res.LastInsertId ()
    checkErr (err)

    fmt.Println (Id)
    // Update
    stmt, err = db.Prepare ("update userinfo September username = where uid =?")
    checkErr (err)

    res, err = stmt.Exec ("astaxieupdate", id)
    checkErr (err)

    Affect, err: = res.RowsAffected ()
    checkErr (err)

    fmt.Println (Affect)

    // Query
    rows, err: = db.Query ("SELECT * FROM userinfo")
    checkErr (err)

    is rows.Next () {
        var uid int
        var username string
        var department string
        var created string
        err = rows.Scan (& uid, username &, & department, & created)
        checkErr (err)
        fmt.Println (uid)
        fmt.Println (username)
        fmt.Println (department)
        fmt.Println (created)
    }

    // Delete
    stmt, err = db.Prepare ("delete from userinfo where uid =?")
    checkErr (err)

    res, err = stmt.Exec (id)
    checkErr (err)

    Affect, err = res.RowsAffected ()
    checkErr (err)

    fmt.Println (Affect)

    db.Close ()

}

func checkErr (err error) {
    if err! = nil {
        panic (err)
    }
}

Compiling
=======================================
go build dbtest1.go

Running and Bugando
=======================================
[Root @ localhost db] # ./dbtest1
5
1
panic: sql: Scan error on column index 3: unsupported driver -> Scan pair: time.time -> string *

goroutine 1 [running]
main.checkErr (0x7f7fd0c5d740, 0xc20800a540)
/home/test/nscanv1-x86/nscan-x86/db/dbtest1.go:71 + 0x50
main.main ()
/home/test/nscanv1-x86/nscan-x86/db/dbtest1.go:46 + 0x9c6

goroutine 5 [chan receive]:
database / sql. (* DB) .connectionOpener (0xc20802c000)
/usr/lib/golang/src/database/sql/sql.go:589 + 0x4c
created by database / sql.Open
/usr/lib/golang/src/database/sql/sql.go:452 + 0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit ()
/usr/lib/golang/src/runtime/asm_amd64.s:2232 0x1 +

I'm trying to debug with gdb, but without much success. I checked lines 71 and 46 of the file dbtest1.go, but without success.

@firebitsbr

**Comment by mattn** [comment]
This is not an issue of go-sqlite3. go's database/sql doesn't have conversion between time and string. And driver can't handle which type of argument is given.
