### ISSUE TITLE
link with system libsqlite3-dev

### ISSUE THREAD

**Issue by onlyjob** [mattn/go-sqlite3#234]
On [Debian](http://debian.org) it should be possible to link _go-sqlite3_ with system _libsqlite3_ library instead of a bundled copy of SQLite3 amalgamation.
Package [libsqlite3-dev](https://packages.debian.org/unstable/libsqlite3-dev) provides static SQLite3 library and development headers.
Please introduce option to allow use of system library.

Thank you.

**Comment by aviau** [comment]
This is already possible with:
```
go build -tags "libsqlite3"
```

I have written a patch on the Debian repository.

**Comment by onlyjob** [comment]
Here is the patch:

~~~~
Description: Use libsqlite3-dev
Author: Alexandre Viau <alexandre@alexandreviau.net>
Last-Update: 2015-09-03

--- a/sqlite3-binding.h
+++ b/sqlite3-binding.h
@@ -1,5 +1 @@
-#ifndef USE_LIBSQLITE3
-#include "code/sqlite3-binding.h"
-#else
 #include <sqlite3.h>
-#endif
--- a/sqlite3-binding.c
+++ /dev/null
@@ -1,4 +0,0 @@
-#ifndef USE_LIBSQLITE3
-# include "code/sqlite3-binding.c"
-#endif
-
--- a/sqlite3_libsqlite3.go
+++ b/sqlite3_libsqlite3.go
@@ -2,7 +2,6 @@
 //
 // Use of this source code is governed by an MIT-style
 // license that can be found in the LICENSE file.
-// +build libsqlite3
 
 package sqlite3
 
~~~~

**Comment by mattn** [comment]
No, it should be interact with build tag. However i could understand what you want. So i'll look into it in later.

**Comment by onlyjob** [comment]
Thanks.

**Comment by mattn** [comment]
@onlyjob well, do you expect `--tags libsqlite3` should be default?

**Comment by onlyjob** [comment]
I think it would be a good idea. :) It is always better to use system library, when possible.

**Comment by mattn** [comment]
No, I think go-sqlite3 should link static library.

**Comment by onlyjob** [comment]
@mattn, static linking is a security nightmare.
See https://wiki.debian.org/StaticLinking

**Comment by mattn** [comment]
so I provide way to link shared with `--tags libsqlite3`.
