### ISSUE TITLE
compiling project with go-sqlite3 fails on i386 linux

### ISSUE THREAD

**Issue by almindor** [mattn/go-sqlite3#237]
Specifically on ubuntu 14.04 using go 1.4.1

The project builds and links fine when go-sqlite3 usage is commented out and the dependency removed. As soon as it's added in linking of the project binary itself fails with:

/var/tmp/go-link-jV7GbW/000005.o: In function `__udivdi3':
(.text+0x908d0): multiple definition of `__udivdi3'
/var/tmp/go-link-jV7GbW/000000.o:(.text+0x6d90): first defined here
collect2: error: ld returned 1 exit status
/usr/lib/go/pkg/tool/linux_386/8l: running gcc failed: unsuccessful exit status 0x100

Note that it works 100% on amd64 linux. This is a direct compilation, not cross-compilation.

Any ideas?

**Comment by mattn** [comment]
Could you try this on go1.5?

**Comment by almindor** [comment]
Same with 1.5.1

I had a similar problem trying to compile a C program that depended on pre-compiled static linked .a files from a device driver provider. It turned out the link order was important because a symbol was imported twice.

In this case it seems that go-sqlite3 .a file contains a symbol some other dependency has as well and maybe the link order is wrong.

**Comment by mattn** [comment]
so could you please try `go build --tags "libsqlite3 linux"`?

**Comment by ray0807** [comment]
I have the save problem 
![4](https://cloud.githubusercontent.com/assets/7233544/10079159/14388a28-631b-11e5-91d8-7e78192f19fc.png)

**Comment by ray0807** [comment]
I have the same problem  ,please help me , I'm green .
the code is your example.go
I have tried go build --tags "libsqlite3 linux" but it show the same problem.
go version : go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/386
![4](https://cloud.githubusercontent.com/assets/7233544/10079247/7f6c8eac-631b-11e5-99fb-5a516ad1eb8e.png)

**Comment by mattn** [comment]
Are you using gccgo?

**Comment by ray0807** [comment]
It works , thank you ,I don't know why I install gccgo , Anyway  thank you .

**Comment by dehaisea** [comment]
I have the same problem with ray0807,and I have tried apt-get install gccgo to install gccgo,but it dosen't work. I don't know how ray0807 make it work. Please help me.

**Comment by hishamwaleed** [comment]
@mattn  please close this issue there are a lot of solved issues not closed
