### ISSUE TITLE
Question: how to make use of error code from error.go?

### ISSUE THREAD

**Issue by mattcui** [mattn/go-sqlite3#244]
I saw there is error.go file, but I don't know how to leverage this file to get the proper return code. For examples, sometimes there probably occurs "database is locked" when update or insert a record in a table concurrently, so I hope to get the error code (ErrBusy) from such error to help me determine if needing to retry. But the err returned from db.Exec() is just a string, how to leverage your error.go to get the expected return code? Thanks.

```go
_, err = db.Exec("UPDATE COMPANY SET ADDRESS = 'Texas' WHERE ID = ?;", randomRowId)
```

**Comment by mattn** [comment]
Try below.
```go
if sqliteErr, ok := err.(sqlite3.Error); ok {
	if sqliteErr.Code == ErrBusy {
		fmt.Println("busy")
	}
}
```

**Comment by mattcui** [comment]
Thanks, it works. The key is to use sqlite3.Error instead of Error. Since I generally import go-sqlite3 as below, I can't state it like sqlite3.Error, which cause to use the built-in Error instead of Error in go-sqlite3.

```go
_ "github.com/mattn/go-sqlite3"
```

**Comment by mattn** [comment]
yes, right.

**Comment by mattcui** [comment]
Thanks again! Closing the issue.

**Comment by Yakabuff** [comment]
How can we do this with `errors.Is` and `errors.As`?

**Comment by rittneje** [comment]
Until #949 is done:
```go
var sqliteErr sqlite3.Error
if errors.As(err, &sqliteErr) {
    // use sqliteErr.Code
}
```
