### ISSUE TITLE
error in go get github.com/mattn/go-sqlite3

### ISSUE THREAD

**Issue by thewhitetulip** [mattn/go-sqlite3#245]
When I try to get this repo, i see this error,

# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

using go1.5

**Comment by mattn** [comment]
what C compiler do you use?

**Comment by TheAvenueToff** [comment]
## Go
> vagrant@vagrant-ubuntu-trusty-64:~$ go version
> go version go1.2.1 linux/amd64

## gcc
> vagrant@vagrant-ubuntu-trusty-64:~$ gcc --version
> gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
> Copyright (C) 2013 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

## error
> vagrant@vagrant-ubuntu-trusty-64:~$ go get github.com/mattn/go-sqlite3
>     # github.com/mattn/go-sqlite3
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte
> Go type not supported in export: [0]byte

**Comment by mattn** [comment]
Thank you. No namespace?

On 10/18/15, TheAvenueToff <notifications@github.com> wrote:
> ## Go
>> vagrant@vagrant-ubuntu-trusty-64:~$ go version
>> go version go1.2.1 linux/amd64
>
> ## gcc
>> vagrant@vagrant-ubuntu-trusty-64:~$ gcc --version
>> gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
>> Copyright (C) 2013 Free Software Foundation, Inc.
>> This is free software; see the source for copying conditions.  There is NO
>> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
>> PURPOSE.
>
> ## error
>> vagrant@vagrant-ubuntu-trusty-64:~$ go get github.com/mattn/go-sqlite3
>>     # github.com/mattn/go-sqlite3
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>> Go type not supported in export: [0]byte
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-sqlite3/issues/245#issuecomment-148950788


-- 
- Yasuhiro Matsumoto

**Comment by thewhitetulip** [comment]
go1.2.1 apparently (I think I had updated that to use go1.5 God only knows how this happened )

gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by mattn** [comment]
So closable?

**Comment by thewhitetulip** [comment]
The resolution is that we have to use anything above go1.4

**Comment by mostafadahab** [comment]
issue return in 1.5.2
