### ISSUE TITLE
Can't compile native binary on Windows with go 1.5.1

### ISSUE THREAD

**Issue by jhowardmsft** [mattn/go-sqlite3#248]
Hi @mattn - Docker very recently upgraded from go 1.4.3 to go 1.5.1. If you recall, I'm working on the port of docker to Windows.

With the 1.5.1 update, I can no longer compile (more specifically, link) docker.exe with SQLite, either dynamically or statically when using GitHub.com/mattn/go-sqlite3 as the database driver. This is when trying to perform a native compile, as opposed to a cross-compile of Windows binary on Linux.

I see this error from link:
c:\go1.5.1\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Program Files/mingw-w64/x86_64-5.2.0-win32-seh-rt_v4-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../..
/x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\jhoward\AppData\Local\Temp\go-link-381922907/0
00000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

So that indicates a 32/64-bit incompatibility of some kind. I have upgraded my mingw-64 from 4.9 to 5.2 as you can (indirectly) see from the path to ld.exe in the above output, but that has made no difference.

Oddly it doesn't seem to repro on a simple test program with main.go containing:

package main
import (
        _ "github.com/mattn/go-sqlite3"
)
func main () {
}

That go builds fine using both `go build` (static) and `go build -tags "libsqlite3"` (dynamic).

Yet commenting out these lines from the docker code: https://github.com/docker/docker/blob/master/pkg/graphdb/conn_sqlite3_windows.go#L5-L7, the daemon does link both statically and dynamically (go build -tags "daemon [libsqite3]") from the GitHub.com/docker/docker/docker directory. So I've pretty well convinced myself there is some incompatibility with this library and go 1.5.1, but I just can't repro it outside the context of docker. As I say, everything works just fine if I go back to go 1.4.3 (and still use mingw-w64 v5.2).

Do you by any chance have any suggestions? I've hit a roadblock at this point, this CGO stuff is not something I understand particularly well.

Thanks!
John.

**Comment by jhowardmsft** [comment]
If it helps at all, I tried a go build -x -tags "daemon" to get some more info out of the exact build flags called by the compiler and linker.

The relevant bits are for the compile:


mkdir -p $WORK\github.com\mattn\go-sqlite3\_obj\
mkdir -p $WORK\github.com\mattn\
cd e:\go\src\github.com\docker\docker\vendor\src\github.com\mattn\go-sqlite3
CGO_LDFLAGS="-g" "-O2" "-lmingwex" "-lmingw32" "c:\\go1.5.1\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\mattn\\go-sqlite3\\_obj\\" -importpath github.com/mattn/go-sqlite3 -- -I "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\mattn\\go-sqlite3\\_obj\\" -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -I. -fno-stack-check -fno-stack-protector -mno-stack-arg-probe backup.go error.go sqlite3.go sqlite3_load_extension.go sqlite3_windows.go

cd e:\go\src\github.com\docker\docker\vendor\src\github.com\mattn\go-sqlite3
gcc -I "e:\\go\\src\\github.com\\docker\\docker\\vendor\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 -print-libgcc-file-name
gcc -I "e:\\go\\src\\github.com\\docker\\docker\\vendor\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 -I "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\mattn\\go-sqlite3\\_obj\\" -g -O2 -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -I. -fno-stack-check -fno-stack-protector -mno-stack-arg-probe -o "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\mattn\\go-sqlite3\\_obj\\_cgo_main.o" -c "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\mattn\\go-sqlite3\\_obj\\_cgo_main.c"

And the link:


"c:\\go1.5.1\\pkg\\tool\\windows_amd64\\link.exe" -o "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\docker\\docker\\docker\\_obj\\exe\\a.out.exe" -L "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034" -L "e:\\go\\src\\github.com\\docker\\docker\\vendor\\pkg\\windows_amd64" -L "e:\\go\\pkg\\windows_amd64" -extld=gcc -buildmode=exe -buildid=6d12dae27a39fe824c6465803ae04f8dc1dda26e "C:\\Users\\jhoward\\AppData\\Local\\Temp\\go-build207626034\\github.com\\docker\\docker\\docker.a"
# github.com/docker/docker/docker
c:\go1.5.1\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Program Files/mingw-w64/x86_64-5.2.0-win32-seh-rt_v4-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\jhoward\AppData\Local\Temp\go-link-977496243/000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status


I should add this is running on a Windows 10 x64 machine.
Thanks again,
John.

**Comment by mattn** [comment]
Hmm, I'm trying go1.5.1 official binary and master branch of go-sqlite3 on windows7 64bit machine.
I'm using C compiler bundled on msys2.

```
gcc (Rev3, Built by MSYS2 project) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
code is same as your.
```go
package main
import (
    _ "github.com/mattn/go-sqlite3"
)
func main () {
}
```

 But can't reproduce it. Which version of gcc do you use?

**Comment by mattn** [comment]
I tried same condition with go tip(master branch). But not reproduced.

**Comment by jhowardmsft** [comment]
Thanks for getting back to me so quickly.

e:\go\src\github.com\docker\docker>gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 5.2.0

Yeah, I couldn't repro with that simple cut-down sample. I'm busy going the opposite direction cutting out as much of docker code as I can to get to a point it can compile so I can hopefully find exactly what are the repro conditions.

**Comment by jhowardmsft** [comment]
Hi @mattn  - I've worked out the conflict, but not the reason. I use rsrc (https://github.com/akavel/rsrc) @akavel to compile in an icon and manifest docker for Windows 10. 

A simple repro repo is at https://github.com/jhowardmsft/sql1.5.1. The .syso (binary containing the manifest) file in there is generated by rsrc -manifest sql1.5.1.exe.manifest -o rsrc.syso.

Compiling that repro repo will fail with the same link error I am seeing in docker. It compiles if I either remove the manifest binary, or comment out the SQL driver import from main.go. 

So it looks like there's some incompatibility here between go 1.5.1, your SQL driver and RSRC. But I'm not sure what.....

**Comment by jhowardmsft** [comment]
I suspect it's a go bug. I opened an issue on the go mailing list: https://groups.google.com/forum/#!topic/golang-nuts/pZB_QQQk2Z4

**Comment by mattn** [comment]
I'm thinking it's not go's bug. syso file is OS related file format. especially, resourcc file is it. Maybe same as https://github.com/golang/go/issues/12448

**Comment by jhowardmsft** [comment]
The workaround provided in https://groups.google.com/forum/#!topic/golang-nuts/pZB_QQQk2Z4 works for me. I can close this issue. Thanks again for the help, as always!

**Comment by bearmingo** [comment]
I meet a similarity issue when add `C:\msys64\usr\bin` to env PATH . I has installed msys in my system and  installed gcc by `pacman -Sy gcc`.

After I install gcc by follow code, and add path("C:\msys64\mingw64\bin") to env PATH. it is OK.
```bash
pacman -Sy mingw64/mingw-w64-x86_64-gcc
```

**Comment by rhettli** [comment]
> I suspect it's a go bug. I opened an issue on the go mailing list: https://groups.google.com/forum/#!topic/golang-nuts/pZB_QQQk2Z4

Hi , I also get the problem like you,  if I generate a icon file[res.syso] and I can build it successfuly. how can i solve this problem

thx
