### ISSUE TITLE
undefined reference 'pthread_mutexattr_settype' and "DSO missing from command line"

### ISSUE THREAD

**Issue by cpg** [mattn/go-sqlite3#256]
Hi,

Do you have any clues about why compiling this package in isolation fails?

Attempting to compile under fedora 23, I get the following error:

```bash
/usr/bin/ld: /home/project/fs/pkg/gccgo_linux_amd64/github.com/mattn/libgo-sqlite3.a(sqlite3-binding.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I believe I have all the libraries in the system (which before, the upgrade to Fedora 23, could compile this library ok).

However, I am also, almost sure it's not an issue with your code, since `go get github.com/mattn/go-sqlite3` actually compiles.

My project has the code for go-sqlite3 in `src/github.com/mattn/go-sqlite3/` as a submodule. The reason is that it gets built as part of building a package in an isolated environment.

Any ideas?

**Comment by mattn** [comment]
do you use gccgo?

**Comment by cpg** [comment]
I would say yes :)

This is based on the fact that I see that in the error message and also this folder pkg/gccgo_linux_amd64/

Now, I do not recall having made that choice (perhaps it's the default?), or how to control it.

**Comment by mattn** [comment]
I confirm behavior only on go not gccgo.

**Comment by cpg** [comment]
i don't understand the answer. i never chose gccgo, and i don't know who or why selects it. i found some files in my system called gccgo and i brutally removed them, which makes this issue go away.

the mystery will remain.

**Comment by imuneer** [comment]
I am having the exact same issue.

I have installed go, gcc, gccgo and etc. What can resolve this?

**Comment by TheMrNomis** [comment]
I had the same problem here, solved with:
`export CGO_LDTHREAD=-lpthread`

**Comment by cairb** [comment]
I installed golang go and the problem went away:
sudo apt  install golang-go
it was gccgo which gave me a similar error:
rcai@master:~/Downloads/cilium-1.2.3/examples/kubernetes/addons/etcd-operator$ go get -u github.com/cloudflare/cfssl/cmd/cfssl
# github.com/cloudflare/cfssl/cmd/cfssl
/usr/bin/ld: $WORK/b001/_pkg1_.a(_x010.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
AFAICS, it seems not related on go-sqlite3.
