### ISSUE TITLE
Dont compile on linux(Mint)

### ISSUE THREAD

**Issue by cmplx** [mattn/go-sqlite3#257]
src/github.com/mattn/go-sqlite3/backup.go:10:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
Where to get this file?

**Comment by mattn** [comment]
maybe your compilation environment seems broken.

**Comment by hltan** [comment]
i have the same problem. fresh install of debian, gvm and go1.6. how should I fix my broken environment?

**Comment by mattn** [comment]
check `go env` command output and `CC` is your expected.

**Comment by hltan** [comment]
i had to install gccgo. don't know why, but it worked after that.

**Comment by youknow98** [comment]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/liujie/GoWorkSpace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build882896047=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

==============================================
this is my "go env"

liujie@liujie-VPCEA1S4C ~ $ go install github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
GoWorkSpace/src/github.com/mattn/go-sqlite3/backup.go:14:20: fatal error: stdlib.h: No such file or directory
compilation terminated.

============================================================
but can't build this.why?

**Comment by mattn** [comment]
I wonder your C compiler is broken or something missing installed. Could you please try this?

```
$ cat > foo.c
#include <stdlib.h>
int main() {}
^D

$ gcc foo.c
```

**Comment by sredXNY** [comment]
This thing is also happening to me, I also have a fresh install of Linux Mint and I get exactly the same error. Any solution on this?

**Comment by sredXNY** [comment]
I managed to make it work by installing build-essentials, with the next commands:

```
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get update
sudo apt-get -f install
sudo aptitude install build-essential
sudo aptitude update
```

**Comment by dbtrnl** [comment]
`sudo apt install build-essential` worked for me as well.
Using **Linux Mint 20.3 Cinnamon 5.2.7**.

Looks like Mint comes with some libs essential for Golang compilation not installed.

Partial output of `sudo apt install build-essential` (perhaps to help narrow down which of those libs is necessary?)

```bash
The following additional packages will be installed:
  g++ g++-9 libc-dev-bin libc6-dev libcrypt-dev libstdc++-9-dev
Suggested packages:
  g++-multilib g++-9-multilib gcc-9-doc glibc-doc libstdc++-9-doc
The following NEW packages will be installed:
  build-essential g++ g++-9 libc-dev-bin libc6-dev libcrypt-dev libstdc++-9-dev
0 upgraded, 7 newly installed, 0 to remove and 15 not upgraded.
```

**Comment by rittneje** [comment]
I believe libc6-dev and gcc  are the only ones you'll need.
