### ISSUE TITLE
Duplicate symbols error on OSX

### ISSUE THREAD

**Issue by Gys** [mattn/go-sqlite3#258]
If I do 

    go install github.com/mattn/go-sqlite3

or 

    go get github.com/mattn/go-sqlite3

Then I get a long list of similar errors:

    ....
    duplicate symbol _sqlite3_prepare16_v2 in:
    $WORK/github.com/mattn/go-sqlite3/_obj/sqlite3-binding.o
    $WORK/github.com/mattn/go-sqlite3/_obj/sqlite3.o

And then at the end:

    ld: 201 duplicate symbols for architecture x86_64

Any idea what is happening and how this can be solved ?

go version
go version go1.5.1 darwin/amd64
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

**Comment by shaxbee** [comment]
I cannot reproduce it. Can we close it?

**Comment by Gys** [comment]
Yes.

**Comment by Gys** [comment]
I deleted the $GOPATH/src/github.com/mattn/go-sqlite3 folder and then installed it again. That solved the problem.
