### ISSUE TITLE
can not install go-sqlite3

### ISSUE THREAD

**Issue by Smallinger** [mattn/go-sqlite3#265]
i got this error everytime, and can not install sqlite3

github.com/mattn/go-sqlite3
callback.go:32:119: expected ']', found ':'
callback.go:60:73: expected ';', found '{'

**Comment by mattn** [comment]
what version of go do you use?

**Comment by Junxx** [comment]
root@***:~# go version
go version go1.0.2

**Comment by mattn** [comment]
too old

**Comment by adamryman** [comment]
@mattn Could this be closed?
