### ISSUE TITLE
After Go 1.6 upgrade, go-sqlite3 is recompiled every time go test is run

### ISSUE THREAD

**Issue by jeremytregunna** [mattn/go-sqlite3#273]
Content of this bug report is exactly what's written on the tin. Upgraded to Go 1.6 and now, each time I run `go test`, I get to wait for go-sqlite3 to recompile. Every. Time. Is there something that's changed in Go that requires an update in this library, or what's the workaround?

**Comment by vovkasm** [comment]
I think I can answer this question ;-)
 1. I just remove `$GOPATH/pkg/darwin_amd64/github.org/mattn/` directory and now can see same behaviour
 2. To fix this, simple install go-sqlite3: `go get github.com/mattn/go-sqlite3` (or may be even `cd $GOPATH/src/github.com/mattn/go-sqlite3 && go install .`)

**Comment by jeremytregunna** [comment]
:+1: this worked.
