### ISSUE TITLE
Building on Arch Linux with go 1.5.3 linux/amd64 churns RAM and CPU

### ISSUE THREAD

**Issue by rjp** [mattn/go-sqlite3#283]
rjp> go get github.com/mattn/go-sqlite3
[2+ minutes of 100% CPU and 350MB of RAM use later]
rjp> 

According to pacman, sqlite is "sqlite 3.10.2-1" and go is "go 2:1.5.3-3". Machine was idle (loadav <0.5) before and after the compilation step. Seems to be reliably reproducible.

This is the offending command -

/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/cc1 -quiet -I /home/rjp/go/src/github.com/mattn/go-sqlite3 -I /tmp/go-build559916575/github.com/mattn/go-sqlite3/_obj/ -I . -D_REENTRANT -D SQLITE_ENABLE_RTREE -D SQLITE_THREADSAFE -D SQLITE_ENABLE_FTS3 -D SQLITE_ENABLE_FTS3_PARENTHESIS -D SQLITE_ENABLE_FTS4_UNICODE61 /home/rjp/go/src/github.com/mattn/go-sqlite3/sqlite3-binding.c -quiet -dumpbase sqlite3-binding.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build559916575/github.com/mattn/go-sqlite3/_obj/sqlite3-binding.o -g -O2 -std=gnu99 -fPIC -fmessage-length=0 -o /tmp/ccmbV1Dv.s

**Comment by mattn** [comment]
Hmm, if you want to build eventhough build as non-static module, use `go build -tag libsqlite3`
