### ISSUE TITLE
code/ subdirectory is not properly handled by the go tool

### ISSUE THREAD

**Issue by dgsb** [mattn/go-sqlite3#293]
The sqlite3 amalgamation files are ignored by the go tool. It does not cause any issue during the buils as these files are included by higher level other C files, but it prevent to easily vendor this package with the help of godep for instance. The command go list -json should list these file somehow.

**Comment by codefx9** [comment]
Hi,
We are facing a similar issue related to godep when trying to build a static binary. Here is my stack trace:
```
++ go install -v github.com/mattn/go-sqlite3
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
In file included from ../github.com/mattn/go-sqlite3/backup.go:9:0:
./sqlite3-binding.h:2:34: fatal error: code/sqlite3-binding.h: No such file or directory
 #include "code/sqlite3-binding.h"
                                  ^
compilation terminated.
```
We will really appreciate  a quick resolution of this issue.

**Comment by mattn** [comment]
okay could you please make pull-request?

**Comment by codefx9** [comment]
@mattn, I have tried the pull request from @dgsb. That fixed build issues for me.

**Comment by dgsb** [comment]
@codefx9 you might also try to migrate your project to [constabulary/gb](http://github.com/constabulary/gb), which works like a charm.
