### ISSUE TITLE
Compile time error in centos 5.3

### ISSUE THREAD

**Issue by vijaygiri10** [mattn/go-sqlite3#295]
github.com/mattn/go-sqlite3
/usr/bin/ld: unrecognized option '--build-id=none'
/usr/bin/ld: use the --help option for usage information
collect2: ld returned 1 exit status

I am getting  above error while compiling my code

**Comment by mattn** [comment]
please show me `go env`

**Comment by vijaygiri10** [comment]
GOARCH="amd64"
GOBIN="/root/goworkspace"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/goworkspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by mattn** [comment]
Maybe, your C compiler is too old.
