### ISSUE TITLE
Can't compile on windows

### ISSUE THREAD

**Issue by genyx** [mattn/go-sqlite3#297]
Hi, I'm getting 
```
$ go get github.com/mattn/go-sqlite3

# github.com/mattn/go-sqlite3
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

i'm on windows and my "go env" is
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\prg\Go
set GORACE=
set GOROOT=D:\Go
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

its just this package. others work fine. any idea?

**Comment by mattn** [comment]
Maybe your C compiler doesn't support 64bit.

**Comment by Scarfmonster** [comment]
To fix this you need a windows gcc port which supports 64bit. I used [this one](https://sourceforge.net/projects/mingw-w64/) and it is working perfectly. Just remember to remove the old gcc from path and add this to path and it should work fine.

**Comment by Slacki** [comment]
@Scarfmonster Thank you, that worked for me.

**Comment by mattn** [comment]
@genyx closable?

**Comment by Slacki** [comment]
@mattn I had exactly the same issue and it was due to 32 bit version of compiler. Installing 64 bit version resolved it. I think you can close it now.

**Comment by genyx** [comment]
My MinGW did some bad stuff. Scarfmonster posted a good link ;)

**Comment by Sevistuo** [comment]
-----

**Comment by yschkatula** [comment]
In my case, the issue was resolved by running this at admin-elevated prompt:
c:\> choco install mingw

Then appending PATH variable with the folder where you got choco'ed the mingw:
<your tools folder>\mingw64\bin

**Comment by rafaelcn** [comment]
Installation using [chocolatey ](https://chocolatey.org/packages/mingw)is quite easy, I recommend going with that.
