### ISSUE TITLE
Errors cross compile to windows 64

### ISSUE THREAD

**Issue by tiaguinho** [mattn/go-sqlite3#303]
I'm trying cross compile from linux to windows 64 and the following error has occurred

runtime/cgo
gcc: error: unrecognized command line option ‘-mthreads’

Any ideias?

**Comment by mattn** [comment]
Are you using mingw64 C compiler on linux?

**Comment by tiaguinho** [comment]
I wasn't.
But after some research I found a page in stackoverflow so i try.
First install this two packages

apt-get install gcc-multilib
apt-get install gcc-mingw-w64

After that I use this command to compile

GOOS=windows GOARCH=386 CGO_ENABLED=1 CXX_FOR_TARGET=i686-w64-mingw32-g++ CC_FOR_TARGET=i686-w64-mingw32-gcc go build

This works for me.

**Comment by x1unix** [comment]
@tiaguinho you can build your app in  [go-mingw](https://hub.docker.com/r/x1unix/go-mingw) Docker container which contains all necessary MinGW deps in future.

**Comment by williambrode** [comment]
Anyone know how to fix this?  @tiaguinho solution doesn't seem to work (I'm guessing that's why it has so many downvotes).  Building in the go-mingw docker container works but is extremely slow.  Would like to be able to build locally.

**Comment by x1unix** [comment]
@williambrode mount your GOPATH (or use Docker volume) to keep Go build cache.

**Comment by rittneje** [comment]
@williambrode Should be something like this:
```
sudo apt-get install gcc-mingw-w64
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build ...
```

Be sure to set `CC`, **not** `CXX_FOR_TARGET`/`CC_FOR_TARGET`. Those two are only relevant when building the Go compiler from scratch.

**Comment by mateors** [comment]
@rittneje thank you very much, its worked for me, i am using linux ubuntu.

first installed the package the compile for windows.
```
sudo apt-get install gcc-mingw-w64
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build 
```

**Comment by elgs** [comment]
@rittneje this works thanks! But it doesn't seem to work for GOARCH=arm64.

**Comment by navaneeth-dev** [comment]
Works on amd64. But can anyone tell me what is the difference between gcc-mingw-w64 and mingw-w64 package in debian

**Comment by x1unix** [comment]
@navaneeth-dev `mingw-w64` is a metapackage that includes `gcc-mingw-w64`, which is a C compiler.

See https://packages.debian.org/buster/mingw-w64
