### ISSUE TITLE
How to run a dot command like ".import file.csv test"?

### ISSUE THREAD

**Issue by evt** [mattn/go-sqlite3#305]
``` go
_, err = db.Exec(".import epf.csv video")
if err != nil {
    log.Fatal(err)
}
```

`Error: near ".": syntax error`

**Comment by otoolep** [comment]
In my experience, those commands are not supported by this library. `.schema` will result in the same thing.

**Comment by mattn** [comment]
it's a feature of sqlite3 command not this library. if you want, you need to implement the feature or call sqlite3 command.

```
exec.Command("sqlite3", "-cmd", ".import sample.csv ").CaptureOutput()
```
