### ISSUE TITLE
GLIBC_2.14 NOT FOUND ISSUE

### ISSUE THREAD

**Issue by vijaygiri10** [mattn/go-sqlite3#307]
version `GLIBC_2.14' not found (required to start /opt/vijay/./vistaraagent) 
 in suse/ubuntu/centos( where GLIBC<2.14)

when i removed your pkg and build binary than i didn't get any error .it worked where i am building it has 2.18 GLIBC.

**Comment by oldfeel** [comment]
I have encountered this problem, too.

**Comment by GJRTimmer** [comment]
Closed because outdated; please re-open if this is still active.
