### ISSUE TITLE
Windows cross compile to Linux failed

### ISSUE THREAD

**Issue by ankyo** [mattn/go-sqlite3#308]
D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>setlocal

D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>set CGO_ENABLED=1

D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>set GOOS=linux

D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>go install --tags "libsqlite3 linux"
# runtime/cgo

C:\Users\ankyo\AppData\Local\Temp\go-build534230386\runtime\cgo_obj_cgo_main.c:1:0: error: -fPIC ignored for target
all code is position independent) [-Werror]
 int main() { return 0; }
 ^
cc1.exe: all warnings being treated as errors

D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>endlocal

D:\Apps\DevEnv\go\vendor\src\github.com\mattn\go-sqlite3>pause

**Comment by mattn** [comment]
Because you don't use cross C compiler for the linux.

**Comment by mattn** [comment]
I don't know well but you need to install C compiler support linux.
