### ISSUE TITLE
gcc Unrecognized Options ‘-no-pie’

### ISSUE THREAD

**Issue by ghj1976** [mattn/go-sqlite3#310]
`# go get github.com/mattn/go-sqlite3`
`# github.com/mattn/go-sqlite3
gcc: 无法识别的选项 ‘-no-pie’ `

gcc Unrecognized Options ‘-no-pie’

`# cat /proc/version`
Linux version 2.6.32-642.1.1.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 31 21:57:07 UTC 2016

 `# cat /etc/centos-release`
CentOS release 6.8 (Final)

**Comment by ghj1976** [comment]
this is a bug in golang(go1.6.2 linux/amd64)。
https://github.com/golang/go/issues/15900

**Comment by mattn** [comment]
no way to fix by go-sqlite3 if this is really a bug of golang. closable?

**Comment by ghj1976** [comment]
yes， close
