### ISSUE TITLE
warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated

### ISSUE THREAD

**Issue by monoflash** [mattn/go-sqlite3#311]
```
github.com/mattn/go-sqlite3/sqlite3-binding.c:18709:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in OS X 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
```

This warning displayed in macOS Sierra (v. 10.12)

**Comment by mattn** [comment]
please your patch to the author of sqlite3.

**Comment by objectivesheep** [comment]
Any way to bypass sqlite3?

**Comment by nyarly** [comment]
Repeated in #332

**Comment by hktalent** [comment]
mac os 10.12.3
cd /usr/local/opt/go/src/github.com/mattn
git clone https://github.com/mattn/go-sqlite3.git
cd go-sqlite3
git pull

cd /usr/local/opt/go/src/github.com/future-architect/vuls
make install
...........
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting github.com/parnurzeal/gorequest
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting github.com/rifflock/lfshook
[INFO]	--> Exporting github.com/moul/http2curl
[INFO]	Replacing existing vendor dependencies
go install -ldflags "-X 'main.version=v0.2.0' -X 'main.revision=1e8f24d'"
# github.com/future-architect/vuls/vendor/github.com/mattn/go-sqlite3
In file included from vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:2:
vendor/github.com/mattn/go-sqlite3/code/sqlite3-binding.c:16475:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by domino14** [comment]
this is making Go compilation extremely slow. anyone know what to do?

**Comment by hktalent** [comment]
is，ok，now，i do：
$ pwd
/usr/local/Cellar/go/1.7.5/src/github.com
QQ1160:github.com xiatian$ ls
Masterminds		gpmgo			mattn
future-architect	kotakanbe
QQ1160:github.com xiatian$ ls kotakanbe/
go-cve-dictionary
QQ1160:github.com xiatian$ ls future-architect/
vuls
QQ1160:github.com xiatian$ ls mattn/
go-sqlite3
QQ1160:github.com xiatian$ ls gpmgo/
gopm

dir must to /usr/local/Cellar/go/1.7.5/src/github.com, so is ok
@domino14 thanks
