### ISSUE TITLE
Compiling package with Macports prefix

### ISSUE THREAD

**Issue by c9s** [mattn/go-sqlite3#312]
My build failed with the message:

```
/usr/include/module.map:1:25: warning: unknown attribute 'extern_c' [-Wignored-attributes]
/usr/include/module.map:1561:21: warning: unknown attribute 'extern_c' [-Wignored-attributes]
/usr/include/module.map:1577:26: warning: unknown attribute 'extern_c' [-Wignored-attributes]
/usr/include/module.map:1602:23: warning: unknown attribute 'extern_c' [-Wignored-attributes]
/usr/include/module.map:1635:23: warning: unknown attribute 'extern_c' [-Wignored-attributes]
/usr/include/module.map:1662:22: warning: unknown attribute 'extern_c' [-Wignored-attributes]
# github.com/mattn/go-sqlite3
ld: warning: directory not found for option '-L/usr/local/opt/sqlite/lib'
# github.com/mattn/go-sqlite3
ld: warning: directory not found for option '-L/usr/local/opt/sqlite/lib'

```

**Comment by mattn** [comment]
Could you please show me `go env`?

**Comment by GJRTimmer** [comment]
@c9s Have you done `brew install sqlite`

Please re-open if this still is current.

**Comment by big-harry** [comment]
I can confirm that this issue still persists using MacPorts when using the sqlite_icu build tag. On both x86_64 and arm64, MacPorts installs packages into /opt/local. A quick fix I used was to add `CGO_CFLAGS=-I/opt/local/include CGO_LDFLAGS=-L/opt/local/lib`. I tried to patch the paths into sqlite3_libsqlite3.go and sqlite3_opt_icu.go on my machine, but it wouldn't compile the modified version.
