### ISSUE TITLE
Null values screw up a read

### ISSUE THREAD

**Issue by Bleezworld** [mattn/go-sqlite3#313]
Considering the table

    Field1 (int) | Field2 (text) | Field3 (text)
         1       |   row12       |  NULL
         2       |   row22       |  row23
         3       |   NULL        |  NULL
         4       |   NULL        |  row43

and a scan of the table

    package main
    
    import (
        "database/sql"
        "fmt"
        _ "github.com/mattn/go-sqlite3"
    )
    
    func main() {
        var db *sql.DB
        db, _ = sql.Open("sqlite3", "......../test.db")
        rows, _ := _db.Query("SELECT Field1, Field2, Field3 FROM tab")
        for rows.Next() {
            var a int
            var b, c string
            rows.Scan(&a, &b, &c)
            fmt.Println(a, b, c)
        }
    }

The output is

    1 row12 
    2 row22 row23
    3  
    4  

but I expect to see

    1 row12 
    2 row22 row23
    3  
    4  row43

**Comment by mattn** [comment]
you should use a type nullable not string.
