### ISSUE TITLE
GCC still required?

### ISSUE THREAD

**Issue by mandolyte** [mattn/go-sqlite3#315]
The readme indicates that I do not need to have gcc installed, but:
$ go get github.com/mattn/go-sqlite3
 # github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
$ go install github.com/mattn/go-sqlite3
 # github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
$ go version
go version go1.6.1 windows/amd64
$

**Comment by mattn** [comment]
please show me your `go env`

**Comment by mandolyte** [comment]
$  go install github.com/mattn/go-sqlite3
 # github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
$ go env
set GOARCH=amd64
set GOBIN=C:\Users\210019484\Workspace/bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\210019484\Workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
$

**Comment by mattn** [comment]
As your `go env` said, your environment require gcc. If you set environment CC, you may be possible to do you want.

**Comment by Yashiroo** [comment]
Is it possible to clarify what is to be changed in the CC go env variable in order for this to install? I'm trying to go get this package and it's showing me the same error at the first comment, except i have go 1.5.3

**Comment by mattn** [comment]
you need to install gcc.

**Comment by Yashiroo** [comment]
Sorry, my bad.
GCC is already available in MinGW64, i just had to add the directory to the path (MinGW64\bin)
