### ISSUE TITLE
Usecase: create in-memory database with io.Reader

### ISSUE THREAD

**Issue by MOZGIII** [mattn/go-sqlite3#317]
I am reading sqlite database with `archive/zip`, and it would be great if I could read from `io.Reader` to in-memory version of the database.
Is this possible?

**Comment by sqweek** [comment]
I don't think so. It would be technically possible to do directly via a custom implementation for sqlite's VFS layer (although I expect you would be restricted to read-only mode); I'm not aware of an existing implementation.

A simpler approach might be to store the SQL command required to create & populate the database in the zip file, and read+execute those commands to initialise an in-memory database?

**Comment by MOZGIII** [comment]
I don't remember why I needed it now. Pretty sure I was not in control of the input, and it was read-only. So, probably it was just an optimization manner to avoid storing the database file on disk - I'm almost certain is was recieved from some kind of socket already.

**Comment by GJRTimmer** [comment]
Closed because not needed anymore.
