### ISSUE TITLE
sqlite3-binding.c is built even when dynamic linking is requested

### ISSUE THREAD

**Issue by marienz** [mattn/go-sqlite3#318]
Commit 3a5555302e9b06eb5461016462900f1412ae3f7c added a `+build !libsqlite3` constraint to `sqlite3-binding.c`. Commit 5505c7c92e7621c80224ae7f11b480d6d5d6b415 replaced `sqlite3-binding.c` with an unaltered copy of upstream's amalgamation, accidentally removing the build constraint.

Without this constraint, libsqlite3-binding.c is built even when `--tags=libsqlite3` is used (requesting dynamically linking to libsqlite3). This unnecessarily increases build times.

I'd send a pull request that just adds the constraint back, but it's very easy to reintroduce this problem the next time the embedded copy of SQLite is upgraded. Some kind of test is required, and I haven't thought of how to write one yet.

**Comment by gammons** [comment]
:+1: to this issue.  I ran into it using the gorm sqlite3 dialect, which just imports this repo.  Just importing the sqlite3 library is enough to cause 25+ second run times on my computer.

Repoing is easy:

```go
package main

import (
	"fmt"

	//_ "github.com/jinzhu/gorm/dialects/sqlite"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	fmt.Println("Hi!")
}
```

```
~ time go run main.go
Hi!
go run main.go  24.37s user 0.38s system 100% cpu 24.634 total
```

It takes nearly 25 seconds for each run!

**Comment by gammons** [comment]
Nevermind, running `go install github.com/mattn/go-sqlite3` fixed my issue.  Sorry about the trouble!

**Comment by marienz** [comment]
#339 mostly fixed this.
