### ISSUE TITLE
Source code not showing in Coveralls.

### ISSUE THREAD

**Issue by a-p-** [mattn/go-sqlite3#319]
Coveralls isn't able to show the source code for the files in its coverage reports, apparently due to invalid GitHub OAuth credentials being used.

For example, open:
    https://coveralls.io/github/mattn/go-sqlite3

Then within the "SOURCE FILES ON MASTER" section, click on a source file (like "sqlite3.go"):
    https://coveralls.io/builds/7023599/source?filename=sqlite3.go

This message is shown:

```
SOURCE NOT AVAILABLE

The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
```

**Comment by mattn** [comment]
This is an issue of cover command not sqlite3.

**Comment by a-p-** [comment]
Right, it isn't an issue with go-sqlite3 itself. But wouldn't you be the "repo owner" mentioned in the Coveralls error message, who could update the OAuth credentials?

**Comment by mattn** [comment]
cover command doesn't recognize CGO. So never upload file C file names to coveralls.
