### ISSUE TITLE
Update views

### ISSUE THREAD

**Issue by Kaffeekaethe** [mattn/go-sqlite3#320]
I am using this package in a small project in which I am using views.

Now I know that views itself cannot be updated, but it's usually possible to define a trigger to change the underlying tables that create the view. Afterwards, if you execute an update on the view, the underlying table changes. So e.g. my command:

 _UPDATE table SET attr1="7", attr2="name" WHERE id=1;_

would work.

With this package I get the error: 

_"cannot modify table because it is a view"_

Is there either a way to enable the modification of views or is there a the possibility to implement this function?

**Comment by mattn** [comment]
See https://www.sqlite.org/lang_createview.html

>You cannot DELETE, INSERT, or UPDATE a view. Views are read-only in SQLite.

**Comment by Kaffeekaethe** [comment]
You cannot modify view, but you usually can implement a trigger so instead of the above error the trigger is executed and modifies the underlying table. 

However this did also work with this driver.  I just didn't implement the trigger that get called upon the "UPDATE <view>"-command correctly. Now that it's set up properly I do not get the error anymore and can call the "UPDATE <view>"-command. Sorry for the inconvenience.

**Comment by mattn** [comment]
> Sorry for the inconvenience.

No prob. Good to hear you got solve.
