### ISSUE TITLE
Using Pragma

### ISSUE THREAD

**Issue by MikhailKlemin** [mattn/go-sqlite3#325]
Hi !
How do yo use `PRAGMA pragma_name = value;` ? I tried it, got no error, but it was not working too :( 

For example
```
        db, err := sqlx.Open("sqlite3", "./mydata.db")
		if err != nil {
			log.Fatal(err)
		}
		defer db.Close()
		_, err = db.Exec("PRAGMA journal_mode = OFF;")
		if err != nil {
			log.Fatal(err)
		}

```		

After this journal file still keeps appearing on my drive when I work with database...

**Comment by dgsb** [comment]
Hello @MikhailKlemin, I did not reprodude your issue with the following sample https://gist.github.com/dgsb/6061941d2185f761848b143f080f4cd9
I did not see any journal file appearing when using this pragma. Could you provide more information on how to reproduce the issue.

On a side note, are you sure you want to turn the journal off ?

**Comment by MikhailKlemin** [comment]
Hi @dgsb  thanks! 
I think I found source of my error. 
I created the database in one function, but insert the data in another function, and I though that if I state `db.Exec("PRAGMA journal_mode = OFF")` when I created the db, it will be enough.  
But  it is clear now, that if I open the database file from other function, I have to ` db.Exec("PRAGMA journal_mode = OFF")` there too.

**Comment by dgsb** [comment]
Yes the pragma value is associated with the connection object. But be careful, if you desactivate the journal, your data can be not safe under some circumstances.

**Comment by MikhailKlemin** [comment]
Yes, I know about risks. I was trying to see if disabling journal would reduce IO load, and allow more concurrent inserts without "database locked" thing. This was not for production of any kind.
