### ISSUE TITLE
Concurrency and multiple :memory databases

### ISSUE THREAD

**Issue by hsnewman** [mattn/go-sqlite3#326]
I have a program which has two go routines which within each the go routine creates a separate memory database.  

Each go routine loops, within each they do the following:
1) create a memory table from a select from a persistent database
2) loop through the data created (using the in memory database)
3) drop the memory table
4) loop

I am getting the "DROP: database table is locked: sqlite_master DROP TABLE xxxxx" error, but inconsistently on one or both of the tables.

My question:
Can you have two in memory databases which have independent goroutines accessing each?  I'm not having two goroutines access both, it is a 1 to 1 relationship.  1 goroutine creates, accesses, and drops 1 memory database.

Both databases are opened with: 
sql.Open("sqlite3", "file::memory:?cache=shared&loc=auto&mode=rwc")

Thanks!

**Comment by mattn** [comment]
please try to use mode=memory `file:memdb1?mode=memory&cache=shared`

**Comment by hsnewman** [comment]
I believe that solved that issue. Thanks!

**Comment by hsnewman** [comment]
I added another routine creating another table, and again I'm getting "database table is locked: sqlite_master".  Will "mode=memory file:memdb1?mode=memory&cache=shared" work with more than 2 tables?

**Comment by mattn** [comment]
I don't make sure but `memdb1` should be namespace for the tables. So it should work with same connect strings.
