### ISSUE TITLE
Error building go app : undefined: SQLiteConn

### ISSUE THREAD

**Issue by Murf** [mattn/go-sqlite3#327]
..\..\github.com\mattn\go-sqlite3\tracecallback_noimpl.go:7: undefined: SQLiteConn

OS: Windows 10 Pro 64
c++ compiler framework: MinGW64

**Comment by mattn** [comment]
can't reproduce this. what is different from general situation?

**Comment by Murf** [comment]
I have used the test code under "Quickstart" from https://github.com/go-gorp/gorp
I have go version go1.7.1 windows/amd64

I used  "github.com/mattn/go-sqlite3" and it build and installed fine

Any other info you need Matt?

**Comment by mattn** [comment]
please try with `go build -x` on $GOPATH/github.com/mattn/go-sqlite3

**Comment by Murf** [comment]
https://gist.github.com/Murf/ac2d4a17e524c71a01096160408bd7d9

**Comment by mattn** [comment]
What about `go env` ?

**Comment by Murf** [comment]
D:\Working\go\src\github.com\mattn\go-sqlite3>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Working\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\brettm\AppData\Local\Temp\go-build709739654=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

**Comment by mattn** [comment]
> I used "github.com/mattn/go-sqlite3" and it build and installed fine

But not? Is this an issue related on tests?

**Comment by Murf** [comment]
D:\Working\go\src\github.com>
D:\Working\go\src\github.com>rmdir /s mattn
mattn, Are you sure (Y/N)? y
D:\Working\go\src\github.com>go get github.com/mattn/go-sqlite3
D:\Working\go\src\github.com>

That is what I meant Matt, I did not get any errors when I installed it

**Comment by mattn** [comment]
Okay, then what is remaining issue?

**Comment by Murf** [comment]
Matt, I think if is a cross compiler issue
this works:
go build -v test.go

this does not:
D:\Working\go\src\local\syslog-connector-go>set GOARCH=amd64

D:\Working\go\src\local\syslog-connector-go>set GOOS=linux

D:\Working\go\src\local\syslog-connector-go>go build -v test.go
...
log
database/sql
github.com/mattn/go-sqlite3
gopkg.in/gorp.v1
(#) github.com/mattn/go-sqlite3
..\..\github.com\mattn\go-sqlite3\tracecallback_noimpl.go:7: undefined: SQLiteConn

**Comment by Murf** [comment]
Further..
I used set CGO_ENABLED=1
and now have this problem (which seems to have progressed at least)

D:\Working\go\src\local\syslog-connector-go>go build -v test.go
runtime/internal/sys
runtime/internal/atomic
runtime
errors
math
internal/race
sync/atomic
unicode/utf8
sort
sync
unicode
runtime/cgo
io
syscall
bytes
strings
time
strconv
# runtime/cgo
C:\Go\src\runtime\cgo\gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
C:\Go\src\runtime\cgo\gcc_linux_amd64.c:61:2: error: unknown type name 'sigset_t'
  sigset_t ign, oset;
  ^~~~~~~~
C:\Go\src\runtime\cgo\gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
C:\Go\src\runtime\cgo\gcc_linux_amd64.c:61:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors
regexp/syntax
reflect
os
regexp
fmt
database/sql/driver
net/url
log
database/sql
gopkg.in/gorp.v1

**Comment by Murf** [comment]
I think it is because cgo not supported for cross compilation in Go, I will move my dev environment to a linux container.
Thanks Matt, please close

**Comment by andrejvanderzee** [comment]
On Linux I am unable to compile without cgo. Is there any solution to this?

$ CGO_ENABLED=0 go build --ldflags '-extldflags "-static"' -ldflags '-s' -a -installsuffix cgo
# github.com/mattn/go-sqlite3
../../../../github.com/mattn/go-sqlite3/tracecallback_noimpl.go:7: undefined: SQLiteConn

**Comment by mattn** [comment]
go-sqlite3 require ENABLE_CGO=1

**Comment by nkumar15** [comment]
to be more clear CGO_ENABLED=1 is needed.

**Comment by codenoid** [comment]
i'm using ubuntu 18.04

command :

```
CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o app.exe app.go
```

error : 

```
gcc: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?
```

**Comment by rittneje** [comment]
@codenoid You need to set CC to a valid Windows cross compiler. By default you are using the one for your host (Linux).

**Comment by codenoid** [comment]
@rittneje yea, just successfully compile my application in target host (windows)
