### ISSUE TITLE
golang 1.7.1 deprecation warning

### ISSUE THREAD

**Issue by stephenhu** [mattn/go-sqlite3#328]
running on mac os x, recently downloaded go 1.7.1, on build i get the following warning which doesn't block progress, but certainly should be something that needs to be addressed.

this warning doesn't appear with go 1.6.3

mbahu:gostats hu$ go get github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
In file included from ../../mattn/go-sqlite3/sqlite3-binding.c:2:
../../mattn/go-sqlite3/code/sqlite3-binding.c:18400:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by mattn** [comment]
send report this issue to author of sqlite3. this is not an issue of go-sqlite3.

**Comment by nyarly** [comment]
Repeated in #332
