### ISSUE TITLE
cannot build  go-sqlite3 in macOS 10.12

### ISSUE THREAD

**Issue by Macbets** [mattn/go-sqlite3#332]
i tried use go install github/mattn/go-sqlite3 and get bad strings in build log 

../../.go/src/github.com/mattn/go-sqlite3/sqlite3-binding.c:20515:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by mattn** [comment]
This is not an issue of go-sqlite3. Please report this to the author of sqlite3

**Comment by nyarly** [comment]
I've just reported this to the sqlite3 authors, who's position is roughly "wontfix" on the grounds that a) it's a harmless warning and that b) Apple makes use of the OSAtomicCompareAndSwapPtrBarrier function in their own code, so the deprecation is unlikely to become a removal any time soon and c) compiling with -DSQLITE_WITHOUT_ZONEMALLOC (which is there for 10.2 support) removes the call regardless if there's a concern about being caught out without the function call.

So, upshot is that SQLite isn't going to make a change here for the forseeable future.

That said, if there were a way to suppress the warning during builds? If nothing else, it pollutes every `go test` that touches go-sqlite3. I don't know enough about how cgo works to recommend a concrete solution.

**Comment by mattn** [comment]
If put `-DDSQLITE_WITHOUT_ZONEMALLOC` into sqlite3.go, do this fix your issue? Sorry I don't have mac.

**Comment by nyarly** [comment]
It might fix the issue *if* at some future point the deprecated function were deleted by Apple, which sounds unlikely.

I think the PR (merged already) has a better solution for the time being. And the foreseeable future.

**Comment by jadeydi** [comment]
I fixed this problem, by following steps:

1. update homebrew
2. update sqlite
3. git pull github.com/mattn/go-sqlite3

U can try this.

**Comment by puzanov** [comment]
Had the same issue. Here is how I fixed it.
$ brew update
$ brew reinstall sqlite
$ go get -v -u github.com/mattn/go-sqlite3
