### ISSUE TITLE
can not install go-sqlite3

### ISSUE THREAD

**Issue by xingcuntian** [mattn/go-sqlite3#334]
go get -u github.com/mattn/go-sqlite3
# cd /data/golang/src/github.com/mattn/go-sqlite3; git pull --ff-only
来自 https://github.com/mattn/go-sqlite3
 * [新分支]          gh-pages   -> origin/gh-pages
 * [新分支]          master     -> origin/master
 * [新分支]          systemlib  -> origin/systemlib
 * [新标签]          v1.0.0     -> v1.0.0
 * [新标签]          v1.1.0     -> v1.1.0
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/mattn/go-sqlite3: exit status 1

**Comment by mattn** [comment]
This is your configuration or you may have modification in the directory.
