### ISSUE TITLE
Building on OS X 10.12 uses deprecated calls (sqlite3-bindings.c)

### ISSUE THREAD

**Issue by mattwszolek** [mattn/go-sqlite3#336]
On line 20515 `success = OSAtomicCompareAndSwapPtrBarrier(NULL, newzone, (void * volatile *)&_sqliteZone_);` function `OSAtomicCompareAndSwapPtrBarrier` is deprecated. Compiler suggests to use `atomic_compare_exchange_strong()` from C11 (in stdatomic.)

**Comment by mattn** [comment]
Maybe you don't use latest? https://github.com/mattn/go-sqlite3/commit/61c9552d18d1b0c026cb3a55ad3cbb3b36e76c61
