### ISSUE TITLE
Prepared statement broken if prepared after transaction Begin() with :memory: database

### ISSUE THREAD

**Issue by azdagron** [mattn/go-sqlite3#337]
If you are using a `:memory:` database, start a transaction, prepare a statement using the `db`, and then try to use that statement with the transaction via `tx.Stmt()`, you get broken behavior.

Here is a minimal repro:
```
package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := sql.Open("sqlite3", ":memory:")
	check(err)

	_, err = db.Exec(`CREATE TABLE foo(value text)`)
	check(err)

	tx, err := db.Begin()
	check(err)

	stmt, err := db.Prepare(`DELETE FROM foo`)
	check(err)

	_, err = tx.Stmt(stmt).Exec()
	check(err)

	err = tx.Commit()
	check(err)
}
```
When this executes, the statement fails with `no such table: foo`, even though the table exists.

This does NOT repro if any of the following are true:
1) you are backed by a file, instead of `:memory:`
2) you prepare the statement before the `db.Begin()`
3) you prepare the statement with `tx.Prepare` instead of `db.Prepare`

This breaks the guarantee the `sql` interface is supposed to provider wherein you can use a `db.Prepare`'d statement with a transaction via `tx.Stmt`.

**Comment by mattn** [comment]
Use `file:memdb1?mode=memory&cache=shared` instead of `:memory:`.

**Comment by azdagron** [comment]
That is very surprising. Thanks.
