### ISSUE TITLE
Question: how to enable FTS5?

### ISSUE THREAD

**Issue by genez** [mattn/go-sqlite3#340]
I am trying to perform a full-text search but I get this error:
`no such module: fts5`
I understand that I should enable SQLITE_ENABLE_FTS5 pre-processor symbol but I don't know how I can do it

**Comment by genez** [comment]
sorry, it was easy: just go build --tags "fts5" myapplication.go

**Comment by Soltus** [comment]
how to debug but not build use fts5

**Comment by hvaoc** [comment]
To run with Full Text search support 
```
go run --tags "fts5" ./main.go
```

To run with Full Text search support 
```
go build --tags "fts5" ./main.go
```
