### ISSUE TITLE
It don't run from a image named alpine when use docker.

### ISSUE THREAD

**Issue by barnettZQG** [mattn/go-sqlite3#341]
I go build my app with go-sqlite3 in linux.but it don't run in alpine container.

```
backup.go:14:20: fatal error: stdlib.h: No such file or directory compilation terminated.
```

I don't know why is it.If I use ubuntu environment compiler can run in ubuntu?

**Comment by mattn** [comment]
Do you have installed gcc?

**Comment by homotopycolimit** [comment]
RUN apk add --update gcc g++

**Comment by rennanfelipe** [comment]
I'm passing the same problem
Did you solve it?

**Comment by rennanfelipe** [comment]
I'm solve it installing sqlite3 in my OS!

**Comment by goofansu** [comment]
`RUN apk add --update gcc musl-dev` is enough

**Comment by wmzy** [comment]
I go build my app with go-sqlite3 in alpine container.But it don't run in centos6.
> /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

**Comment by majewsky** [comment]
@wmzy Yeah, that's because Alpine uses musl libc, whereas Centos uses glibc. If your program is linked against one sort of libc, it cannot run on a system that uses a different one. Not a problem with this package.
