### ISSUE TITLE
Cannot build/run apps on OS X 10.2

### ISSUE THREAD

**Issue by mlen108** [mattn/go-sqlite3#343]
Looked through issues here & still unable to fix the problem.

I've updated my work laptop to OS X 10.2 and all my apps which use go-sqlite3 do not compile/run.

trying:
`go run app.go`

results in:
```
# pgz/vendor/github.com/mattn/go-sqlite3
cc1: error: unrecognized command line option "-Wno-c99-extensions"
```

Have already checkout https://github.com/mattn/go-sqlite3/commit/61c9552d18d1b0c026cb3a55ad3cbb3b36e76c61

More info:
`go version`

> go version go1.7.3 darwin/amd64

`sqlite3 --version`

> 3.15.0 2016-10-14 10:20:30 707875582fcba352b4906a595ad89198d84711d8

`go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxx/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="/usr/local/bin/gcc-4.2"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="/usr/local/bin/g++-4.2"
CGO_ENABLED="1"
```

Any help on how to resolve this would be appreciated.

**Comment by mlen108** [comment]
Hmm, removing the change introduced in https://github.com/mattn/go-sqlite3/commit/61c9552d18d1b0c026cb3a55ad3cbb3b36e76c61 resolves the problem for me.

**Comment by mattn** [comment]
If remove only `-Wno-c99-extensions`, do you get expected?

**Comment by mlen108** [comment]
Indeed, removed `-Wno-c99-extensions` and I can run/build my apps.
