### ISSUE TITLE
panic: sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by joaquinicolas** [mattn/go-sqlite3#344]
**I my import:**
`import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	_ "github.com/mattn/go-sqlite3"
)`

I try run go get but after go get ran the error not fix.
Can anybody help me? Thank!

**Comment by mattn** [comment]
Because you didn't `go get github.com/mattn/go-sqlite3`
