### ISSUE TITLE
go1.8: support for additional features

### ISSUE THREAD

**Issue by kardianos** [mattn/go-sqlite3#346]
Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by mattn** [comment]
Look into it in later. But context.Context is used for the new feature. How do you think backward compatibility?

**Comment by kardianos** [comment]
You make a valid point. I'm looking into it now.

**Comment by kardianos** [comment]
Use "golang.org/x/net/context" and arrange your files like the sample in the google docs in the section "Supporting pre-go1.8 side by side."

**Comment by mattn** [comment]
Okay, at the first, I'll add code without context features. ex ColumnTypeXXX. Thanks.

**Comment by mattn** [comment]
I'm implementing HasNextResultSet, I have one question. When the several queries in a string, driver should send all of queries? if the part of query was wrong, following queries should not be executed?

**Comment by kardianos** [comment]
My understand with sqlite (which could be wrong) is that it will execute
multiple sql statements in a single prepared batch so long as they are
separated by semicolon. However from initial looking it doesn't seem like
the sqlite engine supports multiple result sets. This is distinct from say
MS SQL Server or My SQL which will return from the server multiple result
sets from just a single query.

So I think you should just send any query string to sqlite like normally.
It just may not support NextResultSet, but unsure.

**Comment by mattn** [comment]
Merged into master branch. https://github.com/mattn/go-sqlite3/pull/348

Thanks.

**Comment by mattn** [comment]
However, I have some projects to do same. :-(

**Comment by mattn** [comment]
Ah, I miss IsolationContext.

**Comment by mattn** [comment]
SQLite3 doesn't support transaction isolate level. It only support single lock transaction per database. So I don't support IsolationContext for go-sqlite3.

@kardianos thanks your advices.
