### ISSUE TITLE
How to compile the 32-bit go-sqlite3 ?

### ISSUE THREAD

**Issue by LonelyPale** [mattn/go-sqlite3#358]
My environment is win7 64-bit, I would like to install 32-bit go-sqlite3, I would like to ask how do?

GOARCH=386
GOOS=windows
GOPATH=F:\lib\GOPATH;F:\Projects\GoProject\FileSpider
GOROOT=E:\app\go\

D:\Users\htky>go install github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
F:\lib\GOPATH\src\github.com\mattn\go-sqlite3\tracecallback_noimpl.go:8: undefined: SQLiteConn

**Comment by mattn** [comment]
you can see the verbose output with `go build -x`

**Comment by LonelyPale** [comment]
D:\Users\htky>go build -x github.com/mattn/go-sqlite3
WORK=D:\Users\htky\AppData\Local\Temp\go-build620098078
mkdir -p $WORK\github.com\mattn\go-sqlite3\_obj\
mkdir -p $WORK\github.com\mattn\
cd F:\lib\GOPATH\src\github.com\mattn\go-sqlite3
"E:\\app\\go\\pkg\\tool\\windows_amd64\\compile.exe" -o "D:\\Users\\htky\\AppDat
a\\Local\\Temp\\go-build620098078\\github.com\\mattn\\go-sqlite3.a" -trimpath "D
:\\Users\\htky\\AppData\\Local\\Temp\\go-build620098078" -p github.com/mattn/go-
sqlite3 -complete -buildid 7aec5bba0b576bb82ae2193a0d07600b41f1a57c -D _/F_/lib/
GOPATH/src/github.com/mattn/go-sqlite3 -I "D:\\Users\\htky\\AppData\\Local\\Temp
\\go-build620098078" -I "F:\\lib\\GOPATH\\pkg\\windows_386" -pack "F:\\lib\\GOPA
TH\\src\\github.com\\mattn\\go-sqlite3\\tracecallback_noimpl.go"
# github.com/mattn/go-sqlite3
F:\lib\GOPATH\src\github.com\mattn\go-sqlite3\tracecallback_noimpl.go:8: undefin
ed: SQLiteConn

**Comment by mattn** [comment]
what output for `go env`?

**Comment by LonelyPale** [comment]
D:\Users\htky>go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\lib\GOPATH;F:\Projects\GoProject\FileSpider
set GORACE=
set GOROOT=E:\app\go
set GOTOOLDIR=E:\app\go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m32 -fmessage-length=0 -fdebug-prefix-map=D:\Users\htky\AppData\
Local\Temp\go-build441319386=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=0

**Comment by LonelyPale** [comment]
D:\Users\htky>gcc --version
gcc (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mattn** [comment]
because `CGO_ENABLED` is 0.

**Comment by LonelyPale** [comment]
set CGO_ENABLED=1
D:\Users\htky>go build -x github.com/mattn/go-sqlite3
WORK=D:\Users\htky\AppData\Local\Temp\go-build713268030
mkdir -p $WORK\runtime\cgo\_obj\
mkdir -p $WORK\runtime\
cd E:\app\go\src\runtime\cgo
CGO_LDFLAGS="-g" "-O2" "-lmsvcrt" "-lm" "-mthreads" "E:\\app\\go\\pkg\\tool\\win
dows_amd64\\cgo.exe" -objdir "D:\\Users\\htky\\AppData\\Local\\Temp\\go-build713
268030\\runtime\\cgo\\_obj\\" -importpath runtime/cgo -import_runtime_cgo=false
-import_syscall=false -- -I "D:\\Users\\htky\\AppData\\Local\\Temp\\go-build7132
68030\\runtime\\cgo\\_obj\\" -Wall -Werror cgo.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd E:\app\go\src\runtime\cgo
gcc -I "E:\\app\\go\\src\\runtime\\cgo" -m32 -mthreads -fmessage-length=0 "-fdeb
ug-prefix-map=D:\\Users\\htky\\AppData\\Local\\Temp\\go-build713268030=/tmp/go-b
uild" -gno-record-gcc-switches -I "D:\\Users\\htky\\AppData\\Local\\Temp\\go-bui
ld713268030\\runtime\\cgo\\_obj\\" -g -O2 -Wall -Werror -o "D:\\Users\\htky\\App
Data\\Local\\Temp\\go-build713268030\\runtime\\cgo\\_obj\\_cgo_main.o" -c "D:\\U
sers\\htky\\AppData\\Local\\Temp\\go-build713268030\\runtime\\cgo\\_obj\\_cgo_ma
in.c"
E:/app/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mi
ngw32/bin/ld.exe: cannot find -lmingwex
E:/app/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mi
ngw32/bin/ld.exe: skipping incompatible E:/app/mingw64/bin/../lib/gcc/x86_64-w64
-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for
 -lmsvcrt
E:/app/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mi
ngw32/bin/ld.exe: skipping incompatible E:/app/mingw64/bin/../lib/gcc/x86_64-w64
-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib\libmsvcrt.a when searching for
 -lmsvcrt
E:/app/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mi
ngw32/bin/ld.exe: skipping incompatible E:/app/mingw64/bin/../lib/gcc/x86_64-w64
-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for
 -lmsvcrt
E:/app/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mi
ngw32/bin/ld.exe: cannot find -lmsvcrt
collect2.exe: error: ld returned 1 exit status

**Comment by LonelyPale** [comment]
Will -lmsvcrt  Where can I find?

**Comment by mattn** [comment]
Sorry, I don't know. Maybe you should install 32bit compiler.

**Comment by LonelyPale** [comment]
Okay, thank you.

**Comment by LonelyPale** [comment]
The problem is solved,
1. Install TDM-GCC 32-bit.
2, set CGO_ENABLED = 1.
But MingW64 not be able to cross-compiler?

**Comment by mattn** [comment]
maybe you should set path to 32bit compiler prefer than 64bit? Sorry, I don't know.
But good to hear.
