### ISSUE TITLE
Dependency tree for tools/upgrade.go

### ISSUE THREAD

**Issue by alexedwards** [mattn/go-sqlite3#361]
Using [gvt](https://github.com/FiloSottile/gvt) (and presumably other tools that support automatic recursive dependency vendoring) leads to a big bunch of dependencies being added when vendoring go-sqlite3.

``` bash
$ gvt fetch github.com/mattn/go-sqlite3
2016/12/08 16:00:03 Fetching: github.com/mattn/go-sqlite3
2016/12/08 16:00:10 · Fetching recursive dependency: golang.org/x/net/context
2016/12/08 16:00:14 · Fetching recursive dependency: github.com/PuerkitoBio/goquery
2016/12/08 16:00:21 ·· Fetching recursive dependency: golang.org/x/net/html
2016/12/08 16:00:21 ··· Fetching recursive dependency: golang.org/x/text/encoding/htmlindex
2016/12/08 16:00:40 ···· Fetching recursive dependency: golang.org/x/text/encoding/charmap
2016/12/08 16:00:40 ····· Fetching recursive dependency: golang.org/x/text/encoding
2016/12/08 16:00:40 ······ Fetching recursive dependency: golang.org/x/text/transform
2016/12/08 16:00:40 ······ Fetching recursive dependency: golang.org/x/text/runes
2016/12/08 16:00:40 ······ Fetching recursive dependency: golang.org/x/text/internal/utf8internal
2016/12/08 16:00:40 ······ Fetching recursive dependency: golang.org/x/text/language
2016/12/08 16:00:40 ······· Fetching recursive dependency: golang.org/x/text/internal/gen
2016/12/08 16:00:40 ········ Fetching recursive dependency: golang.org/x/text/unicode/cldr
2016/12/08 16:00:40 ······· Fetching recursive dependency: golang.org/x/text/internal/tag
2016/12/08 16:00:40 ·· Fetching recursive dependency: github.com/andybalholm/cascadia
```

It looks like this is because the `tool/upgrade.go` file imports `github.com/PuerkitoBio/goquery`, which is used to extract the download URLs from https://www.sqlite.org/download.html. In turn, this package has a big dependency tree.

As `tool/upgrade.go` isn't an core part of the package, would renaming the `tool` directory to `_tool` (so it follows the same naming convention as the `_examples`  directory) be reasonable? An underscore prefix would make it possible for vendoring tool users to (optionally) ignore the directory and keep a cleaner dependency tree, in the same way that any dependencies imported in the examples can be ignored.

**Comment by mattn** [comment]
Ooops, sorry.
