### ISSUE TITLE
sqlite3_go18.go:49: undefined: driver.TxOptions

### ISSUE THREAD

**Issue by houtian** [mattn/go-sqlite3#367]
sqlite3_go18.go:49: undefined: driver.TxOptions

**Comment by mattn** [comment]
please upgrade go

**Comment by glycerine** [comment]
I'm using go1.8 beta1 on darwin, and this still happens. osx10.11.6.

**Comment by mattn** [comment]
please upgrade go.

https://github.com/golang/go/blob/d0501f1da9c54a8053940feeb86e1644ffaae522/src/database/sql/driver/driver.go#L180-L183

**Comment by houtian** [comment]
I update golang to 1.7.3 ，now, I don‘t have the bug
