### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by newhow** [mattn/go-sqlite3#370]
go get -u github.com/mattn/go-sqlite3

got error:
--------------------------------------------------------
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by mattn** [comment]
try `go get -u -d github.com/mattn/go-sqlite3`

**Comment by mattn** [comment]
And try to check your http_proxy?

**Comment by newhow** [comment]
Thank you. It seems that its not a common issue but special to my network settings.

**Comment by mattn** [comment]
So closable?

**Comment by newhow** [comment]
yes. Its not an issue of the package.
