### ISSUE TITLE
Building go-sqlite3 in vagrant fails with error: /usr/bin/ld: cannot find -lrocksdb

### ISSUE THREAD

**Issue by smithbk** [mattn/go-sqlite3#371]
When trying to "go build" this package within vagrant, I get a "cannot find -lrocksdb" error.
I can't find any references to rocksdb.  Is there supposed to be this dependency? 
Any ideas on how to solve?   Thanks

Here is the error I'm getting ...

# github.com/mattn/go-sqlite3
/usr/bin/ld: cannot find -lrocksdb
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
go-sqlite3 doesn't refer rocksdb. maybe your project refer something depend on rocksdb.
