### ISSUE TITLE
using timeout context panics. 

### ISSUE THREAD

**Issue by gaillard** [mattn/go-sqlite3#380]
At line 769 of sqlite3.go there is 

```
go func() {
		select {
		case <-ctx.Done():
			C.sqlite3_interrupt(s.c.db)
			rows.Close()
		case <-rows.done:
		}
	}()
```

when using a timeout context and getting back sql.Rows, if you do both a rows.Close() and cancel() the rows.Close() line above is executed twice, allowing `close(rc.done)` to get called twice on line 840, which panics.
Doesn't matter if you call cancel() first or rows.Close() first, and it's documented not to matter according to the database/sql and context pkgs.
I guess its happening because both cases can proceed and its choosing the first.
A simple non blocking select on line 840 fixes it.

**Comment by gaillard** [comment]
So it seems like it needs to be 
```
go func(db *C.sqlite3) {
	select {
	case <-ctx.Done():
		select {
		case <-rows.done:
		default:
			C.sqlite3_interrupt(db)
			rows.Close()
		}
	case <-rows.done:
	}
}(s.c.db)
```

**Comment by mattn** [comment]
exec() doesn't have rows. so it should be only to be query(). will fix.

**Comment by gaillard** [comment]
cool thx, but doesn't the same thing happen for exec() with the done chan?

**Comment by mattn** [comment]
exec() is blocking, query() is not. so done in exec() should be closed in defer.

**Comment by gaillard** [comment]
Ah right, i'll test the latest commit today thanks!

**Comment by gaillard** [comment]
So it still needs something like 
```
if rc.done != nil {
	close(rc.done)
	select {
	case <-rc.done: //maybe closed from context.
	default:
		close(rc.done)
	}
}
```
for the case where someone cancels the context, and then closes the rows with Close() that these lines are from.
In that case the goroutine is unblocked getting its execution right before the rows.Close() when the caller closes the rows, so the channel is closed twice.

**Comment by gaillard** [comment]
Also on the latest commit here https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L775 if your going to pass the s.c.db into goroutine func explicitly it should be used, but its still using the closed over var.

**Comment by mattn** [comment]
```go
	go func(db *C.sqlite3) {
		select {
		case <-ctx.Done():
			select {
			case <-rows.done:
			default:
				C.sqlite3_interrupt(db)
				rows.Close()
			}
		case <-rows.done:
		}
	}(s.c.db)
```
Is this you want?

**Comment by gaillard** [comment]
No, shouldn't the code here https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L842 instead be:

```
if rc.done != nil {
	close(rc.done)
	select {
	case <-rc.done: //maybe closed from context.
	default:
		close(rc.done)
	}
}
```

Since https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L776 can happen because of a context cancel and then it could be followed by a call to https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L837 which would end up closing the done channel twice.

**Comment by mattn** [comment]
Could you please send me pull-requset?

**Comment by GJRTimmer** [comment]
@gaillard any update ?

**Comment by gaillard** [comment]
Fix that is there already works well.
