### ISSUE TITLE
MacOSX 10.12.3 compilation fails

### ISSUE THREAD

**Issue by fasilenko** [mattn/go-sqlite3#381]
$ go get bitbucket.org/liamstask/goose/cmd/goose

github.com/mattn/go-sqlite3

../../../../github.com/mattn/go-sqlite3/sqlite3-binding.c:16475:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by mattn** [comment]
did you see https://github.com/mattn/go-sqlite3/issues/336 ?

**Comment by fasilenko** [comment]
ok. thanx a lot for info!!
