### ISSUE TITLE
can`t install on windows!!

### ISSUE THREAD

**Issue by 756445638** [mattn/go-sqlite3#385]
$ go install github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
cc1.exe: error: unrecognized command line option "-fno-stack-protector"
C:\Users\Dell\AppData\Local\Temp\cgo-gcc-input-484182171.c:0: sorry, unimplemented: 64-bit mode not compiled in

$ go version
go version go1.8 windows/amd64

$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\dev\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

**Comment by mattn** [comment]
As the message says `sorry, unimplemented: 64-bit mode not compiled in`

**Comment by 756445638** [comment]
what version of gcc I have to install to compile this package??

blow is my gcc -v output:
 gcc.exe   --version
gcc.exe (GCC) 3.4.5 (mingw-vista special r3)
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++.exe  --version
g++.exe (GCC) 3.4.5 (mingw-vista special r3)
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mattn** [comment]
>gcc.exe (GCC) 3.4.5 (mingw-vista special r3)
>Copyright (C) 2004 Free Software Foundation, Inc.

Too old. Should be gcc5 or later maybe.

**Comment by 756445638** [comment]
I must install gcc5 on windows??
Look like it is hard to install gcc5 on windows for me!
is there some other way to install this package??

**Comment by mattn** [comment]
install [msys2](http://www.msys2.org/). then type `pacman -S mingw-w64-x86_64-gcc`. maybe 10 or 20 minutes.

**Comment by Lindenk** [comment]
Does it look like 98981b4a3bc61c9f76cd54c691f1262041973c3e breaks cross compiling when also using go 1.8?

**Comment by 756445638** [comment]
I have installed this package successfully,thank you a lot!
