### ISSUE TITLE
backwards incompatible Error changes

### ISSUE THREAD

**Issue by aronatkins** [mattn/go-sqlite3#394]
The set of changes which start returning `*Error` instead of `Error` are backwards incompatible.
This includes the commit:
https://github.com/mattn/go-sqlite3/commit/cf4bd560f1588d96c502b4c3407fe1a10cef4a28

We have code that was doing something like (testing for a constraint error):

```go
if serr, ok := err.(sqlite3.Error); ok {
  return serr.Code == sqlite3.ErrConstraint
}
```

This is causing the error:
```
foofile.go:112: impossible type assertion:
	sqlite3.Error does not implement error (Error method has pointer receiver)
```

**Comment by azr** [comment]
This broke goose as well : https://bitbucket.org/liamstask/goose/issues/66/cannot-go-get-from-docker-image-golang-18

**Comment by aronatkins** [comment]
My workaround is to fetch through gopkg.in:
```go
import "gopkg.in/mattn/go-sqlite3.v1"
```

This points at the 1.2.0 tag (November 2016).

**Comment by azr** [comment]
Cool thanks, will try & do a PR there

**Comment by mattn** [comment]
Sorry, I'll fix go-sqlite3 soon.
