### ISSUE TITLE
Conn not closed when error inside a connection hook

### ISSUE THREAD

**Issue by gaillard** [mattn/go-sqlite3#397]
relavent spots that need a close:
https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L625
https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L619
https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L612

**Comment by mattn** [comment]
Sure!

https://github.com/mattn/go-sqlite3/commit/fc03fa998970a0110f9727c0441985b35ab50055

Thank you
