### ISSUE TITLE
clang called with every build

### ISSUE THREAD

**Issue by Gys** [mattn/go-sqlite3#401]
I am running OSX latest and Golang 1.8

I installed go-sqlite3 with:
`go get github.com/mattn/go-sqlite3`
`brew install sqlite3`
`go install github.com/mattn/go-sqlite3`

If I now do `go build` for my project, it takes about 50 seconds to build. In the background a `clang` process is started that takes most of this time.
If instead I do `go build --tags "libsqlite3 darwin"` then the `clang` process does not start and the build takes only 10 seconds.

From the readme I thought after `go install github.com/mattn/go-sqlite3`  the c compiler would not be needed anymore ?

**Comment by mattn** [comment]
If you use flags `--tags`, you should use them for the `install` command too. `go install --tags "libsqlite3 darwin" github.com/mattn/go-sqlite3`.

**Comment by Gys** [comment]
Thanks for the quick reply !

However, it does not make any a difference how I do the install. Running `go build` still uses clang.

Btw, I noticed that `go install --tags "libsqlite3 darwin" github.com/mattn/go-sqlite3` compiles very quickly and results in a go-sqlite3.a file of only 415Kb.
Whereas `go install github.com/mattn/go-sqlite3` takes much longer (using clang) and results in a 2.0Mb size for go-sqlite3.a.

**Comment by mattn** [comment]
Maybe, you should use gcc instead of clang.

**Comment by Gys** [comment]
I installed gcc with `brew install gcc` (takes about 90 minutes, in case others want to try as well).
Then I set `export CC=/usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6`
Now its the process `cc1` that is started every time where it was `clang` before. So it did not change anything.

**Comment by Gys** [comment]
I found the cause: the package should not be vendored. I guess in that case the installed version is not found ? So it is compiled every time again.
I removed it from vendor.json and then installed again. After that the build takes less then 10 seconds :-)

**Comment by mattn** [comment]
Ah, sorry about my unuseful advices. But good to hear it.

**Comment by Gys** [comment]
Thanks anyway for the quick replies which are motivating and especially for all the good work !

**Comment by mageddo** [comment]
It can be avoided with the follow workaround 

preparing the env

```bash
GOPATH=~/tmpgo && \
PJT=$GOPATH/src/mypjt && \
mkdir -p $PJT/vendor && \
cd $PJT && \
go get -u -v github.com/mattn/go-sqlite3 && \
cp -r $GOPATH/src/github.com/ $PJT/vendor/ && \
echo 'package main
import _ "github.com/mattn/go-sqlite3"
func main(){}
' > $PJT/main.go &&
```
testing

```
$ time go run main.go 
real	0m28.084s
user	0m27.464s
sys	0m0.528s

$ time go run main.go 
real	0m28.041s
user	0m27.516s
sys	0m0.464s
```
Caching the vendor package
```
go install -v mypjt/vendor/github.com/mattn/go-sqlite3
```
Testing it again 
```
time go run main.go 
real	0m0.319s
user	0m0.292s
sys	0m0.052s
```
