### ISSUE TITLE
the length of SQLiteConn has not changed while close the db or close the SQLiteConn

### ISSUE THREAD

**Issue by lucifercha** [mattn/go-sqlite3#413]
```go
 	sqlite3conn := []*sqlite3.SQLiteConn{}
	sql.Register("sqlite3_with_hook_example",
		&sqlite3.SQLiteDriver{
			ConnectHook: func(conn *sqlite3.SQLiteConn) error {
				sqlite3conn = append(sqlite3conn, conn)
				return nil
			},
		})
```
I register a with SQLiteDriver with a "ConnectHook" like [https://github.com/mattn/go-sqlite3/blob/master/_example/hook/hook.go](url)  .And when i open a new db, the length of sqlite3conn is 2,but whether to close the new database or close the connection，the length of sqlite3conn is still 2.
Is that reasonable？

**Comment by mattn** [comment]
because it's reference. and the connection will be closed atomaticaly.
