### ISSUE TITLE
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol (Ubuntu 16.04)

### ISSUE THREAD

**Issue by minhajakhterkhan199** [mattn/go-sqlite3#417]
Yesterday, gogland on Ubuntu download new updates and after getting updates, it shows below error message in gogland Debugging only . Previously it worked fine. 
Please advise to solve the issue. I also tried to install brew sqllite3 but it also shows Error: No available formula with the name "sqllite3" 
  
GOROOT=/usr/local/go
GOPATH=/home/minhaj/GoLang
/usr/local/go/bin/go build -o /home/minhaj/GoLang/bin/GoLangRun -gcflags "-N -l" "-ldflags=-linkmode internal" /home/minhaj/GoLang/src/IndoorMass/IndoorMain.go
# command-line-arguments
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol close
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol access
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol getcwd
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol ftruncate64
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol fcntl
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol read
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol write
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol fchmod
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol unlink
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol mkdir
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol rmdir
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol fchown
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol geteuid
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol mmap64
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol munmap
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol mremap
github.com/mattn/go-sqlite3(.data.rel): unexpected R_X86_64_64 relocation for dynamic symbol readlink
github.com/mattn/go-sqlite3(.data.rel): unhandled relocation for close (type 42 rtype 1)
github.com/mattn/go-sqlite3(.data.rel): unhandled relocation for access (type 42 rtype 1)
github.com/mattn/go-sqlite3(.data.rel): unhandled relocation for getcwd (type 42 rtype 1)
github.com/mattn/go-sqlite3(.data.rel): relocation target stat64 not defined
/usr/local/go/pkg/tool/linux_amd64/link: too many errors
 
Thanks...

**Comment by mattn** [comment]
dup https://github.com/mattn/go-sqlite3/issues/414

**Comment by minhajakhterkhan199** [comment]
Please advise where to set this -x -ldflags -linkmode=external in gogland IDE for debugging mode.

**Comment by mattn** [comment]
see https://github.com/mattn/go-sqlite3/issues/404

**Comment by minhajakhterkhan199** [comment]
Issue is fixed, please see below link
https://youtrack.jetbrains.com/issue/GO-3857
