### ISSUE TITLE
golang sql.DB proposal is looking for driver maintainer comments.

### ISSUE THREAD

**Issue by james-lawrence** [mattn/go-sqlite3#418]
I recently created a proposal for sql.DB to allow drivers to create open functions without having to go through the sql.Open(...) and its associated registry. The go team has asked for driver maintainers to comment on it.

this was one of the drivers I pointed out where it would be useful, if you could take a few minutes to read the proposal and comment on whether it would be useful that'd be greatly appreciated.

https://github.com/golang/go/issues/20268

**Comment by GJRTimmer** [comment]
@mattn could you look into this request.

**Comment by james-lawrence** [comment]
not necessary anymore, the work was done and released in go 1.10.
