### ISSUE TITLE
I can't build go-sqlite3 on windows/amd64

### ISSUE THREAD

**Issue by xiaojiaqi** [mattn/go-sqlite3#419]
C:\Users\xxx\Desktop\firefox\src\github.com>go version
go version go1.7.1 windows/amd64

C:\Users\xxx\Desktop\firefox\src\github.com>go install github.com/mattn/go-sqlit
e3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

C:\Users\xxx\Desktop\firefox\src\github.com>

how to resolve this issue? thanks

**Comment by mattn** [comment]
install gcc.

**Comment by xiaojiaqi** [comment]
from the README：
if you install go-sqlite3 with go install github.com/mattn/go-sqlite3, you don't need gcc to build your app anymore.
