### ISSUE TITLE
Can not support datetime with milliseconds?

### ISSUE THREAD

**Issue by Pana** [mattn/go-sqlite3#420]
I have a sqlite3 database have some records saved by Node.js. With an datetime column like 2017-04-23 10:53:11.252 +00:00  go-sqlite3 can not scan it to an time.Time variable, even can not scan to a string variable.

**Comment by mattn** [comment]
go-sqlite3 support following formats for timestamp.

https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L129-L137

**Comment by GJRTimmer** [comment]
Closed
