### ISSUE TITLE
RegisterAggregator requires "trace" build tag?

### ISSUE THREAD

**Issue by cathalgarvey** [mattn/go-sqlite3#433]
There may be a very good reason for this, for example gating the use of `reflect` behind a tag, but I was confused to discover that `RegisterAggregator` was not a default feature when I found it in one of the examples.

The line is [here](https://github.com/mattn/go-sqlite3/blob/ecc5105e21a211082827d69227de0899d3462e16/sqlite3_trace.go#L259), and I can only get the `custom_func` example to build with `go build -tags trace`.

That's fine, if documented more clearly. But, does including `-tags trace` install performance-degrading hooks elsewhere? Is there a disadvantage to enabling the `trace` flag?

Thanks!

**Comment by mattn** [comment]
>does including -tags trace install performance-degrading hooks elsewhere? Is there a disadvantage to enabling the trace flag?

Yes. If you are okay to install go-sqlite3 system-global, please do `go -tags trace install` on directory of go-sqlite3.

**Comment by cathalgarvey** [comment]
Is it possible to separate the two? The performance-costly hooks and the `RegisterAggregator` function?
