### ISSUE TITLE
installed mingw for 64bit windows, still cannot build

### ISSUE THREAD

**Issue by student020341** [mattn/go-sqlite3#435]
I tried searching this issue, 
```
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
```
and it looks like most of the resolved issues had obvious problems. In my scenario, I installed mingw and added the bin folder to my path. I can do gcc -v and which gcc, and that yields...
```
$ which gcc
/c/Program Files/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/mingw64/bin/gcc

```

I am able to run go get and go install for "github.com/mattn/go-sqlite3" but I still get that error when I try to build. I think go install is working because I have go-sqlite3.a in my gopath pkg directory... is there some special way I need to use it if we can't figure out the gcc issue?

**Comment by mattn** [comment]
May be space contained in `Program Files`. I can't help you because this is not depend on go-sqlite3.

**Comment by student020341** [comment]
So windows can find it but go cannot because of the space? Thanks for the suggestion, will give that a try.

**Comment by mattn** [comment]
Why you use gcc command from UNIX like shell? Try to do with command prompt.

**Comment by Jason-Abbott** [comment]
FWIW, I played with getting a build to work in the Win10 Unix tools but gave up after time wasted. Instead, I recorded these steps in my project README. They've worked several times.
- Download and install `tdm64-gcc-5.1.0-2.exe` from http://tdm-gcc.tdragon.net/download.
- Go to Program Files and click on "MinGW Command Prompt". This will open a console with the correct environment for using MinGW with GCC.
- Within this console, navigate to your GOPATH.
- Enter the following commands:
```
go get -u github.com/mattn/go-sqlite3
go install github.com/mattn/go-sqlite3
```

**Comment by mattn** [comment]
Yes, That's my expected.

**Comment by student020341** [comment]
I have 4 things to try now the next moment I am at my work station, thank you both!

I thought the issue could be that gcc is in my user path but not my system path... but I will try all of these things. 

Hey @Jason-Abbott , after I do go install, is there anything special I need to do to use the "installed" file? I thought I did go get & go install before, but it still told me it could not find gcc. Or is this perhaps a bug with liteide?

**Comment by Jason-Abbott** [comment]
@student020341 I didn't have to do anything additional. It's in the path after installation so everything works as expected after that. I switch between Win10 and OSX once or twice a day (laptop/desktop) and the steps above have kept it seamless.

**Comment by gosp** [comment]
Hello,
It is better to install `mingw` using (msys2)[http://www.msys2.org/]
It supports `msys2` is installed in `D:\Tools\msys64\`
+ perform `pacman -S mingw-w64-x86_64-gcc` in `msys2_shell` after installing `msys2` 
+ perform `pacman -S mingw-w64-x86_64-sqlite3` to install sqlit3 native library
+ add `D:\Tools\msys64\mingw64\bin` to `PATH` environment

**Comment by student020341** [comment]
Realized I never updated this, my apologies everyone!

After putting the path in the system variables, go under the hood was able to build this properly with gcc! :+1:

**Comment by ilhamsr** [comment]
i've added the mingw64 to my user & system variables, but windows still can't find the gcc, does the variable name matter?
![image](https://user-images.githubusercontent.com/42727440/64141595-e2301780-ce32-11e9-959a-f3fd9293a196.png)


> Realized I never updated this, my apologies everyone!
> 
> After putting the path in the system variables, go under the hood was able to build this properly with gcc! 👍
