### ISSUE TITLE
Install go-sqlite3 still require gcc

### ISSUE THREAD

**Issue by kpvt001** [mattn/go-sqlite3#441]
I used 

> go install github.com/mattn/go-sqlite3

still notice gcc not found

**Comment by mattn** [comment]
dup #175 or #315 or #212

**Comment by rdslw** [comment]
@mattn You seems to have constant flow of bugs like this. 

I think I found the root cause: it's bad wording on readme.md which confuses users. I forsure was confused :) and saw many others. If I may suggest uou should replace paragraph stating:

> go-sqlite3 is cgo package. If you want to build your app using go-sqlite3, you need gcc. However, if you install go-sqlite3 with go install github.com/mattn/go-sqlite3, you don't need gcc to build your app anymore.

to this one:

> go-sqlite3 is cgo package. If you want to build your app using go-sqlite3, you need gcc. You may uninstall gcc after first time compilation after installing go-sqlite3.a into gopath. You can do this with command: go install github.com/mattn/go-sqlite3. This means you still need gcc for the initial build, but you can uninstall it afterwards.

**Comment by mattn** [comment]
Could you please send pull-request?
