### ISSUE TITLE
mac build linux

### ISSUE THREAD

**Issue by wuxsoft** [mattn/go-sqlite3#444]
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -v -p 1 -o linx_spisqlitetomysql
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
sync
io
unicode
unicode/utf8
bytes
math
syscall
time
os
strconv
reflect
fmt
context
database/sql/driver
sort
database/sql
hash
crypto
crypto/sha1
container/list
crypto/subtle
crypto/cipher
crypto/internal/cipherhw
crypto/aes
encoding/binary
crypto/des
math/rand
strings
math/big
crypto/elliptic
crypto/sha512
encoding/asn1
crypto/ecdsa
crypto/hmac
crypto/md5
bufio
internal/syscall/unix
crypto/rand
crypto/rc4
crypto/rsa
crypto/sha256
crypto/dsa
crypto/x509/pkix
encoding/hex
encoding/base64
encoding/pem
path/filepath
io/ioutil
internal/nettrace
internal/singleflight
net
crypto/x509
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/crypto/chacha20poly1305
vendor/golang_org/x/crypto/curve25519
crypto/tls
log
net/url
github.com/go-sql-driver/mysql
golang.org/x/net/context
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:18: undefined: SQLiteConn
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:26: undefined: SQLiteConn
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:27: undefined: namedValue
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:29: undefined: namedValue
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:35: undefined: SQLiteConn
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:36: undefined: namedValue
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:44: undefined: SQLiteConn
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:49: undefined: SQLiteConn
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:54: undefined: SQLiteStmt
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:63: undefined: SQLiteStmt
../../../go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:36: too many errors
regexp/syntax
regexp
github.com/robfig/config
compress/flate
golang.org/x/crypto/pbkdf2
hash/crc32
path
github.com/yeka/zip

**Comment by mattn** [comment]
Please use cross C compiler instead host compiler.
