### ISSUE TITLE
connection returned that was never out

### ISSUE THREAD

**Issue by hsnewman** [mattn/go-sqlite3#445]
I'm getting a "connection returned that was never out" randomly when I am doing the following (it happens occasionally):

pointsdb.Exec("UPDATE points set NumOfStarDates = NumOfStarDates + 1 WHERE Nme = ?", username)

Is there a possible bug?  I'm thinking it has something to do with running out of resources or something.

**Comment by mattn** [comment]
What version of go do you use?

**Comment by hsnewman** [comment]
go version
go version go1.6.2 linux/amd64

sqlite3 -version
3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f

Thanks!
Harris

**Comment by mattn** [comment]
Could you please minimal code to reproduce?

**Comment by hsnewman** [comment]
pointsdb.Exec("UPDATE points set NumOfStarDates = NumOfStarDates + 1 WHERE Nme = ?", username)

**Comment by mattn** [comment]
No, please show me whole part of your code. it seems your code doesn't close connections.
