### ISSUE TITLE
Double close SQLiteRows.done channel

### ISSUE THREAD

**Issue by unlikezy** [mattn/go-sqlite3#448]
This issue is found in this post: https://github.com/golang/go/issues/20160. Running the code in that post with go1.8.3 will cause "close of closed channel" panic.
The reason is that SQLiteRows.Close doesn't set rc.done to nil after close it. (code in sqlite3.go, near line 983)
Somehow SQLiteRows.Close is called in goroutine created in SQLiteStmt.query function, racing with user's rows.Close.
Solution is to add rc.done=nil (and also add a Mutex.Lock in SQLiteRows.Close function might be better).
The code below is tested working fine:
``` 
func (rc *SQLiteRows) Close() error {
    if rc.s.closed {
        return nil
    }    
    if rc.done != nil {
        rc.mu.Lock()
        close(rc.done)
        rc.done = nil
        rc.mu.Unlock()
    }    
    if rc.cls {
        return rc.s.Close()
    }    
    rv := C.sqlite3_reset(rc.s.s)
    if rv != C.SQLITE_OK {
        return rc.s.c.lastError()
    }    
    return nil
}
````

**Comment by mattn** [comment]
Thank you
