### ISSUE TITLE
Issue installing on Mac OS

### ISSUE THREAD

**Issue by slava-vishnyakov** [mattn/go-sqlite3#45]
Had some problems installing the lib on Mac, so just wanted to leave this here for future people searching for help:

after 

```
brew install pkgconfig
brew install sqlite3
```

I've tried `pkg-config --cflags --libs sqlite3`, but got:

```
# pkg-config --cflags sqlite3
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found
exit status 1
```

What you need to do:

```
sudo PKG_CONFIG_PATH=/usr/local/Cellar/sqlite/3.7.15.2/lib/pkgconfig/ go get github.com/mattn/go-sqlite3
```

Please replace `3.7.15.2` with your version.

Thanks for the lib!

**Comment by forhappy** [comment]
I ran into the problem when compiling go-sqlite3:

go get -x github.com/mattn/go-sqlite3
cd .
git clone https://github.com/mattn/go-sqlite3 /Users/hpfu/Go/src/github.com/mattn/go-sqlite3
cd /Users/hpfu/Go/src/github.com/mattn/go-sqlite3
git show-ref
cd /Users/hpfu/Go/src/github.com/mattn/go-sqlite3
git checkout master
WORK=/var/folders/l0/v1jzk76917q9ckqrmr1nxyjhc3c67y/T/go-build158102097
mkdir -p $WORK/github.com/mattn/go-sqlite3/_obj/
mkdir -p $WORK/github.com/mattn/
cd /Users/hpfu/Go/src/github.com/mattn/go-sqlite3
CGO_LDFLAGS="-g" "-O2" /usr/local/Cellar/go/1.3.3/libexec/pkg/tool/darwin_amd64/cgo -objdir $WORK/github.com/mattn/go-sqlite3/_obj/ -- -I $WORK/github.com/mattn/go-sqlite3/_obj/ -std=gnu99 -I. -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE backup.go error.go sqlite3.go sqlite3_other.go
 # github.com/mattn/go-sqlite3
In file included from Go/src/github.com/mattn/go-sqlite3/backup.go:9:
./sqlite3.h:35:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>     /* Needed for the definition of va_list */
         ^
1 error generated.

**Comment by mattn** [comment]
Are you using gcc? Then, what version of gcc do you use?

**Comment by forhappy** [comment]
Hi @mattn , I'm using clang 3.3 in Mac OS X 10.9.5

**Comment by mattn** [comment]
`go env CC` is `clang` ?
