### ISSUE TITLE
database/sql: feedback for non-DSN DB opener

### ISSUE THREAD

**Issue by kardianos** [mattn/go-sqlite3#450]
Related Issue: golang/go#20268
CL: https://go-review.googlesource.com/c/53430

There are two general ways we are considering supporting non-DSN opens.

The current CL has a Connector that is separate from the driver instance. I have a suspicion that it might be better to have the Connector be part of the Driver interface (see the CL comments).

Your feedback on this issue, CL, or the Go issue would be appreciated.

**Comment by GJRTimmer** [comment]
@mattn could you look into this ?

**Comment by kardianos** [comment]
This is in go1.10. look up sql.OpenDB

**Comment by GJRTimmer** [comment]
This will be added with the v2.0.0 release
