### ISSUE TITLE
[PATCH] Add support for solaris

### ISSUE THREAD

**Issue by andy-js** [mattn/go-sqlite3#459]
The patch below adds support for linking against libsqlite3 on Solaris.

<pre>
diff --git a/sqlite3_libsqlite3.go b/sqlite3_libsqlite3.go
index 135863e..e4557e6 100644
--- a/sqlite3_libsqlite3.go
+++ b/sqlite3_libsqlite3.go
@@ -10,5 +10,6 @@ package sqlite3
 #cgo CFLAGS: -DUSE_LIBSQLITE3
 #cgo linux LDFLAGS: -lsqlite3
 #cgo darwin LDFLAGS: -L/usr/local/opt/sqlite/lib -lsqlite3
+#cgo solaris LDFLAGS: -lsqlite3
 */
 import "C"
diff --git a/sqlite3_other.go b/sqlite3_other.go
index a20d02c..f721b5e 100644
--- a/sqlite3_other.go
+++ b/sqlite3_other.go
@@ -9,5 +9,6 @@ package sqlite3
 /*
 #cgo CFLAGS: -I.
 #cgo linux LDFLAGS: -ldl
+#cgo solaris LDFLAGS: -lc
 */
 import "C"
</pre>

**Comment by mattn** [comment]
Thank you
