### ISSUE TITLE
Test failed: TestShortTimeout

### ISSUE THREAD

**Issue by zhsj** [mattn/go-sqlite3#464]
original from https://tests.reproducible-builds.org/debian/rb-pkg/unstable/arm64/golang-github-mattn-go-sqlite3.html

--- FAIL: TestShortTimeout (5.60s)
	sqlite3_go18_test.go:83: Executing db initializing statements
	sqlite3_go18_test.go:128: context deadline exceeded

This test failed. I looked at the code, I don't know why this line https://github.com/mattn/go-sqlite3/blob/05548ff55570cdb9ac72ff4a25a3b5e77a6fb7e5/sqlite3_go18_test.go#L128 wants the previous call to be finished in 10ms?

**Comment by TheTincho** [comment]
Actually, *micro*seconds! I think the test is expecting the timeout will fire after that line, but it is too fragile..

It seems to me we should disable this test in Debian, unless somebody thinks of a way of doing it in a more robust way.

**Comment by mattn** [comment]
Hmm, may be 10millisecond is bits large value for memory database.

**Comment by zhsj** [comment]
@mattn why not check the error is `context.DeadlineExceeded` like the following lines?

**Comment by mattn** [comment]
Ah... this test is wrong. I'll fix in soon.
