### ISSUE TITLE
Question regarding connections/transaction concurrency.

### ISSUE THREAD

**Issue by gaillard** [mattn/go-sqlite3#466]
It looks like the database/sql pkg has the potential to serially interleave transaction and non transaction calls against the same connection grabbed from the pool, if I am reading the source right. Yet sqlite has strong guarantees about having serializable isolation, but only between different connections. Is that maintained in this driver somehow? Since the driver can't influence how the database/sql pkg chooses connections from its own pool, I would think this property is broken?

I might have hit the issue in some code, i'll get together a repro.

**Comment by mattn** [comment]
>Is that maintained in this driver somehow?

No. Beacause sqlite3 doesn't support isolation levels.

related on https://github.com/mattn/go-sqlite3/issues/400 ?

**Comment by gaillard** [comment]
I have confirmed this was a race condition created in my own code, thanks!
