### ISSUE TITLE
Windows: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by mrichman** [mattn/go-sqlite3#467]
Running go 1.9.1 on windows/amd64 (Windows 10)

When calling `go get github.com/mattn/go-sqlite3` (or `go install`) I get the following error:

`exec: "gcc": executable file not found in %PATH%`

**Comment by opoppe** [comment]
go-sqlite3 is a cgo package, you're gonna need gcc to compile it. 
[MinGW-w64](https://sourceforge.net/projects/mingw-w64/) should do the trick.

**Comment by mrichman** [comment]
@opoppe Which of these settings is correct?

![image](https://user-images.githubusercontent.com/11228/31615303-28a8452e-b257-11e7-84f1-598255b97ce8.png)

**Comment by opoppe** [comment]
@mrichman Just change the architecture to x86_64 and you should be good to go

**Comment by GJRTimmer** [comment]
@opoppe See https://stackoverflow.com/questions/29947302/meaning-of-options-in-mingw-w64-installer?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by nbxtruong** [comment]
This one's for you @mrichman 
http://tdm-gcc.tdragon.net/download

**Comment by mattn** [comment]
I suggest this one.

https://musl.cc/

**Comment by mrichman** [comment]
I haven't used Windows since May 2018, but thank you for replying :) I'm sure someone can benefit.

**Comment by amuc2** [comment]
https://github.com/dinedal/textql/issues/65

**Comment by mikelee1** [comment]
save my day

**Comment by RomanSoviak** [comment]
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download - minGW installer

**Comment by boddumanohar** [comment]
```
choco install mingw
```

**Comment by GundamDweeb** [comment]
> ```
> choco install mingw
> ```

This worked for me on Windows 10

**Comment by rittneje** [comment]
@jackios What do you see if you run `where gcc`?

**Comment by jackios** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mattn/go-sqlite3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 凌晨0:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mattn/go-sqlite3] Windows: "gcc": executable file not found in %PATH% (#467)





 
@jackios What do you see if you run where gcc?

**Comment by salatieltiel** [comment]
This [video ](https://www.youtube.com/watch?v=Zcy981HhGw0) should help you.
