### ISSUE TITLE
sqlite error message should looks like "SQLITE_NOTADB file is not a database"

### ISSUE THREAD

**Issue by bronze1man** [mattn/go-sqlite3#475]
I just found that the error mesage of sqlite3 "file is encrypted or is not a database"  is change from "file is encrypted or is not a database" (3.15.1) to "file is not a database" (3.21.0) .
but they all have the same sqlite3ErrName "SQLITE_NOTADB".
So I think all the error message should looks like "SQLITE_NOTADB file is not a database" to make error type check from golang code eaiser.
I can check that the error is file corrupt by strings.Contains(err.Error(),"SQLITE_NOTADB")

Only human readable error message is a bad idea too.When that error message is return, it will be more difficult to search that message in google.

**Comment by mattn** [comment]
go-sqlite3 get message from sqlite3 library. I wonder that should do for this.

**Comment by GJRTimmer** [comment]
@bronze1man The error string is returned from SQLite.

```c++
    /* SQLITE_AUTH        */ "authorization denied",
    /* SQLITE_FORMAT      */ 0,
    /* SQLITE_RANGE       */ "column index out of range",
    /* SQLITE_NOTADB      */ "file is not a database",
    /* SQLITE_NOTICE      */ "notification message",
    /* SQLITE_WARNING     */ "warning message",
```

However you should be able to detect it.
The errors returnd from the lower layer SQLite are wrapped in this package into `Error`

`SQLITE_NOTADB` is defined in C with code `26`

```c++
#define SQLITE_NOTADB      26   /* File opened that is not a database file */
```

[Error Implementation](https://github.com/mattn/go-sqlite3/blob/master/error.go#L19-L25)

You should be able to cast your received error to `Error` of this package and then check if `Code` is `26`.

Hope this helps.
