### ISSUE TITLE
It seems that this library isn't able to use in GAE.

### ISSUE THREAD

**Issue by ghost** [mattn/go-sqlite3#478]
Hi.
I want to deploy my app in Google App Engine.

so I ran the code below...
```
goapp serve
```

Then this error has occured

```
go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/mattn/go-sqlite3/doc.go from GOPATH
```

I think this error won't be resolved as long as this library import "unsafe".
Do you have any ideas?

**Comment by mattn** [comment]
go-sqlite3 is cgo package. so you can't use this.
