### ISSUE TITLE
race: limit on 8192 simultaneously alive goroutines is exceeded, dying

### ISSUE THREAD

**Issue by mattn** [mattn/go-sqlite3#482]
@kardianos

I see that some tests on travis got fail with following errors on master branch.

```
race: limit on 8192 simultaneously alive goroutines is exceeded, dying
```
https://travis-ci.org/mattn/go-sqlite3/jobs/297414230

I looked this on go-sqlite3 but I can't what happen on this. I tried to following patch to make sure the goroutine finished, but not resolved.

```diff
diff --git a/sqlite3.go b/sqlite3.go
index 3b4c5fb..9799321 100644
--- a/sqlite3.go
+++ b/sqlite3.go
@@ -202,6 +202,7 @@ type SQLiteResult struct {
 
 // SQLiteRows implement sql.Rows.
 type SQLiteRows struct {
+	wg       sync.WaitGroup
 	s        *SQLiteStmt
 	nc       int
 	cols     []string
@@ -1066,7 +1067,9 @@ func (s *SQLiteStmt) query(ctx context.Context, args []namedValue) (driver.Rows,
 		done:     make(chan struct{}),
 	}
 
+	rows.wg.Add(1)
 	go func(db *C.sqlite3) {
+		defer rows.wg.Done()
 		select {
 		case <-ctx.Done():
 			select {
@@ -1111,9 +1114,12 @@ func (s *SQLiteStmt) exec(ctx context.Context, args []namedValue) (driver.Result
 		return nil, err
 	}
 
+	var wg sync.WaitGroup
 	done := make(chan struct{})
-	defer close(done)
+
+	wg.Add(1)
 	go func(db *C.sqlite3) {
+		defer wg.Done()
 		select {
 		case <-ctx.Done():
 			C.sqlite3_interrupt(db)
@@ -1127,9 +1133,13 @@ func (s *SQLiteStmt) exec(ctx context.Context, args []namedValue) (driver.Result
 		err := s.c.lastError()
 		C.sqlite3_reset(s.s)
 		C.sqlite3_clear_bindings(s.s)
+		close(done)
+		wg.Wait()
 		return nil, err
 	}
 
+	close(done)
+	wg.Wait()
 	return &SQLiteResult{id: int64(rowid), changes: int64(changes)}, nil
 }
 
@@ -1143,6 +1153,7 @@ func (rc *SQLiteRows) Close() error {
 	rc.closed = true
 	if rc.done != nil {
 		close(rc.done)
+		rc.wg.Wait()
 	}
 	if rc.cls {
 		rc.s.mu.Unlock()
diff --git a/sqlite3_go18_test.go b/sqlite3_go18_test.go
index 2662fcf..2e3a95b 100644
--- a/sqlite3_go18_test.go
+++ b/sqlite3_go18_test.go
@@ -80,7 +80,6 @@ func randStringBytes(n int) string {
 }
 
 func initDatabase(t *testing.T, db *sql.DB, rowCount int64) {
-	t.Logf("Executing db initializing statements")
 	for _, query := range testTableStatements {
 		_, err := db.Exec(query)
 		if err != nil {
```
Could you please what happen on master branch?

**Comment by mattn** [comment]
go-sqlite3 use goroutine to be possible to interrupt query. But the patch above should wait the finish.

**Comment by kardianos** [comment]
I'll look into.

**Comment by kardianos** [comment]
@mattn I think this is a cgo thing. Even when I comment out the two goroutines that watch for context cancelation it still fails with the same error.

What we have determined so far:
 * The error isn't a race condition, but it is only triggered when the race detector is on.
 * Even when the sqlite package doesn't itself spawn new go-routines, it still exhausts all available goroutines.
 * The test opens only a few connections per connection pool, but many (100000) connection pool opens and closes.

Probably the best next step would be to interrupt the test in progress and see who the go routines belong to.

**Comment by kardianos** [comment]
@mattn Thanks for testing on golang/go:master!  The connectionResetter method in the sql pool has a bug that causes a goroutine leak (at least with the race detector on, probably always) when a pool is closed.

I'll work up a golang/go CL in a bit that should solve this.
Thanks again!

**Comment by kardianos** [comment]
Fixed on master. Go 1.9 is not affected.

**Comment by mattn** [comment]
Cool! Thank you!

**Comment by mattn** [comment]
TestStress is now green on master branch. https://travis-ci.org/mattn/go-sqlite3/jobs/297508817
