### ISSUE TITLE
Open returns no error on failed attempt.

### ISSUE THREAD

**Issue by MaineTim** [mattn/go-sqlite3#486]
Sorry if this is normal behavior, or I'm doing something wrong, but on Linux-arm a call to Open fails to return an error when the attempt is unsuccessful due to insufficient permissions, or an non-existent directory in the file path, for example. The same circumstances cause an error on open under Python and the sqlite command line utility. The package was installed using: go install -tags "libsqlite3 linux" github.com/mattn/go-sqlite

**Comment by mattn** [comment]
Could you please show me your code to reproduce?

**Comment by MaineTim** [comment]
Sorry about that!
```
package main

import (
    "database/sql"
    "fmt"
    _ "github.com/mattn/go-sqlite3"
    "os"
    "runtime"
)

const sqlTable = `
CREATE TABLE IF NOT EXISTS runtimes(
StartTime TEXT,
EndTime TEXT,
InsertedDatetime TEXT
);
`
func main() {
    defer os.Exit(0)

    fmt.Println("Attempting to open DBase: ", os.Args[1])
    db, err := sql.Open("sqlite3", os.Args[1])
    if err != nil {
        fmt.Printf("Database open error: %s\n", err)
        runtime.Goexit()
    }
    defer db.Close()
    fmt.Println("Attempting to create table.")
    _, err = db.Exec(sqlTable)
    if err != nil {
        fmt.Printf("Table creation error: %s\n", err)
        runtime.Goexit()
    }
}
```
I tried it on both linux-arm and linux-x86_64 with the same results. If access isn't possible, the Open won't fail, but the Exec will. 
```
 ./testDB test.db
Attempting to open DBase:  test.db
Attempting to create table.

 ./testDB /root/test.db
Attempting to open DBase:  /root/test.db
Attempting to create table.
Table creation error: unable to open database file
```

**Comment by mattn** [comment]
SQLite3 does not flush cache until some triggers. To flush cache forcibly, it should set `pragmra synchronous` like `conn.Exec("pragma synchronous")`.

http://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by MaineTim** [comment]
Okay, so using something like 
```
        db, err := sql.Open("sqlite3", os.Args[1])
        if err == nil && db != nil {
                _, err = db.Exec("pragma synchronous")
        }
        if err != nil {
                fmt.Printf("Database open error: %s\n", err)
                runtime.Goexit()
        }
```
does raise the error, so that's fine. I guess my question now: is there a reason to open (create a connection to) a database you can't actually access? Why does the Open call allow it?

Thanks!

**Comment by mattn** [comment]
It is a behavior of sqlite3.

```
$ echo deadbeef > dummy.db
$ sqlite3 dummy.db
```
You will not see the errors.

**Comment by MaineTim** [comment]
You know, I could swear I got an error from ` sqlite3 /root/test.db` before, but clearly no. 
::facepalm::
So it's _Python_ that is "modifying" behavior when it fails on connection:
```
Traceback (most recent call last):
  File "./test_db_open.py", line 14, in <module>
    conn = sqlite3.connect("/root/test.db")
sqlite3.OperationalError: unable to open database file
```
Anyway, my apologies for the confusion on my part, and my thanks for your help (and your sharing of the package!)
