### ISSUE TITLE
Support for dynamic update

### ISSUE THREAD

**Issue by Vikash082** [mattn/go-sqlite3#492]
I have Table 'T' . It has columns 'A', 'B', 'C' and 'D'. Currently if I have to update 'B', I have query like this:
q := "Insert into T (A) values (?)" 
r, err = tx.Exec(q, "XYZ")  // tx -> transaction

If B, C, D all are updatable column. I need to have different insert statement. Also I have to write multiple condition to select which insert statement to use. Is there a way to avoid writing all the conditional statement and enumerate all the different queries ?

**Comment by GJRTimmer** [comment]
I think that conditionally building the query as a string and then executing it would be a good approach.
