### ISSUE TITLE
arm undefined: SQLiteConn

### ISSUE THREAD

**Issue by 2250526295** [mattn/go-sqlite3#494]
--> linux/arm error: exit status 2
Stderr: # github.com/mattn/go-sqlite3
C:\Users\xu\go\src\github.com\mattn\go-sqlite3\sqlite3_go18.go:18:10: undefined: SQLiteConn

**Comment by mattn** [comment]
please find same issue from issues. May be, you don't install C compiler, or you are trying to do cross compiling but not installed cross C compiler.

**Comment by 2250526295** [comment]
thank you 
apt-get install gcc-arm-linux-gnueabi
`
root@ubuntu:~# go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="/usr/bin/arm-linux-gnueabi-gcc-5"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
`

**Comment by qianguozheng** [comment]
This looks not work for my ubuntu
