### ISSUE TITLE
Not implemented NextResultSet

### ISSUE THREAD

**Issue by mattn** [mattn/go-sqlite3#497]
will do

**Comment by GJRTimmer** [comment]
From #348 

> I decide NOT to support NextResultSet/HasNextResultSet because the go's multiple result is not same as sqlite's one.

Closed

**Comment by zgramana** [comment]
@GJRTimmer I'm a bit confused as the top of this issue says `will do`, but issue #348 which you reference as the reason for closing this ends with @mattn saying he changed his mind and `will do` (and then created this issue to track it). Should this issue not still remain open?

**Comment by zgramana** [comment]
Unless or until it is fully supported, I'd also like to propose that `NextResultSet` be implemented by a stub which always sets an error that is returned by a check to `sql.Rows.Err()` to something along the lines of: `errors.New("NextResultSet is not currently implemented by this sqlite3 driver")`. 

The current behavior of being a (silent) no-op leads people to believe it is supposed to work, which can lead to wasting time trying to figure out why it doesn't. ;-)
