### ISSUE TITLE
panic: "database table is locked" when multiple writes occur concurrently

### ISSUE THREAD

**Issue by spiffytech** [mattn/go-sqlite3#50]
I encountered the problem from Issue 39 and applied the resolution of adding "?cache=shared&mode=rwc" to my open string. Now, when multiple writers run concurrently, I encounter a different error:

```
panic: database table is locked: <table name>
```

Some research indicate SQLite has an API for waiting for the locking query to finish so the next query can be run. Please implement this, so that manually managing concurrent writes, or write retries, is unnecessary.

https://www.sqlite.org/unlock_notify.html

**Comment by gdm85** [comment]
I am using e28cd440fabdd39b9520344bc26829f61db40ece and this issue is still reproducible. I am not using WAL mode, but a connection string like ``file:locked.sqlite?cache=shared&mode=rwc``

@mattn should it be already fixed in current master?

**Comment by dustinhiatt-wf** [comment]
I am using the following connection string `file:locked.sqlitecache=shared&mode=rwc&_busy_timeout=50000000` and creating a new connection for every method call, and setting WAL to true to try and avoid contention but I'm getting constant `table is locked` errors.  This is especially true if the table is `:memory:`.  Is there an easy way for me to set FULL_MUTEX?

**Comment by gdm85** [comment]
I think the first aspect to clear would be if go-sqlite3 itself is goroutine-safe, e.g. if a single instance can be called from multiple goroutines.

Although related, such aspect is separate from the internal SQLite3 locking mechanism (which of course is a nice feature to use) that can work across different processes.
