### ISSUE TITLE
sqlite3_go18.go:18:10: undefined: SQLiteConn

### ISSUE THREAD

**Issue by 456vv** [mattn/go-sqlite3#502]
my version：go 1.9.2

C:\Users\admin>go get github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
K:\code\GO\src\github.com\mattn\go-sqlite3\sqlite3_go18.go:18:10: undefined: SQLiteConn

**Comment by mattn** [comment]
Maybe you are trying to do cross C compile. But you don't use corss-C-compiler. find your issue from [issues](https://github.com/mattn/go-sqlite3/issues?q=is%3Aissue+SQLiteConn+is%3Aclosed)
