### ISSUE TITLE
macOS: link: segmentation fault on developing versions of Go

### ISSUE THREAD

**Issue by elpinal** [mattn/go-sqlite3#503]
## Go version
```
go version devel +4435fcfd6c Thu Nov 30 14:39:19 2017 +0000 darwin/amd64
```

## OS
macOS 10.13.1

## What I do

`main.go`:
```
package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	_, _ = sql.Open("sqlite3", ":memory")
}

```

```
$ go build
```

## What I got

```
GOROOT/pkg/tool/darwin_amd64/link: GOROOT/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: segmentation fault
```
(exit status 2)

## Notes

The error happens since Go 4435fcfd6c3e9751b470809307b4afc7c1769098.
And still occurs on master of Go.
Not happen on go1.9.2, the latest release.

On CentOS it is seemed that the error wasn't reproduced.

Just to make sure: Clang version: Apple LLVM version 9.0.0 (clang-900.0.38)

Perhaps this error is due to Go itself. If so, I think the key may be https://github.com/golang/go/commit/4435fcfd6c3e9751b470809307b4afc7c1769098.

**Comment by suzuken** [comment]
refs https://github.com/golang/go/issues/23046

**Comment by elpinal** [comment]
Thank you! I'll read it later.

**Comment by elpinal** [comment]
Fixed in https://github.com/golang/go/commit/fdecaa837cf94f6679a7683c1929e3b22ab1e07d
