### ISSUE TITLE
cross compile for windows amd64 on Mac OS x

### ISSUE THREAD

**Issue by vtphan** [mattn/go-sqlite3#506]
I'm using Mac OS X Sierra.  This is how I compiled for Windows 64amd:

env GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=gcc CXX=gcc go build -o myprog

I got this error message (which I believe is due to using go-sqlite3):

runtime/cgo
clang: error: argument unused during compilation: '-mthreads' [-Werror,-Wunused-command-line-argument]

Any idea how to fix this?  Thanks.

**Comment by mattn** [comment]
You use host C compiler instead of cross C compiler. Check your `go env` and $CC. you must set $CC to the your cross C compiler.
