### ISSUE TITLE
Compile on linux-mipsle

### ISSUE THREAD

**Issue by woraser** [mattn/go-sqlite3#509]
Hi:
   How can I Compile go-sqlite3 on linux-mipsle? I used command:GOOS=linux GOARCH=mipsle go install,but it did not work。

**Comment by mattn** [comment]
You must use cross C compiler not host compiler. So must set $CC to the path of compiler (for mips)

**Comment by woraser** [comment]
Thanks, it worked

**Comment by fghjhuang** [comment]
can you help me? i also need to use sqlite in mips in openwrt linux system

**Comment by woraser** [comment]
It's my notes，you can try it.I haven't been doing it for a long time.
```
cgo LDFLAGS: -L /opt/libs -l sqlite3
go install cgo LDFLAGS: -L/opt/libs -lsqlite3
CGO_ENABLED=1 GOOS=linux GOARCH=mipsle go build

**Comment by woraser** [comment]
> can you help me? i also need to use sqlite in mips in openwrt linux system

It's my notes，you can try it.I haven't been doing it for a long time.
```
cgo LDFLAGS: -L /opt/libs -l sqlite3
go install cgo LDFLAGS: -L/opt/libs -lsqlite3
CGO_ENABLED=1 GOOS=linux GOARCH=mipsle go build

**Comment by fghjhuang** [comment]
> > can you help me? i also need to use sqlite in mips in openwrt linux system
> 
> It's my notes，you can try it.I haven't been doing it for a long time.
> 
> ```
> cgo LDFLAGS: -L /opt/libs -l sqlite3
> go install cgo LDFLAGS: -L/opt/libs -lsqlite3
> CGO_ENABLED=1 GOOS=linux GOARCH=mipsle go build
> ```

thank you！ i will try it
