### ISSUE TITLE
Return the same connection to the SQL Pool layer

### ISSUE THREAD

**Issue by sfilargi** [mattn/go-sqlite3#510]
Is there any good reason why the driver doesn't return, or have an option to return, the same connection to the sql pool layer?

I.e. in: `func (d *SQLiteDriver) Open(dsn string) (driver.Conn, error)`, can we just reuse the previously opened connection?

Doesn't sqlite handle better multiple requests to the same handle vs opening multiple connections?

**Comment by GJRTimmer** [comment]
To my knowledge because SQLite is file-based for writing is takes an exclusive file-lock. And everybody has to wait.
