### ISSUE TITLE
Add sqlite3 provided userauth module?

### ISSUE THREAD

**Issue by akamensky** [mattn/go-sqlite3#513]
sqlite3 provides userauth module that is included in the source code (`ext/userauth/`), but not included in default builds.

Adding this module would not change any existing applications behavior, but will be a great addition for many developers who are looking for embedded database with some degree of protection.

**Comment by GJRTimmer** [comment]
This is certainly something to look into.

However please note the following.

From user-auth.txt (SQLite Repository)
```
The sqlite_user table is inaccessible (unreadable and unwriteable) to
non-admin users and is read-only for admin users.  However, if the same
database file is opened by a version of SQLite that omits
the -DSQLITE_USER_AUTHENTICATION compile-time option, then the sqlite_user
table will be readable by anybody and writeable by anybody if
the "PRAGMA writable_schema=ON" statement is run first.
```

Would this be acceptable ?

When combining this with a `SEE` extension adding the userauth module would be great.

**Comment by akamensky** [comment]
> Would this be acceptable ?

I think that is fine.

**Comment by GJRTimmer** [comment]
I created a working compilation of the userauth module into go-sqlite3, I have to create all the bindings for Go and write the go functions.

**Comment by GJRTimmer** [comment]
Moved to #579
