### ISSUE TITLE
Bad function design `Exec()`

### ISSUE THREAD

**Issue by xahon** [mattn/go-sqlite3#517]
I think `func (c *SQLiteConn) exec(ctx context.Context, query string, args []namedValue) (driver.Result, error)` has bad design.

```Go
Raw(db, "--
SELECT something_useful FROM bbbb WHERE (user_id = $1);
INSERT INTO user_comments (user_id, comment_id)
   SELECT $2, id FROM comments WHERE (date = $1);", 
UserId, CommentDate)
```

This example will fail because `exec` function splices args array each sql command separated by `;`  
To make it work you need to pass `UserId, UserId, CommentDate` parameters and so on if it will has more queries.  
I think it's designed bad because `$` placeholder is indexable and there's no reason to splice array unlike `?` placeholder

**Comment by mattn** [comment]
Please look namedArgs https://github.com/mattn/go-sqlite3/blob/master/sqlite3_go18_test.go#L20

Or please file new issue on https://github.com/golang/go since go-sqlite3 is driver for `database/sql`.

**Comment by xahon** [comment]
@mattn i already pushed new the same issue in go-sqlite3. Thanks for `sql.Named` mention
