### ISSUE TITLE
Compilation error with go1.6.2

### ISSUE THREAD

**Issue by gameraccoon** [mattn/go-sqlite3#522]
With go1.6.2 I start getting this error:

> cannot find package "context" in any of

Found this info, that path to the **context** package is changed.
https://stackoverflow.com/questions/42802278/install-context-package-in-golang

This diff helped me with the problem:
```diff --git a/sqlite3.go b/sqlite3.go
index 739f91d..0859c27 100644
--- a/sqlite3.go
+++ b/sqlite3.go
@@ -136,7 +136,7 @@ static int _sqlite3_limit(sqlite3* db, int limitId, int newLimit) {
 */
 import "C"
 import (
-       "context"
+       "golang.org/x/net/context"
        "database/sql"
        "database/sql/driver"
        "errors"
```

**Comment by gameraccoon** [comment]
Sorry, missclicked and created this issue before editing it. Will fix the text in couple of minutes.

**Comment by GJRTimmer** [comment]
From Golang 1.7 the `golang.org/x/net/context` has been moved into the core packages as `context`.

This package currently does not run tests against Golang 1.6.x see [.travis-ci.yml](../blob/master/.travis.yml)

@mattn Can you confirm this ? And if this package does not support Golang 1.6.x should we close this ?

**Comment by mattn** [comment]
As @GJRTimmer  mentioned, I had dropped 1.6 already.
