### ISSUE TITLE
Feature, non-breaking build with CGO disabled

### ISSUE THREAD

**Issue by jckimble** [mattn/go-sqlite3#523]
@mattn There's a few people that have problems with go-sqlite3 when compiling a static binary. I for one create them to have minimal docker containers while using this driver for local testing. So my question is what do you think of me creating a pull request that makes go-sqlite3 build with "CGO_ENABLED=0" by creating a stub that compiles only when cgo is disabled.

Any thoughts on this from the community is appreciated.

**Comment by mattn** [comment]
go-sqlite3 is cgo package. so you can't build go-sqlite3 with CGO_ENABLED=0.

**Comment by jckimble** [comment]
@mattn I'm aware of that, but i guess you did awnser my question of would you accept a pull request that would make it non-breaking for static builds. My last commit in my forked repo makes it non-breaking if you reconsider

**Comment by mattn** [comment]
Ah, your change is that make go-sqlite3 be possible to build even if not cgo, right?

**Comment by jckimble** [comment]
Correct

**Comment by mattn** [comment]
Okay, could you please send me your pull-request?
