### ISSUE TITLE
query sql, it seems hanging

### ISSUE THREAD

**Issue by hwhe** [mattn/go-sqlite3#528]
goroutine 65 [syscall, 714 minutes, locked to thread]:
github.com/mattn/go-sqlite3._Cfunc_sqlite3_step(0x7fbfac002198, 0x7fbf00000000)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:833 +0x49
github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func1(0x7fbfac002198, 0x0)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/github.com/mattn/go-sqlite3/sqlite3.go:798 +0x60
github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc423af5630, 0xc423afb040, 0x4, 0x4, 0x4, 0x4)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/github.com/mattn/go-sqlite3/sqlite3.go:798 +0x5d
database/sql.(*Rows).nextLocked(0xc423f68800, 0xc422cdbb68)
	/opt/tools/go/src/database/sql/sql.go:2218 +0x6c
database/sql.(*Rows).Next.func1()
	/opt/tools/go/src/database/sql/sql.go:2203 +0x3c
database/sql.withLock(0xfc9e00, 0xc423f68830, 0xc422cdbba8)
	/opt/tools/go/src/database/sql/sql.go:2614 +0x65
database/sql.(*Rows).Next(0xc423f68800, 0x0)
	/opt/tools/go/src/database/sql/sql.go:2204 +0x83
service/icagent/plugins.(*Batcher).getBatchFromDb(0xc4229fb8f0, 0x0, 0xffffffffffffffff, 0xffffffffffffffff, 0xc423185a70)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:177 +0x6d7
service/icagent/plugins.(*Batcher).batchAndSend(0xc4229fb8f0, 0xb190f7)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:92 +0x61
service/icagent/plugins.(*Batcher).run(0xc4229fb8f0)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:73 +0x161
created by service/icagent/plugins.(*Batcher).Start
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:43 +0x82

goroutine 67 [chan receive, 714 minutes]:
service/icagent/plugins.(*BatcherProcess).listenToChannel(0xc4229f9bd0, 0xc4229df0d4, 0x7)
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/BatcherProcess.go:67 +0xb2
created by service/icagent/plugins.(*BatcherProcess).Start
	/opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/BatcherProcess.go:52 +0x19f

**Comment by hwhe** [comment]
Batcher plugin is my reader plugin, Persise plugin is my writer plugin; 
The two plugin user one same RWMutex, sometime the two plugin hanging for servral hours. This issue occur in a small probability.

goroutine 12 [semacquire, 643 minutes]:
sync.runtime_Semacquire(0xc422a0092c)
         /opt/tools/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc422a00920)
         /opt/tools/go/src/sync/rwmutex.go:43 +0x49
service/icagent/db.(*DbAndLock).ReadLock(0xc4229fc830)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/db/DbRegistry.go:41 +0x2f
service/icagent/plugins.(*Batcher).getBatchFromDb(0xc4229fbe30, 0x0, 0x0, 0x0, 0x0)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:123 +0x77
service/icagent/plugins.(*Batcher).batchAndSend(0xc4229fbe30, 0xb190f7)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:92 +0x61
service/icagent/plugins.(*Batcher).run(0xc4229fbe30)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:73 +0x161
created by service/icagent/plugins.(*Batcher).Start
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:43 +0x82

goroutine 14 [semacquire, 643 minutes]:
sync.runtime_Semacquire(0xc422a00928)
         /opt/tools/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).Lock(0xc422a00920)
         /opt/tools/go/src/sync/rwmutex.go:91 +0x6e
service/icagent/db.(*DbAndLock).WriteLock(0xc4229fc830)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/db/DbRegistry.go:53 +0x2f
service/icagent/plugins.deleteIdRange(0xa3c200, 0xc423df2ec0)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/Batcher.go:234 +0x6b
service/icagent/plugins.(*BatcherProcess).listenToChannel(0xc422ae0230, 0xc4229df184, 0x9)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/BatcherProcess.go:75 +0x337
created by service/icagent/plugins.(*BatcherProcess).Start
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/BatcherProcess.go:52 +0x19f



goroutine 56 [semacquire, 643 minutes]:
sync.runtime_SemacquireMutex(0xc422a00924)
         /opt/tools/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc422a00920)
         /opt/tools/go/src/sync/mutex.go:87 +0x9d
sync.(*RWMutex).Lock(0xc422a00920)
         /opt/tools/go/src/sync/rwmutex.go:86 +0x2d
service/icagent/db.(*DbAndLock).WriteLock(0xc4229fc830)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/db/DbRegistry.go:53 +0x2f
service/icagent/plugins.(*PersisterProcess).persist(0xc4229faaf0, 0xc4227a6000, 0x64, 0x64, 0x1)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/PersisterProcess.go:117 +0xa8
service/icagent/plugins.(*PersisterProcess).Start(0xc4229faaf0)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/plugins/PersisterProcess.go:104 +0x4ae
service/icagent/framework.(*PluginManager).Start.func1.1(0xc42299b540)
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/framework/plugin_management.go:130 +0x5a
created by service/icagent/framework.(*PluginManager).Start.func1
         /opt/build/workspace/ICAgent/Dragon/compile/cloud_master/src/service/icagent/framework/plugin_management.go:131 +0x63

**Comment by mattn** [comment]
As far as I can see, it seems not depend on go-sqlite3.

**Comment by GJRTimmer** [comment]
Closed because no update; please re-open if this is still active.
