### ISSUE TITLE
Go equivalent of `sqlite3 DB .dump` ? 

### ISSUE THREAD

**Issue by schollz** [mattn/go-sqlite3#535]
The `sqlite3` cli tool has the useful functionality of [dumping a database](https://sqlite.org/cli.html) into SQL text format.

Is there a Golang equivalent way of doing this? I use `go-sqlite3` frequently and don't see anything in the API that will do this (please correct me if I'm wrong). 

I also don't know of any other libraries that access the same functionality, so I'm stuck with executing `sqlite3` directly:

```golang
out, _:= exec.Command("sqlite3 DB .dump").Output()
ioutil.WriteFile("DB.sql", out, 0644)
```

I'm posting here, because maybe someone had the same problem and found a solution? Otherwise, @mattn feel free to close this because its not really an issue with this library (which I love dearly!), but more of a feature request.

**Comment by otoolep** [comment]
[rqlite](https://github.com/rqlite/rqlite), which also uses https://github.com/mattn/go-sqlite3/, backs up the database via the `Backup` call. You can see it in action here: https://github.com/rqlite/rqlite/blob/master/db/db.go#L105

That is how the backup functionality described at https://github.com/rqlite/rqlite/blob/master/DOC/BACKUPS.md is implemented.

Perhaps this would work for you?

**Comment by schollz** [comment]
@otoolep Thanks. I like that method for backing up. 

However, I specifically want to generate **SQL text** [as described in this article](http://www.sqlitetutorial.net/sqlite-dump/). I like the SQL text because it makes incremental uploads to a server storage a lot easier (using diff patches).

**Comment by schollz** [comment]
Okay, I'm solving my own issue. I made [schollz/sqlite3dump](https://github.com/schollz/sqlite3dump) which is a Golang port of [Python's iterdump for sqlite3](https://docs.python.org/3.6/library/sqlite3.html#sqlite3.Connection.iterdump). You can just give it a database name and a `io.Writer` and it will write SQL text for the database that can serve to back it up.

**Comment by otoolep** [comment]
Interesting @schollz -- thanks for the reference. I might incorporate this functionality into rqlite at some point.
