### ISSUE TITLE
go-sqlite3 doesn't set sql.ColumnType.DatabaseTypeName() when query contains MAX(column_name)

### ISSUE THREAD

**Issue by rbastic2** [mattn/go-sqlite3#539]
Hi,

I have written a test in my Go ORM, github.com/rbastic/dyndao, to show that SQLite has a flaw in DatabaseTypeName handling when a query contains a MAX() function:

https://github.com/rbastic/dyndao/commit/02d053c5c55c574e7635131b7521d922c90328ad

If you change line 393 to read SELECT %s instead of SELECT MAX(%s) you will see that wrapping a column name with a SQL function call will break the ORM.

Is it possible to fix this? This works in other database drivers (MySQL, Oracle, and Postgres, from what I just checked.)

rbastic@marvin:~/go-src/src/github.com/rbastic/dyndao/adapters/sqlite$ DB_TRACE=1 make test
[....output snipped....]
=== RUN   TestMain/MaxWhereQuery
panic: dyndao GenColumnPointers: ct.DatabaseTypeName() does not appear to be implemented - typeName was an empty string [recovered]
	panic: dyndao GenColumnPointers: ct.DatabaseTypeName() does not appear to be implemented - typeName was an empty string

goroutine 7 [running]:
testing.tRunner.func1(0xc4203a8000)
	/home/rbastic/go1.10/src/testing/testing.go:742 +0x29d
panic(0x821180, 0x904190)
	/home/rbastic/go1.10/src/runtime/panic.go:505 +0x229
github.com/rbastic/dyndao/adapters/sqlite.MakeColumnPointers(0xc420073680, 0xc4200aa2c0, 0xc420025de0, 0x1, 0x1, 0xc42000e040, 0x1, 0x1, 0x0, 0x4c71c9, ...)
	/home/rbastic/go-src/src/github.com/rbastic/dyndao/adapters/sqlite/bind.go:186 +0x858
github.com/rbastic/dyndao/orm.(*ORM).RetrieveManyWithSQLTx(0xc420094820, 0x908c60, 0xc420138780, 0x0, 0x8a9c5b, 0x6, 0xc420014420, 0x2f, 0xc420025de0, 0x1, ...)
	/home/rbastic/go-src/src/github.com/rbastic/dyndao/orm/retrieve.go:247 +0x542
github.com/rbastic/dyndao/orm.(*ORM).RetrieveManyWithSQL(0xc420094820, 0x908c60, 0xc420138780, 0x8a9c5b, 0x6, 0xc420014420, 0x2f, 0xc420025de0, 0x1, 0x1, ...)
	/home/rbastic/go-src/src/github.com/rbastic/dyndao/orm/retrieve.go:195 +0xe5
github.com/rbastic/dyndao/adapters/core/test.testMaxWhereQueryBug(0xc420094820, 0xc4203a8000)
	/home/rbastic/go-src/src/github.com/rbastic/dyndao/adapters/core/test/test.go:398 +0x412
github.com/rbastic/dyndao/adapters/core/test.TestSuiteNested.func17(0xc4203a8000)
	/home/rbastic/go-src/src/github.com/rbastic

**Comment by mattn** [comment]
What do you expect? SQLite3 return typeof("") as text.

**Comment by rbastic2** [comment]
no worries. it's the fault of my orm's design. i bypassed it by querying directly with database/sql.
thanks.
