### ISSUE TITLE
nil slice to zero-length blob

### ISSUE THREAD

**Issue by lucasmrod** [mattn/go-sqlite3#542]
Changes to fix https://github.com/mattn/go-sqlite3/issues/424 also make `nil` slice be converted to zero-length blob. Instead, `nil` slice should be converted to value `NULL`.
```
Current code:
	[]byte -> zero length blob
	nil    -> zero length blob
Proposal:
	[]byte -> zero length blob
	nil    -> NULL blob
```
I can submit a PR if the proposal makes sense to you.

**Comment by GJRTimmer** [comment]
@lucasmrod makes sense, can you submit a PR of evaluation and testing, please also include tests in your PR.
