### ISSUE TITLE
go build --tags "icu" error 

### ISSUE THREAD

**Issue by nntaoli** [mattn/go-sqlite3#543]
`sqlite3-binding.c:171322:10:fatal error: 'unicode/utypes.h' file not found
`
os：
17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by nntaoli** [comment]
fixed
`
 

1.  brew install icu4c
2.   brew link icu4c
3.   CGO_CFLAGS="-I/usr/local/opt/icu4c/include" CGO_LDFLAGS="-L/usr/local/opt/icu4c/lib" go build --tags "icu

"
`

**Comment by chrjsrayman** [comment]
If you are building on Debian installing `libicu-dev` fixed this error for me.
