### ISSUE TITLE
Problems building with --tags json1

### ISSUE THREAD

**Issue by thisisaaronland** [mattn/go-sqlite3#544]
Hi,

I am trying to add `json1` support to this package which uses `go-sqlite3` under the hood:

https://github.com/whosonfirst/go-whosonfirst-sqlite

I have updated the [build process](https://github.com/whosonfirst/go-whosonfirst-sqlite/blob/master/Makefile#L17-L35) to install `go-sqlite3`with the `--tags json1` flag per the docs: 

```
@GOPATH=$(GOPATH) go get "github.com/mattn/go-sqlite3"
@GOPATH=$(GOPATH) go install --tags json1 "github.com/mattn/go-sqlite3"
```

And everything builds/compiles properly but I am still getting "no such function: json_extract". I _think_ I am doing everything correctly but maybe I'm missing something? Thoughts?

```
package main

import (
        "flag"
        "github.com/whosonfirst/go-whosonfirst-sqlite/database"
	"log"
)

func main (){

        dsn := flag.String("dsn", ":memory:", "")
        driver := flag.String("driver", "sqlite3", "")

        flag.Parse()

	db, err := database.NewDBWithDriver(*driver, *dsn)

        if err != nil {
           log.Fatal(err)
        }

        defer db.Close()

        conn, err := db.Conn()

        if err != nil {
           log.Fatal(err)
        }

	sql := "SELECT id, properties, geom FROM geojson WHERE json_extract(properties, '$.placetype') = 'venue'"
        _, err = conn.Query(sql)

        if err != nil {
           log.Fatal(err)
        }

        log.Println("OK")
}
```

**Comment by FiloSottile** [comment]
You need to build your actual binary with `--tags json1`, the tags apply to all dependencies every time.

**Comment by thisisaaronland** [comment]
Ah, okay. That would be the part that I was missing :D 

I re-built my tests with and without the `--tags` flag and everything works (or doesn't work) as expected.

Thanks!
