### ISSUE TITLE
error with master branch(commit d896508f87298565da02ed92730e7065c3de10b8) code compile for linux/android 

### ISSUE THREAD

**Issue by jacentsao** [mattn/go-sqlite3#551]
I have update my go-sqlite3 to the master branch(commit d896508f87298565da02ed92730e7065c3de10b8 ), and when i compile to linux/android i meet error below while for windows it's ok to compile:
```
github.com/mattn/go-sqlite3
../github.com/mattn/go-sqlite3/sqlite3-binding.c:31637:42: error: 'pread64' undeclared here (not in a function)
   { "pread64",      (sqlite3_syscall_ptr)pread64,    0  },
                                          ^
../github.com/mattn/go-sqlite3/sqlite3-binding.c:31655:42: error: 'pwrite64' undeclared here (not in a function)
   { "pwrite64",     (sqlite3_syscall_ptr)pwrite64,   0  },
```

but when i downgrade to commit 615c193e01d8d462eef7ee390171506f531a1c9a (Date:   Tue Oct 24 11:57:10 2017 +0900), it's ok to compile to android/linux and windows.

**Comment by mattn** [comment]
As far as I can see sqlite3-binding.c, pread64 and pwrite64 are not defined without HAVE_PREAD64/HAVE_PWRITE64.

**Comment by mattn** [comment]
Ah, sorry. It is defined in sqlite3.go. So we need to avoid `-DHAVE_PREAD64` on android.

**Comment by mattn** [comment]
Could you please try this patch?

```diff
diff --git a/sqlite3.go b/sqlite3.go
index 58bdab1..683562d 100644
--- a/sqlite3.go
+++ b/sqlite3.go
@@ -10,7 +10,7 @@ package sqlite3
 /*
 #cgo CFLAGS: -std=gnu99
 #cgo CFLAGS: -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1
-#cgo linux CFLAGS: -DHAVE_PREAD64=1 -DHAVE_PWRITE64=1
+#cgo linux,!android CFLAGS: -DHAVE_PREAD64=1 -DHAVE_PWRITE64=1
 #cgo CFLAGS: -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61
 #cgo CFLAGS: -DSQLITE_TRACE_SIZE_LIMIT=15
 #cgo CFLAGS: -DSQLITE_DISABLE_INTRINSIC
```

**Comment by jacentsao** [comment]
Thanks for your quickly reply, it works well for me, Thank you very much.

**Comment by mattn** [comment]
fixed in https://github.com/mattn/go-sqlite3/pull/552
