### ISSUE TITLE
Possible to open connection on already opened file?

### ISSUE THREAD

**Issue by sum12** [mattn/go-sqlite3#556]
I am trying to understand https://github.com/mattn/go-sqlite3/blob/a72efd674f654961a11ac41aae72c0e43963fe6c/sqlite3.go#L794 so let me know if I do make sense.

iiuc the above `Open` function will always create a file if the `dsn` says so.
Is it possible to open a connection when a "writer" is already available, or if a file handle is available ?

**Comment by mattn** [comment]
As far as I know, yes it is possible. But the filesystem must support lock.

**Comment by GJRTimmer** [comment]
> As far as I know, yes it is possible. But the filesystem must support lock.

This is correct, fully possible, and the locking is indeed managed by the OS Kernel.

Please note however the following restrictions:
* OS + FileSystem Must support Locking
* `PRAGMA locking_mode` must be set to `NORMAL` if it is set to exclusive then there will be an exclusive lock on the file.

Answered. 

@mattn Please Close.

**Comment by sum12** [comment]
thank you.

Can you give me some example how I can do that?

**Comment by GJRTimmer** [comment]
@sum12 have you read the README on the new options we implemented ? Check out the Connection String settings.
