### ISSUE TITLE
go-sqlite3 with static library

### ISSUE THREAD

**Issue by Stoyvo** [mattn/go-sqlite3#557]
Thanks for go-sqlite3!

It is difficult to find documentation on how to reference a custom build sqlite3 library (EG: libsqlcipher-osx.a)

Currently I can use such library if I edit sqlite3.go and add:
```
#cgo CFLAGS: -I/Development/sqlcipher/sqlcipher-static-osx/include
#cgo LDFLAGS: /Development/sqlcipher/sqlcipher-static-osx/osx-libs/libsqlcipher-osx.a -framework Security -framework Foundation
```
and build with:
`go build -tags libsqlite3 -v -ldflags "-s -w"`

However this requires a very specific change to the package and bad practice.

How do we specify these LD and C flags without modifying the package?

**Comment by mattn** [comment]
You can use CGO_CFLAGS and CGO_LDFLAGS environment variables.
