### ISSUE TITLE
[Proposal] Reduce build time

### ISSUE THREAD

**Issue by GJRTimmer** [mattn/go-sqlite3#567]
@mattn What do you think about reducing build time on Travis CI ?

# Proposal
* Remove Golang:master
* Aggregate several features into a single build `GOTAGS` command

**Comment by mattn** [comment]
Yes, it's too long. I prefer second.

**Comment by GJRTimmer** [comment]
I also would like to suggest we support 2 versions backwards. This would mean the following.

- Golang Current: 1.10.x
- Backwards support 2 versions: Golang:1.9, Golang:1.8 and completly drop 1.7.

@mattn How do you feel about this ?

**Comment by mattn** [comment]
Sounds good to me. Please do.

**Comment by GJRTimmer** [comment]
Oke, submitting change to PR #563 and closing this Issue with commit.

**Comment by GJRTimmer** [comment]
Autoclose on merge of #563
