### ISSUE TITLE
How foreign key on delete cascade is enforced?

### ISSUE THREAD

**Issue by vonzcy** [mattn/go-sqlite3#585]
I am trying to have one relation foreign key reference the primary key in another relation, so I wrote 
```
CREATE TABLE table1 (id INTEGER NOT NULL PRIMARY KEY);

CREATE TABLE table2 (
   name TEXT, 
   fid INTEGER,
   FOREIGN KEY (fid) REFERENCES table1(id) ON DELETE CASCADE
); 
```

But I do not see the effect of cascade deletion. After deleting one tuple from table1, tuples having foreign key referencing that tuple in table1 are not deleted. Did I miss anything?

Thanks!

**Comment by vonzcy** [comment]
@GJRTimmer Ohhhhh. That's the point! Thanks for the catch!

**Comment by GJRTimmer** [comment]
@vonzcy did the PRAGMA solve your case ? We are currently supporting these PRAGMA through the new additions of the [connection string](https://github.com/mattn/go-sqlite3#connection-string).
