### ISSUE TITLE
Problem on Windows 10 running go install

### ISSUE THREAD

**Issue by DaleBingham** [mattn/go-sqlite3#587]
When I run the below in my cygwin64 terminal in my application directory I get the following error. I installed all the tools in cygwin64's setup.exe and I exported the CGO_ENABLED=1 to ensure that showed up with I did 'set'. I also can type 'gcc' and it fires correctly. Hopefully this is a simple thing.  I also set the CGO_ENABLED=1 in my windows command prompt for Win10 and got the same exact error. 

-----------------------------------------------

$ go install github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
/usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

**Comment by DaleBingham** [comment]
with the -x

gcc -I "C:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\" -g -O2 -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_TRACE_SIZE_LIMIT=15 -DSQLITE_OMIT_DEPRECATED -DSQLITE_DISABLE_INTRINSIC -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -Wno-deprecated-declarations "-IC:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -fno-stack-check -fno-stack-protector -mno-stack-arg-probe -o "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x010.o" -c sqlite3_windows.cgo2.c
cd C:\Users\019631\go\src\github.com\mattn\go-sqlite3
gcc -I "C:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\" -g -O2 -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_TRACE_SIZE_LIMIT=15 -DSQLITE_OMIT_DEPRECATED -DSQLITE_DISABLE_INTRINSIC -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -Wno-deprecated-declarations "-IC:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -fno-stack-check -fno-stack-protector -mno-stack-arg-probe -o "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x011.o" -c sqlite3-binding.c
cd $WORK\b001
gcc -I "C:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\" -g -O2 -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_TRACE_SIZE_LIMIT=15 -DSQLITE_OMIT_DEPRECATED -DSQLITE_DISABLE_INTRINSIC -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -Wno-deprecated-declarations "-IC:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -fno-stack-check -fno-stack-protector -mno-stack-arg-probe -o "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_cgo_main.o" -c _cgo_main.c
cd C:\Users\019631\go\src\github.com\mattn\go-sqlite3
gcc -I "C:\\Users\\019631\\go\\src\\github.com\\mattn\\go-sqlite3" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_cgo_.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_cgo_main.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x001.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x002.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x003.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x004.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x005.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x006.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x007.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x008.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x009.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x010.o" "C:\\Users\\019631\\AppData\\Local\\Temp\\go-build028313626\\b001\\_x011.o" -g -O2 -lmingwex -lmingw32
# github.com/mattn/go-sqlite3
/usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
It is cygwin compiler. You should use mingw compiler instead.

**Comment by DaleBingham** [comment]
That was it thank you! I used mingw-64 and had to make sure on the MinGW install I selected 64 bit v. i686 w32 and all was good to go. Thank you for such a quick reply.
