### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by gjrtimmer** [mattn/go-sqlite3#598]
# Go-SQLite3 v2.0.0 

***WORK IN PROGRESS***

# Please Submit Your Wishes / Requests

## Planned Updates
* [ ] Add Context to errors [More Information](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully)
* [x] Add additional tests for provided options
* [x] Fix Extension loading; current when a module cannot be found it returns an unknown error 115 from SQLite; provided more error information which extension could not be loaded.
* [x] Implement Golang:1.10 SQL Connector
* [x] Rewrite connection configuration
* [x] See if sqlite3.go can be split on a functional level with moving to code for statements to its own file
* [x] Update Examples
* [x] Research if in combination with new configuration if the DSN connection can be configured with options without a `_` prefix.
* [x] Add more comments to explain workings to allow easier contribution
* [x] Add contributing guide
* [x] Increase code coverage
* [x] Implement Golang project layout

## Tests
Write additional tests

* [x] Foreign Keys
* [ ] FTS5
* [ ] ICU
* [x] Introspect
* [ ] JSON1
* [ ] Secure Delete (If possible)
* [X] Stat4
* [x] User Auth

**Comment by GJRTimmer** [comment]
@mattn Please checkout and take a look, documentation is not done yet. Can you provide some feedback for me ?

**Comment by mattn** [comment]
Thanks your great works. I'm thinking all of task are not required for 2.0.0 .

**Comment by GJRTimmer** [comment]
@mattn Will update the tasks

**Comment by GJRTimmer** [comment]
@mattn I will complete the 2.0.0 and incorporate all the current missing items like documentation.

**Comment by GJRTimmer** [comment]
@mattn I would like to know how do you feel about introducing a dependency on `github.com/pkg/errors`  so we can wrap errors and provide more and better error information.

**Comment by mattn** [comment]
I don't have strong opinion but what the use-case?

**Comment by y4dkit** [comment]
Is there a support for Update Hook? (https://www.sqlite.org/c3ref/update_hook.html)

Is it possible to set a callback whenever I insert, update or delete?

**Comment by GJRTimmer** [comment]
@mattn Use case is to better track down errors; we can add an additional context error where it occurs. So when printing the stacktrace you can better track down where it originated.

**Comment by GJRTimmer** [comment]
@y4dkit Will look into it; I will try so see if I at least can inject the open Pre-Update Hook.
Have you written an example for the update hook maybe ?

**Comment by AlekSi** [comment]
I would like v2 be compatible with Go modules.

**Comment by powerjungle** [comment]
Shouldn't this be added to the list as well? https://github.com/mattn/go-sqlite3/pull/802
It's kinda weird leaving ORDER BY and LIMIT behind.

**Comment by mattn** [comment]
This isn't working, at least not the latest. I would like to thank to gjrtimmer for challenging this change. Unfortunately this didn't match my intentions. Closing.
