### ISSUE TITLE
Virtual table examples not building

### ISSUE THREAD

**Issue by rparth** [mattn/go-sqlite3#609]
#:~/go/src/github.com/mattn/go-sqlite3/_example/vtable$ go build
# github.com/mattn/go-sqlite3/_example/vtable
./main.go:14:15: conn.CreateModule undefined (type *sqlite3.SQLiteConn has no field or method CreateModule)
./vtable.go:22:70: undefined: sqlite3.VTab
./vtable.go:23:10: c.DeclareVTab undefined (type *sqlite3.SQLiteConn has no field or method DeclareVTab)
./vtable.go:36:71: undefined: sqlite3.VTab
./vtable.go:46:31: undefined: sqlite3.VTabCursor
./vtable.go:65:39: undefined: sqlite3.InfoConstraint
./vtable.go:65:68: undefined: sqlite3.InfoOrderBy
./vtable.go:65:91: undefined: sqlite3.IndexResult
./vtable.go:66:10: undefined: sqlite3.IndexResult
#:~/go/src/github.com/mattn/go-sqlite3/_example/vtable$

**Comment by GJRTimmer** [comment]
You forget to compile with the vtable module.

See READMEE Feature section.

```bash
go build -v -tags=sqlite_vtable .
```

**Comment by rparth** [comment]
Awesome thanks! I didnt see anything in the readme on the vtable. Maybe README needs an update.
