### ISSUE TITLE
_examples/mod_vtable/Makefile missing include path for g++

### ISSUE THREAD

**Issue by rparth** [mattn/go-sqlite3#610]
_examples/mod_vtable/Makefile missing include path for g++, compile fails with sqlite-bindings.h cannot find for #include.....

make
g++ -fPIC -shared -o sqlite3_mod_vtable.so sqlite3_mod_vtable.cc -lsqlite3 -lcurl
sqlite3_mod_vtable.cc:3:10: fatal error: sqlite3-binding.h: No such file or directory
 #include <sqlite3-binding.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:21: recipe for target 'sqlite3_mod_vtable.so' failed
make: *** [sqlite3_mod_vtable.so] Error 1

**Comment by GJRTimmer** [comment]
This is known, will be fixed in the 2.0.0 branch.

This is the fixed Makefile

```bash
# Get Current Directory
CURDIR = $(shell pwd)

ifeq ($(OS),Windows_NT)
EXE=extension.exe
EXT=sqlite3_mod_vtable.dll
RM=cmd /c del
LIBCURL=-lcurldll
LDFLAG=
else
EXE=extension
EXT=sqlite3_mod_vtable.so
RM=rm
LDFLAG=-fPIC
LIBCURL=-lcurl
endif

# Include source from repository
CFLAGS=-I$(CURDIR)/../../driver

all : $(EXT) $(EXE)

$(EXE) : extension.go
	go build -v -tags=sqlite_vtable $<

$(EXT) : sqlite3_mod_vtable.cc
	g++ $(LDFLAG) $(CFLAGS) -shared -o $@ $< $(LIBCURL)

clean :
	@-$(RM) $(EXE) $(EXT)
```

**Comment by GJRTimmer** [comment]
Also to run from current build directory.

```bash
LD_LIBRARY_PATH=$(pwd) ./extension
```

**Comment by rparth** [comment]
Awesome thanks!
