### ISSUE TITLE
Cannot compile with Gomobile

### ISSUE THREAD

**Issue by ehsannm** [mattn/go-sqlite3#613]
I get this error when i bind my project with go mobile:

mattn/go-sqlite3/error.go:14:17: invalid constant type invalid type)))

the error is for this line:

// ErrNoMask is mask code.
const ErrNoMask C.int = 0xff

any help?

**Comment by mattn** [comment]
I'm not familier to gombile but it is possible to comple CGO package?

**Comment by GJRTimmer** [comment]
@ehsannm Have you checked the README ? Please see https://github.com/mattn/go-sqlite3/issues/201#issuecomment-150725323
