### ISSUE TITLE
Upgrade to SQLite 3.25.1

### ISSUE THREAD

**Issue by azawawi** [mattn/go-sqlite3#638]
Please upgrade to SQLite 3.25.1 (hot-fix) released on 2018-09-18. Change log is available [here](https://www.sqlite.org/changes.html).

Thanks.

**Comment by pupizoid** [comment]
@mattn, can you also draft new release so I can update dependency in my project, since I'm using go modules?

**Comment by mattn** [comment]
Sorry, sqlite3 3.25.1 have a bug that can't build.

```
Job #859.11
https://coveralls.io/jobs/40431301
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3_user_authenticate’:
sqlite3-binding.c:219361:3: error: too few arguments to function ‘sqlite3ExpirePreparedStatements’
   sqlite3ExpirePreparedStatements(db);
   ^
sqlite3-binding.c:80218:21: note: declared here
 SQLITE_PRIVATE void sqlite3ExpirePreparedStatements(sqlite3 *db, int iCode){
                     ^
FAIL	github.com/mattn/go-sqlite3 [build failed]
```
sqlite3ExpirePreparedStatements have two usage difference.

**Comment by azawawi** [comment]
@mattn Thanks. 3.25.2 is already out on 2018-09-25. They seem to be pushing releases like crazy after window functions have been added. Change log is available [here](https://www.sqlite.org/changes.html). I see one entry for compiler warnings / minor problems. Hopefully it will fix it.

**Comment by azawawi** [comment]
Thanks :+1:
