### ISSUE TITLE
MacOS 10.13.6 - go-sqlite3 stalls indefinitely on 'go build'

### ISSUE THREAD

**Issue by bowerscd** [mattn/go-sqlite3#646]
On 10.13.6, compiling a project with 'go build' when importing go-sqlite3, results in the compilation process stalling indefinitely.

minimum code sample:

```golang
package main

import (
    "database/sql"
    "fmt"

    _ "github.com/mattn/go-sqlite3"
)

func main() {
    fmt.Printf("Hello, World!\n")
    db, err := sql.Open("sqlite3", "file:db.sqlite")
    if err != nil {
        panic(err)
    }
    defer db.Close()
}
```

`go version`: `go1.11 darwin/amd64`
`sqlite3 -version`: `3.25.2 2018-09-25 19:08:10 fb90e7189ae6d62e77ba3a308ca5d683f90bbe633cf681865365b8e92792d1c7`

environment vars:
`CGO_ENABLED=1`
`CC=clang`
Oddly enough, `go get -u github.com/mattn/go-sqlite3` and `go install github.com/mattn/go-sqlite3` terminate and work fine.

When I refit the above code to work with the postgres/MySQL driver compilation completed, so it's something related to `go-sqlite3`.

Any ideas?

**Comment by mattn** [comment]
What version of go do you use? I'm not an user of OSX and I don't make sure but older version of Go with CGO doesn't work on High Siera. https://github.com/golang/go/issues/27843

**Comment by bowerscd** [comment]
`go version` reports `go1.11.1 Darwin/amd64`. Updated yesterday from 1.11.0. (I use the homebrew install - which appears to be different from [golang/go#27843](
https://github.com/golang/go/issues/27843). 

I cannot reproduce this on a linux container running go 1.11.1 with CC=clang and clang 7.0.0 installed. It does take a bit, but it terminates. 

The only difference between the two environments other than the OS, would be clang. 

On OSX: `clang -v`
```
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
On Linux: `clang -v`
```
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/sbin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/sbin/../lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Selected GCC installation: /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

Tested my theory about clang by installing gcc-8 via home-brew, exporting `CC=gcc-8`.

Compilation Terminates. It appears go-sqlite3 (or possibly cgo) is having some difficulty with the OSX version of clang.
