### ISSUE TITLE
Support 3.25.2 sqlite

### ISSUE THREAD

**Issue by tkinz27** [mattn/go-sqlite3#656]
3.25.2 was released 2018-09-25 and has a few new features that seem pretty useful, specifically support for window functions and new features to alter table such as rename column.

**Comment by mattn** [comment]
already supported :)

https://github.com/mattn/go-sqlite3/blob/c7c4067b79cc51e6dfdcef5c702e74b1e0fa7c75/sqlite3-binding.h#L127

**Comment by tkinz27** [comment]
Ah nice. I was only looking at the releases. I see a bunch of work on a 2.0 release. Are their plans for a 1.10 release?

**Comment by mattn** [comment]
tagged v1.10.0.
