### ISSUE TITLE
Revert PR #671

### ISSUE THREAD

**Issue by rittneje** [mattn/go-sqlite3#672]
PR #671 was merged to fix issue #667. However, as I stated on that issue, there was no bug. Please revert this unnecessary change.

As per the documentation of [`sql.Open`](https://golang.org/pkg/database/sql/#Open):
> Open may just validate its arguments without creating a connection to the database. To verify that the data source name is valid, call Ping.

Consequently, there would be no error returned from `sql.Open` in this case.

As per the [SQLite documentation](https://www.sqlite.org/c3ref/open.html):
> mode: The mode parameter may be set to either "ro", "rw", "rwc", or "memory". Attempting to set it to any other value is an error. If "ro" is specified, then the database is opened for read-only access, just as if the SQLITE_OPEN_READONLY flag had been set in the third argument to sqlite3_open_v2(). If the mode option is set to "rw", then the database is opened for read-write (but not create) access, as if SQLITE_OPEN_READWRITE (but not SQLITE_OPEN_CREATE) had been set. Value "rwc" is equivalent to setting both SQLITE_OPEN_READWRITE and SQLITE_OPEN_CREATE. If the mode option is set to "memory" then a pure in-memory database that never reads or writes from disk is used. It is an error to specify a value for the mode parameter that is less restrictive than that specified by the flags passed in the third parameter to sqlite3_open_v2().

Therefore, SQLite will already do what you want it to do. No change is necessary. Testing (without the recent change) confirms that:
1. While `sql.Open` does not itself return an error, no database actually gets created, contrary to the original bug report.
2. `db.Ping()` does return an error as expected.

Testing with the recent change does not have any impact on this behavior. `sql.Open` still does not return an error, as it is not supposed to.

**Comment by mattn** [comment]
Could you please send me PR?

**Comment by rittneje** [comment]
Fixed by #673.
