### ISSUE TITLE
In-memory: no such table

### ISSUE THREAD

**Issue by pupizoid** [mattn/go-sqlite3#677]
Hi! I've faced strange behavior, working with in-memory sqlite3 database with go-sqlite3. I initialize a connection, create database and insert some data into it in the single `Exec`. 

After that I perform a select query to set to zero last inserted rowid (thats important to me). And then when i'm trying to perform an insert query I get the "no such table" error.

This behavior is reproduced only when I create an in-memory database from go, if I create database file everything runs as expected. Moreover when I exec same queries on a in-memory database using sqlite3 cmd binary everything works fine too.

Here is a simple code that panics, but should not...
```go
package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		panic(err)
	}

	db.Exec(`
		create table test(field text);
		insert into test(field) values ('test 1'), ('test 2'), ('test 3');
	`)

	_, err = db.Query("select count(*) from test;")
	if err != nil {
		panic(err)
	}

	_, err = db.Exec("insert into test(field) values ('test 4')")
	if err != nil {
		panic(err)  // panics here!
	}
}
```
I'm using go-sqlite3 1.10.0 with go1.11.2 darwin/amd64

**Comment by rittneje** [comment]
Try `sql.Open("sqlite3", "file::memory:?cache=shared")`. See "Why I'm getting no such table error?" in the [FAQ](https://github.com/mattn/go-sqlite3/blob/master/README.md#faq).

**Comment by pupizoid** [comment]
Thank you for the answer, that helped!
