### ISSUE TITLE
Add low-level system error code to Error struct

### ISSUE THREAD

**Issue by boramalper** [mattn/go-sqlite3#678]
Based my discussion with @rittneje in #618, we've realised that it would be really useful to add low-level system error code to [Error struct](https://godoc.org/github.com/mattn/go-sqlite3#Error).

> ## Low-level system error code
>
>     int sqlite3_system_errno(sqlite3*);
>
> Attempt to return the underlying operating system error code or error number that caused the most recent I/O error or failure to open a file. The return value is OS-dependent. For example, on unix systems, after `sqlite3_open_v2()` returns `SQLITE_CANTOPEN`, this interface could be called to get back the underlying "errno" that caused the problem, such as `ENOSPC`, `EAUTH`, `EISDIR`, and so forth.
>
> https://www.sqlite.org/c3ref/system_errno.html

If the maintainers are fine with it, I can give it a try as well. =)

**Comment by rittneje** [comment]
Note that the system errno is only meaningful if the primary error code is `SQLITE_CANTOPEN` or `SQLITE_IOERR`, and the extended error code is _not_ `SQLITE_IOERR_NOMEM`.

```c
SQLITE_PRIVATE void sqlite3SystemError(sqlite3 *db, int rc){
  if( rc==SQLITE_IOERR_NOMEM ) return;
  rc &= 0xff;
  if( rc==SQLITE_CANTOPEN || rc==SQLITE_IOERR ){
    db->iSysErrno = sqlite3OsGetLastError(db->pVfs);
  }
}
```

Also, `syscall.Errno` would be a good choice for the type of this new struct field, as it has an `Error` method to output a human-readable message. https://golang.org/pkg/syscall/#Errno.Error

The change would probably be something like this:
```go
func lastError(db *C.sqlite3) error {
    rv := C.sqlite3_errcode(db)
    extrv := C.sqlite3_extended_errcode(db)

    var systemErrno syscall.Errno
    if rv == C.SQLITE_CANTOPEN || (rv == C.SQLITE_IOERR && extrv != C.SQLITE_IOERR_NOMEM) {
        systemErrno = C.sqlite3_system_errno(db)
    }

    ...
}

...

func errorString(err Error) string {
    str := C.GoString(C.sqlite3_errstr(C.int(err.Code)))
    if err.SystemErrno != 0 {
        str += ": " + err.SystemErrno.Error()
    }
    return str
}
```

**Comment by GJRTimmer** [comment]
@rittneje @boramalper can you provide a PR and some tests ?
