### ISSUE TITLE
how to get column name and database name?? 

### ISSUE THREAD

**Issue by hackertron** [mattn/go-sqlite3#687]
Hi , i can't seem to figure out how to get database and column name from a table . I did saw the doc but can't get an example for it.

db.Query() // what should go here ?

**Comment by rittneje** [comment]
To get column names, call the [`Columns`](https://golang.org/pkg/database/sql/#Rows.Columns) method on the `sql.Rows` object returned by `db.Query`. What do you mean by "database name"?

**Comment by hackertron** [comment]
database name like by default the sqlite database has main as database name . 

```
sqlite> .database
seq  name             file                                                      
---  ---------------  ----------------------------------------------------------
0    main             /home/nightmare/practice/go/foo.db                        

```

**Comment by rittneje** [comment]
If I understand what you are trying to do correctly, it sounds like you are looking for these:
- fetch the schema for a table: https://www.sqlite.org/pragma.html#pragma_table_info
- fetch the list of all databases: https://www.sqlite.org/pragma.html#pragma_database_list
