### ISSUE TITLE
named parameters not handled correctly

### ISSUE THREAD

**Issue by rittneje** [mattn/go-sqlite3#697]
As per [the documentation](https://www.sqlite.org/c3ref/bind_blob.html), SQLite allows three types of parameter names: `@foo`, `:foo`, and `$foo`. However, this library only considers the `:foo` form, which causes the following perfectly valid query to fail:
```go
db.Exec("INSERT INTO Foo VALUES (@fooid)", sql.Named("fooid", 5))
```

Furthermore, this library does not properly handle the user providing a parameter with an unrecognized name, as can be seen [here](https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L1777). If the parameter name is unrecognized, `sqlite3_bind_parameter_index` returns 0. But this return value is blindly passed to the various `sqlite3_bind_X` routines. These routines are expecting an index of at least 1, so such a call is plainly invalid. Parameters with unrecognized names should be ignored.
```go
db.Exec("INSERT INTO Foo VALUES (:fooid)", sql.Named("fooid", 5). sql.Named("barid", 10))
```
This tries to bind 10 at index 0 (since `barid` isn't a valid parameter). Instead, the `barid` parameter should be ignored.

**Comment by emersion** [comment]
It seems this has been fixed in #811. Maybe we can close this issue?
