### ISSUE TITLE
Update to sqlite 3.27

### ISSUE THREAD

**Issue by dkumor** [mattn/go-sqlite3#698]
There was recently a new version of sqlite released (3.27), which has support for `VACUUM INTO`, which would be useful for one of my projects. Would it be possible to upgrade the embedded amalgamation to the most recent version?

Reference: https://www.sqlite.org/releaselog/3_27_2.html

**Comment by mattn** [comment]
Closed by https://github.com/mattn/go-sqlite3/pull/702
