### ISSUE TITLE
Dynamic link SQLite .dll and .so file?

### ISSUE THREAD

**Issue by Niondir** [mattn/go-sqlite3#700]
Can I somehow deliver my go program with SQLite as a DLL or .so file (depending on the OS). I have some trouble cross compiling from my windows machine for Linux and ARM.

**Comment by rittneje** [comment]
Unfortunately, it's not that simple. While you can dynamically link against SQLite by providing the `libsqlite3` build tag, you would still a proper C cross-compiler, and you'd need the right .so file to link against at compile time. I'd recommend compiling inside a Linux VM or docker container. [This article](https://www.acmesystems.it/arm9_toolchain) should help you install the cross-compiler you'll need inside that Linux image. When cross-compiling, be sure to set `CGO_ENABLED`, `CC`, `GOOS`, `GOARCH`, and `GOARM` appropriately.

**Comment by GJRTimmer** [comment]
Little tip, when you are working from a Windows based host.
Run Windows 10 and just install `WSL`. Gives you a Linux environment on your Windows machine. Quite neat and very handy while crosscompiling.
