### ISSUE TITLE
How to precompile package and build app without gcc

### ISSUE THREAD

**Issue by xjtdy888** [mattn/go-sqlite3#703]
Is it possible to pre-compile cross-platform go-sqlite3.a in advance to avoid gcc when building applications.
I installed linux and windows go-sqlite3.a using a cross compiler.

```
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc-posix CXX=x86_64-w64-mingw32-g++-posix HOST=x86_64-w64-mingw32 PREFIX=/usr/x86_64-w64-mingw32 GOOS=windows  /go1.12/bin/go install github.com/mattn/go-sqlite3
```

```
CGO_ENABLED=1  GOOS=linux  /go1.12/bin/go install github.com/mattn/go-sqlite3
```
Now I have compiled go-sqlite3.a
```
root@f4d4056fc15d:/go/src/github.com/mattn/go-sqlite3# find /go/pkg/|grep go-sqlite3.a
/go/pkg/windows_amd64/github.com/mattn/go-sqlite3.a
/go/pkg/linux_amd64/github.com/mattn/go-sqlite3.a
root@f4d4056fc15d:/go/src/github.com/mattn/go-sqlite3# 
```
I started trying to compile _example/simple,
On Linux if  CGO_ENABLED=0 is do not work;

```
root@f4d4056fc15d:/go/src/github.com/mattn/go-sqlite3/_example/simple# CGO_ENABLED=0 go build
root@f4d4056fc15d:/go/src/github.com/mattn/go-sqlite3/_example/simple# ./simple
2019/03/20 03:54:27 "Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub": 
	create table foo (id integer not null primary key, name text);
	delete from foo;
```
Compile of Windows, Build is be fine
```
GOOS=windows GOARCH=amd64 go build
```
But running the prompt requires CGO_ENABLED
```
C:\Users\workspace\Desktop>simple.exe
2019/03/21 12:03:44 "Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub":
        create table foo (id integer not null primary key, name text);
        delete from foo;
```

Where am I wrong?

**Comment by rittneje** [comment]
It doesn't work because of how Go's build cache works. Because the value of `CGO_ENABLED` changed, it doesn't consider the output of the first build to be usable when you build the second time.

Can you explain why you are trying to avoid gcc? What exactly are you trying to accomplish?

**Comment by xjtdy888** [comment]
Thanks Reply！
Because CGO compilation brings complex compilation environment problems, if can use pre-compiled library files, build applications more easily and quickly.

**Comment by rittneje** [comment]
Can you elaborate on what problems you are facing? What platform(s) do you develop on? What platform(s) do you actually deploy/release on?

It's hard to say without knowing your full situation, but my initial inclination is to suggest using docker to containerize your build environment.

**Comment by xjtdy888** [comment]
The compilation environment that cgo depends on is very difficult. 
I am thinking about compiling the sqlite.a files of each platform on a complete machine and distributing them to other machines. Then other build machines do not need too complicated environment. Compile multiple platform targets directly, but it seems that this is not a reality

**Comment by mattn** [comment]
If you have libsqlite3.a on the target system, you can use `libsqlite3` build tag. See README.md.

**Comment by rittneje** [comment]
Using a pre-built libsqlite3 will not really help in this situation. You still need to use cgo when compiling your Go application. All it means is you don't need the SQLite source code, but that's already included in this library anyway.

> The compilation environment that cgo depends on is very difficult.

I'm not sure what you mean by this. What platforms do you intend to compile for? If developers only need to make native builds (i.e., compile for their own machines), this is pretty straightforward. If you truly need to support cross-compilation, like I said I'd highly recommend just using docker.

**Comment by GJRTimmer** [comment]
Closable ?
