### ISSUE TITLE
How to change SQLITE_MAX_VARIABLE_NUMBER?

### ISSUE THREAD

**Issue by MuzTank** [mattn/go-sqlite3#704]
I tried to change the default SQLITE_MAX_VARIABLE_NUMBER from 999 to 500000.
I already edited sqlite3-binding.c
![image](https://user-images.githubusercontent.com/8184152/55069304-501f2880-50b6-11e9-8d5e-05e972efbf98.png)

And then I remove $GOPATH\pkg\windows_amd64\github.com\mattn\go-sqlite3.a
Then I do 'go install github.com/mattn/go-sqlite3' again.

The new go-sqlite3.a shows up but I try to execute the query again, still showed error 'too many SQL variables'.

Environment:
go version go1.11.4 windows/amd64
Windows 10 64-Bit
GCC installed on C:\TDM-GCC-64\bin\gcc.exe
C:\TDM-GCC-64\bin\ already in PATH

Thanks

**Comment by rittneje** [comment]
This is likely due to Go's build cache, introduced in 1.10.

>The go command periodically deletes cached data that has not been
used recently. Running 'go clean -cache' deletes all cached data
>
>The build cache correctly accounts for changes to Go source files,
compilers, compiler options, and so on: cleaning the cache explicitly
should not be necessary in typical use. However, the build cache
does not detect changes to C libraries imported with cgo.
If you have made changes to the C libraries on your system, you
will need to clean the cache explicitly or else use the -a build flag
(see 'go help build') to force rebuilding of packages that
depend on the updated C libraries.

**Comment by MuzTank** [comment]
> This is likely due to Go's build cache, introduced in 1.10.
> 
> > The go command periodically deletes cached data that has not been
> > used recently. Running 'go clean -cache' deletes all cached data
> > The build cache correctly accounts for changes to Go source files,
> > compilers, compiler options, and so on: cleaning the cache explicitly
> > should not be necessary in typical use. However, the build cache
> > does not detect changes to C libraries imported with cgo.
> > If you have made changes to the C libraries on your system, you
> > will need to clean the cache explicitly or else use the -a build flag
> > (see 'go help build') to force rebuilding of packages that
> > depend on the updated C libraries.

I've done these steps:
- `go build -a -o go-sqlite3.a -i github.com/mattn/go-sqlite3`
- move go-sqlite3.a to $GOPATH\pkg\github.com\mattn\go-sqlite3
- `go clean -cache`
- run my program and still cannot exceed 999 variables...

Any wrong steps? Or maybe lack of steps?

**Comment by rittneje** [comment]
Don't be messing around with the pkg folder like that. (The command you wrote doesn't really make sense anyway.) Please delete your pkg folder to undo whatever you did. Then try the following.

1. `go clean -cache`
2. _compile_ your program
3. run your program

If you are still having issues, please post the actual commands you are running to compile and run your program.

**Comment by MuzTank** [comment]
My work folder is $GOPATH\src\bulkinsert

My sqlite3-binding.c
![image](https://user-images.githubusercontent.com/8184152/55129827-324fd300-514b-11e9-9283-6e08b9d86030.png)

First attempt:
1. `cd %GOPATH%\src\bulkinsert`
2. `go clean -cache`
3. `go build -a -o bulkinsert.exe -i bulkinsert`
4. `bulkinsert.exe`
5. Still failed
![image](https://user-images.githubusercontent.com/8184152/55129919-78a53200-514b-11e9-92ab-958d288165c3.png)

Second attempt:
1. `cd %GOPATH%\src\bulkinsert`
2. `go clean -cache`
3. `go build .`
4. `bulkinsert.exe`
5. Still failed
![image](https://user-images.githubusercontent.com/8184152/55129879-61664480-514b-11e9-9f02-314fa22ea763.png)

**Comment by rittneje** [comment]
It is working properly for me, so I'm not sure what the issue is. Can you describe the actual query with these 400k parameters? How was this query constructed?

Also, a very simple test case to try.
```go
package main

import (
    "database/sql"
    _ "github.com/mattn/go-sqlite3"
)

func main() {
    db, _ := sql.Open("sqlite3", ":memory:")
    defer db.Close()

    db.SetMaxOpenConns(1)

    if _, err := db.Exec("CREATE TABLE Foo(FooID INTEGER NOT NULL)"); err != nil { panic(err) }

    s, err := db.Prepare(`INSERT INTO Foo(FooID) VALUES (?999),(?)`)
    if err != nil { panic(err) }
    s.Close()
}
```

If that doesn't give you an error about "too many variables", then we know the problem is that your limit is too low, and not that your limit isn't being used.

**Comment by MuzTank** [comment]
> It is working properly for me, so I'm not sure what the issue is. Can you describe the actual query with these 400k parameters? How was this query constructed?
> 
> Also, a very simple test case to try.
> 
> ```go
> package main
> 
> import (
>     "database/sql"
>     _ "github.com/mattn/go-sqlite3"
> )
> 
> func main() {
>     db, _ := sql.Open("sqlite3", ":memory:")
>     defer db.Close()
> 
>     db.SetMaxOpenConns(1)
> 
>     if _, err := db.Exec("CREATE TABLE Foo(FooID INTEGER NOT NULL)"); err != nil { panic(err) }
> 
>     s, err := db.Prepare(`INSERT INTO Foo(FooID) VALUES (?999),(?)`)
>     if err != nil { panic(err) }
>     s.Close()
> }
> ```
> 
> If that doesn't give you an error about "too many variables", then we know the problem is that your limit is too low, and not that your limit isn't being used.

I join the '?' and its values into different string slices then execute it like below codes

`func helper_inserttodb(rows []interface{}) error {
  /**
    rows = [[M 014207080 2001420708017 0 林氏木業北歐多功能三人布沙發床+腳凳(附4顆抱枕)1012-米白色   20980 11999 1B03 0000104515 197-112-45.5CM 75KG 2018-11-07 2018-11-12   0 N http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=1B09014207080] [M 014207082 2001420708215 0 Pohon Goreng   20980 11999 1B03 0000104515 197-112-45.5CM 75KG 2018-11-07 2018-11-12   0 N http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=XXX] [M 014207093 2001420709311 0 林氏木業北歐 現代百變多功能儲物L型布沙發(附抱枕)995-淺灰色   36800 19920 1B03 0000104515 191-113-102.5CM 134KG 2018-11-07 2018-11-12   0 N http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=1B09014207093] ... 400000x]
    reflect.TypeOf(rows) = []interface{}
   */
	db, err := sql.Open("sqlite3", "./testdb.db")
	if err != nil {
		return err
	}
	defer db.Close()
	log.Println("Start inserting...")
	valueStrings := make([]string, 0, len(rows))
	valueArgs := make([]string, 0, len(rows)*10)
	for _, row := range rows {
		value, _ := row.([]interface{})
		rowCustom := ""
		for x := 9; x < len(value); x++ {
			if value[x] == "" {
				rowCustom += "-"
			} else {
				rowCustom += value[x].(string)
			}
			rowCustom += "|||"
		}
		rowCustom = strings.TrimRight(rowCustom, "|||")
		valueStrings = append(valueStrings, "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
		valueArgs = append(valueArgs, value[0].(string))
		valueArgs = append(valueArgs, value[1].(string))
		valueArgs = append(valueArgs, value[2].(string))
		valueArgs = append(valueArgs, value[3].(string))
		valueArgs = append(valueArgs, value[4].(string))
		valueArgs = append(valueArgs, value[5].(string))
		valueArgs = append(valueArgs, value[6].(string))
		valueArgs = append(valueArgs, value[7].(string))
		valueArgs = append(valueArgs, value[8].(string))
		valueArgs = append(valueArgs, rowCustom)
	}
  /**
    valueStrings = [(?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ... ]
    reflect.TypeOf(valueStrings) = []string
    
    valueArgs = [M 014207080 2001420708017 0 林氏木業北歐多功能三人布沙發床+腳凳(附4顆抱枕)1012-米白色   20980 11999 1B03|||0000104515|||197-112-45.5CM|||75KG|||2018-11-07|||2018-11-12|||-|||-|||0|||N|||http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=1B09014207080 M 014207082 2001420708215 0 Pohon Goreng   20980 11999 1B03|||0000104515|||197-112-45.5CM|||75KG|||2018-11-07|||2018-11-12|||-|||-|||0|||N|||http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=XXX M 014207093 2001420709311 0 林氏木業北歐現代百變多功能儲物L型布沙發(附抱枕)995-淺灰色   36800 19920 1B03|||0000104515|||191-113-102.5CM|||134KG|||2018-11-07|||2018-11-12|||-|||-|||0|||N|||http://www.trplus.com.tw/webredirect?Rtype=QRCode&RPage=1B09014207093 ... ] - M is the first entry for each line
    reflect.TypeOf(valueArgs) = []string
  */
  statement := fmt.Sprintf("INSERT INTO inventories(action, no, bc, layout_idx, name, area, unit, price, promo_price, custom_fields) VALUES %s", strings.Join(valueStrings, ","))
  _, err = db.Exec(statement, valueArgs...)
  if err != nil {
    return err
  }

	log.Println("Finish inserting...")
	return nil
}`

**Comment by rittneje** [comment]
If I'm understanding your code snippet correctly, you are inserting 400k entries, but each entry has 10 values, for a grand total of 4 million parameters. Is that correct? If so, your 500k limit is still too small.

(By the way, you may want to consider opening a transaction and doing all these inserts in a loop. Then you won't even need to increase the limit or do stuff with `Sprintf`.)

**Comment by MuzTank** [comment]
oh damn, that's correct...

**Comment by MuzTank** [comment]
> If I'm understanding your code snippet correctly, you are inserting 400k entries, but each entry has 10 values, for a grand total of 4 million parameters. Is that correct? If so, your 500k limit is still too small.
> 
> (By the way, you may want to consider opening a transaction and doing all these inserts in a loop. Then you won't even need to increase the limit or do stuff with `Sprintf`.)

I tried inserting in a loop but it takes long long long time... 21 minutes, I tried a way to insert it in the fastest possible way

**Comment by rittneje** [comment]
Not sure whether this is what you already tried, but I would normally do something like this:

```go
tx, err := db.Begin()
if err != nil {
    return err
}
defer tx.Rollback()

stmt, err := tx.Prepare("INSERT INTO inventories(action, no, bc, layout_idx, name, area, unit, price, promo_price, custom_fields) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
if err != nil {
    return err
}
defer stmt.Close()

for _, row := range rows {
    if _, err := stmt.Exec(row.([]interface{})...); err != nil {
        return err
    }
}

return tx.Commit()
```

**Comment by MuzTank** [comment]
Thx @rittneje it works now
