### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DenWebDeveloper** [mattn/go-sqlite3#707]
`$ go get -u github.com/mattn/go-sqlite3
# runtime/cgo
gcc_libinit_windows.c:  function «x_cgo_sys_thread_create»:
gcc_libinit_windows.c:57:12: error: implicit declaration of function «_beginthread»; did you mean «OpenThread»? [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
            OpenThread
cc1:all warnings are treated as errors`

`$ gcc --version
gcc (GCC) 7.4.0
`

**Comment by rittneje** [comment]
Your C compiler may not be supported by Go. https://github.com/golang/go/issues/12029
