### ISSUE TITLE
Update to SQLite 3.28

### ISSUE THREAD

**Issue by thiekus** [mattn/go-sqlite3#711]
Hi, there are recently a new version of SQLite 3.28 is out there. Personally this update is interesting since has support ```VACUUM INTO``` for read only databases. Would you like to update amalgamation sqlite code to this version?

Changelog: https://www.sqlite.org/releaselog/3_28_0.html

**Comment by mattn** [comment]
Closed by https://github.com/mattn/go-sqlite3/pull/712
