### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by wakwanza** [mattn/go-sqlite3#714]
Building from master or from release 1.9.0 on windows fails with the error attached

**go**
go version go1.12.5 windows/amd64

**gcc**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/7.4.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 7.4.0 (GCC)

**System**
OsName                                     : Microsoft Windows Server 2016 Standard
OsType                                       : WINNT
OsOperatingSystemSKU          : StandardServerEdition
OsVersion                                  : 10.0.14393

[builerr.txt](https://github.com/mattn/go-sqlite3/files/3161212/builerr.txt)

**Comment by mattn** [comment]
You are using msys compiler NOT mingw compiler.
