### ISSUE TITLE
build for mipsle failed

### ISSUE THREAD

**Issue by hongjinlin** [mattn/go-sqlite3#715]
CC=mips-linux-musl-gcc CXX=mips-linux-musl-g++ CGO_ENABLED=1 GOOS=linux GOARCH=mipsle GOMIPS=softfloat  go build -ldflags="-s -w" main.go

How can i build for little endian?Thank you!
If i change "GOARCH=mipsle" To "GOARCH=mips" is ok, but my target is little endian~

_Originally posted by @hongjinlin in https://github.com/mattn/go-sqlite3/issues/384#issuecomment-490831876_

# command-line-arguments
/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64/link: running mips-linux-musl-gcc failed: exit status 1
/usr/local/Cellar/musl-cross/0.9.7_1/libexec/bin/../lib/gcc/mips-linux-musl/6.3.0/../../../../mips-linux-musl/bin/ld: /var/folders/1q/3d6q6x2s6057s6fgwdxr7ffw0000gn/T/go-link-651072203/go.o: compiled for a little endian system and target is big endian
/usr/local/Cellar/musl-cross/0.9.7_1/libexec/bin/../lib/gcc/mips-linux-musl/6.3.0/../../../../mips-linux-musl/bin/ld: /var/folders/1q/3d6q6x2s6057s6fgwdxr7ffw0000gn/T/go-link-651072203/go.o: endianness incompatible with that of the selected emulation
/usr/local/Cellar/musl-cross/0.9.7_1/libexec/bin/../lib/gcc/mips-linux-musl/6.3.0/../../../../mips-linux-musl/bin/ld: failed to merge target specific data of file /var/folders/1q/3d6q6x2s6057s6fgwdxr7ffw0000gn/T/go-link-651072203/go.o
collect2: error: ld returned 1 exit status

**Comment by hongjinlin** [comment]
MacOS Majove 0.14.4 (18E226)

go version go1.11.2 darwin/amd64

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hongjinlin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hongjinlin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1q/3d6q6x2s6057s6fgwdxr7ffw0000gn/T/go-build079041265=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by rittneje** [comment]
I'm not very familiar with mips, but are you sure you are using the right C compiler? From what I can find it sounds like you are supposed to be using mipsel-linux-musl-gcc instead.

**Comment by hongjinlin** [comment]
> I'm not very familiar with mips, but are you sure you are using the right C compiler? From what I can find it sounds like you are supposed to be using mipsel-linux-musl-gcc instead.

https://github.com/mattn/go-sqlite3/issues/384#issuecomment-433584967
I use this tool , i also can not found, it is my also my question 
brew install FiloSottile/musl-cross/musl-cross --with-mipsel

**Comment by rittneje** [comment]
@hongjinlin Please do `CC=mipsel-linux-musl-gcc` instead. (You don't actually have to set `CXX` so that part can be removed.)

**Comment by hongjinlin** [comment]
@rittneje I have tried "https://github.com/richfelker/musl-cross-make" this tool before,but build failed on my mac ,i have used ql database instead.Thank you very much!
