### ISSUE TITLE
Can't compile on Win10

### ISSUE THREAD

**Issue by xiekong** [mattn/go-sqlite3#717]
![image](https://user-images.githubusercontent.com/16237228/57675656-24033b00-7655-11e9-931b-8cc998a8fc3a.png)
build error：
![image](https://user-images.githubusercontent.com/16237228/57675690-3aa99200-7655-11e9-8aaa-a0f01a3b4a86.png)

**Comment by rittneje** [comment]
Your screenshot is cut off. Can you please paste the build error as text?

**Comment by xiekong** [comment]
> Your screenshot is cut off. Can you please paste the build error as text?

GOROOT=C:\Go #gosetup
GOPATH=E:\gowork\NovelReader;E:\go #gosetup
C:\Go\bin\go.exe build "-ldflags=-H windowsgui" -o E:\gowork\NovelReader\bin\NovelReader.exe -gcflags "all=-N -l" com/xiekong/novelreader/main #gosetup
# com/xiekong/novelreader/main
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\xiaomi\AppData\Local\Temp\go-link-242730499\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

**Comment by xiekong** [comment]
`GOROOT=C:\Go #gosetup
GOPATH=E:\gowork\NovelReader;E:\go #gosetup
C:\Go\bin\go.exe build "-ldflags=-H windowsgui" -o E:\gowork\NovelReader\bin\NovelReader.exe -gcflags "all=-N -l" com/xiekong/novelreader/main #gosetup
# com/xiekong/novelreader/main
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\xiaomi\AppData\Local\Temp\go-link-242730499\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status`

**Comment by xiekong** [comment]
@rittneje `GOROOT=C:\Go #gosetup
GOPATH=E:\gowork\NovelReader;E:\go #gosetup
C:\Go\bin\go.exe build "-ldflags=-H windowsgui" -o E:\gowork\NovelReader\bin\NovelReader.exe -gcflags "all=-N -l" com/xiekong/novelreader/main #gosetup
# com/xiekong/novelreader/main
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\xiaomi\AppData\Local\Temp\go-link-242730499\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status`

**Comment by rittneje** [comment]
Can you try adding `-a` to the `go build` command? (i.e., `C:\Go\bin\go.exe build -a ...`)

**Comment by xiekong** [comment]
> Can you try adding `-a` to the `go build` command? (i.e., `C:\Go\bin\go.exe build -a ...`)
Still failing



GOROOT=C:\Go #gosetup
GOPATH=E:\gowork\NovelReader;E:\go #gosetup
C:\Go\bin\go.exe build -a "-ldflags=-H windowsgui" -o E:\gowork\NovelReader\bin\NovelReader.exe -gcflags "all=-N -l" com/xiekong/novelreader/main #gosetup
# com/xiekong/novelreader/main
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\xiaomi\AppData\Local\Temp\go-link-942329495\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

**Comment by rittneje** [comment]
To confirm, your Windows machine is 64-bit, correct? Also, what do you get if you type `where gcc` in the console?

**Comment by xiekong** [comment]
@rittneje My Windows machine is 64-bit
![image](https://user-images.githubusercontent.com/16237228/60227730-f4d22180-98c2-11e9-94ea-f9f2c4dca114.png)
gcc in the console

![image](https://user-images.githubusercontent.com/16237228/60227764-0b787880-98c3-11e9-92e1-8827e42ac34b.png)

**Comment by rittneje** [comment]
@xiekong Nothing immediately jumps out to me as suspicious, and I am unable to reproduce this issue on my machine. At this point I would suggest filing an issue against Go to see if one of the Go authors can assist you. https://github.com/golang/go/issues

**Comment by xiekong** [comment]
@rittneje Thank you

**Comment by mattn** [comment]
Closable?
