### ISSUE TITLE
version 1.10.0 is not having latest source code

### ISSUE THREAD

**Issue by kedar100** [mattn/go-sqlite3#719]
https://github.com/mattn/go-sqlite3/releases/tag/v1.10.0 links to source code zip file for 1.10.0.
But when I download file it still shows all code from version1.9.0

e.g. file **github.com\mattn\go-sqlite3\sqlite3-binding.h** from 1.9.0 has below lines
**#define SQLITE_VERSION        "3.25.2"**
#define SQLITE_VERSION_NUMBER 3025002
#define SQLITE_SOURCE_ID      "2018-09-25 19:08:10 fb90e7189ae6d62e77ba3a308ca5d683f90bbe633cf681865365b8e92792d1c7"

When I download same file from source code zip for version 1.10.0 there is surprisingly no change in this file. OR rather any source file.

Now, if I get version 1.10.0 source using "go get" command the same file is shown as:
**#define SQLITE_VERSION        "3.28.0"**
#define SQLITE_VERSION_NUMBER 3028000
#define SQLITE_SOURCE_ID      "2019-04-16 19:49:53 884b4b7e502b4e991677b53971277adfaf0a04a284f8e483e2553d0f83156b50"

**Comment by mattn** [comment]
please try `go get -u`

**Comment by kedar100** [comment]
hi,

go get -u does get the laetest source.
Problem is with deps -update OR deps -init
both these commands fetch version as 1.10 but do bring source code of 1.09.
again what I feel is the zip file associated on  mattn site i.e. (https://github.com/mattn/go-sqlite3/archive/v1.10.0.zip)
contains source code of 1.09.

regards,
Kedar

**Comment by GJRTimmer** [comment]
Not update since May, latest is 1.11.0; Issue Closed
