### ISSUE TITLE
The data is not synchronized in real time between file and memory

### ISSUE THREAD

**Issue by penhauer-xiao** [mattn/go-sqlite3#720]
After the service is started, a data is inserted into the db file of sqllite3 through navicat, the service does not select the data (the service is to select every 3 seconds); restart the service, open the sqllite db file, we can select the one data at this time.

the data is not synchronized in real time between file and memory?   Or does  go-sqlite3  not read data from files in sqllite3 db in real time?

**Comment by rittneje** [comment]
Please provide more detail on your exact issue. What queries are being executing from navicat? What queries are being executed from your Go application? Is your Go application using any transactions? How are you opening the database file? Please provide the actual `sql.Open` line.

**Comment by penhauer-xiao** [comment]
The first step is to use navicat to open the existing sqllite3 file and create a table.
`
CREATE TABLE IF NOT EXISTS topic(
  id            TINYINT PRIMARY KEY NOT NULL,
  name          NVARCHAR(30) NOT NULL,
  update_time   DATETIME DEFAULT (datetime(CURRENT_TIMESTAMP, 'localtime'))
);
`
The second step is to open my service, the code is as follows:
`
package main

import (
        "database/sql"
	"time"

	_ "github.com/mattn/go-sqlite3"
	"github.com/sirupsen/logrus"
)
func main() {
	db, err := sql.Open("sqlite3", "trans.db")
	if err != nil {
		logrus.Errorln(err)
		return
	}
	defer db.Close()

	go func() {
  		rows, err := db.Query("select id,name from topic")
		if err != nil {
			logrus.Errorln(err)
			return
		}
		defer rows.Close()

 		for rows.Next() {
 			var id int
                        var name string
			if err := rows.Scan(&id,&name); err != nil {
				logrus.Errorln(err)
 				return
			}
                        logrus.Debugln("select ok", id, name )  // the data from navicat insertion; not obtained by query
		}
		time.Sleep(time.Second * 5)
	}()
}
`
The third step is to insert the data in navicat and return to success.
`
insert into topic(id,name) VALUES(1,"myclass")
`
but the data from navicat insertion; not obtained by query.

If I terminate my service and then start execution, I get my insert data.

**Comment by rittneje** [comment]
Which version of Go are you using (as reported by running `go version`)? Also, please try calling `rows.Close` at the bottom of the loop before calling `time.Sleep` and see if that changes anything.

**Comment by penhauer-xiao** [comment]
@rittneje   According to your thinking, the problem still exists.
`
$ go version
go version go1.12.4 linux/amd64
`

![image](https://user-images.githubusercontent.com/6280121/58365253-fd19f400-7ef3-11e9-95d2-7d5dbfe2be66.png)

**Comment by rittneje** [comment]
> According to your thinking, the problem still exists.

Sorry, I'm not sure what you meant by this. Did you mean that you tried adding `rows.Close` like I mentioned and it still doesn't work?

To clarify, you are able to reproduce the issue with _just_ the `main` function you pasted above, correct? No additional code is needed in the Go binary?

As a test, please try opening the same database via the SQLite CLI. Then update it via navicat, and then run your `SELECT` query at the command line and see if you get the right output.

```
$ sqlite3 trans.db
sqlite> select id, name from topic;
```

**Comment by penhauer-xiao** [comment]
> > According to your thinking, the problem still exists.
> 
> Sorry, I'm not sure what you meant by this. Did you mean that you tried adding `rows.Close` like I mentioned and it still doesn't work?
> >Yes, it still doesn't work

> To clarify, you are able to reproduce the issue with _just_ the `main` function you pasted above, correct? No additional code is needed in the Go binary?
> > Yes,  I adding `rows.Close` like you mentioned and it still doesn't work

> As a test, please try opening the same database via the SQLite CLI. Then update it via navicat, and then run your `SELECT` query at the command line and see if you get the right output.
> > I tested, sqlite3 cli and the service I wrote are the same problem.

**Comment by penhauer-xiao** [comment]
@rittneje  Maybe the problem with navicat

**Comment by rittneje** [comment]
Yeah, if you are observing the same issue with the CLI, it's possible that navicat is somehow causing it. Not really sure how though. Perhaps someone for the SQLite community will be able to shed some light on the matter. https://www.sqlite.org/support.html
