### ISSUE TITLE
Report warning os MacOS 10.14.5

### ISSUE THREAD

**Issue by violin0622** [mattn/go-sqlite3#721]
my code is:
```golang
package main

import(
    _ "github.com/mattn/go-sqlite3"
)

func main(){
    println("hel")
}
```
when running `go build` ,result is:
> \# violin/sq
> ld: warning: building for macOS, but linking in object file (/var/folders/9k/g9fr68yx00dfx_9790kccrb80000gn/T/go-link-904695182/go.o) built for

although it still can build an executable, and seems work well, but the warning message make people uncomfortable. how to deal with it? 
here's my env:
> GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/violin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/violin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/violin/Projects/go/src/violin/sq/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9k/g9fr68yx00dfx_9790kccrb80000gn/T/go-build560338982=/tmp/go-build -gno-record-gcc-switches -fno-common"
> 

> clang -v
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
>

> ld -v
@(#)PROGRAM:ld  PROJECT:ld64-510.3
BUILD 10:27:00 May 27 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 11.0.0, (clang-1100.0.20.17) (static support for 23, runtime is 23)
TAPI support using: Apple TAPI version 11.0.0 (tapi-1100.0.10.2)
>

**Comment by mattn** [comment]
This is silmilar issue to https://github.com/golang/go/issues/26064

**Comment by rittneje** [comment]
This does seem like an issue with the Go compiler, as opposed to this library. In any case, try `go build -a` just to be safe.

**Comment by fabstu** [comment]
Same here. Best guess it's about go itself.

```
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
[1]    93094 abort      my-app
```

**Comment by violin0622** [comment]
Yes, it is similar, but not same ,I think. 
First, I'm not using gomobile, but only built for macOS on macOS instead.
Secondly, there's nothing after 'linking in object file(...) build for' message. So I even can't confirm which platform's obj file  it is  linking for  😢. 

Plus, there's no warnning with macOS version 10.14, but when I upgrade OS, the warning appears. 

I tried `go build -a` but same warning still appears.
@rittneje I'm sorry but is there any way that I can confirm the issue witch Go compiler or this library? If it's an issue witch Go, I'll turn to go project for help, thanks.

**Comment by mholt** [comment]
I'm also experiencing this warning. Let me know how I can help debug this. :)

**Comment by rittneje** [comment]
@violin0622 Are you certain there's nothing after "build for" in the output message? Please run `go build -x &> out.txt` and then paste the entirety of out.txt here.

**Comment by mholt** [comment]
@rittneje I can confirm there is nothing after "build for" in the output.

**Comment by rittneje** [comment]
@mholt That's really strange, and would definitely imply some sort of bug in the Go toolchain. Would you also be able to run that `go build -x` command and paste the output here?

**Comment by mholt** [comment]
@rittneje Here you go:

```
$ go build -x sqlite.go
WORK=/var/folders/sf/7w4p15_15jb59d7kwy0wglh40000gn/T/go-build427504901
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
# import config
packagefile github.com/mattn/go-sqlite3=/Users/matt/Dev/pkg/darwin_amd64/github.com/mattn/go-sqlite3.a
packagefile runtime=/usr/local/go/pkg/darwin_amd64/runtime.a
EOF
cd /Users/matt/Desktop
/usr/local/go/pkg/tool/darwin_amd64/compile -o $WORK/b001/_pkg_.a -trimpath $WORK/b001 -p main -complete -buildid elkbV7CMhzKPV7PMFCsp/elkbV7CMhzKPV7PMFCsp -goversion go1.12.6 -D _/Users/matt/Desktop -importcfg $WORK/b001/importcfg -pack -c=4 ./sqlite.go
/usr/local/go/pkg/tool/darwin_amd64/buildid -w $WORK/b001/_pkg_.a # internal
cp $WORK/b001/_pkg_.a /Users/matt/Library/Caches/go-build/25/253a31dcc6bd6c21b1d1327108a621eb1d1be212f9bd682af36a50d6a4bdc7df-d # internal
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=$WORK/b001/_pkg_.a
packagefile github.com/mattn/go-sqlite3=/Users/matt/Dev/pkg/darwin_amd64/github.com/mattn/go-sqlite3.a
packagefile runtime=/usr/local/go/pkg/darwin_amd64/runtime.a
packagefile context=/usr/local/go/pkg/darwin_amd64/context.a
packagefile crypto/sha1=/usr/local/go/pkg/darwin_amd64/crypto/sha1.a
packagefile crypto/sha256=/usr/local/go/pkg/darwin_amd64/crypto/sha256.a
packagefile crypto/sha512=/usr/local/go/pkg/darwin_amd64/crypto/sha512.a
packagefile database/sql=/usr/local/go/pkg/darwin_amd64/database/sql.a
packagefile database/sql/driver=/usr/local/go/pkg/darwin_amd64/database/sql/driver.a
packagefile errors=/usr/local/go/pkg/darwin_amd64/errors.a
packagefile fmt=/usr/local/go/pkg/darwin_amd64/fmt.a
packagefile io=/usr/local/go/pkg/darwin_amd64/io.a
packagefile math=/usr/local/go/pkg/darwin_amd64/math.a
packagefile net/url=/usr/local/go/pkg/darwin_amd64/net/url.a
packagefile reflect=/usr/local/go/pkg/darwin_amd64/reflect.a
packagefile strconv=/usr/local/go/pkg/darwin_amd64/strconv.a
packagefile strings=/usr/local/go/pkg/darwin_amd64/strings.a
packagefile sync=/usr/local/go/pkg/darwin_amd64/sync.a
packagefile time=/usr/local/go/pkg/darwin_amd64/time.a
packagefile runtime/cgo=/usr/local/go/pkg/darwin_amd64/runtime/cgo.a
packagefile syscall=/usr/local/go/pkg/darwin_amd64/syscall.a
packagefile internal/bytealg=/usr/local/go/pkg/darwin_amd64/internal/bytealg.a
packagefile internal/cpu=/usr/local/go/pkg/darwin_amd64/internal/cpu.a
packagefile runtime/internal/atomic=/usr/local/go/pkg/darwin_amd64/runtime/internal/atomic.a
packagefile runtime/internal/math=/usr/local/go/pkg/darwin_amd64/runtime/internal/math.a
packagefile runtime/internal/sys=/usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a
packagefile crypto=/usr/local/go/pkg/darwin_amd64/crypto.a
packagefile hash=/usr/local/go/pkg/darwin_amd64/hash.a
packagefile sort=/usr/local/go/pkg/darwin_amd64/sort.a
packagefile sync/atomic=/usr/local/go/pkg/darwin_amd64/sync/atomic.a
packagefile unicode=/usr/local/go/pkg/darwin_amd64/unicode.a
packagefile unicode/utf8=/usr/local/go/pkg/darwin_amd64/unicode/utf8.a
packagefile internal/fmtsort=/usr/local/go/pkg/darwin_amd64/internal/fmtsort.a
packagefile os=/usr/local/go/pkg/darwin_amd64/os.a
packagefile math/bits=/usr/local/go/pkg/darwin_amd64/math/bits.a
packagefile internal/race=/usr/local/go/pkg/darwin_amd64/internal/race.a
packagefile internal/poll=/usr/local/go/pkg/darwin_amd64/internal/poll.a
packagefile internal/syscall/unix=/usr/local/go/pkg/darwin_amd64/internal/syscall/unix.a
packagefile internal/testlog=/usr/local/go/pkg/darwin_amd64/internal/testlog.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/usr/local/go/pkg/tool/darwin_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=f1emFMb5ec332jExW2S3/elkbV7CMhzKPV7PMFCsp/JbGkqZyl9fmghVyGbKdY/f1emFMb5ec332jExW2S3 -extld=clang $WORK/b001/_pkg_.a
/usr/local/go/pkg/tool/darwin_amd64/buildid -w $WORK/b001/exe/a.out # internal
# command-line-arguments
ld: warning: building for macOS, but linking in object file (/var/folders/sf/7w4p15_15jb59d7kwy0wglh40000gn/T/go-link-331632953/go.o) built for 
mv $WORK/b001/exe/a.out sqlite
rm -r $WORK/b001/
```

**Comment by rittneje** [comment]
@mholt @violin0622 Nothing jumps out at me as an immediate problem. I would recommend filing an issue against Go itself. https://github.com/golang/go/issues Perhaps one of the Go authors will be able to shed some light on this.

**Comment by obynio** [comment]
I had the same problem and found a fix. You need to update the Mojave's Command Line Tools manually using the installer available here https://developer.apple.com/download/more/

Take the most recent corresponding to your macOS version. That was `Command Line Tools (macOS 10.14) for Xcode 10.2.1.dmg` for me.

**Comment by obynio** [comment]
I had the same problem and found a fix. You need to update the Mojave's Command Line Tools manually using the installer available here https://developer.apple.com/download/more/

Take the most recent corresponding to your macOS version. That was `Command Line Tools (macOS 10.14) for Xcode 10.2.1.dmg` for me. Tell me if it solved your issue.

**Comment by fabstu** [comment]
Installing the latest Xcode and it installing the newest CLI tools on startup solved this for me too.

**Comment by mholt** [comment]
That worked for me too. Thanks @obynio. Why does that fix it?

**Comment by obynio** [comment]
I just came across a similar thread and decided to give it a try. Honestly I did not dig any further because  people seems to disagree about the root cause ¯\\\_(ツ)\_/¯

**Comment by GJRTimmer** [comment]
Issue closed; please re-open if required.
