### ISSUE TITLE
What's the deal with the last release?

### ISSUE THREAD

**Issue by Vorlif** [mattn/go-sqlite3#723]
I am a bit confused about the latest version 1.10. This version has the same version number as the previous release and is therefore not loaded, at least with go modules. To work around this problem I deleted my local version and reloaded it with `go get -u github.com/mattn/go-sqlite3`. Afterwards, I had the latest 1.10 version. This versioning can lead to strange behavior, since two developers on a project use the same version number of go-sqlite3 but a different code base.

Furthermore, it says in the Changelog that SQLite version 3.28 is used now, but in the file `sqlite3-binding.h` it says 3.25.2. Also, here on GitHub, in the source code of the release and in the corresponding branch, version 3.25.2 is still stored. 

Did I do something wrong or did I get it wrong?

Thank you for your work and in advance for the answer.

**Comment by mattn** [comment]
What do you mean same version? go-sqlite3 does not have go.mod.

**Comment by Vorlif** [comment]
It is not necessary that go-sqlite has a go.mod. If a project has a go.mod and this project has go-sqlite as a dependency, the last tagged version of go-sqlite is automatically used. The last tagged version of go-sqlite was 1.10. A few days ago you created a new release of go-sqlite which has the version number 1.10 again.

Example: If developer A loaded go-sqlite a month ago, the old version 1.10 was loaded automatically. Developer B starts development today, pulls out the current project and loads the go.mod dependencies. In the go.mod version 1.10 of go-sqlite is defined which is then loaded from GitHub. This version is newer than developer A. So developer A and B have the same version number (1.10) but different versions.

Or are there no differences between the old and the new 1.10 version?

**Comment by mattn** [comment]
If go-sqlite3 does not have go.mod, Go uses older commit in same version.

**Comment by mattn** [comment]
The commits which pushed into master branch after 1.10.0 is not used until I will tag next version. (If you use tag v1.10.0). If you want to follow latest version, you should use `@latest`.

**Comment by Vorlif** [comment]
> If go-sqlite3 does not have go.mod, Go uses older commit in same version.

I think it works differently with modules. Do you think you could increase the version number for future releases? :blush:  This would make it easier to use the latest version with a versioning system (like dep, module, etc.). 

> The commits which pushed into master branch after 1.10.0 is not used until I will tag next version.

That makes sense. You wrote in the release notes that SQLite 3.28.0 is now being used, but the commit for the change was added after the 1.10 tag. [Compare of v1.10 and master](https://github.com/mattn/go-sqlite3/compare/v1.10.0...master)

Is the master stable enough for productive use?

Thanks for your time

**Comment by GJRTimmer** [comment]
> > If go-sqlite3 does not have go.mod, Go uses older commit in same version.
> 
> I think it works differently with modules. Do you think you could increase the version number for future releases? 😊 This would make it easier to use the latest version with a versioning system (like dep, module, etc.).
> 
> > The commits which pushed into master branch after 1.10.0 is not used until I will tag next version.
> 
> That makes sense. You wrote in the release notes that SQLite 3.28.0 is now being used, but the commit for the change was added after the 1.10 tag. [Compare of v1.10 and master](https://github.com/mattn/go-sqlite3/compare/v1.10.0...master)
> 
> Is the master stable enough for productive use?
> 
> Thanks for your time

Yes master is stable enough for production use.
