### ISSUE TITLE
provided "_auth" but without "_auth_user" and "_auth_pass" cannot be detected

### ISSUE THREAD

**Issue by coderev** [mattn/go-sqlite3#724]
**Problem description:**
in file sqlite3.qo, the line 1525, 1528 as following:
```
		if len(authUser) < 0 {
			return nil, fmt.Errorf("Missing '_auth_user' while user authentication was requested with '_auth'")
		}
```
```
		if len(authPass) < 0 {
			return nil, fmt.Errorf("Missing '_auth_pass' while user authentication was requested with '_auth'")
		}
```
When the connection string is set to ""file:foo.db?_auth" (the _auth_user and _auth_pass were intentionally omitted for testing), the above code block cannot detect the missing parameters, because  the input "authUser" and "authPass" is 0, not less than zero.
**How to reproduce:**
use the following connection string to reproduce it:
```
	db, err := sql.Open("sqlite3", "file:foo.db?_auth")
	checkErr(err)
```

**Comment by GJRTimmer** [comment]
@coderev Thank you for pointing out. Will look into it
