### ISSUE TITLE
date type is returned differently whether key or not

### ISSUE THREAD

**Issue by SmallRoomLabs** [mattn/go-sqlite3#726]
If a date field is just a regular field it is compatible with the go type time.Time, but if the date field is set as a key it is apparently returned as a []uint8.  Is this the expected behavior or is it a bug?

(Running on "go version go1.12.6 darwin/amd64")

### Results from the test code from below

```
$ go run fail.go;

testWithNoKey dt= 2019-06-17 20:35:47 +0000 UTC  txt= DT IS FIELD

testWithKey  sql: Scan error on column index 0, name "dt": unsupported Scan, 
storing driver.Value type []uint8 into type *time.Time
```

### Full test code that creates a new database, two populated tables and then tries to select from it.

```
package main

import (
	"database/sql"
	"fmt"
	"os"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	_, _ = os.Create("test.db")
	db, _ := sql.Open("sqlite3", "./test.db")
	db.Exec("CREATE TABLE testWithNoKey (dt date, txt varchar(20))")
	db.Exec("CREATE TABLE testWithKey (dt KEY date, txt varchar(20))")
	db.Exec("INSERT INTO testWithNoKey (dt,txt) VALUES(datetime('now'),'DT IS FIELD')")
	db.Exec("INSERT INTO testWithKey (dt,txt) VALUES(datetime('now'),'DT IS KEY')")

	var dt time.Time
	var txt string

	fmt.Println()
	err := db.QueryRow("SELECT dt,txt FROM testWithNoKey").Scan(&dt, &txt)
	if err != nil {
		fmt.Println("testWithNoKey ", err)
	} else {
		fmt.Println("testWithNoKey dt=", dt, " txt=", txt)
	}

	fmt.Println()
	err = db.QueryRow("SELECT dt,txt FROM testWithKey").Scan(&dt, &txt)
	if err != nil {
		fmt.Println("testWithKey ", err)
	} else {
		fmt.Println("testWithKey dt=", dt, " txt=", txt)
	}
}
```

**Comment by rittneje** [comment]
It's because your schema is invalid. You are looking for `dt date primary key`. The reason you didn't get an error is because SQLite doesn't really validate the column type at all - it literally just takes whatever you write and rolls with it. https://www.sqlite.org/datatype3.html

```
sqlite> create table foobar(x abc def xyz);
sqlite> pragma table_info(foobar);
cid|name|type|notnull|dflt_value|pk
0|x|abc def xyz|0||0
```

**Comment by SmallRoomLabs** [comment]
Oh no.... How could I have forgot the "primary" for the key. Apparently the muscle memory for SQL dosen't last 10 years - I've primarily been doing embedded for all those years.  

Hmm, I wonder if there's a SQL -validator much like W3C html/css validators? But considering the number of different dialect/implementations of the language I guess the answer to that is no.

Mea Culpa....  Thanks for straitening this out...
