### ISSUE TITLE
so wired bug of golang func of regex and with json tag

### ISSUE THREAD

**Issue by gobysec** [mattn/go-sqlite3#728]
go build --tags "json1"

```golang
func TestABC(t *testing.T) {
	dbfile := "test.sqlite3"
	err := os.Remove(dbfile)

	regexFn := func(re, s string) (bool, error) {
		b, e := regexp.MatchString(re, s)
		return b, e
	}

	sql.Register("sqlite3_with_go_func_test",
		&sqlite3.SQLiteDriver{
			ConnectHook: func(conn *sqlite3.SQLiteConn) error {
				return conn.RegisterFunc("regexp", regexFn, true)
			},
		})

	db, err := sql.Open("sqlite3_with_go_func_test", "sqlite:"+dbfile)

	_, err = db.Exec("drop TABLE if exists test")
	_, err = db.Exec("CREATE TABLE test(id varchar(100), json TEXT)")
	_, err = db.Exec(`insert into test(id, json) values ('111', '{}')`) // if this line comment, then the result will be right
	_, err = db.Exec(`insert into test(id, json) values ('222', '{"banner":"HTTP/1.1 404 Not Found\r\nServer: testServer/1.0"}')`)

	rows, err := db.Query(`
		SELECT * FROM test 
		WHERE json_extract ( json, "$.banner" ) REGEXP "(?is)testServer"
ORDER BY id`)
	assert.Nil(t, err)
	defer rows.Close()

	size := 0
	for rows.Next() {
		size ++
	}
	assert.Equal(t, 1, size)
	//dumpTable(rows)
}
```

if this line comment, then the result will be right:
```golang
_, err = db.Exec(`insert into test(id, json) values ('111', '{}')`) // if this line comment, then the result will be right
```

It seems that regex only called once, but I want every row to check. I need some help, thanks.

**Comment by rittneje** [comment]
@gobysec To clarify, what result are you seeing in the failure case? Also, in your code snippet you are not checking the error from `db.Exec`, nor are you checking `rows.Err()` after your `rows.Next()` loop. Please be sure you are not getting errors in either of these cases.

**Comment by gobysec** [comment]
> @gobysec To clarify, what result are you seeing in the failure case? Also, in your code snippet you are not checking the error from `db.Exec`, nor are you checking `rows.Err()` after your `rows.Next()` loop. Please be sure you are not getting errors in either of these cases.

I remove err check for minify code but I'm very sure that every code is run without any errors. 
The result is just empty rows, but if comment the first insert code, it will be ok with 1 row out.

**Comment by rittneje** [comment]
@gobysec If you look at `rows.Err()` after your `rows.Next()` loop, you'll see that it's reporting an error: `argument must be BLOB or TEXT`. This is because `json_extract` is returning `null` for the `{}` entry, and your function doesn't allow for `nil`. However, at this time, this library does not allow user-defined functions to accept pointers; it simply spits out an error stating `don't know how to convert to *string`. I am going to file a feature request for that. In the meantime, please change your condition to `WHERE IFNULL(json_extract(json, "$.banner"), "") REGEXP "(?is)testServer"`.

**Comment by gobysec** [comment]
> IFNULL(json_extract(json, "$.banner"), "")

Yep, so cool, I know how to do right now, tks so much ;)

**Comment by gobysec** [comment]
> @gobysec If you look at `rows.Err()` after your `rows.Next()` loop, you'll see that it's reporting an error: `argument must be BLOB or TEXT`. This is because `json_extract` is returning `null` for the `{}` entry, and your function doesn't allow for `nil`. However, at this time, this library does not allow user-defined functions to accept pointers; it simply spits out an error stating `don't know how to convert to *string`. I am going to file a feature request for that. In the meantime, please change your condition to `WHERE IFNULL(json_extract(json, "$.banner"), "") REGEXP "(?is)testServer"`.

Yep, so cool, I know how to do right now, tks so much ;)
