### ISSUE TITLE
disk usage is high on windows

### ISSUE THREAD

**Issue by 756445638** [mattn/go-sqlite3#730]

**Comment by mattn** [comment]
I can't understand what you mean.

**Comment by 756445638** [comment]
I will give you more information.

**Comment by 756445638** [comment]
Go is a tool for managing Go source code.

Usage:

        go <command> [arguments]

The commands are:

        bug         start a bug report
        build       compile packages and dependencies
        clean       remove object files and cached files
        doc         show documentation for package or symbol
        env         print Go environment information
        fix         update packages to use new APIs
        fmt         gofmt (reformat) package sources
        generate    generate Go files by processing source
        get         download and install packages and dependencies
        install     compile and install packages and dependencies
        list        list packages or modules
        mod         module maintenance
        run         compile and run Go program
        test        test packages
        tool        run specified go tool
        version     print Go version
        vet         report likely mistakes in packages

Use "go help <command>" for more information about a command.

Additional help topics:

        buildmode   build modes
        c           calling between Go and C
        cache       build and test caching
        environment environment variables
        filetype    file types
        go.mod      the go.mod file
        gopath      GOPATH environment variable
        gopath-get  legacy GOPATH go get
        goproxy     module proxy protocol
        importpath  import path syntax
        modules     modules, module versions, and more
        module-get  module-aware go get
        packages    package lists and patterns
        testflag    testing flags
        testfunc    testing functions

Use "go help <topic>" for more information about that topic.

**Comment by 756445638** [comment]
$ go env


set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\SICBATCH\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\SICBATCH\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\SICBATCH\AppData\Local\Temp\go-build599471966=/tmp/go-build -gno-record-gcc-switches

**Comment by 756445638** [comment]
[pprof.samples.cpu.002.pb.gz](https://github.com/mattn/go-sqlite3/files/3357305/pprof.samples.cpu.002.pb.gz)

**Comment by 756445638** [comment]
Is this enough for you to debug the problem?
we trying to save time serial data in sqlite db.

**Comment by mattn** [comment]
>disk usage is high on windows

Which kind of disk usage?

* executable file?
* database file?

**Comment by 756445638** [comment]
please wait a little.

**Comment by 756445638** [comment]
maybe the hard driver is broken!!!
need more test

**Comment by 756445638** [comment]
I switch write data to my Usb hard driver, worked very fine .
Is the sqlite write data almost random the the hard driver ??

**Comment by 756445638** [comment]
I write the data per 500 ms , this is the problem !!
right now I change write data very 30s , works fine!!
sorry to bother you!!
