### ISSUE TITLE
Memory leak when using WantExpandedSQL

### ISSUE THREAD

**Issue by gwenn** [mattn/go-sqlite3#733]
https://github.com/mattn/go-sqlite3/blob/25ecb14adfc7543176f7d85291ec7dba82c6f7e4/sqlite3_trace.go#L91
http://sqlite.org/c3ref/expanded_sql.html
> The string returned by sqlite3_expanded_sql(P), on the other hand, is obtained from sqlite3_malloc() and must be free by the application by passing it to sqlite3_free().

**Comment by GJRTimmer** [comment]
@gwenn Thanks for pointing out, fix available in branch `fix-733` could you please test and verify.

Thanks in advance.
