### ISSUE TITLE
Compile error inside Grafana

### ISSUE THREAD

**Issue by andig** [mattn/go-sqlite3#739]
This is a little off-topic, however I was hoping to find help. I'm trying to cross-build Grafana from source and it depends on sqlite:

    ~/htdocs/grafana master* ⇣⇡
    ❯ GO111MODULE=on go run build.go -goos linux -pkg-arch amd64 build pkg-archive latest
    Version: 6.3.3, Linux Version: 6.3.3, Package Iteration: 1566543129
    rm -r ./bin/linux-amd64/grafana-server
    rm -r ./bin/linux-amd64/grafana-server.md5
    go version
    go version go1.12.9 darwin/amd64
    Targeting linux/amd64
    go build -ldflags -w -X main.version=6.3.3 -X main.commit=84d0a71b2 -X main.buildstamp=1565860092 -X main.buildBranch=master -o ./bin/linux-amd64/grafana-server ./pkg/cmd/grafana-server
    # github.com/grafana/grafana/pkg/services/sqlstore/migrator
    pkg/services/sqlstore/migrator/sqlite_dialect.go:89:27: undefined: sqlite3.Error
    pkg/services/sqlstore/migrator/sqlite_dialect.go:99:33: undefined: sqlite3.ErrConstraintUnique
    exit status 2
    exit status 1

Refs:
- https://community.grafana.com/t/sqlite3-error-when-compling-grafana/10973
- https://community.grafana.com/t/sqlite3-dependency-error-during-cross-compile/1808/2
- https://github.com/grafana/grafana/issues/11557

**Comment by mattn** [comment]
You must use cross-C-compiler not host-compiler.

**Comment by GJRTimmer** [comment]
@andig Closable ?

**Comment by suyi-levi** [comment]
I have met the same problem. How did you solve the problem?

**Comment by andig** [comment]
If you cross-compile you‘ll also need a C cross compiler.
