### ISSUE TITLE
go-sqlite when go build with windows gui program error

### ISSUE THREAD

**Issue by huprince** [mattn/go-sqlite3#741]
**cmd error log:**
D:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/mingw-w64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\HUDENG~1\AppData\Local\Temp\go-link-643890423\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
The [issue](https://github.com/golang/go/issues/12448) is same, how to solve?

**Comment by mattn** [comment]
Probably, you are using 64bit go and 32bit C compiler.
