### ISSUE TITLE
undefined: SQLiteConn

### ISSUE THREAD

**Issue by relax-admin** [mattn/go-sqlite3#742]
Error when building with golang:1.12-alpine

```golang
CGO_ENABLED=0  go build
```
error

```bash
# github.com/mattn/go-sqlite3
../github.com/mattn/go-sqlite3/sqlite3_opt_preupdate.go:12:16: undefined: SQLiteConn
```

**Comment by rittneje** [comment]
Why are you building with cgo disabled?

**Comment by relax-admin** [comment]
Because when doing unit testing, I hope to use golang-alpine to build the image directly, because it will be smaller.

After cgo is disabled, the following packages are compileable, and go-sqlite3 can be compiled before this method（SQLiteConn） is used.

```Dockerfile
go get go.uber.org/zap && \
    go get github.com/dgrijalva/jwt-go && \
    go get github.com/go-sql-driver/mysql && \
    go get github.com/mattn/go-sqlite3 && \
    go get github.com/spf13/viper && \
    go get github.com/labstack/echo && \
    go get github.com/go-xorm/core && \
    go get github.com/go-xorm/builder && \
    go get github.com/urfave/cli && \
    go get github.com/satori/go.uuid && \
    go get github.com/google/go-querystring/query && \
    go get github.com/go-kit/kit/endpoint && \
    go get github.com/go-kit/kit/transport/http && \
    go get github.com/go-kit/kit/transport/grpc && \
    go get github.com/pangpanglabs/goutils/... && \
    go get github.com/pangpanglabs/echoswagger && \
    go get github.com/asaskevich/govalidator && \
    go get github.com/sirupsen/logrus && \
    go get github.com/gomodule/redigo/redis && \
    go get github.com/denisenkom/go-mssqldb && \
    go get gopkg.in/mgo.v2 && \
    go get github.com/gorilla/mux && \
    go get github.com/gorilla/context && \
    go get github.com/gorilla/securecookie && \
    go get github.com/gorilla/sessions && \
    go get github.com/gorilla/websocket && \
    go get github.com/jinzhu/configor && \
    go get github.com/patrickmn/go-cache && \
    go get github.com/unrolled/render && \
    go get github.com/urfave/negroni && \
    go get github.com/Shopify/sarama && \
    go get github.com/bsm/sarama-cluster && \
    go get github.com/colinmarc/go-presto && \
    go get github.com/prestodb/presto-go-client/presto && \
    go get github.com/aliyun/aliyun-oss-go-sdk/oss && \
    go get github.com/360EntSecGroup-Skylar/excelize && \
    go get gopkg.in/go-playground/validator.v9 && \
    go get github.com/RichardKnop/machinery/v1 && \
    go get github.com/renstrom/shortuuid && \
    go get github.com/json-iterator/go && \
    go get github.com/pkg/errors && \
    go get github.com/kardianos/govendor

```

**Comment by rittneje** [comment]
Sorry I don't follow. Using alpine does not necessitate disabling cgo.

**Comment by relax-admin** [comment]
I just found this sentence in the README.md document, please close this issue.

**Important: because this is a CGO enabled package you are required to set the environment variable CGO_ENABLED=1 and have a gcc compile present within your path.**

**Comment by ikirker** [comment]
So, for what it's worth, I started getting this error message when building with Go 1.12 on linux-amd64 (RHEL 7.4) for non-native arches from 2ea5857c0eb3179b078ce5fb881ace11eb28f285 onwards -- I'm *guessing* from the README I now might need a cross-compiling `CC` to be set, where I didn't seem to have to worry about that before.

Not really a maintainer's problem, I know, but I thought it might be useful to report.

**Comment by rittneje** [comment]
@ikirker This library certainly cannot be compiled without cgo in any meaningful sense. And using cgo has always required you to explicitly set `CGO_ENABLED=1` and `CC=<cross compiler>` when cross-compiling. I can't speak to how it managed to work for you previously, but it probably should not have.

**Comment by relax-admin** [comment]
Sometimes we may have multiple environments, such as staging and qa and prd, staging using sqlite, qa and prd using mysql

In the qa and prd environment, we want to use **CGO_ENBALE=0** build, but because staging environment uses sqlite, it will inevitably use **_ "github.com/mattn/go-sqlite3"** in our code, which will lead to build failure

**Comment by rittneje** [comment]
@relax-admin That sounds like a bad idea. You should be using a consistent setup in each environment. http://michael.robellard.com/2015/07/dont-test-with-sqllite-when-you-use.html

**Comment by relax-admin** [comment]
@rittneje Thank you very much for this article, and now our test and build environment is unified to mysql.

**Comment by mattn** [comment]
G
