### ISSUE TITLE
osx build fail  CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build error reporting

### ISSUE THREAD

**Issue by echobool** [mattn/go-sqlite3#756]
os version :macos 10.15.1
go version: 1.13.1
go env:
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/luojinyi/Library/Caches/go-build"
GOENV="/Users/luojinyi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/luojinyi/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/luojinyi/go/src/mymicro/configure-srv/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/34/fh5s01vs5hx6d_zqg0s4ybc00000gn/T/go-build632305009=/tmp/go-build -gno-record-gcc-switches -fno-common"

CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build

<img width="1157" alt="QQ20191114-225351@2x" src="https://user-images.githubusercontent.com/8441357/68868153-fbf2b280-0731-11ea-95b5-b42d8e4ed4ec.png">

**Comment by rittneje** [comment]
@echobool You need a proper C cross-compiler. By default it is using the one for your host, which appears to be Mac. You need a C compiler that targets 64-bit Linux.

**Comment by echobool** [comment]
@rittneje Can you give me a detailed installation process? Thank you。Try to install the online tutorial without success。

**Comment by echobool** [comment]
brew install FiloSottile/musl-cross/musl-cross 
It will run normally after installation, thank you。

**Comment by rittneje** [comment]
@echobool An alternative would be to use docker to compile the binary. For example:
```dockerfile
FROM golang:1.12-alpine
RUN apk add --no-cache gcc musl-dev
```
```bash
docker build --pull -t golang-cgo:1.12-alpine .
```

Then use `docker run` to run that image with whatever Go directory mounted (`-v`), and run `go build` inside of the container.

**Comment by echobool** [comment]
thank you

**Comment by LittleBuster** [comment]
> @echobool An alternative would be to use docker to compile the binary. For example:
> 
> ```dockerfile
> FROM golang:1.12-alpine
> RUN apk add --no-cache gcc musl-dev
> ```
> 
> ```shell
> docker build --pull -t golang-cgo:1.12-alpine .
> ```
> 
> Then use `docker run` to run that image with whatever Go directory mounted (`-v`), and run `go build` inside of the container.

Very helpful for docker. Thank you!

**Comment by sandhyadalavi** [comment]
I'm trying to create a docker image to run go binary which is using go-sqlite3. I'm running the docker build/run on Mac(Darwin) system. 

here is the dockerfile 

`# --- stage 1 ---
FROM golang:1.16 AS builder

WORKDIR /build

RUN dpkg --add-architecture amd64 \
    && apt update \
    && apt-get install -y --no-install-recommends gcc-x86-64-linux-gnu libc6-dev-amd64-cross

# Cache optimization
COPY go.mod go.sum Makefile ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=1 CC=x86_64-linux-gnu-gcc GOOS=linux GOARCH=amd64 go build -o bin/binary cmd/main.go
# --- stage 2 ---
FROM scratch


WORKDIR /
COPY --from=builder /build/bin/binary /

ENTRYPOINT ["/binary"]`


when I run the docker image on mac, I get below error

standard_init_linux.go:228: exec user process caused: no such file or directory

I want to create docker image which can run on any system without any issue.

**Comment by yashvardhan-kukreja** [comment]
+1 @sandhyadalavi

**Comment by rittneje** [comment]
@yashvardhan-kukreja @sandhyadalavi As I mentioned in #992, any binary compiled with cgo will be dynamically linked with libc, which means you need to include that in the final image. If you are still having a problem, please open a new issue.
