### ISSUE TITLE
how to set cache_size for every connection in connection pool?

### ISSUE THREAD

**Issue by just1900** [mattn/go-sqlite3#762]
How to set `cache_size` for  every connection in the connection pool while using database/sql to Open the sqlite?
Currently, below is the way I use the sqlite driver, and set connection size to 20.
```
db, err = sql.Open("sqlite3", "file:test.db")
db.SetMaxOpenConns(20)
db.Exec("PRAGMA cache_size = 4000")
```
Is that effective to exec `"PRAGMA cache_size = 4000"` once on initializing ?

**Comment by rittneje** [comment]
What you have right now will only issue the PRAGMA on one of the 20 connections. Instead, you can register a custom driver with a ConnectHook to issue the PRAGMA. That will make sure it happens every time the standard library opens a new connection in its pool.

**Comment by just1900** [comment]
@rittneje Sorry, I'm not very understand for how to 

> register a custom driver

Can you explain it more clear or provide a piece of code ?

**Comment by rittneje** [comment]
One way to do it:

```go
func init() {
    sql.Register("sqlite3_cache_size", &sqlite3.SQLiteDriver{
        ConnectHook: func(c *sqlite3.SQLiteConn) error {
            _, err := c.Exec("PRAGMA cache_size = 4000", nil)
            return err
        }
    })
}

...

db, err := sql.Open("sqlite3_cache_size", "file:test.db")
...
```

**Comment by just1900** [comment]
It helped, Thanks : )
