### ISSUE TITLE
Query parameter for encoding

### ISSUE THREAD

**Issue by tredoe** [mattn/go-sqlite3#766]
Add a query parameter to set the encoding at creating a table.

https://www.sqlite.org/pragma.html#pragma_encoding
https://stackoverflow.com/questions/21348459/set-pragma-encoding-utf-16-for-main-database-in-sqlite

**Comment by rittneje** [comment]
In the meantime, if this is blocking you, you can use a connect hook to issue the pragma. See https://github.com/mattn/go-sqlite3/issues/762#issuecomment-561134655.

**Comment by tredoe** [comment]
Why does this issue was closed without any reason.
