### ISSUE TITLE
Trouble installing on windows

### ISSUE THREAD

**Issue by shixish** [mattn/go-sqlite3#77]
I'm installing into Windows 8 64 bit

When I run: `go get github.com/mattn/go-sqlite3`
I get this:
  # github.com/mattn/go-sqlite3
  In file included from sqlite3.go:4:
  sqlite3.h:35: stdarg.h: No such file or directory
  sqlite3.go:5: stdlib.h: No such file or directory
  sqlite3.go:6: string.h: No such file or directory
  sqlite3.go:35: stdio.h: No such file or directory
  sqlite3.go:36: stdint.h: No such file or directory

Any ideas of what's screwing up?

I saw that there's an issue for a Windows 64 bit bug here:
https://github.com/mattn/go-sqlite3/issues/27

But I don't think it's the same issue..?

**Comment by apeshave** [comment]
I installed 64 bit GCC but still I am facing this issue.
