### ISSUE TITLE
How to handle IN ($1)?

### ISSUE THREAD

**Issue by neilalexander** [mattn/go-sqlite3#773]
Using this query as an example:
```
SELECT foo FROM bar WHERE baz IN ("one","two","three")
```
What is the best way to be able to pass in `"one","two","three"` so that SQLite treats it as a list of values and not one single value?

As far as I can see, if the statement is prepared like this:
```
SELECT foo FROM bar WHERE baz IN ($1)
```
... and then a value like `"one","two","three"` is passed in to `$1` using `Stmt.QueryContext` or similar, the input is escaped and arrives at SQLite as one value, therefore the query fails.

I also tried implementing a type that implements `sql.Valuer` and `sql.Scanner` and passing that in instead, but the same problem seems to exist.

Is there a way to handle cases like this?

**Comment by maksa** [comment]
From what I know there is no way to pass a list of arbitrary size as a single param and have it unrolled in the prepared statement. This basically boils down to everybody rolling his own "sqlify-my-list" method and sprintf-ing the query.

**Comment by mattn** [comment]
SQLite3 does not have APIs to bind array to placeholder.

See https://www.sqlite.org/c3ref/bind_blob.html
