### ISSUE TITLE
Tags, releases and changelings

### ISSUE THREAD

**Issue by AlekSi** [mattn/go-sqlite3#774]
https://github.com/mattn/go-sqlite3/releases shows 1.10.0 as the latest release. There are five newer tags after that without changelogs, including v2.0.1 and v2.0.2. That's confusing.

I propose to add short changelogs to releases, and then explain v2 in README.

**Comment by mattn** [comment]
v2.0.0 is unfortunatal release. So there are no big changes.

https://github.com/mattn/go-sqlite3/issues/755

**Comment by AlekSi** [comment]
Thanks for explaining. Given that issue and #598 I propose to say something like "v2 is a WIP, do not use yet" in README.

**Comment by mattn** [comment]
https://github.com/mattn/go-sqlite3/commit/ed406dd4e2a041e9394ce1f6dd647ad15f092e25

Updated README.md
