### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled

### ISSUE THREAD

**Issue by AVCADO** [mattn/go-sqlite3#778]
`go get github.com/mattn/go-sqlite3/` = cc1.exe: sorry, unimplemented: 64-bit mode not compiled.
Any help?

SPECS:
Windows 10 Home

**Comment by TheGolurk** [comment]
The same error

**Comment by mattn** [comment]
Do you use 32bit C compiler?

**Comment by AVCADO** [comment]
no, 64bit

**Comment by mattn** [comment]
Probably, you should set correct PATH environment variable.
