### ISSUE TITLE
Closing connection doesn't free the file from windows

### ISSUE THREAD

**Issue by icypheri** [mattn/go-sqlite3#783]
Problem: When closing a db connection by calling db.Close(), file is not getting completely released from windows. 
Symptom: trying to manually delete the file, windows is not allowing, saying its being used by the go program.
Observation: if a connection is opened for any sqlite3 db file, it never gets released till the go app is stopped.

Is there anyway to close the connection to a file and release it completely from go memory?

**Comment by mattn** [comment]
I can not reproduce it.
```
package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/mattn/go-sqlite3"
)

func run() {
	os.Remove("./foo.db")

	db, err := sql.Open("sqlite3", "./foo.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	sqlStmt := `
	create table foo (id integer not null primary key, name text);
	delete from foo;
	`
	_, err = db.Exec(sqlStmt)
	if err != nil {
		log.Printf("%q: %s\n", err, sqlStmt)
		return
	}

	tx, err := db.Begin()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err := tx.Prepare("insert into foo(id, name) values(?, ?)")
	if err != nil {
		log.Fatal(err)
	}
	defer stmt.Close()
	for i := 0; i < 100; i++ {
		_, err = stmt.Exec(i, fmt.Sprintf("こんにちわ世界%03d", i))
		if err != nil {
			log.Fatal(err)
		}
	}
	tx.Commit()

	rows, err := db.Query("select id, name from foo")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var name string
		err = rows.Scan(&id, &name)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, name)
	}
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}

	stmt, err = db.Prepare("select name from foo where id = ?")
	if err != nil {
		log.Fatal(err)
	}
	defer stmt.Close()
	var name string
	err = stmt.QueryRow("3").Scan(&name)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(name)

	_, err = db.Exec("delete from foo")
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.Exec("insert into foo(id, name) values(1, 'foo'), (2, 'bar'), (3, 'baz')")
	if err != nil {
		log.Fatal(err)
	}

	rows, err = db.Query("select id, name from foo")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var name string
		err = rows.Scan(&id, &name)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, name)
	}
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	run()
	println("hit entry key after delete foo.db")
	var b [1]byte
	os.Stdin.Read(b[:])
}
```

**Comment by rittneje** [comment]
@icypheri Can you share a minimal reproduction of this issue?

@mattn I noticed that this library uses `sqlite3_close_v2` rather than `sqlite3_close`. See https://www.sqlite.org/c3ref/close.html
> If the database connection is associated with unfinalized prepared statements or unfinished sqlite3_backup objects then sqlite3_close() will leave the database connection open and return SQLITE_BUSY. If sqlite3_close_v2() is called with unfinalized prepared statements and/or unfinished sqlite3_backups, then the database connection becomes an unusable "zombie" which will automatically be deallocated when the last prepared statement is finalized or the last sqlite3_backup is finished.

I'm wondering if perhaps some prepare statement or something is getting silently leaked, resulting in the database never actually closing.

**Comment by icypheri** [comment]
@mattn @rittneje After going through your code, I could find that some db queries were getting leaked which caused the connection to become zombie. I fixed the code and the leakage problem is gone. Now, its working as expected. I believe, the issue should be closed now.
