### ISSUE TITLE
go vet: possible misuse of unsafe.Pointer

### ISSUE THREAD

**Issue by dtbartle** [mattn/go-sqlite3#791]
When running `go vet ./...` I see a few errors that should be fixed:
```
./sqlite3.go:476:63: possible misuse of unsafe.Pointer
./sqlite3.go:494:67: possible misuse of unsafe.Pointer
./sqlite3.go:507:71: possible misuse of unsafe.Pointer
./sqlite3.go:524:67: possible misuse of unsafe.Pointer
./sqlite3.go:538:70: possible misuse of unsafe.Pointer
```

**Comment by rittneje** [comment]
It looks like these are all flagging uses of the `newHandle` function, which indeed violates the rules about `uintptr` to `unsafe.Pointer` conversions. In particular, it returns an incrementing counter and then tries to treat it as a pointer, which I believe has the capacity to really confuse the garbage collector, or worse.

https://golang.org/pkg/unsafe/#Pointer
>  Conversion of a uintptr back to Pointer is not valid in general.
> 
> A uintptr is an integer, not a reference. Converting a Pointer to a uintptr creates an integer value with no pointer semantics. Even if a uintptr holds the address of some object, the garbage collector will not update that uintptr's value if the object moves, nor will that uintptr keep the object from being reclaimed.

This function ought to be replaced with a compliant implementation, like [this](https://github.com/mattn/go-pointer/blob/master/pointer.go).
