### ISSUE TITLE
Implement database/slq/driver.Valuer

### ISSUE THREAD

**Issue by nektro** [mattn/go-sqlite3#792]
At current, it is not possible to effectively use custom types and parses all values as underlying column type in a `fmt.Sprintf("%v")` format.

**Comment by rittneje** [comment]
@nektro Please provide more detail on what exactly you are trying to do.

**Comment by nektro** [comment]
Given the following type:

```go
type Array []string

// Scan - Implement the database/sql/driver Scanner interface
func (a *Array) Scan(value interface{}) error {
	if value == nil {
		*a = Array([]string{})
		return nil
	}
	if bv, err := driver.String.ConvertValue(value); err == nil {
		if v, ok := bv.(string); ok {
			if len(v) > 0 {
				*a = Array(strings.Split(v, ","))
			} else {
				*a = Array([]string{})
			}
			return nil
		}
	}
	return errors.New("failed to scan Array")
}

// Value - Implement the database/sql/driver Valuer interface
func (a Array) Value() (driver.Value, error) {
	return strings.Join(a, ","), nil
}
```

If I create an empty instance of this `Array{}` struct and insert into a column with the type `text` and `mattn/go-sqlite3` as the `database/sql` engine, the contents of the column will be `[]` instead of the expected ``.

**Comment by nektro** [comment]
This ended being due to an unrelated piece of code of mine. Sorry in advance.
