### ISSUE TITLE
Why not use the parameter _loc

### ISSUE THREAD

**Issue by buexplain** [mattn/go-sqlite3#793]
https://github.com/mattn/go-sqlite3/blob/67986a7832dcbda29de5c1341b3dec6c6d97511a/sqlite3.go#L2093
Why not use the parameter `rc.s.c.loc`,thanks.
```golang
var t time.Time
s = strings.TrimSuffix(s, "Z")
l := time.UTC
if rc.s.c.loc != nil {
    l = rc.s.c.loc
}
for _, format := range SQLiteTimestampFormats {
    if timeVal, err = time.ParseInLocation(format, s, l); err == nil {
        t = timeVal
        break
    }
}
```

**Comment by rittneje** [comment]
Note that the existing code calls `time.In` afterwards.
https://github.com/mattn/go-sqlite3/blob/67986a7832dcbda29de5c1341b3dec6c6d97511a/sqlite3.go#L2102-L2104

With what you are proposing, the behavior would be slightly different. `time.ParseInLocation` only uses the provided location if the input time string doesn't have a location. However, using `time.In` forces the result to always be in the provided location.

https://play.golang.org/p/VF2q-LuM01f
