### ISSUE TITLE
PTHREAD_MUTEX_INITIALIZER undeclared build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by sangshuduo** [mattn/go-sqlite3#794]
I am working to build with a multipass instance Ubuntu server 18.04. Did anyone encounter this issue? Any clue? Thanks. 

$ go build
# _/home/ubuntu/work/go-sqlite3
sqlite3-binding.c: In function ‘pthreadMutexAlloc’:
sqlite3-binding.c:26100:41: error: ‘PTHREAD_MUTEX_INITIALIZER’ undeclared (first use in this function); did you mean ‘SQLITE3_MUTEX_INITIALIZER’?
 #define SQLITE3_MUTEX_INITIALIZER(id) { PTHREAD_MUTEX_INITIALIZER }
                                         ^
sqlite3-binding.c:26197:5: note: in expansion of macro ‘SQLITE3_MUTEX_INITIALIZER’
     SQLITE3_MUTEX_INITIALIZER(2),
     ^~~~~~~~~~~~~~~~~~~~~~~~~
sqlite3-binding.c:26100:41: note: each undeclared identifier is reported only once for each function it appears in
 #define SQLITE3_MUTEX_INITIALIZER(id) { PTHREAD_MUTEX_INITIALIZER }
                                         ^
sqlite3-binding.c:26197:5: note: in expansion of macro ‘SQLITE3_MUTEX_INITIALIZER’
     SQLITE3_MUTEX_INITIALIZER(2),
     ^~~~~~~~~~~~~~~~~~~~~~~~~
sqlite3-binding.c:26222:9: warning: implicit declaration of function ‘pthread_mutexattr_init’; did you mean ‘pthreadMutexInit’? [-Wimplicit-function-declaration]
         pthread_mutexattr_init(&recursiveAttr);
         ^~~~~~~~~~~~~~~~~~~~~~
         pthreadMutexInit
sqlite3-binding.c:26223:9: warning: implicit declaration of function ‘pthread_mutexattr_settype’ [-Wimplicit-function-declaration]
         pthread_mutexattr_settype(&recursiveAttr, PTHREAD_MUTEX_RECURSIVE);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
sqlite3-binding.c:26223:51: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function); did you mean ‘SQLITE_MUTEX_RECURSIVE’?
         pthread_mutexattr_settype(&recursiveAttr, PTHREAD_MUTEX_RECURSIVE);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~
                                                   SQLITE_MUTEX_RECURSIVE
sqlite3-binding.c:26224:9: warning: implicit declaration of function ‘pthread_mutex_init’; did you mean ‘pthreadMutexInit’? [-Wimplicit-function-declaration]
         pthread_mutex_init(&p->mutex, &recursiveAttr);
         ^~~~~~~~~~~~~~~~~~
         pthreadMutexInit
sqlite3-binding.c:26225:9: warning: implicit declaration of function ‘pthread_mutexattr_destroy’ [-Wimplicit-function-declaration]
         pthread_mutexattr_destroy(&recursiveAttr);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
sqlite3-binding.c: In function ‘pthreadMutexFree’:
sqlite3-binding.c:26272:5: warning: implicit declaration of function ‘pthread_mutex_destroy’; did you mean ‘pthreadMutexFree’? [-Wimplicit-function-declaration]
     pthread_mutex_destroy(&p->mutex);
     ^~~~~~~~~~~~~~~~~~~~~
     pthreadMutexFree
sqlite3-binding.c: In function ‘pthreadMutexEnter’:
sqlite3-binding.c:26321:3: warning: implicit declaration of function ‘pthread_mutex_lock’; did you mean ‘pthreadMutexAlloc’? [-Wimplicit-function-declaration]
   pthread_mutex_lock(&p->mutex);
   ^~~~~~~~~~~~~~~~~~
   pthreadMutexAlloc
sqlite3-binding.c: In function ‘pthreadMutexTry’:
sqlite3-binding.c:26367:7: warning: implicit declaration of function ‘pthread_mutex_trylock’; did you mean ‘pthreadMutexAlloc’? [-Wimplicit-function-declaration]
   if( pthread_mutex_trylock(&p->mutex)==0 ){
       ^~~~~~~~~~~~~~~~~~~~~
       pthreadMutexAlloc
sqlite3-binding.c: In function ‘pthreadMutexLeave’:
sqlite3-binding.c:26405:3: warning: implicit declaration of function ‘pthread_mutex_unlock’; did you mean ‘pthreadMutexAlloc’? [-Wimplicit-function-declaration]
   pthread_mutex_unlock(&p->mutex);
   ^~~~~~~~~~~~~~~~~~~~
   pthreadMutexAlloc
sqlite3-binding.c: In function ‘sqlite3ThreadCreate’:
sqlite3-binding.c:30242:10: warning: implicit declaration of function ‘pthread_create’; did you mean ‘timer_create’? [-Wimplicit-function-declaration]
     rc = pthread_create(&p->tid, 0, xTask, pIn);
          ^~~~~~~~~~~~~~
          timer_create
sqlite3-binding.c: In function ‘sqlite3ThreadJoin’:
sqlite3-binding.c:30262:10: warning: implicit declaration of function ‘pthread_join’; did you mean ‘pthreadMutexEnd’? [-Wimplicit-function-declaration]
     rc = pthread_join(p->tid, ppOut) ? SQLITE_ERROR : SQLITE_OK;
          ^~~~~~~~~~~~
          pthreadMutexEnd

**Comment by rittneje** [comment]
What version of Go and what version of gcc are you using? Can you also post the output of `go env`?

**Comment by sangshuduo** [comment]
$ go version
go version go1.14 linux/amd64


$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build315568983=/tmp/go-build -gno-record-gcc-switches"

**Comment by sangshuduo** [comment]
I doubt it's an issue of multipass 1.0. After I upgrade to multipass 1.1.0, the go build works good.
