### ISSUE TITLE
vtable CreateModule hook is missing

### ISSUE THREAD

**Issue by kirubasankars** [mattn/go-sqlite3#799]
```go 
package main

import (
	"database/sql"

	sqlite3 "github.com/mattn/go-sqlite3"
)

func main() {
	sql.Register("sqlite3_with_extensions", &sqlite3.SQLiteDriver{
		ConnectHook: func(conn *sqlite3.SQLiteConn) error {
			return conn.CreateModule("github", nil)
		},
	})
}
```

Build output.

./main.go:12:15: conn.CreateModule undefined (type *sqlite3.SQLiteConn has no fi
eld or method CreateModule)

When I run go test in go-sqlite3

$ go test --run TestCreateModule
**testing: warning: no tests to run**
PASS
ok      github.com/mattn/go-sqlite3     0.312s

**Comment by rittneje** [comment]
https://github.com/mattn/go-sqlite3/blob/4d8693d6ee0f25c2cfa598aeda2d9c2a5d11f8eb/sqlite3_opt_vtable.go#L6
You must build with either `-tags "sqlite_vtable"` or `-tags "vtable"`.
