### ISSUE TITLE
can`t close

### ISSUE THREAD

**Issue by meimz** [mattn/go-sqlite3#820]
like this can`t close the databsae , 

![image](https://user-images.githubusercontent.com/14367223/83852605-9f46fb80-a746-11ea-94d6-dea96ea67c70.png)

but this can

![image](https://user-images.githubusercontent.com/14367223/83852575-95bd9380-a746-11ea-8e9e-95b6c3f4df9c.png)

**Comment by mattn** [comment]
What is your problem? Please explain more description.

**Comment by meimz** [comment]
> What is your problem? Please explain more description.

like above pictures

not use for rows.Next(){}  picture one Memory is not released

**Comment by mattn** [comment]
Do you mean it is memory leak? How to check it? Please provide minimal code to reproduce.

**Comment by meimz** [comment]
sorry It‘s my fault ,not your's.
