### ISSUE TITLE
How to compile go-sqlite3 in win7 x64 use arm-none-linux-gnueabihf-gcc for arm linux?

### ISSUE THREAD

**Issue by xzzh999** [mattn/go-sqlite3#834]
Hi~ 
nice work~

when i compile go-sqlite3 for the target arm linux on win7, i failed the building when use goland.
the env is ```CC=arm-none-linux-gnueabihf-gcc;GOOS=linux;GOARCH=arm;CGO_ENABLED=1```

i download the gcc from [this page](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads), and use ```gcc-arm-9.2-2019.12-mingw-w64-i686-arm-none-linux-gnueabihf.tar.xz```

the errors:
```
# runtime/cgo
collect2.exe: fatal error: CreateProcess: No such file or directory
compilation terminated.
```
and i tried restart goland, it failed the same.

need u help, thanks~

**Comment by xzzh999** [comment]
finally i build it ok by follow steps:

```
1.  go to https://www.linaro.org/downloads/ to download arm-linux-gnueabihf, and select
     gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf.tar.xz

2.  set env to: 
     CC=arm-linux-gnueabihf-gcc;CXX=arm-linux-gnueabihf-g++;CGO_ENABLED=1;GOOS=linux;GOARCH=arm;GOARM=7

3. set go buld argments:
     -ldflags="-extldflags=-static"
```

**Comment by xzzh999** [comment]
relate: 
#242
#504

**Comment by reski-rukmantiyo** [comment]
> finally i build it ok by follow steps:
> 
> ```
> 1.  go to https://www.linaro.org/downloads/ to download arm-linux-gnueabihf, and select
>      gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf.tar.xz
> 
> 2.  set env to: 
>      CC=arm-linux-gnueabihf-gcc;CXX=arm-linux-gnueabihf-g++;CGO_ENABLED=1;GOOS=linux;GOARCH=arm;GOARM=7
> 
> 3. set go buld argments:
>      -ldflags="-extldflags=-static"
> ```

hi @xzzh999 , just wondering is it also aplicable for linux as well? i'm using ubuntu 18.04 . Thanks

**Comment by xzzh999** [comment]
@reski-rukmantiyo u just need the right cross gcc, it should works.
