### ISSUE TITLE
[usage] How to get last row id?

### ISSUE THREAD

**Issue by hoangtuan151** [mattn/go-sqlite3#837]
Hi team,
Thanks for your work.

Currently, I'm using `prepare statement` to run the SQL insert command (my table have an ID column which is `AUTOINCREMENT PRIMARY KEY`. I've searched this github repos but could not find out the way to get the last row inserted's ID.

Pls help me. Thanks in advanced!

**Comment by rittneje** [comment]
Use the `Result.LastInsertRowId` method. https://golang.org/pkg/database/sql/#Result

```go
result, err := stmt.Exec(...)
if err != nil {
    return 0, err
}

return result.LastInsertRowId()
```

**Comment by hoangtuan151** [comment]
It does not seem work, here's screenshot:

![Screenshot from 2020-08-01 11-45-50](https://user-images.githubusercontent.com/17728615/89094307-bf183a00-d3ec-11ea-96b7-dde782f8ec52.png)

**Comment by rittneje** [comment]
Sorry, I mistyped. It's `LastInsertId` not `LastInsertRowId`.
