### ISSUE TITLE
Eponymous-only virtual tables

### ISSUE THREAD

**Issue by anacrolix** [mattn/go-sqlite3#846]
Does this package support [eponymous-only virtual tables](https://sqlite.org/vtab.html#eponymous_only_virtual_tables)? I see some vtable related files that have the sqlite_vtable and vtable build tags, but I can't tell if they would allow a NULL xCreate.

**Comment by mattn** [comment]
Did you try to build with `-tags sqlite_vtable` ?

**Comment by rittneje** [comment]
It doesn't support them. This repo hard-codes `xCreate` to a function that ultimately calls the `Create` method on the `Module` interface implementation. Consequently, there is no mechanism at present to cause it to be `null`.

https://github.com/mattn/go-sqlite3/blob/6a8b30186d28277f09a0ba6df3d3fa3859c5c499/sqlite3_opt_vtable.go#L202-L227

**Comment by anacrolix** [comment]
Thank you @rittneje

**Comment by patrickdevivo** [comment]
Thank you @rittneje for providing context, coming across this issue when searching around for `eponymous virtual table` in this library and this is very helpful. Based on the current implementation, do you think it would be possible to implement a means of passing a `null` as the `xCreate` method? Unfortunately, I don't have much experience with c/cgo, but would love to experiment (ideally with some guidance!) to try adding support for eponymous virtual tables in this package. The current virtual table implementation is really cool and has been doing quite a bit of heavy lifting in [a project](https://github.com/augmentable-dev/askgit) I've been building!

**Comment by rittneje** [comment]
One option I can think of is to add an optional interface. Something like:
```go
type EponymousOnlyModule interface {
    Module
    EponymousOnlyModule()
}
```
Then you could say that if the module implements `EponymousOnlyModule()`, then `xCreate` should be `null` and the `Create` method is ignored. Regular modules will not define the `EponymousOnlyModule()` method at all.

In terms of the `sqlite3_module` object, the simplest approach is to copy the `goModule` object (except set `xCreate` to `null`), and then choose one or the other in `CreateModule`. Another approach would be to dynamically create the `sqlite3_module` object in `CreateModule`, but I am not currently certain of the rules surrounding freeing that memory.

**Comment by patrickdevivo** [comment]
@rittneje FYI #885 attempts to implement what you suggested above - would love any feedback if you're available! Thanks again for the help!
