### ISSUE TITLE
ErrNoRows

### ISSUE THREAD

**Issue by hyprnick** [mattn/go-sqlite3#853]
Is `sql.ErrNoRows` implemented?  When I query an empty table, I don't get any rows back but also the `err` is still nil.  

```golang
package main

import (
	"database/sql"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSqlite(t *testing.T) {
	db, err := sql.Open("sqlite3", "file:test.db?mode=memory")
	if err != nil {
		panic(err)
	}
	defer db.Close()
	db.SetMaxOpenConns(1)

	_, err = db.Exec("create table test (id primary key)")
	assert.Nil(t, err)

	_, err = db.Query("select id from test")
	assert.NotNil(t, err)
	assert.Equal(t, sql.ErrNoRows, err)
}
```

**Comment by rittneje** [comment]
`sql.ErrNoRows` is returned by the database/sql package (not the underlying driver) when you use `QueryRow` and there isn't at least one result row. However, when you use `Query`, the `sql.Rows` object it returns will not return any errors, but rather will return `false` from `Next()` the first time you call it.

**Comment by hyprnick** [comment]
Ok, thanks for the explanation.  I'll use it that way.
