### ISSUE TITLE
read from sql file

### ISSUE THREAD

**Issue by hajsf** [mattn/go-sqlite3#857]
Is there a built in way to read sql statement from a stand alone `.sql` file, or I've to read it as a text then execute it in my statement?

**Comment by rittneje** [comment]
I don't think so, but you should be able to do something like this:

```go
db, err := sql.Open(...)
if err != nil {
    ...
}

...

b, err := ioutil.ReadFile("path/to/file.sql")
if err != nil {
    ...
}

if _, err := db.Exec(string(b)); err != nil {
    ...
}

...
```

**Comment by hajsf** [comment]
Thanks, with `// go embed` https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/ I can secure the SQL statement in a file, and call it as you mentioned.
