### ISSUE TITLE
Compile with go-sqlite3 but NOT system-supplied sqlite3? (E.g. hand-compiled sqlite3.o instead?)

### ISSUE THREAD

**Issue by doublemeat** [mattn/go-sqlite3#858]
Is it possible to make go-sqlite3 use a hand-compiled sqlite3.o (or .so|.dll) in the project directory, rather than the system-installed version?

I've been banging my head against the wall for days, trial and error (so far nothing but error), and my google fingers are getting RSI. Figured it's time to just ask.

But...why? Because I'm writing some personal utilities that I'll need for at least a couple of decades if not longer. It may need to be maintainable for maybe 5-10 years.

(*Sure, getting the right older version of Go for maintenance, in the future, will itself be a challenge. But there are no other dependencies besides sqlite3, and just that one requirement - an older version of Go - seems manageable. Keeping a virtual machine image on-hand with the correct older versions of the whole toolchain and lib versions of stuff could work in theory, but in practice, just worrying about the go version seems more manageable - even if that means firing up an ancient Linux distro live CD, someday in the future.*)

(*Oh also, I realize that this long-running need might seem impossible to predict. But it's based on the fact that I'm still using a similar family of utilities I wrote in Visual Basic decades ago, now having to resort to running them under tweaked Wine prefixes, and refactoring the output. They need to be, ahem, updated.*)

This is the whole reason I'm even considering Go, which will require learning a new language. Well that and also the elegant cross-platform-ness. (And is vastly preferable to re-learning C or C++, which to me would be a squandered substantial investment in time! I don't care to ever again use C or C++ as long as I live. Go, as a language, has high value well beyond learning it just for this narrow requirement. I love C# (dotnet core), but its runtime dependencies [or ginormous binary size], and inability to statically link dependencies, make it a non-starter for this odd requirement.)

I've tried various combinations of --ldflags, CGO_LDFLAGS, CGO_ENABLED, import "C"-related psuedo-headers, etc.

It finally dawned on me that this particular community might easily know the exact answer, or immediately that it's not possible.

Thanks!

**Comment by doublemeat** [comment]
Oh - I also tried renaming sqlite3.o to sqlite3.syso, with and without some other combinations. Part of the problem is I'm *so* new to Go, I don't yet really know what I'm doing, and can't even yet conceptualize much of a systematic approach to the trial and error.

**Comment by rittneje** [comment]
By default this library statically links against the C files included in the repo. https://github.com/mattn/go-sqlite3/blob/master/sqlite3-binding.c

I'm not entirely sure from your description whether this is acceptable for what you need to do. Are you encountering some issue or compilation failure? Or are you just trying to understand how this library works (and by extension how the Go compiler integrates with C libraries)?

**Comment by doublemeat** [comment]
@rittneje I could have been more concise. I suppose part of the length was a proactive defense of the perceived inevitable comments of "why do you want to do it the nonstandard way" (i.e. not build with system-installed sqlite3).

I'm trying to get my application to build (and statically link) with *my own* copy of sqlite3 (either amalgamation source code, .o object binary, or .so library binary) - and specifically NOT the system-installed version (through apt-get). I need to do this:

1. To rebuild sqlite3 with the compile-time options I need - including `SQLITE_OMIT_LOAD_EXTENSION` [aka `--tags "sqlite_omit_load_extension"`?], to avoid the build errors involving "dlopen", which my system-installed version was not compiled with.

1. To further promote decades-long maintainability for this specific project, where all I need to worry about in the future is the appropriate [old] version of go (and possibly an older version of Linux that might be needed for that).

**Comment by rittneje** [comment]
That file is the SQLite amalgamation, modified slightly so it plays nicely with how this repo compiles. By default this library will statically compile against that C file, not the system shared library.

To compile against the system library, you pass `-tags libsqlite3` to the Go compiler. If you instead want it to link against your custom version, I _think_ you would want to:
1. compile your SQLite as a static library (i.e., libsqlite3.a)
2. set `LIBRARY_PATH` to the absolute directory containing the library
3. set `CPATH` to the absolute directory containing your sqlite3.h file
3. compile your go program with `-tags libsqlite3`

I've never tried doing this, so I can't guarantee it'll work.

**Comment by doublemeat** [comment]
> That file is the SQLite amalgamation, modified slightly so it plays nicely with how this repo compiles. By default this library will statically compile against that C file, not the system shared library.

Perfect! That's exactly what I want and have been trying to accomplish. (How ironic. And pleasantly surprising!)

> To compile against the system library, you pass `-tags libsqlite3` to the Go compiler.

Oh that's good to know. Without that tidbit I would have assumed I just needed that tag anyway.

> If you instead want it to link against your custom version, I _think_ you would want to:

Good to know to for future reference.

Can't thank you enough!
