### ISSUE TITLE
ExecContext ignores cancels on busy database

### ISSUE THREAD

**Issue by gilbsgilbs** [mattn/go-sqlite3#863]
Hi!

I noticed that if you call `ExecContext` on a busy database and then cancel the context, the execution still hangs until `busy_timeout` is reached. Here is a repoduction:

```go
// open a DB with a busy timeout of 10 seconds
db, err := sql.Open("sqlite3", "file:db.sqlite?mode=rwc&_busy_timeout=10000")
if err != nil {
	panic(err)
}

// Create a dummy table
if _, err = db.Exec("create table if not exists foo (id integer primary key)"); err != nil {
	panic(err)
}

// Start a new transaction and write things to lock the DB
tx, err := db.Begin()
if err != nil {
	panic(err)
}
defer tx.Rollback()
if _, err = tx.Exec("insert into foo (id) values (0)"); err != nil {
	panic(err)
}

// Create a context that'll automatically cancel in 50 milliseconds
ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(50 * time.Millisecond))
defer cancel()

// This hangs 10 seconds, ignoring the deadline
_, err = db.ExecContext(ctx, "insert into foo (id) values (0);")
```

Is this intended and tight to the way the C library works internally? From a user's perspective, this looks like a bug and is not consistent with the behavior of other database drivers.

What hangs is [this channel listen](https://github.com/mattn/go-sqlite3/blob/92f580b350d88e068bfbe223ea51f64044c0f280/sqlite3.go#L1953) which is blocked because [this call to _sqlite3_step_row_internal](https://github.com/mattn/go-sqlite3/blob/92f580b350d88e068bfbe223ea51f64044c0f280/sqlite3.go#L1970) cancels.

**Comment by itizir** [comment]
That's an interesting one! I've tried to dig a little into it, and the conclusions I reached are probably not what you wanted to hear (unless I missed something and someone corrects me)...

The tl;dr is:
1. it's up to the client to try and avoid locking up the table with silly transactions
2. it's up to the client to wrap the sql calls in some async logic if they need the application to never block beyond context cancellation

What's blocking is indeed SQLite itself, in `sqlite3_step`, and calling `sqlite3_interrupt` doesn't have an immediate effect. [This thread is an interesting read](http://sqlite.1065341.n5.nabble.com/Using-sqlite3-interrupt-with-a-timeout-td105257.html). So as you said it's down to the internal workings of the C code.

You may want the go driver to take care of 2. above for you, but it probably shouldn't: giving up on waiting for the sqlite call to end means you can't tell whether it indeed got cancelled or if it actually ran, and you're leaking a goroutine until it's completed. If these things are OK for whatever application you have, you can always add the asynchronicity yourself, but it seems reasonable to me that this is not the default behaviour.

**Comment by gilbsgilbs** [comment]
Hi! Thanks for looking into it. My investigations led me to the same conclusions as you so I'm not surprised. IMHO, I'd say SQLite is at fault here either for not interrupting the step or for not providing a proper API to interrupt the step. I agree that this driver shouldn't try to circumvent SQLite's API (unless we're both missing an easy solution that doesn't involve leaking threads).

As there don't seem to be a good solution yet, let's just close this as wontfix. Thanks again :+1: .
