### ISSUE TITLE
Unable to query dbstat using go-sqlite3

### ISSUE THREAD

**Issue by deka108** [mattn/go-sqlite3#886]
Hi,

I am using macOS, and have installed `sqlite3` using `brew` and have the dbstat virtual table enabled. I wanted to get the size information on my tables.

If I'm using the installed sqlite3, I was able to run the following query to get the statistics of the tables I wanted to know in the db by querying the dbstat table.
```sql
SELECT * FROM dbstat WHERE name = '[table_name]';
```
Since I was able to run the above query successfully in the sqlite3 cons, I assume that the `SQLITE_ENABLE_DBSTAT_VTAB` flag was set during sqlite3 installation.

However, I am unable to run the above query in go.
```go
db, err := sql.Open("sqlite3", dbPath)
if err != nil {
	log.Fatal().Err(err)
}
defer db.Close()

query := fmt.Sprintf("SELECT * FROM dbstat WHERE name = '%s';", tableName)

rows, err := db.Query(query)
if err != nil {
	log.Fatal().Err(err)
}
``` 
From the code above, rows will be nil, hence we are not able to query dbstat in go.

My questions are:
1. How do I enable and access dbstat using go-sqlite3?
2. How do I get the metadata information about the rows / columns' memory size in sqlite?

Thank you so much.

**Comment by rittneje** [comment]
By default, this library statically compiles SQLite, so it is not using the same installation as the command line tool. Currently, this library does not set `SQLITE_ENABLE_DBSTAT_VTAB`. To do so, you would need to add a sqlite3_opt_dbstat_vtab.go file that sets the option. Note that these files have Go build tags.

```go
// +build sqlite_dbstat_vtab

package sqlite3

/*
#cgo CFLAGS: -DSQLITE_ENABLE_DBSTAT_VTAB=1
#cgo LDFLAGS: -lm
*/
import "C"
```

Once that change is made, you then just pass the `sqlite_dbstat_vtab` build tag to the Go compiler. Also be sure to add the new tag to both `'Tags: full'` cases in .github/workflows/go.yaml so the merge gate properly exercises the new file.
