### ISSUE TITLE
How to upgrade the inner sqlite version? 3.25.2 have some security bug.

### ISSUE THREAD

**Issue by maxpaynebupt** [mattn/go-sqlite3#890]
How to upgrade the inner sqlite version? 3.25.2 have some security bug.

**Comment by arp242** [comment]
This library ships with SQLite 3.33.0; so update the go-sqlite3 version to get SQLite 3.33.0.

You can't update it otherwise, unless you fork it.

**Comment by rittneje** [comment]
This library is now using SQLite 3.39.4. If a different version is desired, the only options at present are to fork, or to use the libsqlite3 build tag to link against another version.
