### ISSUE TITLE
Errors in virtual table cursor methods don't seem to be handled

### ISSUE THREAD

**Issue by patrickdevivo** [mattn/go-sqlite3#902]
This is something I've noticed, though haven't been able to fully understand the cause of - errors returned from functions in the `VTabCursor` interface ([here](https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_vtable.go#L661)) don't seem to be handled/emitted. I notice these methods commonly use something that looks like this:

```c
if (pzErr) {
  return setErrMsg(pCursor, pzErr);
}
```

when handling the go error, as opposed to methods of the [`VTab` interface](https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_vtable.go#L639)

This can be reproduced by adding an early:

```go
return ErrAbort
```

in this `BestIndex` [implementation](https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_vtable_test.go#L69) in the tests, and seeing them fail with an error from the virtual table.

However, adding the same early error return to a function on the cursor, such [as here](https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_vtable_test.go#L105), the tests pass fine.

Maybe it's an issue with how SQLite handles errors from vtab cursors? Though the [documentation here](https://sqlite.org/vtab.html) does make mention of returning SQLite error codes in the cursor implementation functions.

If someone has an idea or is able to point me in the right direction I'd be happy to start a PR!

**Comment by rittneje** [comment]
@patrickdevivo Can you post a minimal reproduction of the issue, including your implementation of `VTabCursor`, etc. and your test code?

**Comment by patrickdevivo** [comment]
hi @rittneje sure, I've put together this repo: https://github.com/patrickdevivo/vtab-cursor-errs which has also helped me confirm some behavior. The vtab implementation there is essentially a copy+paste of what's in one of the tests of this repository. 

I've added [this line](https://github.com/patrickdevivo/vtab-cursor-errs/blob/master/vtab.go#L83), which returns an error from the `Next()` function of the cursor interface. I've noticed that doing so does stop execution of the query, however does not "fail" the query in a way that would be expected for a go user (at least to me).

It appears there's no great way of knowing if an error occurred (and the cursor was prematurely stopped) or not. Does this make sense? If not, happy to try to make my example clearer.

**Comment by rittneje** [comment]
An error from `VTabCursor.Next()` is "caught" by `rows.Next()`, not `rows.Scan()`. Consequently, you need to call [`rows.Err()`](https://golang.org/pkg/database/sql/#Rows.Err) to see it. (Note that you should always call `rows.Err()` after your `rows.Next()` loop, not just when using virtual tables.)

**Comment by patrickdevivo** [comment]
@rittneje I see! thanks so much for that! Confirmed that the "silly error" does indeed get returned by a call to `rows.Err()`. I should probably read the go sql docs more closely!

Thanks for your help and confirmation
