### ISSUE TITLE
warning: ignoring #pragma GCC diagnostic

### ISSUE THREAD

**Issue by Skeeve** [mattn/go-sqlite3#907]
When trying to cross-compile for a pocketbook in a ubuntu docker image using go 1.14.7 or 1.15.6, I get

```text
# runtime/cgo
cc1: warnings being treated as errors
_cgo_export.c:6: warning: ignoring #pragma GCC diagnostic
_cgo_export.c:7: warning: ignoring #pragma GCC diagnostic
_cgo_export.c:8: warning: ignoring #pragma GCC diagnostic
```

I'm using https://github.com/Skeeve/inkview/tree/feature/upgrade_go_1.15.6

The environment when starting `go get github.com/mattn/go-sqlite3` is

```bash
PWD=/app
GOARCH=arm
GOARM=5
HOME=/root
GOROOT=/go
PATH=/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CC=arm-none-linux-gnueabi-gcc
CGO_ENABLED=1
GOOS=linux
GOPATH=/gopath
```

When using go 1.9 (https://github.com/dennwc/inkview) go-sqlite seemed to compile correct and I could run the example program.

I'm a complete newbie in regards to (cross-)compiling and go. Maybe someone can give me a hint what I'm messing up?

**Comment by rittneje** [comment]
What version of arm-none-linux-gnueabi-gcc are you using?

**Comment by Skeeve** [comment]
```bash
root@59071c37656e:/app# arm-none-linux-gnueabi-gcc -v
Reading specs from /usr/bin/../lib/gcc/arm-none-linux-gnueabi/4.1.2/specs
Target: arm-none-linux-gnueabi
Configured with: /usr/src/redhat/BUILD/cross-mlib/source/gcc-4.1.2/configure --target=arm-none-linux-gnueabi --host=i686-host_pc-linux-gnu --prefix=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi --with-sysroot=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/arm-none-linux-gnueabi/sysroot --enable-threads --enable-shared --disable-libssp --disable-libgomp --disable-libmudflap --enable-languages=c,c++ --enable-__cxa_atexit --disable-nls
Thread model: posix
gcc version 4.1.2
```

**Comment by rittneje** [comment]
While not officially documented anywhere as far as I can tell, starting with Go 1.12, you need at least gcc 4.6 in order to successfully compile with cgo. (This restriction comes from the Go compiler itself, not this library.) Are you able to use a newer gcc?

**Comment by Skeeve** [comment]
If only I knew how to do that. :(

But thanks for the hint. I will search.

**Comment by Skeeve** [comment]
Thanks @rittneje. Your hint helped me solve the issue.
