### ISSUE TITLE
attach database on memory fail

### ISSUE THREAD

**Issue by enzofoucaud** [mattn/go-sqlite3#916]
hello I had this following error --> no such table: devices when I want to open my existing db in memory mode

 ```
func memoryDB() {
	log.Println("Memory DB")
	sqliteDatabase, _ := sql.Open("sqlite3", "file:metric.db?mode=memory") // Open db
	displayDevices(sqliteDatabase)                                         // See table
	sqliteDatabase.Close()                                                 // Close db
}
```

I see people write "file:metric.db?mode=memory&cache=shared&mode=rwc" however I find it not logical ^^

**Comment by itizir** [comment]
Have a look at the last paragraph of https://www.sqlite.org/sharedcache.html

Your example doesn't really show why you're having the problem, but presumably your code does does some concurrent transactions and so multiple connections are established, each of which will see a separate database unless you set the cache to be shared.

`file:metric.db?mode=memory&cache=shared&mode=rwc`: what looks wrong there is that `mode` is _also_ set to `rwc`.

**Comment by rittneje** [comment]
@enzofoucaud It's a little unclear to me what you are trying to do. Is metrics.db an actual database file on your machine?

**Comment by enzofoucaud** [comment]
I expressed myself very poorly on the error I had, moreover my english is really not good ..

@itizir I'm agree with you for ```file:metric.db?mode=memory&cache=shared&mode=rwc``` he declare in first memory mode but after he declare the rwc mode .. ^^

@rittneje yes it's my actual database and I want to push it in memory mode ! However when I try to do this I can't display the display table because memory mode don't take my db file ..

**Comment by itizir** [comment]
@rittneje was right to ask then: it seems like you're confused about what the `memory` mode is and does. An in-memory database is a database that resides in memory and is not backed by a file on your filesystem; here is the relevant documentation: https://www.sqlite.org/inmemorydb.html. Hopefully this will clear things up!

**Comment by enzofoucaud** [comment]
@itizir No no I understood correctly! I solved my problem differently suddenly!
I used the backups to have the destination (metrics.db) in my source (:memory:) :)

**Comment by itizir** [comment]
Hahah, well now I'm even more confused: not sure I understood what you mean by 'destination in your source', but it doesn't matter if your problem is solved. Glad to hear things are working!

**Comment by rittneje** [comment]
@itizir I think he meant he used the backup API to copy the physical database (source) to an in-memory database (destination).
https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteConn.Backup
https://www.sqlite.org/backup.html

**Comment by itizir** [comment]
Ooh that's interesting, thanks @rittneje!

**Comment by enzofoucaud** [comment]
@rittneje yes !
@itizir yes my english is very very bad,

little snippet code with backup 👍 
```
        // 1 - Initializing the Hook
	var driverName = fmt.Sprintf("sqlite3_%v", time.Now().UnixNano())
	driverConns := []*sqlite3.SQLiteConn{}
	sql.Register(driverName, &sqlite3.SQLiteDriver{
		ConnectHook: func(conn *sqlite3.SQLiteConn) error {
			driverConns = append(driverConns, conn)
			return nil
		},
	})
	// 2 - Open flash memory
	flash, err := sql.Open(driverName, "flash.db") // Open db
	if err != nil {
		return
	}
	flash.Ping()
	createTable(flash)
	srcDbDriverConn := driverConns[0]
	if srcDbDriverConn == nil {
		log.Fatal("The source database driver connection is nil.")
	}
	// 3 - Open in memory
	memory, _ = sql.Open(driverName, ":memory:") // Open db
	memory.Ping()
	destDbDriverConn := driverConns[1]
	if destDbDriverConn == nil {
		log.Fatal("The destination database driver connection is nil.")
	}
	// 4 - Memory Backup
	// Check the driver connections.
	if len(driverConns) != 2 {
		log.Fatalf("Expected 2 driver connections, but found %v.", len(driverConns))
	}
	// Prepare to perform the backup.
	backup, err := destDbDriverConn.Backup("main", srcDbDriverConn, "main")
	if err != nil {
		log.Fatal("Failed to initialize the backup:", err)
	}
	// Test the copying of all remaining pages.
	isDone, err := backup.Step(-1)
	if err != nil {
		log.Fatal("Failed to perform a backup step:", err)
	}
	if !isDone {
		log.Fatal("Backup is unexpectedly not done.")
	}
```
