### ISSUE TITLE
Addition of sqlite3_column_table_name breaks dynamic linking

### ISSUE THREAD

**Issue by stgraber** [mattn/go-sqlite3#917]
The change introduced in #900 will break the build on all systems using `-tags libsqlite3` where the particular sqlite3 build on the system doesn't happen to have been built with the optional feature.

This just broke all our builds (LXD). A workaround is to rebuild libsqlite3 to pass `CFLAGS=DSQLITE_ENABLE_COLUMN_METADATA=1` but I doubt that this will be an option for all users on all Linux distributions...

**Comment by stgraber** [comment]
@otoolep

**Comment by otoolep** [comment]
Suggest #900 should be rolled back.

**Comment by otoolep** [comment]
I see the other PR #918, thanks for that.
