### ISSUE TITLE
Despite setting admin username password, db is fully accessible without auth

### ISSUE THREAD

**Issue by bootstrapsp** [mattn/go-sqlite3#922]
**Current scenario** : 
Env: go version go1.15.7 darwin/amd64
Go-sqlite3: 1.14

**Code** :  
`
func (s SQLDB) DbProvider(storePath string) *sql.DB {
	AUTHUSER = "admin"
	AUTHPASS=  "admin"
	AUTHPASSENCODING = "sha256"

	file := fmt.Sprintf("%s", storePath+"/"+DBName)

	dbClient, err := sql.Open("sqlite3", "file:"+file+"?_auth&_auth_user="+AUTHUSER+"&_auth_pass="+AUTHPASS+"&_auth_crypt="+AUTHPASSENCODING)
	if err != nil {
		log.Fatalln(err)
		return nil
	} else {
		return dbClient
	}

}`

**Behaviour expected:**
When using external tools like IDE, CLI db should require login password to open it

**Actual Behaviour**:
DB can be opened without any auth - i am using IDE like Goland, and I can simply open the db by providing the path and the file
When i check the users table i can see the user and encoded password is there. so not sure what's going on 

Is it a wrong expectation that by giving admin username password it is not protecting the db?

**Comment by itizir** [comment]
> Is it a wrong expectation that by giving admin username password it is not protecting the db?

Indeed the user auth extension is probably not doing what you think it's doing. Have a look at the docs: https://www.sqlite.org/src/doc/trunk/ext/userauth/user-auth.txt

In particular
```
The sqlite_user table is inaccessible (unreadable and unwriteable) to
non-admin users and is read-only for admin users.  However, if the same
database file is opened by a version of SQLite that omits
the -DSQLITE_USER_AUTHENTICATION compile-time option, then the sqlite_user
table will be readable by anybody and writeable by anybody if
the "PRAGMA writable_schema=ON" statement is run first.
```

**Comment by bootstrapsp** [comment]
thanks @itizir, for sharing this. I guess I have more questions than answers now, specifically this mechanism can't be used to protect the db - is there still any other way this can be achieved without having to go through the encryption of complete db?

**Comment by rittneje** [comment]
@bootstrapsp Can you expand upon what specifically you are trying to do? With SQLite, the database is just a file that can be opened with any utility (e.g., `cat`), so attempting to protect it generally makes little sense.

**Comment by bootstrapsp** [comment]
Something like sqlite fully managed from the code is quite handy to deliver like a small little encrypted or protected wallet feature - where I don't have to burden the end user with db setup etc. But i see where you're going with this.

**Comment by rittneje** [comment]
For that you probably want to encrypt with SEE. https://www.sqlite.org/see/doc/release/www/index.wiki At that point the userauth extension would provide no additional value.

Unfortunately I don't believe this library currently supports SEE.

**Comment by bootstrapsp** [comment]
Thanks for the hints @rittneje -  i think i am gonna switch to something like badgerdb seems reasonably straight forward to setup along with encryption. Appreciate the help.
