### ISSUE TITLE
Upgrade built-in SQLite version to 3.35.0 to support ALTER TABLE DROP COLUMN

### ISSUE THREAD

**Issue by c9845** [mattn/go-sqlite3#927]
SQLite update 3.35.0 (2021-03-12) supports the `ALTER TABLE DROP COLUMN` query.  See links for info below.  This is a pretty huge change in SQLite behavior and brings it inline with other SQL engines.

https://sqlite.org/changes.html
https://sqlite.org/lang_altertable.html#altertabdropcol

**Comment by otoolep** [comment]
https://github.com/mattn/go-sqlite3/pull/926

**Comment by tobbe303** [comment]
Version 3.35.5 fixes a database corruption defect related to the newly added ALTER TABLE DROP COLUMN support.

https://sqlite.org/releaselog/3_35_5.html

It would be excellent to have this version supported by go-sqlite3.

Thanks!

**Comment by TsvetkovP** [comment]
Has this problem been fixed? @mattn 
Thank you in advance for the answer!

**Comment by c9845** [comment]
Yes.
