### ISSUE TITLE
closing

### ISSUE THREAD

**Issue by bh321** [mattn/go-sqlite3#937]
I observe the memory accounting, please tell me if I have placed all the closings correctly?

```
db, err := sql.Open("sqlite3", "./b.db")
			if err != nil {
				panic(err)
			}
			defer db.Close()

			rows, err := db.Query("select * loot table where ID > $1", 0)
			if err != nil {
				panic(err)
			}
			defer rows.Close()

			loots := []loot{}

			for rows.Next() {

				f := loot{}
				err := rows.Scan(&f.1, &f.2, &f.3, &f.4)
				if err != nil {
					fmt.Println(err)
					continue
				}
				loots = append(loots, f)
			}

			for _, f := range loots {
				...
				}
			}
```

**Comment by rittneje** [comment]
Not sure what "memory accounting" is, but this looks fine. The only thing missing is checking `rows.Err()` after your `rows.Next()` loop.

Also, just FYI `$1` is actually declaring a parameter _named_ `1`. You might be looking for `?` or `?001`. https://www.sqlite.org/c3ref/bind_blob.html

**Comment by bh321** [comment]
the translator did not work well

memory leak
for some reason, memory goes somewhere

**Comment by rittneje** [comment]
Ah, okay. Can you provide further details on the leak? What tool are you using that detected the leak? What exactly did it say?

**Comment by bh321** [comment]
a day after launch, my program starts to take up about a gigabyte of RAM. thanks a lot for your help, I'll be checking the rest of the code. it started after using sqlite

**Comment by bh321** [comment]
filling the table and updating the table, is everything correct? in terms of closure or something can be improved?

```
db, err := sql.Open("sqlite3", "./b.db")
    if err != nil {
    panic(err)
    }
defer db.Close()
				
result, err := db.Exec("insert or ignore into table (ID, Name) values ($1, $2)", ID, Name)
    if err != nil {
    panic(err)
    }
fmt.Println(result.LastInsertId())
```

```
db, err := sql.Open("sqlite3", "./b.db")
    if err != nil {
    panic(err)
    }
defer db.Close()


result, err := db.Exec("update table set Name = $1 where ID = $2", Name, ID)
    if err != nil {
    panic(err)
    }
fmt.Println(result.LastInsertId())
```


for example, don't you need to do this?

```
db, err := sql.Open("sqlite3", "./b.db")
    if err != nil {
    panic(err)
    }
defer db.Close()


result, err := db.Exec("update table set Name = $1 where ID = $2", Name, ID)
    if err != nil {
    panic(err)
    }
fmt.Println(result.LastInsertId())
defer result.Close()  // <------------- new line
```

**Comment by rittneje** [comment]
No, there is no `result.Close()` method. The `result` object is basically just a DTO exposed via a few getter methods. There's nothing to clean up or release.

> a day after launch, my program starts to take up about a gigabyte of RAM.

Is the memory usage continuing to increase? Or is 1 GB the peak? What are you using to measure the memory usage of your program? Have you looked at the memory allocations with [pprof](https://golang.org/pkg/net/http/pprof/)?

**Comment by bh321** [comment]
but how to forcibly close the connection if the program is executed in an infinite loop

but at the end of the loop you need to close the connection?

**Comment by bh321** [comment]
I understand correctly, in the example it is necessary to act like this?

```
endless loop start <---

db, err := sql.Open("sqlite3", "./b.db")
    if err != nil {
    panic(err)
    }
defer db.Close()


result, err := db.Exec("update table set Name = $1 where ID = $2", Name, ID)
    if err != nil {
    panic(err)
    }
fmt.Println(result.LastInsertId())
return db.Close() <--- new line

end of endless loop <---
```

**Comment by rittneje** [comment]
It's not clear to me what your code is trying to do. Opening and closing the database repeatedly is going to come with some overhead. Also, defers only run when the _function_ exits, NOT between loop iterations. You probably should be doing this:
```go
db, err := sql.Open("sqlite3", "./b.db")
if err != nil {
    panic(err)
}
defer db.Close()

// infinite loop
for {
   // Any defers within doStuff will run when doStuff returns.
   doStuff(db)
}
```

**Comment by bh321** [comment]
Figured it out
thank you so much
