### ISSUE TITLE
native library and intarray

### ISSUE THREAD

**Issue by kroggen** [mattn/go-sqlite3#938]
How to link directly to the native `libsqlite3` if it does not have the `intarray` module?

Can we remove the dependency on the `intarray` module in some way? It appears to be only used on tests...

**Comment by rittneje** [comment]
Can you be more specific? Where is the intarray module being used? I tried to search in this repo but didn't find anything.

**Comment by kroggen** [comment]
Indeed, I guess it was a problem on my computer.

Sorry for that!
