### ISSUE TITLE
practical default extensions...

### ISSUE THREAD

**Issue by rbucker** [mattn/go-sqlite3#944]
Having the ability to load extensions is great... and I'm taking advantage of that. However, at this minute I'm porting the decimal extensions which is embedded in the shell.c file of the autoconf source. And frankly I'd prefer not to have to do that specially since I'm not familiar enough with the source of this project or sqlute. I just happen to have the tenacity to GSD as I need it... just not sure it's the ideal solution.

So after that I'm asking this team to adopt some or all of the extensions or at least something that gets us to the next level.

**Comment by rittneje** [comment]
What exactly are you asking for?

**Comment by rittneje** [comment]
You could argue that about any of the various SQLite extensions though. What is special about this particular one?

It seems like you should be able to use the decimal.c from source instead of extracting it from the generated CLI code. Does that help? https://sqlite.org/src/file?name=ext/misc/decimal.c&ci=tip

**Comment by rbucker** [comment]
I suppose anyone could argue that point. The reason for the request is because I build financial applications and without the extension or taking special care I continue to lose pennies (office space).

It so happens that I extracted the decimal extension and linked it in myself. However I will likely be chasing parity between my extension and this package having to make sure that the versions match etc.  It's a matter of practicality since the package author already updates the 'c' file from time to time it would makes sense that the embedded extensions were included.

It's been a rough week, I hope I was clear and friendly.  THANKS

**Comment by rittneje** [comment]
Ah, I found your [post](https://sqlite.org/forum/forumpost/b86f20c917) over on the SQLite forum. It seems a few people suggested that you store this as a integer number of cents (i.e., fixed-point) instead, in which case this extension would seem unnecessary. This would also be my recommendation.

> It so happens that I extracted the decimal extension and linked it in myself. However I will likely be chasing parity between my extension and this package having to make sure that the versions match etc. It's a matter of practicality since the package author already updates the 'c' file from time to time it would makes sense that the embedded extensions were included.

Can you explain what you mean by "parity" here? The SQLite maintainers are very big on backwards compatibility, meaning that the extension will be compatible with all future versions of SQLite 3.

**Comment by rbucker** [comment]
I do not completely disagree with the replies, however, That question was asked because converting to pennies from a text was not working properly or required some round() and other functions. And that's when someone recommended the decimal extension..I happen to do a great deal of ETL and in some cases I do not know the schema in advance or how some or all of the conditionals will be applied. For example letting the .import command create the schema all of he elements are text. Converting an amount to a different types of table scans... and storing the data as pennies means I need to divide by 100 to format the money and rick dividing 0 by 100 too... where *100 does not have an exception tied to it.

By parity I mean that the project devs import the 'c' file from SQLite... and the decimal.c is in there or in the same tree as the files they are importing. And so importing the decimal.c from the same rev as the sqlite.c is a good idea where as... including this package in my project and hoping that the decimal.c that I extracted will work or not expose a bug that wouldhave been prevented by importing the correct file(s).

**Comment by rbucker** [comment]
This project includes a sqlitre.c file from the sqlite project.  When that file was selected there was also a decimal.c file in the same project. Those two files have parity. If I go and select any decimal.c file and attempt to use it as an extension then I have the extra burden to make certain they are compatible and so there is potential to be out of parity. I have not looked but I suppose if there was a text file in this project that would link me to the version of sqlite that was included then I might have a chance to automate my build and retrieve the correct decimal.c.

Let me try this differently... in the features section of the project home page there is a list of included extensions. I'm not exactly certain where they come from but some of them are likely included in the sqlite source. So I'm asking to include the decimal.c and maybe the ICU.
