### ISSUE TITLE
search by 3 values

### ISSUE THREAD

**Issue by sifaaa** [mattn/go-sqlite3#945]
Please tell me.
But what if you want to find lines of 3 values?

For example,

result, err := db.Exec("delete from table1 where ID = $1 and ceID = $2 and deID = $3", 1, 10, 100)

**Comment by rittneje** [comment]
Can you elaborate on this? Are you facing some issue?

**Comment by sifaaa** [comment]
Yes
the matter is that the third parameter does not work
when I ask this line

result, err := db.Exec("delete from table1 where ID = $1 and ceID = $2 and deID = $3", 1, 10, 100)

then I get the results as if the line was like this

result, err := db.Exec("delete from table1 where ID = $1 and ceID = $2", 1, 10)

**Comment by rittneje** [comment]
I am not able to reproduce this issue. Can you share the entire schema of table1, as well as what all the rows are?

One thing I can say is that the proper way to do numbered parameters in SQLite is with `?` not `$`, as the latter actually creates three parameters _named_ `1`, `2`, and `3`. https://sqlite.org/lang_expr.html#parameters So your query should be:
```
result, err := db.Exec("delete from table1 where ID = ?001 and ceID = ?002 and deID = ?003", 1, 10, 100)
```
However, I do not believe this is the cause of the issue you are facing.

**Comment by sifaaa** [comment]
Thank you very much for your reply
I'll check again ...
If I see the problem again, I will pass on all the information for reproduction.
PS: writing in golang

**Comment by sifaaa** [comment]
works 🤦‍♂️
excuse me please and thank you 🙂
