### ISSUE TITLE
HELP: Query with like and placehold values does not work correctly

### ISSUE THREAD

**Issue by k8scat** [mattn/go-sqlite3#947]
I have a func follow:

```go
func ListUsers(page, pageSize int, name string) ([]*User, error) {
	sql := "select id, name from user where name like '%?%' and status=0 order by update_time desc limit ? offset ?;"
	rows, err := DB.Query(sql, name, pageSize, (page-1)*pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	users := make([]*User, 0)
	for rows.Next() {
		u := new(User)
		if err = rows.Scan(&u.ID, &u.Name); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, nil
}
```

I found `'%?%'` cannot work correctly, and if I use `'%explicit_name%'` rather than an arg `name`, it worked!!

So I am finding how to query with like and placehold values?

**Comment by rittneje** [comment]
SQLite does not support interpolating variables in the middle of strings like that. You will need to use string concatenation instead: `LIKE '%' || ? || '%'`.

**Comment by rittneje** [comment]
Why do you feel it wouldn't be safe?

**Comment by rittneje** [comment]
SQL injection is a concern if you are concatenating into the query string itself, not into the bound parameter values.

This is safe:
```go
db.Query("SELECT * FROM Foo WHERE Name LIKE ?", "%" + name + "%")
```

This is also safe:
```go
db.Query("SELECT * FROM Foo WHERE Name LIKE '%' || ? || '%'", name)
```

This is NOT safe:
```go
db.Query("SELECT * FROM Foo WHERE Name LIKE '%" + name + "%'")
```

There is, of course, the possibility that the `name` variable itself contains underscores and/or percent signs, in which case they will be interpreted in the usual way by `LIKE`. But (1) that isn't a SQL injection attack; and (2) that potential exists regardless of what you do as long as you are using the `LIKE` operator unless you add escape the variable.

**Comment by k8scat** [comment]
Alright, thanks! My problem has been solved and I will close this issue.
