### ISSUE TITLE
Is it compatible with gorm ?

### ISSUE THREAD

**Issue by oSethoum** [mattn/go-sqlite3#948]

**Comment by rittneje** [comment]
This library is what the gorm sqlite driver uses. https://github.com/go-gorm/sqlite/blob/master/sqlite.go#L8

**Comment by oSethoum** [comment]
@rittneje  the one gorm uses doesn't have encryption. tis why am asking.

**Comment by rittneje** [comment]
You didn't mention anything about encryption in your original question. No, this library does not currently support encryption.

Also, I think you may be confused. This library _is_ the one gorm is using.

**Comment by oSethoum** [comment]
@rittneje  thanks for clarifying ^^.
