### ISSUE TITLE
How to build in windows x64 and run on arm aarch64

### ISSUE THREAD

**Issue by qcwd** [mattn/go-sqlite3#956]
When I set CGO_ENABLED=0, it can run correctly but can not open db.
When I set CGO_ENABLED=1, there is an error
aarch64-linux-gnu-gcc:  error: unrecognized command line option '-marm'; did you mean '-fasm'?
My setting is:
GOARCH=arm;GOOS=linux;CGO_ENABLED=1;CC=D:\sdk\gcc-linaro-6.3.1-2017.05-i686-mingw32_aarch64-linux-gnu\bin\aarch64-linux-gnu-gcc;CXX=D:\sdk\gcc-linaro-6.3.1-2017.05-i686-mingw32_aarch64-linux-gnu\bin\aarch64-linux-gnu-g++

**Comment by rittneje** [comment]
GOARCH=arm is 32-bit ARM. Please try with GOARCH=arm64. If that does not work please post the output of running `go env` with all of your various environment variable set.

**Comment by qcwd** [comment]
> GOARCH=arm is 32-bit ARM. Please try with GOARCH=arm64. If that does not work please post the output of running `go env` with all of your various environment variable set.

Think you very much!!!   Setting GOARCH=arm64 solve my issue.
