### ISSUE TITLE
Feature request to add IPv4 extensions

### ISSUE THREAD

**Issue by kainsk** [mattn/go-sqlite3#961]
Would you please add extensions
IPv4 functions like this
https://github.com/mobigroup/sqlite3-inet

may be "answer" porting funcs like
https://github.com/mattn/go-sqlite3/blob/master/_example/custom_func/main.go

**Comment by rittneje** [comment]
@kainsk You can already load extensions by registering them with your driver.

```go
sql.Register("sqlite3-inet", &sqlite3.SQLiteDriver{
    Extensions: ["libsqliteipv4"],
})

...

db, err := sql.Open("sqlite3-inet", "...")
...
```
