### ISSUE TITLE
cannot find db file using sql.open

### ISSUE THREAD

**Issue by EmYiQing** [mattn/go-sqlite3#962]

**Comment by EmYiQing** [comment]
```go
import (
	"database/sql"
	_ "github.com/mattn/go-sqlite3"
)

database,err:=sql.Open("sqlite3","./test.db")
```
there is no error.
but I cannot find test.db.
use go 1.16.5 macos

**Comment by mattn** [comment]
sqlite3 does not generate database file if you did nothing.

**Comment by EmYiQing** [comment]
if i want to create db file if not exists,what can I do,thank you

**Comment by rittneje** [comment]
@EmYiQing `sql.Open` is lazy. It won't actually connect to the database until it has to, and it is at that point that SQLite will create the database if necessary. The general recommendation is to call `Ping` once to force it.

```go
db,err: =sql.Open("sqlite3", "./test.db")
if err != nil {
    ...
}
defer db.Close()

if err := db.Ping(); err != nil {
    ...
}

...
```

**Comment by EmYiQing** [comment]
@rittneje thank you very much,it works!
