### ISSUE TITLE
"Database or disk full" -- with in-memory database. Why?

### ISSUE THREAD

**Issue by otoolep** [mattn/go-sqlite3#969]
https://github.com/rqlite/rqlite/issues/861

Not strictly an issue with  mattn/go-sqlite3 but a user of rqlite 6.1 is getting this message back from the mattn/go-sqlite3. Clearly it's coming from SQLite. Any ideas what might be happening? It's an in-memory database, and much of the advice on the web assumes on-disk, which is not the case here.

**Comment by otoolep** [comment]
Original reporter closed https://github.com/rqlite/rqlite/issues/861, not sure why. So I'll close this issue, but I'm still curious if  anyone knows what this means in the context of an in-memory database.

Is the SQLite Forum a good place to ask questions? Might give that a try.

**Comment by rittneje** [comment]
Yes, I'd recommend asking in the forum. Unfortunately, this kind of issue is beyond my area of familiarity.
