### ISSUE TITLE
undefined: sql.NullTime

### ISSUE THREAD

**Issue by mingdavidqi** [mattn/go-sqlite3#983]
Got this error when run 

The command '/bin/sh -c boxr build centos boxr.json     && boxr dist centos boxr.json -v' returned a non-zero code: 1

# github.com/mattn/go-sqlite3
../depends/src/github.com/mattn/go-sqlite3/sqlite3_type.go:75:25: undefined: sql.NullTime

**Comment by rittneje** [comment]
Which version of Go are you using?

**Comment by mingdavidqi** [comment]
golang: 1.12.4

**Comment by rittneje** [comment]
sql.NullTime was introduced in Go 1.13. This library currently supports Go 1.15+.

**Comment by EnsPzr** [comment]
go version: 1.17
github.com/mattn/go-sqlite3@v1.14.10/sqlite3_type.go:75:25: undefined: sql.NullTime

**Comment by mattn** [comment]
@EnsPzr No one can help you without adding your something additional information.

What do you get with:
```
$ go env
``

**Comment by EnsPzr** [comment]
Sorry.

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/enes/Library/Caches/go-build"
GOENV="/Users/enes/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/enes/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/enes/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/enes/go/go1.17.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/enes/go/go1.17.2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/enes/go/src/github.com/enspzr/go-assigment/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_n/y_vg0cv56b503rbnkcbz7c_00000gn/T/go-build226806050=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by mattn** [comment]
Could you please try:
```
$ GOCC=clang go build
```

**Comment by rittneje** [comment]
@EnsPzr Can you provide more detail on how specifically you are compiling your application? If sql.NullTime to be undefined, that implies you are somehow using a very old Go version.
