### ISSUE TITLE
go drive inner db version is not same as installed db

### ISSUE THREAD

**Issue by JsToCode** [mattn/go-sqlite3#985]
I install SQLite with version 3.28.0, however when I use this driver to run `SELECT sqlite_version();`, a different version 3.36.0 returned.

**Comment by itizir** [comment]
By default this package compiles and embeds its own sqlite. If you want to link externally against your locally installed library you need to build with the `libsqlite3` tag.

**Comment by JsToCode** [comment]
I got it, thanks for your reply.
