### ISSUE TITLE
sqlite_step() is deferred, until Rows.Next() is called

### ISSUE THREAD

**Issue by glebarez** [mattn/go-sqlite3#987]
SQLiteStmt.query() https://github.com/mattn/go-sqlite3/blob/85436841b33e86c07dce0fa2e88c31a97c96a22f/sqlite3.go#L1916-L1932 simply creates Rows{} instance and doesn't actually execute sqlite_step, until Rows.Next() is called
this means that queries for which Rows.Next() is not called, will not be executed at all.
I suppose this is a bug.

Reproduction:
```go
package tests

import (
	"database/sql"
	"testing"

	_ "github.com/mattn/go-sqlite3"
)

func TestQueryBug(t *testing.T) {
	db, err := sql.Open("sqlite3", "test.db")
	if err != nil {
		t.Fatal(err)
	}

	_, err = db.Exec("drop table if exists t1")
	if err != nil {
		t.Fatal(err)
	}

	_, err = db.Exec("create table t1 (c1 integer);")
	if err != nil {
		t.Fatal(err)
	}

	_, err = db.Query("insert into t1 (c1) values (8) returning *")
	if err != nil {
		t.Fatal(err)
	}

	var val int
	row := db.QueryRow("select c1 from t1;")
	err = row.Scan(&val)
	if err != nil {
		t.Fatal(err)
	}
}
```
```console
--- FAIL: TestQueryBug (0.01s)
    /root/sqldev/tests/bug_test.go:35: sql: no rows in result set
```

Moreover, there's side effect of such implementation: when executing queries of multiple SQL statements, like
```
row := db.QueryRow("insert into t1 (c1) values (8);select c1 from t1;")
```
All but the last statements will not be executed, but just prepared and thrown away, see: https://github.com/mattn/go-sqlite3/blob/85436841b33e86c07dce0fa2e88c31a97c96a22f/sqlite3.go#L886

**Comment by rittneje** [comment]
This is not a bug. You are misusing the database/sql package. If you call `Query` then you are expected to iterated through the `Rows` until you reach the end.  For example:

```go
rows, err := db.Query(...)
if err != nil {
    ...
}
defer rows.Close()

for rows.Next() {
    if err := rows.Scan(...); err != nil {
        ...
    }
}

if err := rows.Err(); err != nil {
    ...
}
```

Also, if you call `QueryRow` then it means you are executing a single query (not multiple statements) and only want the first row of the results.
