### ISSUE TITLE
Support sqlite3_file_control() 

### ISSUE THREAD

**Issue by benbjohnson** [mattn/go-sqlite3#999]
Hi @mattn, thanks for the great library. I use it all the time.

I'm using `go-sqlite3` in my [Litestream](https://github.com/benbjohnson/litestream) project for SQLite replication and I've been doing a hack to persist the WAL file across restarts where I just don't call `Close()` on the database. Definitely hacky but it works. However, I recently learned there's `sqlite3_file_control()` opcode called [`SQLITE_FCNTL_PERSIST_WAL`](https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal) that does the same thing.

Is there an existing way to execute `sqlite3_file_control()` in `go-sqlite3`? I didn't see one but I thought I'd ask.

I'm happy to add the functionality. Are you open to accepting a patch for it?

**Comment by rittneje** [comment]
Seems fine. But do be mindful that some users compile against their system installation of SQLite, meaning that not all constants/functions from the statically compiled header file are guaranteed to exist in all cases.

**Comment by benbjohnson** [comment]
@rittneje I pushed up a [pull request](https://github.com/mattn/go-sqlite3/pull/1000) to add a `FileControl()` method to `SQLiteConn` and a corresponding test. I also tested it against Litestream in this [`persist-wal`](https://github.com/benbjohnson/litestream/compare/persist-wal) branch. Let me know if there's anything you'd like me to change with the PR. Thanks!

**Comment by benbjohnson** [comment]
@rittneje @mattn Thanks so much for all the reviews! 🙏
